### ISSUE TITLE
URLErrors on Windows for conda:

### ISSUE THREAD

**Issue by K-Meech** [snakemake/snakemake#100]
Snakemake version: 5.7.4

Using conda: in a rule results in URLError on Windows

$ snakemake -k  -j --use-conda
The flag 'directory' used in rule all is only valid for outputs, not inputs.
Building DAG of jobs...
WorkflowError:
Failed to open environment file Z:\Kimberly\Projects\SBEM_analysis\src\sbem_analysis\snakemake_genes\envs/snakemake_genes.yaml:
URLError: <urlopen error unknown url type: z>

Example rule that errors:

rule QC_graphs:
    input:
        QC_stats = "tables/after_QC_{gene_assignment}.csv"

    output:
        QC = directory("QC_{gene_assignment}")

    conda:
        "envs/snakemake_genes.yaml"

    log:
        "logs/QC_graphs_{gene_assignment}.log"

    threads: 8

    script:
        "scripts/QC_graphs.py"

**Comment by angelo-peronio** [comment]
I am seeing the same with `snakemake 5.12.3` on Windows 10:

```
> snakemake -j 8 -R dummy --use-conda
Building DAG of jobs...
WorkflowError:
Failed to open environment file C:\Users\angelo.peronio\Documents\lavoro-Angelo\muetec\build\2020-03-05-snakemake-test\build.condaenv.yaml:
URLError: <urlopen error unknown url type: c>
  File "C:\tools\miniconda3\envs\muepy-dev\lib\site-packages\snakemake\deployment\conda.py", line 198, in create
  File "C:\tools\miniconda3\envs\muepy-dev\lib\site-packages\snakemake\deployment\conda.py", line 70, in content
  File "C:\tools\miniconda3\envs\muepy-dev\lib\site-packages\snakemake\deployment\conda.py", line 37, in content
```

The `Snakefile`:
```
rule dummy:
    output:
        "dummy.file"
    conda:
        "build.condaenv.yaml"
    shell:
        "echo dummy > dummy.file"
```

I guess it is [how urllib works](https://bugs.python.org/issue6193).
If I understand correctly, the problem is here:
https://github.com/snakemake/snakemake/blob/1e2e234e24b0473fe669124e5d4422385eb5cf12/snakemake/deployment/conda.py#L32-L38

If interested, I could put together a pull request.

**Comment by svHatch** [comment]
Any movement on this? Was there a PR created?

**Comment by melund** [comment]
@svHatch I think I fixed this issue. The tests pass on windows now, but please help test it in real projects.
