### ISSUE TITLE
Print shell commands

### ISSUE THREAD

**Issue by martynakgajos** [snakemake/snakemake#102]
**Snakemake version**
5.7.4

**Describe the bug**
The flag -p does not work. 

**Example**

`snakemake -p --directory $dr --configfile $dr"config.yaml" `

> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 1
> Rules claiming more threads will be scaled down.
> Job counts:
> 	count	jobs
> 	1	CheckQuality
> 	1	all
> 	2
> 
> [Tue Nov 12 11:55:23 2019]
> rule CheckQuality:
>     input: QualityCheck/OJ43/sequencing_summary.txt
>     output: QualityCheck/OJ43/summary.yaml
>     jobid: 2
>     reason: Missing output files: QualityCheck/OJ43/summary.yaml
>     wildcards: sample=OJ43
> 
> Job counts:
> 	count	jobs
> 	1	CheckQuality
> 	1
> MissingOutputException in line 74 of path/Snakefile:
> Missing files after 5 seconds:
> QualityCheck/OJ43/summary.yaml

The rule:
rule CheckQuality:
	input:
		"QualityCheck/{sample}/sequencing_summary.txt"
	output:
		"QualityCheck/{sample}/summary.yaml"
	run:
		"Rscript scripts/MinIONQC.R -i {input} -o QualityCheck/{wildcards.sample}/"

**Comment by SultanOrazbayev** [comment]
Could you try using `shell` instead of `run'?

**Comment by johanneskoester** [comment]
Shell commands are only printed from shell directives in dry run. Also, the above rule is syntactically not correct. Please have a look at the docs and the official tutorial. `run:` is for plain, inline,  Python code. Use `shell:` for invoking shell commands.

**Comment by seb-mueller** [comment]
I had a similar issue and didn't know `-p` is only working in dry run and shell directives.
This should be made clear in the documentation (where this is not mentioned), or maybe implemented for no-dry-runs. 

Present text in [doc](https://snakemake.readthedocs.io/en/stable/executing/cli.html#OUTPUT)
```
--printshellcmds, -p
  Print out the shell commands that will be executed. 
  Default: False
```
Happy so send a PR to include it in the doc
