### ISSUE TITLE
Rule does not symlink rest of files to cache

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#1027]
**Snakemake version**
6.4.1

**Describe the bug**
When caching output files, only the first one is cached and symlinked

**Logs**
```
$ SNAKEMAKE_OUTPUT_CACHE=XXX snakemake -j 1 --cache
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       download_data
        1
Select jobs to execute...

[Fri Jun  4 12:20:19 2021]
rule download_data:
    output: worldcitiespop1.csv, worldcitiespop2.csv
    jobid: 0

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  144M  100  144M    0     0  22.6M      0  0:00:06  0:00:06 --:--:-- 29.2M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  144M  100  144M    0     0  22.3M      0  0:00:06  0:00:06 --:--:-- 28.2M
Moving output file worldcitiespop1.csv to cache.
Symlinking output file worldcitiespop1.csv from cache.
[Fri Jun  4 12:20:32 2021]
Finished job 0.
1 of 1 steps (100%) done
Complete log: .snakemake/log/2021-06-04T122018.771794.snakemake.log
```

**Minimal example**
```
rule download_data:
    output:
        x1="worldcitiespop1.csv",
        x2="worldcitiespop2.csv",
    cache: True
    shell:
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output.x1}; "
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output.x2}; "
```

**Additional context**

**Comment by dariober** [comment]
I landed here by accident and I got curious about caching. The [docs](https://snakemake.readthedocs.io/en/stable/executing/caching.html) say:

> Note that only rules with just a single output file (or directory) or with multiext output files are eligible for caching. The reason is that for other rules it would be impossible to unambiguously assign the output files to cache entries while being agnostic of the actual file names.

So it seems the behaviour you report is somewhat expected. Although it would be nice to get an error if a cached rule has more than one output...

**Comment by fgvieira** [comment]
Hi @dariober, thanks for pointing it out, but it is possible to have several output files if you use (e.g.) `multiext`, like [here](https://github.com/snakemake-workflows/dna-seq-varlociraptor/blob/91b5582c10ab9c5c216fd8e28a2ff83dc6cd9963/workflow/rules/ref.smk#L74-L85).

Do you know if there is other ways to do it?

**Comment by fgvieira** [comment]
In other words, since it is not possible to cache multiple files (as @dariober pointed out), would it possible to have a `multiext` with named output?
