### ISSUE TITLE
Path and expand

### ISSUE THREAD

**Issue by Gutorm** [snakemake/snakemake#103]
**Snakemake version**
5.7.4
**Describe the bug**
Since 5.7.0 Pathlib compatibility has been added. However, the expand() function gets confused by path-objects, it seems to assume strings.

**Logs**
TypeError in line 6 of /mnt/work/gutorm/qcTest/snakeplay/Snakefile.pathlib:
unsupported operand type(s) for +: 'PosixPath' and 'str'
File "/mnt/work/gutorm/qcTest/snakeplay/Snakefile.pathlib", line 6, in <module>

**Minimal example**
from pathlib import Path
hello = "Hello"   # works
hello =  Path("Hello")  # will only work if casted to string or if not expand()-ed
rule test:
    input:  "Snakefile.pathlib"
    output: expand(hello + '{ext}', ext=['.1','.2'])
    run:
        print (output)

**Additional context**
Note that in the example above, using  

output: Path("Hello.1"), Path("Hello.2")

will work
This is not a big issue for now - but it would be nice to know if there is a workaround beside 
1) casting to string in the output: clause
2) casting back to Path in the run: section

I would like to  switch from old-school os.path.* functions but would try to avoid a mix depending on where the variables are used in expand-contexts

**Comment by johanneskoester** [comment]
This error is not coming from Snakemake. You try to concatenate the path object with a string here: `hello + '{ext}'`, which is not supported by pathlib.
