### ISSUE TITLE
External workflow modules and singularity?

### ISSUE THREAD

**Issue by nikostr** [snakemake/snakemake#1039]
**Snakemake version**
6.4.1

**Describe the bug**
Snakedeploy works by creating a new Snakefile, specifying the workflow as a module. It seems as if this leads to the containers being ignored even when using the `--use-singularity` flag. Also described here: https://github.com/snakemake/snakedeploy/issues/16

**Minimal example**

```
mamba create -c bioconda -c conda-forge --name snakemake snakemake snakedeploy
conda activate snakemake
git clone https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling.git
mkdir snakedeploy_test
cd snakedeploy_test
snakedeploy deploy-workflow https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling . --tag v0.3.0
cp -r ../dna-seq-deepvariant-glnexus-variant-calling/.tests .
```

Running `snakemake -j1 --use-conda --conda-frontend mamba --use-singularity` works in the cloned but not in the deployed directory.

**Comment by johanneskoester** [comment]
Closed by PR #1040.
