### ISSUE TITLE
unpack on checkpoint

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [snakemake/snakemake#105]
**Snakemake version**
5.7.4+22.g0c1e56c1.dirty

**Describe the bug**
I want a rule to unpack the input of a function, however the input function depends on a checkpoint. Unpack does not seem to handle this case.

**Minimal example**
```
rule all:
    input:
        "b.txt"

checkpoint a:
    output:
        "a.txt"
    shell:
        "touch {output}"

def aggregate(wildcards):
    # files = {'inp1': "Snakefile"}
    files = {'inp1': checkpoints.a.get(**wildcards).output[0]}
    return files

rule b:
    input:
        unpack(aggregate)
    output:
        "b.txt"
    shell:
        "touch {output}"
```
**Additional context**
I looked a bit around in the code and I am not sure what would be the easiest way for me to work on it. If you can point me in the right direction I might start a PR :smile:

**Comment by annahake** [comment]
@Maarten-vd-Sande would this solve the problem of the nested checkpoints as mentioned here: [https://stackoverflow.com/questions/58823881/how-are-nested-checkpoints-resolved-in-snakemake](url)

**Comment by Maarten-vd-Sande** [comment]
Thanks it works!
