### ISSUE TITLE
Shell block comments are evaluated

### ISSUE THREAD

**Issue by gregdenay** [snakemake/snakemake#1055]
**Snakemake version** 6.3
I know this is not the latest release, but I work on a closed system and getting an update installed can take a long time. 
I saw no mention of this bug in the changelog.

**Describe the bug**
References to Snakemake Params in commented lines of shell blocks are evaluated.
Expected behaviour would be that commented lines are ignored.

**Logs**
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       test
        2

[Fri Jun 18 09:31:56 2021]
rule test:
    output: test_file.txt
    jobid: 1

RuleException in line 9 of /home/debian/NGS/metabarcoding_paper/snakemake_test:
'Params' object has no attribute 'unnescessary'
  File "/home/debian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 140, in run_jobs
  File "/home/debian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 441, in run
  File "/home/debian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 230, in _run
  File "/home/debian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 156, in _run
  File "/home/debian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 162, in printjob
```

**Minimal example**
```
shell.executable("bash")

workdir: workflow.basedir

rule all:
    input: 
        "test_file.txt",
        
rule test:
    output:
        "test_file.txt",
    params:
        some_param=1,
        # unnescessary = 0,
    shell:
        """
        # Comment out a reference to Params
        # param={params.unnescessary}
        touch {output}
        """
```

Kudos to the devs for this amazing Software!

**Comment by johanneskoester** [comment]
Thanks for reporting!
This is technically impossible to avoid. Because snakemake does not parse the shell code before inserting values there. Also, I guess there are many people who would request the opposite, that params are properly replaced with the value there.

Nevertheless, it makes sense to put a note in the docs: 18cc3723

**Comment by johanneskoester** [comment]
You can always mask braces by doubling them to avoid a replacement.

**Comment by gregdenay** [comment]
It males sense, thanks for clearing this up! This issue is normally only happening when debugging shell blocks, which is probably a bad practice to do within a snakemake file anyways.
