### ISSUE TITLE
Jobs not acting as cores locally?

### ISSUE THREAD

**Issue by nikostr** [snakemake/snakemake#1060]
**Snakemake version**
6.5.0

**Describe the bug**
When deploying v0.3.0 of https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling deployed with snakedeploy and running with `snakemake -j50 --use-conda --conda-frontend mamba -p --use-singularity ` on my local machine, multiple 50 thread jobs are launched in parallel. In the documentation I'm interpreting `--jobs` and `--cores` to be aliases locally, but I'm assuming that this is not the expected behavior.

**Comment by johanneskoester** [comment]
Thanks for reporting! Fixed in commit ffa5cf87.
