### ISSUE TITLE
Lint should not require specification of cores

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakemake#1083]
**Is your feature request related to a problem? Please describe.**
I would like not to have to type `-c1` when running the linter. The linter should work without specification of the number of cores, just like dryrun doesn't require number of cores.

```
❯ snakemake lint
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -cN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -c1.
```

Snakemake version: 6.5.2

**Comment by corneliusroemer** [comment]
The same problem occurs with `snakemake --cleanup-metadata`.

In fact, the command that is suggested does not run, because one needs to add the cores as `-c1` for example. So either the docs should be changed or the behaviour of the command:
```
(nextstrain) [roemer0001@worker01 ncov-simple]$ snakemake --profile=profiles/basel-combined-cluster deploy_test all -npr -t
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.Incomplete files:pre-processed/gisaid/alignment.fasta.xz

(nextstrain) [roemer0001@worker01 ncov-simple]$ snakemake --cleanup-metadata pre-processed/gisaid/*
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -cN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -c1.

(nextstrain) [roemer0001@worker01 ncov-simple]$ snakemake --cleanup-metadata pre-processed/gisaid/* -c1(nextstrain)

**Comment by HenningTimm** [comment]
This seems to have been fixed. In case of `--lint`, I think the call would have to be `snakemake --lint`, since without the dashes `lint` is interpreted as a target rule. The lint parameter is already in the list of parameters that do not require execution (and thus require a number of cores). For `--cleanup_metadata` this was added in #1429.

**Comment by corneliusroemer** [comment]
Thank you for clarifying @HenningTimm!
