### ISSUE TITLE
Specifying a path starting with "/" in --default-resources tmpdir=<path> creates a syntax error in checkpoints

### ISSUE THREAD

**Issue by RomainFeron** [snakemake/snakemake#1093]
**Snakemake version**
6.5.3

**Describe the bug**
When using the command line argument `--default-resources` to specify a tmp directory starting with "/", a Syntax Error occurs for the first `checkpoints.xxx.get()` line.

**Logs**

*Using a non-/ tmpdir:*

```bash
(snakemake) ➜  snakemake snakemake -j1 --forceall --default-resources tmpdir=test 
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
example_checkpoint        1              1              1
total                     1              1              1

Select jobs to execute...

[Fri Jul 16 11:09:17 2021]
checkpoint example_checkpoint:
    output: 1.txt, 2.txt, 3.txt
    jobid: 0
    resources: mem_mb=1000, disk_mb=1000, tmpdir=test
Downstream jobs will be updated after completion.

[Fri Jul 16 11:09:17 2021]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /home/romain/work/tmp/snakemake/.snakemake/log/2021-07-16T110917.108029.snakemake.log
```

*Using a / tmpdir:*

```bash
(snakemake) ➜  snakemake snakemake -j1 --forceall --default-resources tmpdir=/home/romain/test
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
InputFunctionException in line 2 of /home/romain/work/tmp/snakemake/Snakefile:
Error:
  SyntaxError: invalid syntax (<string>, line 1)
Wildcards:

Traceback:
```

**Minimal example**
*Code used to generate the logs above:*

```python
checkpoint example_checkpoint:
    '''
    '''
    output:
        '1.txt',
        '2.txt',
        '3.txt'
    shell:
        'touch {output}'


def example_input(wildcards):
    '''
    '''
    rule_input = checkpoints.example_checkpoint.get(**wildcards).output[0] 
    return rule_input


rule example_rule:
    '''
    '''
    input:
        example_input
    output:
        'test.txt'
    shell:
        'cat {input} > {output}'
```

**Comment by DonFreed** [comment]
Thanks for the bug report. I can reproduce the error in v6.8.0.

The value of the `--default_resources` argument goes through one pass of `eval()` evaluation at, https://github.com/snakemake/snakemake/blob/main/snakemake/resources.py#L47-L61. `eval()` of tmp directories that do not start with a `/` will trigger a `NameError` and the original string value will be returned. However, `eval()` of `/home/romain/test` (or another string starting with a `/` triggers a `SyntaxError`, which is not caught in the `except` block, and leads to the error message you are seeing.

As a workaround, you might quote `/home/romain/test` in the `--default_resources` argument. This will pass a quoted string to `eval()`, which will just return the string value:
```
snakemake snakemake -j1 --forceall --default-resources "tmpdir='/home/romain/test'"
```

**Comment by RomainFeron** [comment]
Thanks for the workaround, that will be useful!

**Comment by pvandyken** [comment]
The parsing rules for `--default-resources` are outlined in #1707, as is the need for additional documentation. As such, I'm closing this issue, but please continue the discussion if there is any more relevant information.
