### ISSUE TITLE
Setting jobs in profiles to use all available cores

### ISSUE THREAD

**Issue by mivade** [snakemake/snakemake#11]
(Manually migrated from the original Bitbucket issue #1305)

I am testing out Snakemake profiles and would like to specify the number of jobs to be the same as the number of available cores. When using command-line arguments, I would be able to do this:

```snakemake -j```

and Snakemake will determine the right number of cores to allocate. If I instead of a `profile/config.yaml` file that looks like

```jobs:```

I get this error:

```snakemake: error: argument --cores/--jobs/-j: invalid int value: 'None'```

Is there a way to get the behavior of simply passing `-j` while using profiles?

**Comment by mbhall88** [comment]
So it looks like the default (when `-j` is given with no value) is to get the maximum cores available via a function `available_cpu_count()`

https://github.com/snakemake/snakemake/blob/d48b90baf85fd41a445e71d862990187b02482da/snakemake/__init__.py#L805-L815

To allow adding jobs to a profile it would make sense to me to allow a user to enter `-j 0` to mean the same thing as `-j` on its own. So I guess in the below line you could also check for `args.cores == 0` and then set `args.cores = available_cpu_count()`

https://github.com/snakemake/snakemake/blob/d48b90baf85fd41a445e71d862990187b02482da/snakemake/__init__.py#L1688

However, I am not very familiar with the snakemake codebase and the CLI is very big with lots of off-shoots and different parameters, so I don't know if there are other/better places that would also need to allow for this check?

**Comment by johanneskoester** [comment]
I think the cleanest solution would be to remove the `const` arg from the cli definition and set it manually below, if `args.cores is None`. Then, passing None in the profile should be fine. PRs are welcome!

**Comment by mivade** [comment]
The problem with that approach is then if you don't give `-j` on the command line Snakemake will default to using all available cores. This may not be a serious issue, but it is a breaking change (since the current default is to allocate 1 core).
