### ISSUE TITLE
--conda-frontend value not passed on to cluster jobs

### ISSUE THREAD

**Issue by RNieuwenhuis** [snakemake/snakemake#1108]
**Snakemake version**

v6.6.1

**Describe the bug**

Running a snakemake workflow on a slurm cluster `--cluster 'sbatch <some stuff for submitting>'` and `--conda-frontend conda` my submitted jobs fail. Related to #1009 ?
**Logs**

```
Error: mamba package manager is not available. The mamba package manager (https://github.com/mamba-org/mamba) is an extremely fast and robust conda replacement. It is the recommended way of using Snakemake's conda integration. It can be installed with `conda install -n base -c conda-forge mamba.If you still prefer to use conda, you can enforce that by setting `--conda-frontend conda`.
```
**Minimal example**

**Additional context**

No profiles are installed, conda is available on the nodes because I can run regular jobs using conda on nodes just fine. 
The `--conda-frontend ` argument simply isn't working.

**Comment by BEFH** [comment]
It is doing it again for me. This is hugely problematic.

**Comment by alecpnkw** [comment]
I was also having this issue with v6.9.1, but using LSF. I was able to get things working again by purging all modules I had loaded and then running snakemake again, but don't know how generalizable this is.

**Comment by seung1yoo** [comment]
anyone has a solution? I faced same error.

**Comment by chrsteel-3000** [comment]
Anyone find a workaround for this?
