### ISSUE TITLE
Every --cluster job performs `os.walk(".snakemake/incomplete")` causing a deadlock

### ISSUE THREAD

**Issue by veprbl** [snakemake/snakemake#1158]
**Snakemake version**
Reproduces on 6.7.0, but should go as far as 5.27.0

**Describe the bug**
Jobs submitted using --cluster option perform `os.walk(".snakemake/incomplete")`, which on extremely large directory sizes make jobs hang up on getdents() calls.

**Logs**

**Minimal example**
```bash
# cat Snakefile 
rule Test:
    output: "output/{n}"
    shell: "mv trace {output}"
# snakemake --cores=1 --cluster="strace -f -o trace" output/{1,2,3}
<snip>
# grep -Er -A4 "openat.*incomplete\"" output
output/3:21478 openat(AT_FDCWD, ".snakemake/incomplete", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
output/3-21478 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
output/3-21478 getdents64(3, 0x266e1e0 /* 2 entries */, 32768) = 48
output/3-21478 getdents64(3, 0x266e1e0 /* 0 entries */, 32768) = 0
output/3-21478 close(3)                          = 0
--
output/2:21458 openat(AT_FDCWD, ".snakemake/incomplete", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
output/2-21458 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
output/2-21458 getdents64(3, 0xea21a0 /* 2 entries */, 32768) = 48
output/2-21458 getdents64(3, 0xea21a0 /* 0 entries */, 32768) = 0
output/2-21458 close(3)                          = 0
--
output/1:21468 openat(AT_FDCWD, ".snakemake/incomplete", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
output/1-21468 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
output/1-21468 getdents64(3, 0x1ee51e0 /* 2 entries */, 32768) = 48
output/1-21468 getdents64(3, 0x1ee51e0 /* 0 entries */, 32768) = 0
output/1-21468 close(3)                          = 0
```

**Additional context**
Causes problems when .snakemake is on NFS
Was introduced in #663, cc @mhulsman @johanneskoester

**Comment by mhulsman** [comment]
Thanks for reporting this! Scandir is quick on the filesystem I'm using, so I hadn't noticed this issue. But the problem indeed has to be in filling the _incomplete_cache, which is not necessary for these single-job runs. So the proposed fix should address it.  

However, that the cache is filled is a bit unexpected to me, as I thought these cluster jobs run with '--ignore-incomplete'. So maybe we need have a look why it still calls Persistence.incomplete at all.

**Comment by veprbl** [comment]
Yes, the wrapper would preferably be as thin and lightweight as possible. If you can manage to cut that check out, that would be even better fix, @mhulsman.

**Comment by mhulsman** [comment]
Turns out the reason that incomplete is called by the wrapper is that only CPUExecutor adds in 'ignore-incomplete', but not ClusterExecutor. Not sure why, maybe for clusters that do automatic restarts of failed jobs? But even then... Anyway, probably safer to keep the proposed fix.

**Comment by veprbl** [comment]
In HTCondor a job can be preempted to be restarted again later. I don't recall batch systems that would restart jobs that are explicitly failing.

**Comment by veprbl** [comment]
> I don't recall batch systems that would restart jobs that are explicitly failing.

Actually I retract that. The condor's option `max_retries` does a restart on a non-zero exit code.
