### ISSUE TITLE
slurm submiited job failed silentely

### ISSUE THREAD

**Issue by mewu3** [snakemake/snakemake#1164]
**Snakemake version**
6.7.0

**Describe the bug**
The stdout of snakemake (as show below) remains as the job is normal while actually, the job has already failed.

**Minimal example**
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 1
Job stats:
job          count    min threads    max threads
---------  -------  -------------  -------------
all              1              1              1
qc_before        9              1              1
total           10              1              1

Select jobs to execute...

[Wed Sep  1 16:04:01 2021]
rule qc_before:
    input: /home/mewu3/data/PV_L003_R1.fastq.gz, /home/mewu3/data/PV_L003_R1.fastq.gz
    output: /home/mewu3/test/reports/qc/PV-L003_R1.html, /home/mewu3/test/reports/qc/PV-L003_R2.html
    log: /home/mewu3/test/logs/PV-L003_qcBefore.log
    jobid: 9
    wildcards: SAMPLE=PV-L003
    resources: tmpdir=/tmp

Submitted job 9 with external jobid 'Submitted batch job 39550942'.
```

**Additional context**
The failure message was received by mail.

**Comment by mwort** [comment]
This is likely not a snakemake bug but rather an issue with your cluster (slurm) profile/interface. Are you using a profile created using [this cookiecutter](https://github.com/Snakemake-Profiles/slurm)? What is the snakemake command you are using and what is the final output? or does it just hang thinking the job runs indefinitely?

**Comment by mewu3** [comment]
Command-line: `atlas run --profile cluster --jobs 3`
And yes the profile was created using cookiecutter.

**Comment by corneliusroemer** [comment]
Could it be that your log output directories don't exist? That makes slurm fail silently. I'm talking about the directories that follow `#SBATCH` etc

What's your submit script? This is what mine looks like:

```
#!/bin/sh

#SBATCH --output=log/%j.out                 # where to store the output ( %j is the JOBID )
#SBATCH --error=log/%j.err                  # where to store error messages

# activate conda environment
source $HOME/miniconda3/etc/profile.d/conda.sh
conda activate nextstrain

{exec_job}
```

**Comment by SilasK** [comment]
Hey, I'm the developer of the above-mentioned snakemake pipeline and cluster profile. 

I updated the cluster profile. Now upon error, the clusterwrapper communicate the error to the snakemake via stdout.

Before I printed everything to the stderr. 
Ideally, snakemake would also listen to the stderr.
