### ISSUE TITLE
Using remote files when including a remote snakemake module

### ISSUE THREAD

**Issue by mrvollger** [snakemake/snakemake#1176]
**Is your feature request related to a problem? Please describe.**

When I include a remote workflow as a module, the module when executed doesn't seem to have access to files in the remote repo. For example, the script directive works as expected but if I wanted to include a perl script (or something else that doesn't work with script) I have in `workflow/scripts/` I cannot seem to use a combination of ```SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))``` and then passing `SDIR` as a parameter to the rule. For example:

Remote snakemake 
```
rule fake_remote_module_rule:
  ...
  params:
    sdir=SDIR,
  shell:
    """
   {params.sdir}/scripts/my_perl_script {some inputs}
   """
``` 
local snakemake
```

module fake_remote:
    snakefile:
        "https://github.com/.../Snakefile"
 

use rule * from fake_remote

rule all:
  input: rules.fake_remote_module_rule.output
```

Would not be able to find the correct path in `fake_remote_module_rule`.

**Describe the solution you'd like**
I would like a suggestion of how to use files/scripts in remote modules that cannot be used with the scripts directive. 

**Describe alternatives you've considered**
I moved all the things I could to the scripts directive but there are some things I cannot. 

**Additional context**
There might be some simple solution that I am unaware of, and if so I apologize, but so far I have not been able to find anything to help me with this. 

Thanks in advance!
Mitchell

**Comment by johanneskoester** [comment]
`workflow.source_path` is meant for this purpose: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#accessing-auxiliary-source-files

I think this should solve your issue. Please reopen if I missed something.

**Comment by mrvollger** [comment]
Thanks this is perfect! Sorry I missed it in the docs.
