### ISSUE TITLE
immediate submit only submitting first job in workflow before shutdown

### ISSUE THREAD

**Issue by skitcattCRUKMI** [snakemake/snakemake#118]
**Snakemake version**
Snakemake v5.8.1

**Describe the bug**
In Snakemake v5.7.4 I could use the --immediate-submit argument to submit all the jobs in a workflow to a cluster in one go without waiting for input files. In v5.8.1, only the first job in the workflow is submitted when using immediate submit, after which Snakemake shuts down without an error message.

In scheduler.py v5.7.4 (Lines 404 - 417)
```python3
        """ Do stuff after job is finished. """
        with self._lock:
            if handle_job_success:
                # by calling this behind the lock, we avoid race conditions
                try:
                    self.get_executor(job).handle_job_success(job)
                except (RuleException, WorkflowError) as e:
                    # if an error occurs while processing job output,
                    # we do the same as in case of errors during execution
                    print_exception(e, self.workflow.linemaps)
                    self._handle_error(job)
                    return

            self.dag.finish(job, update_dynamic=update_dynamic)
```
In scheduler.py v5.8.1 (Lines 403 - 415)
```python3
        """ Do stuff after job is finished. """
        with self._lock:
            if handle_job_success:
                # by calling this behind the lock, we avoid race conditions
                try:
                    self.get_executor(job).handle_job_success(job)
                    self.dag.finish(job, update_dynamic=update_dynamic)
                except (RuleException, WorkflowError) as e:
                    # if an error occurs while processing job output,
                    # we do the same as in case of errors during execution
                    print_exception(e, self.workflow.linemaps)
                    self._handle_error(job)
                    return
```

The line `self.dag.finish(job, update_dynamic=update_dynamic)` has been moved into the `if handle_job_success:` statement. `handle_job_success` is false when using --immediate-submit, therefore dag.finish() does not get called, the ready jobs aren't updated, the scheduler thinks all the jobs are completed, and Snakemake shuts down.

**Minimal example**
Snakefile:
```
rule test_3:
	input:
		"test_2.py"

	output:
		"test_3.py"

	shell:
		"touch {input} && touch {output}"

rule test_1:
	output:
		"test_1.py"

	shell:
		"touch {output}"

rule test_2:
	input:
		"test_1.py"

	output:
		"test_2.py"

	shell:
		"touch {input} && touch {output}"
```

Submit command:
`snakemake --cluster 'qsub' --jobs 100 --notemp --immediate-submit`

It would be expected that all three jobs be submitted to the cluster without waiting for input files. Instead, only the first job in this workflow, test_1, is submitted, and then Snakemake shuts down.

**Comment by johanneskoester** [comment]
Thanks for reporting and digging into it. Once PR #129 is merged, may I ask you to try again and close this issue if the fix works?
