### ISSUE TITLE
Input file question

### ISSUE THREAD

**Issue by eeko-kon** [snakemake/snakemake#1190]
Hi! In my workflow, I generate several files with wildcard filenames (parsing through the input files one by one) and in one step I want to introduce all the files together for a single command. Is this possible with `expand`? If not, how can I achieve input: many files with wildcard names separated by blanks (space or tab)?

**Comment by DrYak** [comment]
We exactly do as you ask in our own pipeline (V-pipe) and use `expand` to gather multiple input files.

And [according to the docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#the-expand-function), that's indeed the method to aggregate multiple inputs to a rule.

**Comment by eeko-kon** [comment]
Unfortunately, `expand` won't work. It will indeed create as an input a **list of files** but they will still be introduced one by one to the command line, likely because they are separated by commas, while the command I am using needs to receive many paths/to/files separated by blanks.

**Comment by eeko-kon** [comment]
Issue solved. The problem was that I used 2 input variables , one with and one without expand, so in that case it is important to name the variables, e.g.:

```
rule GNPS_export:
    input:
        var1= "results/GNPSexport/interim/filtered.consensusXML",
        var2= expand("results/{samples}/interim/precursorcorrected_{samples}.mzML", samples=SAMPLES)
    output:
        "results/GNPSexport/MSMS.mgf" 
    shell:
        """
        resources/OpenMS-2.7.0/bin/GNPSExport -in_cm {input.var1} -in_mzml {input.var2} -out {output} 
```
You can use `snakemake --lint` command to check for suggestions for best practices - that is how we figured the issue out.
