### ISSUE TITLE
Howto: check if snakemake is running

### ISSUE THREAD

**Issue by neunzehnachtneun** [snakemake/snakemake#120]
Im not really sure, if this is a bug report or a feature request. In the end, I hopefully just need some support.

For a project our team runs we need the possibility to check if snakemake is still running or already finished. Some parts of the jobs are calculated on a remote server using a ssh connection, which we cannot sustain over a period of a whole day. So we would like to check regularly after a specified time, if the job is finished or not.

Do you think this is possible? If yes, how? ;-)

Thanks!

**Comment by troycomi** [comment]
There may be some other details missing from this request, but here are a few options:
- `pgrep -u $USER snakemake` will give a list of process ids of snakemake.  If it's empty there are none running.
- Monitor your output directory and see when the final output is created:
```
OUTPUT=/path/to/final/output
while [ ! -f "$OUTPUT" ]; do
  sleep 60
done
echo 'All done!'
```
- use [onsuccess or onerror](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#onstart-onsuccess-and-onerror-handlers) handlers to send you an email for either case.
- follow the most recent log file in `.snakemake/log` of your working directory
- look at the console log?

It seems like you may be using nohup or something to keep snakemake running after your ssh connection closes.  Consider using [screen](https://linux.die.net/man/1/screen) or [tmux](https://linux.die.net/man/1/tmux) to maintain your session after you log out.  You can reattach the next login to pick up where you left off.

Sorry if I've missed your question!

**Comment by neunzehnachtneun** [comment]
Thanks a lot @troycomi :-)

Unforunately `pgrep`, `pidof` and `ps` didn't work.
I started a computing-intensive snakemake rule in one terminal and watched the process. I a second terminal I tried to find the process using  `pgrep snakemake`. Unexpectedly it showed me no output.
We are running python scripts with snakemake, so the process name isn't something like `snakemake` but `python`. But looking for a specific python process is like searching the needle in the hay.
Do you have any other ideas?

Thanks!
I already tried to use , but unfortunately it gave me no output. I am running python scripts using snakemake and to check, if the script has finished or not in a second terminal I

**Comment by troycomi** [comment]
Ok, you can still get pgrep to work with the -a flag (to get the full command line) and -f (to match the full command line).  If you are starting with `python my_snake_main.py` you can see if there are any:
```
pgrep -u $USER -af "python my_snake_main.py"
```
In one terminal I have `python -c 'import time; time.sleep(100)'` and
```
$  pgrep -u $USER -af "python -c"                                                                           
18928 python -c import time; time.sleep(100)
```
It seems like conda may prepend the full env path, but you can pipe pgrep "python" through grep to try to find your script.  After all, grep is for finding needles in haystacks.

**Comment by neunzehnachtneun** [comment]
Thanks, this was really helpful!
Found the [needle in the hay](https://www.youtube.com/watch?v=Zfx_S1lNgpI).
