### ISSUE TITLE
Request to "fix" the hello-world

### ISSUE THREAD

**Issue by ketancmaheshwari** [snakemake/snakemake#1223]
The hello-world workflow in snakemake examples requires complex dependencies such as rust based xsv, python's matplotlib and pandas packages. That's not hello-world. Would be nice to have a simpler hello-world.

**Comment by chuaxr** [comment]
This helped me: https://github.com/nathanhaigh/snakemake-hello-world

**Comment by dlaehnemann** [comment]
Thanks for the question and thanks for the link, @chuaxr!

For just trying snakemake out and for example going through the tutorial in the documentation, I think the easiest solution is to use the browser-based GitPod. This has all the dependencies covered, snakemake pre-installed and provides you with a full development environment including a shell and an editor:
https://snakemake.readthedocs.io/en/stable/tutorial/setup.html#run-tutorial-for-free-in-the-cloud-via-gitpod

Thus, you should be up and running within minutes to try everything out. And the tutorial is the best place to get all the basics:
https://snakemake.readthedocs.io/en/stable/tutorial/tutorial.html
