### ISSUE TITLE
subworkflow needs original configfile even if superseded by configfile in superordinate workflow

### ISSUE THREAD

**Issue by fneum** [snakemake/snakemake#123]
**Snakemake version**
5.8.1

**Describe the bug**
It seems that a subworkflow requires its regular configfile (`configfile: "config.yaml"` in `sub/Snakefile`) even though it is superseded in a superordinate workflow with
```
subworkflow sub:
    [...]
    configfile: "config_sub.yaml"
```
From my understanding in this case `snakemake` should not even check, whether the `config.yaml` of the subworkflow exists, since it is not to be used when it's called from another workflow that specifies a different configfile. Am I wrong?

Or is the interpretation of `subworkflow sub: configfile: "config_sub.yaml"` rather to overwrite individual keys of a configuration that already has to exist in `configfile: "config.yaml"` in `sub/Snakefile`?

**Logs**
For the minimal example below:

1. with `sub/config.yaml` **existing** `snakemake -F write_main`:
    -> No error; content in `sub/sample_sub.txt` is correct and comes from `config_sub.yaml`:
```
{param: main_sub}
```

2. with `sub/config.yaml` **deleted** `snakemake -F write_main`:
    -> WorkflowError:

```
Building DAG of jobs...
Executing subworkflow sub.
WorkflowError in line 1 of .../sub/Snakefile:
Config file config.yaml not found.
  File ".../sub/Snakefile", line 1, in <module>
```
    
I would have thought that in the case of being used as subworkflow the line `configfile: config.yaml` in `sub/Snakefile` would be ignored. 

**Minimal example**

Folder structure:
```
|- Snakefile
|- config_sub.yaml
|- sub
   |- Snakefile
   |- config.yaml
```
`Snakefile`:
```python
subworkflow sub:
    workdir: "sub"
    configfile: "config_sub.yaml"

rule write_main:
    input: sub("sample_sub.txt")
```

`config_sub.yaml`:
```yaml
param: main_sub
```

`sub/Snakefile`:
```python
configfile: "config.yaml"

rule write_sub:
    output: "sample_sub.txt"
    shell: "echo {config} > {output}"
```

`sub/config.yaml`:
```yaml
param: sub
```

**Additional context**

I want to include into a git repository with a snakemake workflow, a snakemake subworkflow through a `git submodule` that by default does not have a tracked `config.yaml`. It only has a `config.default.yaml` which the user can use to produce the `config.yaml` if the subworkflow were to be used as standalone. 

Somehow related but not really: #24 #43

**Comment by SultanOrazbayev** [comment]
> From my understanding in this case `snakemake` should not even check, whether the `config.yaml` of the subworkflow exists, since it is not to be used when it's called from another workflow that specifies a different configfile. Am I wrong?
 
> Or is the interpretation of `subworkflow sub: configfile: "config_sub.yaml"` rather to overwrite individual keys of a configuration that already has to exist in `configfile: "config.yaml"` in `sub/Snakefile`?

IIUC, you are right, subworkflow is modularized so it cannot assume anything about the external config.

With regards to your example, the subworkflow contains a link to the configfile, so that file has to exist. If you change the contents of `sub/config.yaml` to:
```
test: 123
```
And try re-running your workflow, you will see that the parameters passed are a combination of the main and sub configurations.
```
echo {'param': 'main_sub', 'test': 123} > sample_sub.txt
```
So to get the behaviour you want, you can create a python conditional that will check for existence of `config.yaml' and if it doesn't exist, then it should load the `config.default.yaml`.

**Comment by fneum** [comment]
Thanks for the insight! And sorry for mistaking this as a bug.

**Comment by fneum** [comment]
Thanks for the insight! And sorry for mistaking this as a bug.
