### ISSUE TITLE
Job failure with shadow directive if log files not created

### ISSUE THREAD

**Issue by jaicher** [snakemake/snakemake#1257]
**Snakemake version**: v6.10.0

**Describe the bug**

For any job that specifies a logfile: if I am not using the shadow directive, it is okay if my job fails to make a logfile itself (because Snakemake creates an empty one at the final location for me, it looks like). But, if I use the shadow directive, I must explicitly make sure that a logfile is created in the specified location, otherwise, my job fails with `FileNotFoundError` in `snakemake.dag.unshadow_output(...)` because the logfile does not exist in the shadow directory, so it cannot move it to its final desired location. I think that if it succeeds without the shadow directive, it should succeed with the shadow directive.

**Minimal example**

As is, this fails. from `FileNotFoundError` in `unshadow_output(...)`. Comment out the shadow directive, and it works.
```
# Snakefile
rule fails_if_shadow_enabled:
    shadow: "minimal"  # comment out and it succeeds
    output: touch("results/fails_if_shadow_enabled.done")
    log: "results/log/fails_if_shadow_enabled.log"
```

This seems like it'd be a pretty easy fix: either automatically touch the logfile in the shadow directory rather than the original location, or ignore FileNotFoundError for logfiles.

**Comment by johanneskoester** [comment]
Fixed with PR #1258.
