### ISSUE TITLE
TES Executor error

### ISSUE THREAD

**Issue by elliot-smith** [snakemake/snakemake#1265]
**Snakemake version** 
6.10.0

**Describe the bug**
Trying to run the example hello-world TES workflow in Snakemake version 6.10.0 does not work due to a WorkflowError. Reverting Snakemake to 6.6.1 starts the execution of the workflow correctly. Could be related to https://github.com/snakemake/snakemake/issues/1260

**Logs**

> (/tmp/conda/snakemake) XXXXX@88665a0ab8a1 hello-world % snakemake \
>     --tes $TES_URL \
>     --use-conda \
>     --envvars CONDA_PKGS_DIRS \
>     --conda-prefix $CONDA_ENVS_PATH \
>     all -j 10 -F --rerun-incomplete
> Building DAG of jobs...
> [TES] Job execution on TES: http://localhost:8000
> Using shell: /bin/bash
> Singularity containers: ignored
> Job stats:
> job                  count    min threads    max threads
> -----------------  -------  -------------  -------------
> all                      1              1              1
> convert_to_pdf           3              1              1
> download_data            1              1              1
> plot_histogram           3              1              1
> select_by_country        3              1              1
> total                   11              1              1
> 
> Select jobs to execute...
> 
> [Wed Nov 17 16:23:20 2021]
> rule download_data:
>     output: data/worldcitiespop.csv
>     jobid: 4
>     resources: tmpdir=/var/folders/xb/ygj1lpcj1bb6hgvyxw3cdfp80000gs/T
> 
> WorkflowError:
> expected str, bytes or os.PathLike object, not LocalSourceFile

**Minimal example**
Terminal 1;
Install Funnel on your local system: https://ohsu-comp-bio.github.io/funnel/download/
Run the server: `funnel server run`
NB: It should output the following text (change the http port in Terminal 2 for tes if it is different)
`
server               Server listening
httpPort             8000
rpcAddress           :9090
time                 2021-11-17T16:19:56-08:00
`

Terminal 2;
Download the Snakemake git directory and change the directory to the hello-world example
Setup a Snakemake environment via Mamba: `mamba create -c conda-forge -c bioconda -n snakemake snakemake`
Activate Snakemake: `conda activate snakemake`
Run the following commands: 

> pip install py-tes
> export TES_URL=http://localhost:8000
> export CONDA_PKGS_DIRS=/tmp/conda
> export CONDA_ENVS_PATH=/tmp/conda

Run the workflow via Snakemake: 

> snakemake \
>     --tes $TES_URL \
>     --use-conda \
>     --envvars CONDA_PKGS_DIRS \
>     --conda-prefix $CONDA_ENVS_PATH \
>     all -j 10 -F --rerun-incomplete

**Additional context**
TES Server used: [Funnel](https://ohsu-comp-bio.github.io/funnel/)

**Comment by cademirch** [comment]
What is the hello-world workflow? Can you provide a link to it? Would like to test with it.

**Comment by elliot-smith** [comment]
I was using the workflow defined here: https://github.com/snakemake/snakemake/tree/main/examples/hello-world

**Comment by cademirch** [comment]
Just tested with the above workflow, and could not reproduce this on version 6.12.1.
