### ISSUE TITLE
Conda environment creation hangs forever when using mamba >= 0.18.0

### ISSUE THREAD

**Issue by tdido** [snakemake/snakemake#1287]
**Snakemake version**
6.11.1

**Describe the bug**
Conda environments creation hangs forever when using mamba >= 0.18.0

**Minimal example**
Snakefile:
```python
rule all:
    output:
        touch("hello.txt")
    conda: "test.yaml"
    shell: "echo testing"
```
test.yaml:
```yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - bwa
```
Command:
```bash
snakemake --use-conda --conda-create-envs-only --cores 1
```

**Additional context**
Fails (hangs forever) with any 0.18.* version, works fine reverting to <= 0.17.0.

Mamba has implemented parallel extraction in 0.18, perhaps that's related?: https://github.com/mamba-org/mamba/releases/tag/2021.11.17

**Comment by siebrenf** [comment]
I can confirm

**Comment by beardymcjohnface** [comment]
I was having the same issue. The new release for mamba (19.0.0) seems to be working again.

**Comment by tdido** [comment]
Yes, I can confirm that it works again with 19.0.0. Closing this for now.
