### ISSUE TITLE
Use modules from private github repository

### ISSUE THREAD

**Issue by lpagie** [snakemake/snakemake#1301]
**Is your feature request related to a problem? Please describe.**  
I would like to use modules from private github repositories. I very much like to option to specify 'imported' modules using a commit tag, as it implements a kinda source version specification of the external modules without having to include the source code itself. But, my repos' are private. Currently, files from github are source from raw URLs which does not allow authentication of any kind.

**Describe the solution you'd like**  
Ability to 'import' modules from private github repos.  
I don't know in detail what a good solution would be. One possibility is to make use of [github's API](https://docs.github.com/en/rest/reference/repos), possibly through [pyGithub](https://pygithub.readthedocs.io/en/latest/introduction.html)

**Describe alternatives you've considered**  
I'm thinking of having local git mirrors of private github repos and sourcing from this but that would require managing local copies.

**Additional context**  
https://stackoverflow.com/q/70275063/4768122

**Comment by tdido** [comment]
See #1761
