### ISSUE TITLE
IncompleteFilesException while using `--rerun-incomplete`

### ISSUE THREAD

**Issue by tbigot** [snakemake/snakemake#1318]
Using Snakemake 6.12.3 with `--cluster` option (slurm), if a job is restarted (if it has been preempted, for instance), Snakemake complains about `IncompleteFilesException`, while I’m using `--rerun-incomplete` option.

### `Snakefile`

```python
rule all:
    input: "foo.txt"
        
rule remote:
    output: "foo.txt"
    shell: "echo Hello && touch foo.txt && echo Done, sleeping && sleep 600 && echo Exiting"
```

### launching main Snakemake instance

```sh
export sbcmd="sbatch --partition=$mypartition -A $myaccount --out=cluster.out --error=cluster.err --job-name=test-snakemake"
snakemake --cluster "$sbcmd" --rerun-incomplete -j 1
```

### re-queuing the cluster job

In parallel to this, after a few seconds of the job “test-snakemake” is executed (checking the last line in `cluster.out` is `Done, sleeping`, and `foo.txt` was touched), re-queuing  the job:

```sh
scontrol requeue $test-snakemake-jobid
```

as a result, we get the following error in the log of the cluster job.

### Content of `cluster.err`:

```
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
foo.txt
```

### Result of the snakemake execution:

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 1
Job stats:
job       count    min threads    max threads
------  -------  -------------  -------------
all           1              1              1
remote        1              1              1
total         2              1              1

Select jobs to execute...

[Thu Jan  6 15:09:38 2022]
rule remote:
    output: foo.txt
    jobid: 1
    resources: tmpdir=/local/scratch/tmp

Submitted job 1 with external jobid 'Submitted batch job 57297336'.
[Thu Jan  6 15:13:08 2022]
Error in rule remote:
    jobid: 1
    output: foo.txt
    shell:
        echo Hello && touch foo.txt && echo Done, sleeping && sleep 600 && echo Exiting
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: Submitted batch job 57297336

Error executing rule remote on cluster (jobid: 1, external: Submitted batch job 57297336, jobscript: /pasteur/zeus/projets/p02/stella-run/tests/bug_snakemake/.snakemake/tmp.e351ls_z/snakejob.remote.1.sh). For error details see the cluster log and the log files of the involved rule(s).
Removing output files of failed job remote since they might be corrupted:
foo.txt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

If I understand well, the script should rerun without complaining.

**Comment by taylorreiter** [comment]
I have the same issue

**Comment by dlaehnemann** [comment]
Thanks for reporting with a good minimal working example! Two quick questions:

1. Could you try this with the newest version of snakemake? Some changes regarding cluster submission have happened since `6.12.3`, so this might also be fixed (although that is not too likely).
2. Also, would you feel comfortable submitting your above minimal example as a test case via a pull request? It is usually easiest to have a look at existing tests, copy a test folder and then work from there. If not, that's perfectly fine -- but if yes, it would speed up fixing this... ;)

**Comment by tbigot** [comment]
1. Very great news: using the 7.3.3 version, I cannot reproduce this bug. The re-queued job executes fines and finish without error. I guess I’ll have to update my arch to use this version!
2. The issue is: to trigger this kind of bug, one has to re-queue the job using a cluster. Can this kind of behavior be triggered in a test case? Is it still relevant, now that the bug seems fixed?
