### ISSUE TITLE
Slurm cluster jobs failing silently

### ISSUE THREAD

**Issue by daynefiler** [snakemake/snakemake#134]
I am having an odd issue after updating to the most recent version of Snakemake (5.8.1). After submitting the jobs on a slurm cluster, most of the jobs fail immediately without writing to the slurm out file, or writing to the job log file.

The snakemake job runs indefinitely, because it cannot sense the jobs failed on the cluster. I have previously had this issue when trying to direct the slurm out, because the folder to hold the output files did not exist. This is not the issue now, as some of the jobs run to completion. 

I can go into the snakemake tmp folder and run any of the jobs, either directly on the head node or by execution with sbatch. The job shows up as finished after running manually. 

All of the 200+ jobs are reading from the same file, which could be the issue, although it has never been an issue in the past. I tried increasing latency wait to 15 seconds and decreased the max-jobs-per-second from 10 to 5 -- no luck. 

run file:

    snakemake -k -p -j 500 -w 15 --max-jobs-per-second 5 --use-conda --rerun-incomplete --cluster-config cluster.json --stats stats.$(date +%F-%H%M).json \
    --cluster "sbatch --parsable -o 'slurmOut/slurm-%j-%x.out' --mem={cluster.memory} -p {cluster.partition} --cpus-per-task={threads} --nodes=1 -t {cluster.time} --job-name='{cluster.name}'"

**Comment by daynefiler** [comment]
The actual files can be seen in the original -- but they do not really illustrate the problem. I will work on creating something reproducible.

**Comment by troycomi** [comment]
I immediately thought about the slurm output directory not existing; that one always gets me.

Can you get some more information from the slurm database?  Something like 
```
sacct -u $USER --format=jobid,jobname,state,exitcode,cputime,timelimit,reqcpus,partition,reqmem
```
Also, be sure they aren't still in the queue.  My guess is there is an issue with the cluster parameters causing sbatch to fail immediately.  If so, the jobs may not show up in sacct.  Post your cluster config if you want another pair of eyes to check it.  You can also try to tee or pipe the stderr of the sbatch command to get its output.

For checking status, I use `--cluster-status` with the [script](https://github.com/Snakemake-Profiles/slurm/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/slurm-status.py) from the snakemake profiles repo.  Be sure that has execution permission before starting and you use parsable in sbatch (which you are).  You can use the entire profile but I just like the status part.

**Comment by daynefiler** [comment]
Thanks for the feedback -- I am at a total loss. I just created a minimal example to replicate the problem, and it ran fine. Yet, I am still having my jobs die immediately on the real problem. 

I am getting errors that look like this:

    MissingOutputException in line 29 of /projects/sequence_analysis/vol5/dfiler/CNV/realData37/Snakefile:
    Missing files after 15 seconds:
    oto12H/counts/C008_B096.counts
    This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.

Each time, I get some small set of jobs that do not fail. And as a job completes, (if jobs are still being submitted) another will start. Usually between 6-12 jobs (out of 250) will run at a time. The cluster parameters are the same between my toy example that runs and this job.

Here is the output from `sacct`:

    (base) [dfiler@ht4 smslurm]$ sacct -u $USER -S 15:30 --format=jobid,jobname,state,exitcode,cputime,timelimit,reqcpus,partition,reqmem | head -n 50
    JobID    JobName      State ExitCode    CPUTime  Timelimit  ReqCPUS  Partition     ReqMem 
    ------------ ---------- ---------- -------- ---------- ---------- -------- ---------- ---------- 
      2519403      exome.get+  COMPLETED      0:0   00:00:23 1-00:00:00        1      batch    20000Mn 
    2519403.bat+      batch  COMPLETED      0:0   00:00:23                   1               20000Mn 
    2519404      exome.get+  COMPLETED      0:0   00:00:28 1-00:00:00        1      batch    20000Mn 
    2519404.bat+      batch  COMPLETED      0:0   00:00:28                   1               20000Mn 
    2519405      exome.get+  COMPLETED      0:0   00:00:32 1-00:00:00        1      batch    20000Mn 
    2519405.bat+      batch  COMPLETED      0:0   00:00:32                   1               20000Mn 
    2519406      exome.get+  COMPLETED      0:0   00:00:36 1-00:00:00        1      batch    20000Mn 
    2519406.bat+      batch  COMPLETED      0:0   00:00:36                   1               20000Mn 
    2519407      exome.get+  COMPLETED      0:0   00:00:40 1-00:00:00        1      batch    20000Mn 
    2519407.bat+      batch  COMPLETED      0:0   00:00:40                   1               20000Mn 
    2519408      exome.get+  COMPLETED      0:0   00:01:21 1-00:00:00        1      batch    20000Mn 
    2519408.bat+      batch  COMPLETED      0:0   00:01:21                   1               20000Mn 
    2519409      exome.get+  COMPLETED      0:0   00:00:34 1-00:00:00        1      batch    20000Mn 
    2519409.bat+      batch  COMPLETED      0:0   00:00:34                   1               20000Mn 
    2519410      exome.get+  COMPLETED      0:0   00:00:35 1-00:00:00        1      batch    20000Mn 
    2519410.bat+      batch  COMPLETED      0:0   00:00:35                   1               20000Mn 
    2519411      exome.get+  COMPLETED      0:0   00:00:49 1-00:00:00        1      batch    20000Mn 
    2519411.bat+      batch  COMPLETED      0:0   00:00:49                   1               20000Mn 
    2519412      exome.get+  COMPLETED      0:0   00:00:31 1-00:00:00        1      batch    20000Mn 
    2519412.bat+      batch  COMPLETED      0:0   00:00:31                   1               20000Mn 
    2519413      exome.get+  COMPLETED      0:0   00:00:42 1-00:00:00        1      batch    20000Mn 
    2519413.bat+      batch  COMPLETED      0:0   00:00:42                   1               20000Mn 
    2519414      exome.get+  COMPLETED      0:0   00:00:30 1-00:00:00        1      batch    20000Mn 
    2519414.bat+      batch  COMPLETED      0:0   00:00:30                   1               20000Mn 
    2519415      exome.get+  COMPLETED      0:0   00:00:43 1-00:00:00        1      batch    20000Mn 
    2519415.bat+      batch  COMPLETED      0:0   00:00:43                   1               20000Mn 
    2519416      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519416.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519417      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519417.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519418      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519418.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519419      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519419.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519420      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519420.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519421      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519421.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519422      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519422.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519423      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519423.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519424      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519424.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519425      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519425.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 
    2519426      exome.get+     FAILED      1:0   00:00:00 1-00:00:00        1      batch    20000Mn 
    2519426.bat+      batch     FAILED      1:0   00:00:00                   1               20000Mn 


It's like the first ones submitted work, then the rest keep failing. The example I setup is as follows, but did not have any issues running on the same machine:

In R:

    ## Setup the file structure
    saveRDS(data.frame(runif(20e6)), file = "test.load")
    dirs <- sprintf("dir%0.2d", 1:20)
    sapply(dirs, dir.create)
    file.symlink(file.path(getwd(), "test.load"), 
                 file.path(getwd(), dirs, "fileTo.load"))
    sapply(file.path(dirs, "inputs"), dir.create)
    npt <- expand.grid(dirs, sprintf("smp%0.2d.txt", 1:20))
    file.create(file.path(npt[[1]], "inputs", npt[[2]]))
    dir.create("slurmOut")

example.R file:

    #!/usr/bin/env Rscript
    
    "Usage: exampleFunc.R -i <inFile> -n <name> -o <outFile>
    
    Options:
      -h --help
      -i <inFile> --inFile <inFile>  input
      -n <name> --name <name>  sample name
      -o <outFile> --outFile <outFile>  output
    " -> doc
    
    require(docopt, quietly = TRUE); opt <- docopt::docopt(doc)
    
    tmp <- readRDS(opt[["--inFile"]])
    tmp$n <- opt[["--name"]]
    saveRDS(tmp, opt[["--outFile"]])

Snakefile

    GLOB=glob_wildcards('{proj}/inputs/{sample}.txt')
    
    rule all:
      input:
      ["%s/outputs/%s.out"%row for row in zip(*GLOB)]
    
    rule makeOut:
      input: "{proj}/fileTo.load"
      output: "{proj}/outputs/{sample}.out"
      params: name = "{sample}"
      log: "{proj}/logs/{sample}.log"
      shell:
        "./example.R -i {input} -n {params.name} -o {output} &> {log}"


runme.snakemake

    snakemake -k -p -j 500 -w 15 --max-jobs-per-second 5 --rerun-incomplete --stats stats.$(date +%F-%H%M).json \
      --cluster "sbatch --parsable -o 'slurmOut/slurm-%j-%x.out' --mem=20000 -p 'batch' --cpus-per-task=1 --nodes=1 -t 1-00:00:00 --job-name='test'"

**Comment by daynefiler** [comment]
The cluster config used in the real problem is:

```
{
    "__default__": {
        "partition": "batch",
        "memory": 20000,
        "name": "exome.{rule}.{wildcards}",
        "time": "1-00:00:00",
    }
}
```

**Comment by daynefiler** [comment]
I have also tried completely deleting the .snakemake folder and starting over. Having the same problem.

**Comment by troycomi** [comment]
I can see a few things, but tell me if I'm incorrect because the example isn't representative of your actual use case.  My feeling is the issue is related to loading the same file so many times, possibly causing R or the OS to run out of file handles.  If the sacct is of your actual usage, your cluster efficiency is very poor, using ~1min of a requested day.  You could try to get around this particular step by running salloc with a few cores (say 10) then running snakemake on that interactive shell with -j 10 to get 10 instances running at once.

The better solution would be to restructure your R code to split out all samples from the one input file as a single job.  Your snakefile could then use a checkpoint with directory output for consumption by upstream rules, or if you know all expected outputs you can list them in a single rule.  If you can share the repo I can see if I can help more, though R isn't my forte.

**Comment by daynefiler** [comment]
> My feeling is the issue is related to loading the same file so many times, possibly causing R or the OS to run out of file handles.

This was my thought. Naive question: Are there file-specific life-time handles? In other words, is there something about the file I can "reset"? I am guessing not, because that would be odd.

In my toy example, I was trying to test the file handle issue by getting the system to simultaneously read the same file. I have also run the real workflow many times in the past without issue.

**Comment by troycomi** [comment]
It could be a change to the underlying file system that caused a new constraint, maybe talk to your sys admins to see if what you are trying to do (open the same file hundreds of times) is reasonable or if there's a better way.

One workaround to your current code would be to copy the file to local scratch with a sample specific name then run the R code on the copy.  If you just want to limit this step to run say 10 jobs at most, you can set a resource.  In terms of resetting the file, if you are closing the file after usage there isn't much else to do.

Another stress test would be to call your R code asynchronously through the shell in a for loop to see if that crashes or gives a more informative error.  You could even pipe to /sys/null to make cleanup easy.

**Comment by daynefiler** [comment]
Seems as though we had some nodes failing, causing the jobs to fail silently. I have NO idea why the toy example didn't also submit jobs to those nodes. Oh well, thank you for the input. (and SORRY for the erroneous report!)
