### ISSUE TITLE
Module prefix breaks remote input files

### ISSUE THREAD

**Issue by koen-vg** [snakemake/snakemake#1347]
**Snakemake version**
main branch

**Describe the bug**
The new `prefix` keyword in snakemake modules is very useful! However, it breaks remote inputs. For example, when a prefix "foo" is applied to some module containing the input file `HTTP.remote("example.com/abc")`, the path of this remote input file is modified to `"foo/example.com/abc"`. This obviously leads to errors when snakemake tries to then download `https://foo/example.com/abc`.

I have a looked into the source code but I honestly couldn't find where to fix this, so I'm just submitting this issue and hoping that someone more knowledgeable can handle this.

Thanks for a great piece of software!

**Comment by johanneskoester** [comment]
Thanks a lot for reporting, good catch. Fixed in commit 5645b3f75066d8d1d8841b6e6732cd8ad098f67f.
