### ISSUE TITLE
Default Remote Prefix breaks when provided inputs

### ISSUE THREAD

**Issue by elliot-smith** [snakemake/snakemake#1362]
**Snakemake version**
6.14.0

**Describe the bug**
When you run the example workflow "cufflinks" (included in this repository), you receive an error with "Missing input files for rule assembly" for several of the files. 

**Logs**
```
snakemake --snakefile Snakefile --force --cores all --keep-target-files --keep-remote --use-conda --default-remote-provider S3 --default-remote-prefix my_bucket/path
Building DAG of jobs...
WorkflowError:
WorkflowError:
    MissingInputException: Missing input files for rule assembly:
    my_bucket/path/mapped/101.bam
    MissingInputException: Missing input files for rule assembly:
    my_bucket/path/mapped/assemblies.txt.bam
MissingInputException: Missing input files for rule assembly:
my_bucket/path/mapped/merged/merged.gtf.bam
```

**Minimal example**
Example: https://github.com/snakemake/snakemake/tree/main/examples/cufflinks
Execution: `snakemake --snakefile Snakefile --force --cores all --keep-target-files --keep-remote --use-conda --default-remote-provider S3 --default-remote-prefix my_bucket/path`

**Additional context**

**Comment by johanneskoester** [comment]
Thanks for reporting. This should be fixed by adding a `local` marker to those input files. The example still lacks conda directives though, for being immediately usable. It is quite early days compared to the current state of Snakemake. The tutorial example is much better suited for trying Snakemake out.
