### ISSUE TITLE
LocalGitFile never opend due to variable passed as string

### ISSUE THREAD

**Issue by Smeds** [snakemake/snakemake#1372]
I have been trying to use repos on my local computer/servers when importing snakemake modules without success and believe I have found a possible issue in the source code.

in the sourcecache.py, snakemake files are opened at line 340 by passing a string object to _open

https://github.com/snakemake/snakemake/blob/5fabffbb4af8e9e122677e5adeaebf2d6bd0eeb3/snakemake/sourcecache.py#L339-L341

but it looks a bit like the code expects a LocalGitFile (line 348) or a SourceFile (line 357). If I remove get_path_or_uri() from line 340 I'm able to successfully open the Snakefile in my module, however it fails when trying to run include statements in the newly opened Snake file. 

Example: fetching module from github which seem to work
```
from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module dna_seq:
    snakefile: github("snakemake-workflows/dna-seq-gatk-variant-calling", path="workflow/Snakefile", tag="main")
    config: config

use rule * from dna_seq

# easily extend the workflow
rule plot_vafs:
    input:
        "filtered/all.vcf.gz"
    output:
        "results/plots/vafs.svg"
    notebook:
        "notebooks/plot-vafs.py.ipynb"
```

modifying the source I'm able to open the snakefile but not call include in the Snakefile

```
from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module dna_seq:
    snakefile: sourcecache.LocalGitFile("file:///beegfs-storage/..../dna-seq-gatk-variant-calling", path="workflow/Snakefile", tag="main")
    config: config

use rule * from dna_seq

# easily extend the workflow
rule plot_vafs:
    input:
        "filtered/all.vcf.gz"
    output:
        "results/plots/vafs.svg"
    notebook:
        "notebooks/plot-vafs.py.ipynb"
```

error
```
TypeError in line 1 of git+/beegfs-storage/..../dna-seq-gatk-variant-calling/workflow/Snakefile@main:
__init__() missing 1 required positional argument: 'path'
  File "/beegfs-storage/..../Snakefile.test.local", line 11, in <module>
  File "git+/beegfs-storage/..../dna-seq-gatk-variant-calling/workflow/Snakefile@main", line 1, in <module>
```

**Comment by johanneskoester** [comment]
Fixed with PR #1376.
