### ISSUE TITLE
Don't delete temporary wrapper scripts

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#14]
This is a copied issue from https://github.com/snakemake-workflows/docs/issues/15, moved to the correct location!
---------------------------------------------------------

I'm trying to get Snakemake working with Singularity, and I need to debug the Singularity command, but the script wrapper that does the execution doesn't exist after the failure, e.g., I need to test:

```bash
 singularity exec --home /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow  --bind /home/vanessa/anaconda3/lib/python3.7/site-packages:/mnt/snakemake /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow/.snakemake/singularity/328e6123b3d8f239ce917fa97ccbbd80.simg bash -c 'set -euo pipefail;  python /home/vanessa/Documents/Dropbox/Code/labs/cherry/snakemake/encode-demo-workflow/.snakemake/scripts/tmp2navashs.wrapper.py'
```
And why is home being force bound to be the present working directory? That seems strange for Singularity. Should it be `--pwd`?

**Comment by SichongP** [comment]
This would be helpful for debugging purposes. I'm trying to troubleshoot a strange issue related to running snakemake on a cluster and not having actual wrapper script makes it much harder. Maybe add an option to save wrapper scripts upon failure?

**Comment by vsoch** [comment]
hey @johanneskoester and @SichongP I started working on this because it seems like a good first issue to add a simple boolean and then not do a delete - I'm currently trying to figure out all the points that we would want to check for the "don't do the delete" argument and then not do the cleanup, and I'm opening this PR (against my own branch) to get some help about where I need to be looking. I've added print debug statements, and then tested running a pipeline, but I don't see them being printed so I suspect I'm missing something!

Could you take a look and offer some guidance? https://github.com/vsoch/snakemake/pull/1/files

It's greatly appreciated as I'm getting my feet wet! I'll definitely be able to help with more as I familiarize with the codebase.

**Comment by johanneskoester** [comment]
Having a flag for optionally not deleting the script sounds indeed like a useful idea. 
The reason for adding the home mount was this issue here: https://bitbucket.org/snakemake/snakemake/issues/856

I am open to a different fix if you think that mounting the home hurts more than it helps.

**Comment by vsoch** [comment]
Thanks @johanneskoester - could you point me to where the delete operation occurs? You can click on the link to my PR to see where I've been looking (and not found it so far).

**Comment by vsoch** [comment]
hey @SichongP - I'm working on this (made good progress today!) and I've added the argument and I'm writing the test. I'm not super experienced with Snakemake so I wanted to ask - where exactly do you expect the wrapper to be? For example, here is output from a dummy test run:

```
/tmp/snakemake-yp3k3rlw/.snakemake/
├── conda
├── conda-archive
├── locks
├── log
│   └── 2019-10-28T181420.328166.snakemake.log
├── metadata
│   ├── dGVzdC50eHQ=
│   └── dGVzdC5vdXQ=
├── shadow
└── singularity
```
Is it only relevant for Singularity, or some particular kind of workflow?

**Comment by vsoch** [comment]
Yes, I think I found them! I added an argument to skip cleanup scripts and it leaves content in .snakemake/scripts. See #66 !
