### ISSUE TITLE
Report does not show attached data

### ISSUE THREAD

**Issue by Drvanon** [snakemake/snakemake#1401]
**Snakemake version**
```bash
(snakemake) de2doro@de2srv1009:~/test_snakemake$ snakemake --version
6.15.5
```

**Describe the bug**
When I run `$ snakemake --report` none of the attachments are downloadable (in edge if I click a table or an image, it opens a new tab entitled about:blank#blocked) and the thumbnails are not visible (to be precise: the `<td />` that should contain the thumbnail is empty.

**Logs**
```bash
(snakemake) de2doro@de2srv1009:~/test_snakemake$ snakemake --report report-test.html
Building DAG of jobs...
Creating report...
Adding fig1.svg (0.028 MB).
Adding testmodel.fig2.png (0.0091 MB).
Adding test.csv (0.0003 MB).
Adding 3.txt (2e-06 MB).
Adding 1.txt (2e-06 MB).
Adding 2.txt (2e-06 MB).
Downloading resources and rendering HTML.
Report created: report-test.html.
```
**Minimal example**
I have made a rough copy of the snakemake test_report directory. When doing so I noticed I needed to download `data/{fig1.svg,fig2.png}`. Attached is the zip file of the precise repository.

[test-report.zip](https://github.com/snakemake/snakemake/files/8078382/test-report.zip)

**Comment by johanneskoester** [comment]
I think such issues have been fixed with Snakemake 7.2. Reports have been rewritten, and now they use simple download and iframe constructs for showing and downloading data. Please reopen or create a new issue if there are still problems with the report.
