### ISSUE TITLE
Docs: report docs claim a linked example report contains custom branding, but it does not.

### ISSUE THREAD

**Issue by cbrueffer** [snakemake/snakemake#1403]
**Describe the bug**

Affected documentation: https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html

The documentation around reports and custom branding links to an example report at https://snakemake.readthedocs.io/en/stable/_downloads/b10d83889c3905e7b7557a62144a51ca/report.html saying that the report contains custom Uni Duisburg-Essen branding, but it does not.

Testing with the custom stylesheet linked in the above documentation in a local workflow works and the branding shows up in the middle of the top section.

Looking at https://github.com/snakemake/snakemake/blob/main/tests/tests.py the stylesheet is actually passed to the test, but it does not appear to be picked up. The expected output report in https://github.com/snakemake/snakemake/tree/main/tests/test_report/expected-results does not have it either.

**Comment by johanneskoester** [comment]
Thanks for reporting! I've fixed this in a recent release.
