### ISSUE TITLE
Failed to evaluate DefaultResources value 'max(2*input.size_mb, 1000)'

### ISSUE THREAD

**Issue by sebschmi** [snakemake/snakemake#1415]
**Snakemake version** 6.15.5

**Describe the bug**
Snakemake crashes with this error message while/right after building the DAG. As far as I understand, `max(2*input.size_mb, 1000)` is the default value for "mem_mb" and "disk_mb"?

This happens when I run snakemake with a target that makes it use a certain rule I added, but the rule is different to that in line 1710. None of the rules touch "disk_mb", (and I also do not set it as a default resource), but many rules update "mem_mb", but to an integer value and not the default resources.

Unfortunately, the error message does not contain a hint to which resources value creates the problem.

After setting disk_mb as a default resource to an integer value, the problem disappears.

**Logs**
```
InputFunctionException in line 1710 of /proj/sebschmi/git/practical-omnitigs/Snakefile:
Error:
  WorkflowError:
    Failed to evaluate DefaultResources value 'max(2*input.size_mb, 1000)'.
        String arguments may need additional quoting. Ex: --default-resources "tmpdir='/home/user/tmp'".
```

**Comment by johanneskoester** [comment]
Thanks for reporting. Here comes a PR that will provide a more detailed error message:
https://github.com/snakemake/snakemake/pull/1430
