### ISSUE TITLE
Input functions improperly returning directory

### ISSUE THREAD

**Issue by wharvey31** [snakemake/snakemake#142]
I think I have discovered a bug when using directories and checkpoints. I have a checkpoint which creates a variable number of files to a certain output directory. I am using an 'aggregate'-esque rule here called merge_hiC which takes all files created from previous rule processing of the checkpoint output. 

The error is that when I use the input function findMerge, it returns only the directory. I even place gibberish after what should be the directory path from the checkpoint and only get the directory path returned as part of the input function.  

In other words, no matter what I put in to the input function, I only get the directory returning from the checkpoint.

**Snakemake version**
This is in Snakemake 5.8.1 and 5.4.4

```python
#!python

def findMerge(wildcards):
	checkpoint_output = checkpoints.splitting.get(read='2').output.split_parts
	return checkpoint_output+'HSkjdfhk'
	# PARTS, = glob_wildcards(os.path.join(checkpoint_output, "hiC_{part}.fastq"))
	# return expand(rules.repair_hiC.output.repaired_bam, part=PARTS)


def findMergeTwo(wildcards):
	checkpoint_output = checkpoints.splitting.get(read='1').output.split_parts
	return checkpoint_output+'HSkjdfhk'
	# PARTS, = glob_wildcards(os.path.join(checkpoint_output, "hiC_{part}.fastq"))
	# return expand(rules.repair_hiC.output.repaired_bam, part=PARTS)


rule all:
	input:
		'alignment/hic/hic.fix.sort.bam',
		findMerge,
		findMergeTwo

rule make_flags:
	output:
		touch(expand('.hiC_{read}', read=['1','2']))

checkpoint splitting:
	input:
		flag = '.hiC_{read}'
	output:
		split_parts=directory("split_hiC/{read}/"),
		combined = temp('split_hiC/hiCAll_{read}.fastq'),
		sort_hi = temp('split_hiC/hiCAll_{read}_sorted.fastq')
	shell:
		'''
		N=$(( $RANDOM % 10))
		for j in $(seq 1 $N); do echo -n $j > {output.split_parts}/hiC_$j.fastq; done
		touch {output.combined}
		touch {output.sort_hi}
		'''

rule map_hiC:
	input:
		split_hiC = 'split_hiC/{read}/hiC_{part}.fastq',
		flag = '.hiC_{read}'
	output:
		sorted_bam = 'alignment/hic/chunks{read, \d+}/{part, \d+}.nsort.bam'
	shell:
		'''
		touch {output.sorted.bam}
		'''


rule repair_hiC:
	input:
		sorted_bam = expand('alignment/hic/chunks{read}/{{part}}.nsort.bam', read=['1','2']),
	output:
		repaired_bam = 'alignment/hic/repaired/{part, \d+}.bam'
	params:
		sge_opts = '-l mfree=4G'
	shell:
		'''
		touch {output.repaired_bam}
		'''


rule merge_hiC:
	input:
		findMerge,
	output:
		sorted_bam = 'alignment/hic/hic.fix.sort.bam',
	shell:
		'''
		file {input}
		touch {output.sorted_bam}
		'''
```

**Comment by troycomi** [comment]
Multiple checkpoints seem to cause issues with the DAG updating properly.  This sounds similar to (this)[https://bitbucket.org/snakemake/snakemake/issues/1284/requesting-checkpoint-output-in-rule-all] but that should be fixed...

Some things to try that will help troubleshoot:
- Removing `split_parts` from the checkpoint call
- The two input functions are identical except for the read wildcard.  Can you incorporate that into your input directives to just use one function?  Limiting the number of 'simultaneous' checkpoints may solve a race condition.
- What happens if you remove the directory modifier?  Change the output of your checkpoint to be the first file that would be produced, then use your glob to find all the parts.  This will determine if it's directory related or just the structure of the snakefile.

Let's see where that gets us!

**Comment by wharvey31** [comment]
Thank you for the quick reply!

I ended up making a couple of changes, and was able to achieve the desired result. 

As a note, changing the checkpoint output call (split_parts) had no effect. Same for the two input functions. The directory modifier was part of a solution, and I am listing the additional changes below. 

1. I removed the directory modifier and changed the output of the checkpoint to the first file made in the rule
2. Added a touch() file to be created after each checkpoint iteration which is required by the merge_hiC step.
3. Changed findMerge to the following:
`def findMerge(wildcards):
	PARTS, = glob_wildcards(os.path.join("split_hiC/1/hiC_{part}.fastq"))
	return expand(rules.repair_hiC.output.repaired_bam, part=PARTS)`

This triggers proper evaluation of the DAG after checkpoints. However, it does not illuminate what the bug is. I am happy to test additionally, but for now have found a satisfying conclusion.

**Comment by troycomi** [comment]
That's interesting, does your input function, findMerge, not directly call the checkpoints object anymore?

If you want to test more, you can refine and simplify your original example to make it a test case. In particular, is it the directory, multiple checkpoint outputs, or their combination that's causing issues?  

It would be great to get more test cases with checkpoints to prevent regression!

**Comment by ptrebert** [comment]
@wharvey31 This looks a lot like the behaviour I also encountered, i.e. input functions returning the directory instead of the files after checkpoint evaluation, see #55 (I just put this here for future reference...)
