### ISSUE TITLE
Google cloud storage not accepted as a remote provider as of snakemake 7.0.1

### ISSUE THREAD

**Issue by CowanCS1** [snakemake/snakemake#1438]
**Snakemake version**
7.0.1

**Describe the bug**
When calling Snakemake with `--google-lifesciences` I receive the error ```WorkflowError: Unknown default remote provider```. The same message is present when excluding google life sciences and directly specifying GS as the remote provider using ` --default-remote-provider GS`. The bug appears to have been introduced in `snakemake==7.0.1` since the same code with `7.0.0` or `6.x` works fine.

**Logs**
Copied error text: 
```
WorkflowError:
Unknown default remote provider.
```

**Minimal example**
Create virtual environment with
```
mamba create -c conda-forge -c bioconda -n snakemake_test snakemake==7.0.1
```

Snakefile
```
rule all:
    shell: 'echo "Test"'
```

Command to execute pipeline
```
snakemake --default-remote-provider GS --default-remote-prefix my_bucket/snakemake_test -j 1
```

Output with snakemake==7.0.1
```
WorkflowError:
Unknown default remote provider.
```

Output with snakemake==7.0.0
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
total        1              1              1

Select jobs to execute...

[Mon Feb 28 15:43:35 2022]
rule all:
    jobid: 0
    resources: tmpdir=/tmp

Test
[Mon Feb 28 15:43:35 2022]
Finished job 0.
1 of 1 steps (100%) done
```

**Comment by CowanCS1** [comment]
Error also seems to be present when explicitly specifying any of the other default remote providers in the provided example, not specific to GS. Haven't tested other executors than local and google life sciences.

**Comment by CowanCS1** [comment]
As in #1439 this issue appears to be due to the `retry` package not being installed as a required dependency. Manually installing `retry` resolved this issue.  Since the error message is different (and less informative in this case) I'm leaving this as an open issue, but once that issue is closed this one can be too.

**Comment by johanneskoester** [comment]
Fixed here: https://github.com/bioconda/bioconda-recipes/pull/33442

thanks for reporting!
