### ISSUE TITLE
Regression: 'retry' module not found

### ISSUE THREAD

**Issue by koen-vg** [snakemake/snakemake#1439]
**Snakemake version**
7.0.1

**Describe the bug**
Despite the python package 'retry' being added as a dependency, it is apparently not installed when setting up snakemake. This leads to a "No module named 'retry'" exception when a snakemake with a remoteprovider is a evaluated.

**Minimal example**
1. In a new directory, create a Snakefile with a single line: `import snakemake.remote`.
2. Install the latest version of snakemake into its own conda environment: `mamba create -c conda-forge -c bioconda -n snakemake snakemake`.
3. Activate the snakemake conda environment: `conda activate snakemake`.
4. Attempt to run the Snakefile: `snakemake -j1`.

This produces:
````
ModuleNotFoundError in line 1 of [...]/Snakefile:
No module named 'retry'
  File "/home/koen/tmp/snakemake-test/Snakefile", line 1, in <module>
````

This seems to be a regression introduced in 8fc23ed09f9c6de7519160797584ff9df3104939, even though the 'retry' package was added to setup.py. I solved it by manually installing 'retry' with pip in the snakemake conda environment.

**Comment by CowanCS1** [comment]
This also appears to be producing the error in #1438

**Comment by johanneskoester** [comment]
This is fixed here: https://github.com/bioconda/bioconda-recipes/pull/33442
