### ISSUE TITLE
The subworkflow is not recognized in snakefile imported as module within another snakefile

### ISSUE THREAD

**Issue by Kdreval** [snakemake/snakemake#1480]
**Snakemake version**

6.13.1

**Describe the bug**

The subworkflow is not recognized in snakefile imported as `module` within another snakefile.

**Additional context**

I have a snakefile that uses subworkflow named `reference_files` to produce several inputs. It executes without issues when treated as isolated analysis. However, when this same snakefile is used within a multi-step workflow in a modularization approach `module`, the snakemake exits with error:
```
Error:
  NameError: name 'reference_files' is not defined
```
If the same snakefile is used with `import`, the subworkflow is respected and executed as expected. See the minimal example below 👇 

**Minimal example**

Snakefile `subworkflow.smk`
```
rule subworkflow:
    output:
        subworkflow = "subworkflow_output.txt"
    shell:
        "touch {output.subworkflow}"
```

Snakefile for `module1.smk`
```
rule module1:
    input:
        module1 = reference_files("subworkflow_output.txt")
    output:
        module1 = "module1_output.txt"
    shell:
        "cat {input.module1} > {output.module1}"
```

Snakefile for `module2.smk`
```
rule module2:
    input:
        module2 = reference_files("subworkflow_output.txt")
    output:
        module2 = "module2_output.txt"
    shell:
        "cat {input.module2} > {output.module2}"
```

This construction of `master.smk` works and executes as expected:
```
subworkflow reference_files:
    workdir:
        "reference/"
    snakefile:
        "subworkflow.smk"

include: "module1.smk"
include: "module2.smk"

rule all:
    input:
        str(rules.module1.output.module1),
        str(rules.module2.output.module2)
```

However, when the snakefile is imported with `module` approach, the subworkflow is not respected and exits with error:
`master.smk`
```
subworkflow reference_files:
    workdir:
        "reference/"
    snakefile:
        "subworkflow.smk"

include: "module1.smk"
include: "module2.smk"
module _test_module2:
    snakefile: "module2.smk"

use rule * from _test_module2 as _dna_*

rule all:
    input:
        str(rules.module1.output.module1),
        str(rules._dna_module2.output.module2)
```
Error message
```
NameError in line 3 of /home/kdreval/lcr-modules/demo/module2.smk:
name 'reference_files' is not defined
  File "/home/kdreval/lcr-modules/demo/master.smk", line 13, in <module>
  File "/home/kdreval/lcr-modules/demo/module2.smk", line 3, in <module>
```

**Comment by johanneskoester** [comment]
Thanks for reporting! This is not a bug but intended behavior. Modules have separate namespaces and information can be passed to them just via the config mechanism. I have now further clarified this in the docs in commit dbed4a3f160106feb15a51d2e8cfcafae531ea57.
