### ISSUE TITLE
Google lifesciences logs do not overwrite and only one per rule

### ISSUE THREAD

**Issue by cademirch** [snakemake/snakemake#1485]
**Is your feature request related to a problem? Please describe.**
When using `--google-lifesciences` stderr and stdout from the job is written and saved to the provided bucket. This is very helpful when your rules fail and you need to debug them. The `gcloud describe` command outputs a json with some of the stderr, but if the command was large/complex, this does not capture all of it. So it is very helpful to have the full stdout/stderr logs saved to the bucket. 

However, in its current implementation there are two problems

1) Only 1 set of logs are saved per rule. So if there are multiple instances of a rule that are run, only 1 set of logs are saved (probably from the instance that finished first)
2) Logs are not overwritten in the bucket. So you run your workflow for the first and there is an error, when you try to make a fix and rerun the workflow the logs from the first run are still in the bucket - making it difficult to check fixes. 

**Describe the solution you'd like**

1) Unique logs per instance of rule run - I believe this would solve both of the above problems.

**Describe alternatives you've considered**

My current solution is to delete the logs between runs. Though this does not solve problem 1.
**Additional context**
I'm curious about your thoughts on this @vsoch. I'd like to work on implementing this, and could definitely use your feedback.

**Comment by vsoch** [comment]
oh that's a good idea! So the way we save logs is actually to add an extra step to the job, and that's done [here](https://github.com/snakemake/snakemake/blob/013a6e8459d0659e05546c849f84151860686004/snakemake/executors/google_lifesciences.py#L731). You'll notice that is actually running this [helper script]() and the "logs" subcommand with the logs folder and job name as the last part, e.g.,:

```
self.gs_logs, job.name 
```
So if we look at that helper script, it's expecting: https://github.com/snakemake/snakemake/blob/013a6e8459d0659e05546c849f84151860686004/snakemake/executors/google_lifesciences_helper.py#L110-L114

And right now we are giving it:

```
google_lifesciences_helper.py save <bucket_name> /google/logs <gs_logs>/<job_name>
```
And the source (/google/logs) and  dest (some custom storage path in the bucket with the gs_logs prefix and the job name) aren't filenames, they are directory names, and what we do is look for everything in /google/logs and plop it in the destination direction.  So I think this should be pretty simple - all you need to do is add the job number to the job name variable (e.g, so it's something like myjob-1 and then see if the log separation is honored.

**Comment by cademirch** [comment]
@vsoch Thanks for the info! I had the same idea of using the job id to separate the job logs. I quickly implemented that and it works, though I'd like to mess with this a bit more to make the logs a little easier to access.
