### ISSUE TITLE
Unpack fails in imported module with prefix keyword

### ISSUE THREAD

**Issue by jaicher** [snakemake/snakemake#1498]
**Snakemake version**: 7.2.1 and current main (7.2.1+8.gd0304435)

**Describe the bug**

If I:

- have a Snakefile which uses the `unpack()` function to define input variables,
- and I include this Snakefile in a second Snakefile using the `module:` statement,
- and I redirect the output from this Snakefile by using the `prefix:` statement,

Then, Snakemake fails with the error "Can only use unpack() on list and dict".

If I exclude the `prefix:` statement, I do not receive this error.

If I am able to rewrite the input using input functions/lambdas, I do not receive this error.

**Minimal example**

Define `OtherSnakefile`:
```
rule a:
    output:
        a = touch("results/a.txt"),

def unpack_a(wildcards):
    return {"a": rules.a.output.a}

def lambda_a(wildcards):
    return rules.a.output.a

rule b:
    input:
        unpack(unpack_a),
        # a = lambda_a,
    output:
        b = touch("results/b.txt"),
```

Define `Snakefile`:
```
rule all:
    input:
        "results/.all.done",

module other:
    snakefile: "OtherSnakefile"
    prefix: "results/other"

use rule * from other as other_*

rule all_impl:
    output:
        out = touch("results/.all.done"),
    input:
        b = rules.other_b.output.b,
```

Running snakemake yields the message:
```
WorkflowError in line 11 of {...}/OtherSnakefile:
Can only use unpack() on list and dict
```

**Additional troubleshooting**

- If I comment out the `prefix:` statement in `Snakefile`, it works.
- If I replace `unpack(unpack_a)` with `a = lambda_a` as in the example, it works.
- On the failure case, `unpack_a` is never called.

If I print the failure case (adding `print(item)` in `rules.py` before the WorkflowError), I get `results/other/<function unpack_a at 0x7fd9dd769940>`.
It looks like the prefix is being erroneously applied to the unpack object, erasing Snakemake's recognition of it as callable.

I'm guessing there's special logic for other input functions that isn't being appropriately generalized to the unpack case?

**Comment by johanneskoester** [comment]
Thanks a lot for reporting! Will be fixed with above PR.
