### ISSUE TITLE
HTTP.RemoteProvider ignores Content-Encoding: gzip when url

### ISSUE THREAD

**Issue by tsibley** [snakemake/snakemake#1508]
**Snakemake version**
`main` branch.

**Describe the bug**
Normally any response with `Content-Encoding: gzip` is automatically decompressed, however this is currently skipped if the URL ends in `.gz`.

https://github.com/snakemake/snakemake/blob/5f7170e095a961ce11ac87467a20879dc4f220f4/snakemake/remote/HTTP.py#L215-L228

A response with `Content-Encoding: gzip` should always be decompressed if possible, regardless of the URL.

The current behaviour which special-cases `.gz` is different than other HTTP clients like your browser or `curl` and very surprising. It is incorrect.

**Minimal example**
Snakefile
```
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

rule:
    input:
        x = HTTP.remote("trs-blab-test.s3.amazonaws.com/x.gz")
    shell: """
        file {input.x}
        gunzip < {input.x} | hexdump -C
    """
```

Buggy output:
```
Downloading from remote: trs-blab-test.s3.amazonaws.com/x.gz
Finished download.
trs-blab-test.s3.amazonaws.com/x.gz: gzip compressed data, last modified: Tue Mar 22 18:32:34 2022, from Unix
00000000  1f 8b 08 08 42 16 3a 62  00 03 78 00 cb 48 cd c9  |....B.:b..x..H..|
00000010  c9 57 28 cf 2f ca 49 e1  02 00 2d 3b 08 af 0c 00  |.W(./.I...-;....|
00000020  00 00                                             |..|
00000022
```

Expected output:
```
Downloading from remote: trs-blab-test.s3.amazonaws.com/x.gz
Finished download.
trs-blab-test.s3.amazonaws.com/x.gz: gzip compressed data, was "x", last modified: Tue Mar 22 18:32:34 2022, from Unix
00000000  68 65 6c 6c 6f 20 77 6f  72 6c 64 0a              |hello world.|
0000000c
```

**Additional context**
Version control history shows this behaviour dates back to 4.4.0 with https://github.com/snakemake/snakemake/commit/bd17a26c76ace65efa53dafdc37a2eb42addfc50.

**Comment by johanneskoester** [comment]
Actually, this is intentional. Because when you specify the input file as ending on .gz, the rule should also expect to receive a gzip file. In contrast, if the content is silently compressed, the rule obviously does not expect zip and decompression should happen because it is only activated for the purpose of better transfer speed.

**Comment by johanneskoester** [comment]
I have added some explanation on this strategy to the docs in commit e6826b6a740ba5b8877f12732c4ad95194833e07.

**Comment by tsibley** [comment]
@johanneskoester I understand your intention, but that's not how most other HTTP clients work. HTTP intentionally avoids semantics on the URL path (like matching `.gz`) and solely uses headers instead. The `Content-Encoding` of the response is always meant to be decoded by the client to obtain the original resource representation described by the `Content-Type`. While a response of `Content-Type: application/gzip` shouldn't be automatically decoded, a response with `Content-Encoding: gzip` should.

[RFC7231 has this to say](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.2.2) on the matter (emphasis mine):

> **If the media type includes an inherent encoding, such as a data format that is always compressed, then that encoding would not be restated in Content-Encoding even if it happens to be the same algorithm as one of the content codings.**  Such a content coding would only be listed if, for some bizarre reason, it is applied a second time to form the representation.  Likewise, an origin server might choose to publish the same data as multiple representations that differ only in whether the coding is defined as part of Content-Type or Content-Encoding, since some user agents will behave differently in their handling of each response (e.g., open a "Save as ..." dialog instead of automatic decompression and rendering of content).

An HTTP server providing a `.gz` resource should declare that as `Content-Type: application/gzip` if the intent is for the client to save compressed data. If it specifies `Content-Encoding: gzip`, then the intent is for the client to save uncompressed data.
