### ISSUE TITLE
CI continuous integration and testing of workflow 

### ISSUE THREAD

**Issue by rcaneill** [snakemake/snakemake#1519]
Hello,

First of all, thanks for the wonderful package snakemake! I use it for 2 years for my scientific analyzes and it is great!

I am now having bigger datasets to analyze, with a lot of steps. I tried to search how to organize continuous integration and testing, but I did not find any example using snakemake. While unit tests are quite simple to write, integration testing seems more complicated.
The way I was doing, was deleting all outputs from time to time and rerun the whole workflow to verify that it is working (and of course it wasn't), and correct all errors.

So my question is, is there a "standard" way to do integration testing with snakemake? (Like tell snakemake to rerun partially the workflow, and compared newly produced outputs with the previously produced ones, or something similar).

Thanks!

**Comment by cademirch** [comment]
@rcaneill Take a look at how [this repo](https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling) has setup github actions. I've emulated this with my own workflows and have had success.

**Comment by Redmar-van-den-Berg** [comment]
@rcaneill I like to tests my pipelines using singularity and [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/#writing-tests-with-pytest-workflow), you can see my example project [here](https://github.com/Redmar-van-den-Berg/snakemake-project). It includes caching for both `conda` and `singularity`, which makes the tests run a lot faster.

**Comment by rcaneill** [comment]
> @rcaneill I like to tests my pipelines using singularity and [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/#writing-tests-with-pytest-workflow), you can see my example project [here](https://github.com/Redmar-van-den-Berg/snakemake-project). It includes caching for both `conda` and `singularity`, which makes the tests run a lot faster.

Thanks @Redmar-van-den-Berg , I finally had time to use pytest-workflow, it works perfectly fine with snakemake. Thanks for the example repository.

I close the issue, as I think that my question is answered.
