### ISSUE TITLE
Add option for default containers

### ISSUE THREAD

**Issue by mivade** [snakemake/snakemake#152]
**Is your feature request related to a problem? Please describe.**

Right now to run jobs in a container, we have to define in each rule what container to use and enable relevant container support on the command line (e.g., with `--use-singularity`). In many cases we have workflows that install all of their dependencies in one environment (conda currently, but I'm exploring the use of Singularity to improve reproducibility) as opposed to having a rule-specific environment. Therefore it would be nice to have a way to specify the environment for *all* rules instead of having to repeat it for each one.

**Describe the solution you'd like**

A new command line option should be added that, when given, runs *all* rules within a specified container, e.g. something like

```--default-singularity-image=/path/to/singularity-image.sif```

**Describe alternatives you've considered**

Depending on the cluster being used, this sort of thing could be set globally with a custom submit script. For example, [HTCondor appears to support this](https://htcondor.readthedocs.io/en/latest/admin-manual/singularity-support.html). However not all systems may support this and it would not work when doing local development.

**Additional context**

Note that similar concepts also apply to conda environments.

**Comment by troycomi** [comment]
I'm mixed on this.  I like the idea of not repeating `singularity: blah` for each rule, but if a rule doesn't have a statement, it isn't immediately clear if that means no container or a default container.  Add in subworkflows and includes and this gets more convoluted.  Decoupling your dependencies from the snakefile through the command line may also impact reproducibility.  Maybe a declaration like configfile would be a better interface?

Anyways, for the time being you can probably achieve most of this with a [shell prefix](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#i-want-to-configure-the-behavior-of-my-shell-for-all-rules-how-can-that-be-achieved-with-snakemake) or by activating the environment before running snakemake locally.  With prefix, I'm not sure if supplying a different container will override the prefix, but my guess is no.

**Comment by mivade** [comment]
To give a little more context, I'm trying to adapt Snakemake workflows to work in different environments, some of which may have Singularity support and others which may not. In that sense, I'm not worried as much about everything within the Snakefile being entirely reproducible (I save the full list of command-line arguments, the environment, etc. so we can re-run things in an identical manner).

I wasn't familiar with the shell prefix option before, but that looks like it could work if it's coupled with a config option (thanks for the suggestion!). You raise some pretty good points about the complexity my original proposal could add in some cases (e.g. subworkflows). I'll leave this open for now while I experiment with options. If using a shell prefix ends up being a workable option, where would be the right place to update the documentation for this? Under FAQs?

**Comment by troycomi** [comment]
FAQs sound right.  Maybe something like, How can I run all my rules in the same container/environment? I would be sure to include the limitations to this approach, specifically how it will behave with conflicting, explicitly-specified containers.

**Comment by mivade** [comment]
So I haven't tested it yet, but reading further in the docs, it looks like something like this is already possible (or at least once was):

https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#combining-conda-package-management-with-containers

**Comment by mivade** [comment]
Closing this since the top-level `singularity` option does this already.
