### ISSUE TITLE
available_cpu_count incorrect in LSF cluster job

### ISSUE THREAD

**Issue by holtjma** [snakemake/snakemake#157]
**Snakemake version**
5.8.2

**Describe the bug**
When grouping jobs that can run in parallel on the cluster, the grouped job will not set allocated resources in the Snakemake workflow leading to an overuse of resources.

**Logs**
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	test_final
	1	test_temp
	1	test_temp2
	3

[Mon Dec 16 09:01:40 2019]
rule test_temp:
    output: results/test_temp_g1.txt
    log: logs/test_temp_g1.log
    jobid: 1
    wildcards: group=g1
    threads: 2
    resources: mem_mb=8000


        echo "bob2" > results/test_temp_g1.txt && sleep 10
        

[Mon Dec 16 09:01:40 2019]
rule test_temp2:
    output: results/test_temp2_g1.txt
    log: logs/test_temp2_g1.log
    jobid: 2
    wildcards: group=g1
    threads: 4
    resources: mem_mb=4000


        echo "bob" > results/test_temp2_g1.txt && sleep 10
        
[Mon Dec 16 09:01:50 2019]
Finished job 1.
1 of 3 steps (33%) done
[Mon Dec 16 09:01:50 2019]
Finished job 2.
2 of 3 steps (67%) done

[Mon Dec 16 09:01:50 2019]
rule test_final:
    input: results/test_temp_g1.txt, results/test_temp2_g1.txt
    output: results/test_final_g1.txt
    log: logs/test_final_g1.log
    jobid: 0
    wildcards: group=g1


        cat results/test_temp_g1.txt results/test_temp2_g1.txt > results/test_final_g1.txt
        
[Mon Dec 16 09:01:50 2019]
Finished job 0.
3 of 3 steps (100%) done
```

**Minimal example**
```

rule test_temp:
    output:
        "results/test_temp_{group}.txt"
    group: "test_{group}"
    threads: 2
    resources:
        mem_mb=8000
    log: "logs/test_temp_{group}.log"
    shell:
        '''
        echo "bob2" > {output} && sleep 10
        '''

rule test_temp2:
    output:
        "results/test_temp2_{group}.txt"
    group: "test_{group}"
    threads: 4
    resources:
        mem_mb=4000
    log: "logs/test_temp2_{group}.log"
    shell:
        '''
        echo "bob" > {output} && sleep 10
        '''

rule test_final:
    input:
        f1="results/test_temp_{group}.txt",
        f2="results/test_temp2_{group}.txt"
    output:
        f3="results/test_final_{group}.txt"
    group: "test_{group}"
    log: "logs/test_final_{group}.log"
    shell:
        '''
        cat {input.f1} {input.f2} > {output.f3}
        '''
```

**Additional context**
In this example, all jobs are grouped but the first two jobs _can_ run in parallel with appropriate resources.  When submitted using the LSF profile (command: `snakemake --profile lsf -j 1 --snakefile test_groups.smk results/test_final_g1.txt`), it submits a job requesting 4 cores and 8000 MB of memory.  Instead of running test_temp and test_temp2 sequentially, it runs them in parallel (see log start/end times).  I believe this is Snakemake not recognizing resources limits due to the first couple lines in the output file, specifically:
```
Provided cores: 64
Rules claiming more threads will be scaled down.
```

**Comment by holtjma** [comment]
One additional note: if I set the threads to a high value (for example, 48 cores on this 64 core machine), then I can confirm the jobs run sequentially as intended:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	test_final
	1	test_temp
	1	test_temp2
	3

[Mon Dec 16 09:18:04 2019]
rule test_temp:
    output: results/test_temp_g1.txt
    log: logs/test_temp_g1.log
    jobid: 0
    wildcards: group=g1
    threads: 48
    resources: mem_mb=8000


        echo "bob2" > results/test_temp_g1.txt && sleep 10
        
[Mon Dec 16 09:18:14 2019]
Finished job 0.
1 of 3 steps (33%) done

[Mon Dec 16 09:18:14 2019]
rule test_temp2:
    output: results/test_temp2_g1.txt
    log: logs/test_temp2_g1.log
    jobid: 1
    wildcards: group=g1
    threads: 48
    resources: mem_mb=4000


        echo "bob" > results/test_temp2_g1.txt && sleep 10
        
[Mon Dec 16 09:18:24 2019]
Finished job 1.
2 of 3 steps (67%) done

[Mon Dec 16 09:18:24 2019]
rule test_final:
    input: results/test_temp_g1.txt, results/test_temp2_g1.txt
    output: results/test_final_g1.txt
    log: logs/test_final_g1.log
    jobid: 2
    wildcards: group=g1


        cat results/test_temp_g1.txt results/test_temp2_g1.txt > results/test_final_g1.txt
        
[Mon Dec 16 09:18:24 2019]
Finished job 2.
3 of 3 steps (100%) done
```

**Comment by troycomi** [comment]
Interesting.  I didn't know you could use wildcards in group names!

Can you confirm a few things:
- Is your job getting all 64 cores from the scheduler or just the (presumably) 4 requested?
- If no threads is set, what's the default?  Similarly, if you set threads on the last rule does this get resolved?
- Can you set the submission command through `--cluster` and observe the same behavior?  There's a ['qsub exe'](https://github.com/snakemake/snakemake/blob/master/tests/test14/qsub) in the tests folder of this repo you can use to test.  Something like `--cluster echo {threads} {mem_mb} ; ./qsub`.

I'm trying to assess if it's a snakemake problem, the profile, or the cluster.

**Comment by holtjma** [comment]
- I can definitely confirm that it's only requesting the 4 (which is what I would expected). Here's a small snippet of the LSF job info:
```
...
                     >, Error File <logs/cluster/test_g1_809770ec.err>, 4 Proce
                     ssors Requested, Requested Resources <select[mem>8000] rus
                     age[mem=8000] span[hosts=1]>;
...
```

- If I remove threads from all jobs, it just sets it to 1 (also as expected).  If I set the last rule to "4", I basically get identical performance as before (requests 4 processes to the cluster, but both of the jobs run in parallel utilizing 6 processes before the `test_final` job runs.
- If I switch to using `--cluster`, I get the same issue as before (both jobs run in parallel & overuse resources).  Here's the command I used for the purpose of testing it:
`snakemake --cluster "bsub -o logs/cluster/test.log -n {threads} -M {resources.mem_mb} -R \"span[hosts=1]\"" -j 1 --snakefile test_groups.smk results/test_final_g1.txt`

Happy to try more things if you've got ideas.  I _think_ the profile and cluster is operating correctly, but I'm fairly new to using profiles.  Historically, I've manually created the `--cluster` command, so it's possibly a profile issue that I'm not familiar with.

**Comment by troycomi** [comment]
If you are requesting 4 cores it means snakemake is inferring the correct number of threads for the group, but then in the allocated node is detecting all cores on the machine instead of those given to it.  I'm having trouble determining where it picks up all the cores.

For non-group jobs, do you see the same message `Provided cores: 64`?

**Comment by holtjma** [comment]
Yes, I do actually.  I commented out the `group` lines in the above.  Here's one of the outputs:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	test_temp2
	1

[Mon Dec 16 12:42:23 2019]
rule test_temp2:
    output: results/test_temp2_g1.txt
    log: logs/test_temp2_g1.log
    jobid: 0
    wildcards: group=g1
    threads: 4
    resources: mem_mb=4000


        echo "bob" > results/test_temp2_g1.txt && sleep 10
        
[Mon Dec 16 12:42:33 2019]
Finished job 0.
1 of 1 steps (100%) done
```

Looking through a bunch of unrelated logs from real pipelines, that number appears to _always_ match the total number of cores on the machine it was assigned to.

**Comment by troycomi** [comment]
Alright.  Can you check `.snakemake/tmp*` for any shell scripts?  They are usually cleaned up but some stick around if the workflow fails.  If so, just confirm that -j is an argument without a specified number of cores; that's how mine all look though in the code there is an option to supply a value.  Then it seems to be an issue with [available_cpu_count](https://github.com/snakemake/snakemake/blob/9d917f38b89220fbabb08079ac5f248200a4b5ea/snakemake/utils.py#L473).

Can you start an interactive job with like 2 cores and walk through some of that code to see how/where it's failing?  Is this a recent issue or seems to be consistent?  Also, if you need a quick fix you can have the second job depend on output of the first to force sequential execution

Maybe a better name for this issue is 'available_cpu_count incorrect in LSF cluster job'.

**Comment by holtjma** [comment]
I caught one running and it appears to not specify a value as you predicted: `... --force -j --keep-target-files ...`

I'm not entirely sure what you're wanting me to do with the interactive job.  Are you talking about trying to run the `available_cpu_count()` code manually to see why it's returning a high number or are you wanting me to try running Snakemake somehow?  As for recent or consistent, I'm not entirely sure.  I only recently had a use case for groups which is why I'm encountering it now.  However, all of the logs I've spot checked have the total number of cores in the log file.

Yea, my quick fix is just to set the threads to a high value (it works for the particular use case I have).

changed title of issue

**Comment by troycomi** [comment]
Yeah, start an interactive job with 2 cpus and in the shell you can check the contents of `/proc/self/status` to see if `Cpus_allowed:` is in it and copy the line.  Then you can step through the code with an interactive python session or a couple of `python -c {CODE}` commands:
```shell
python -c 'print(bin(int({LINE}.replace(",", ""), 16)).count("1"))'  # LINE from /proc/self/status
python -c 'import multiprocessing ; print(multiprocessing.cpu_count())'
```

In my case, the first was set properly but the second was the total cores in the node.

**Comment by holtjma** [comment]
Interesting, looks like it's not fixing it to particular cores which is making it think it has full access to the node:
```
...
Cpus_allowed:	ffffffff,ffffffff
Cpus_allowed_list:	0-63
...
```
I'm assuming this isn't a Snakemake issue then, but rather a lack of constraint on the job being created by our LSF instance right?

**Comment by troycomi** [comment]
Seems like it.  I would ask your sys admin about this.  Hopefully it's a quick fix!

**Comment by holtjma** [comment]
Any chance you know of a workaround via snakemake command line or otherwise?  If not, I'll mark it as closed (and thanks for the help debugging!)

**Comment by troycomi** [comment]
Not without changing some other snakemake source code where it builds the submission.  

I would add the output of the first rule as the input of the second rule.  You will then request the right number of cores in your job but the first rule will be executed first.  You can specify inputs without using their values.

Hope that helps!  I've been meaning to work out how snakemake gets the cores during submission, so this was a little extra motivation.

**Comment by holtjma** [comment]
Yea, I could see that working if my use case matched the example.  In my real example, I basically have multiple copies of rule `A` feeding into a pipeline B, C, D...: `10xA -> B -> C -> D -> ...`.  There might be a way to order them if I can get creative, but it's non-obvious.

Anyways, thanks for the help and sorry for the false bug!
