### ISSUE TITLE
Clarification on singularity configuration to access files outside the working directory.

### ISSUE THREAD

**Issue by nickp60** [snakemake/snakemake#1572]
**Snakemake version:**
7.3.5

**Describe the bug**
I would love some clarification on  symlinks  and containerized rules. In my hands, it seems like running R scripts from containers on symlinked files or files outside the working directory fails. Any advice would be appreciated!

### What I want to do
I want containerized rules to be able to access files outside the working directory, such as shared resource files link database indexes etc.  No issue running such rules with conda, but with singularity it seems like these files are not visible to the container.  This might be able to solved with playing with the systems singularity settings.

### What I end up doing
I've been using locally-executed rule to copy such files to the working directory temporarily.  Symlinking doesn't seem to work.

**Logs**

**Minimal example**
I made a repo with an example workflow, script, inputs, and outputs: https://github.com/nickp60/snakemake-singularity-issue

What happens is the containerized rule relying on copied files succeeds, as does the rule run with conda.  However the containerized rules accessing a remote file or accessing a remote file symlinked to the working directory fail. 

**Additional context**

**Comment by rdenham** [comment]
I think you might need to provide a simpler example with some output. I tested this and I didn't get any errors using  singularity-ce version 3.8.1 and snakemake 6.7.0.

I did change the line in your example repo to:

```sh
snakemake -c 1 -j 1 \
  --use-singularity  \
  --use-conda \
  --config blast=$PWD/blast_hits.csv anno=$HOME/remote.txt \
  --directory ./results/ \
  --keep-going \
  --singularity-args "-B $HOME"

```

but I'm guessing that was just a typo in your README.

In general, singularity won't be able to resolve symlinks unless both the source and destination paths are included in the bind paths. For example:

```sh
ln -s /var/lib/dpkg/alternatives/rename ~/rename
singularity exec docker://bash ls -l ~/rename
```

will produce

![image](https://user-images.githubusercontent.com/513839/163694544-a15a4b94-8832-46d2-a194-6b1cbf382f86.png)

(ie can't resolve the source filename)

**Comment by jksull** [comment]
@nickp60 Have you bound the location of these _external_ files?  For example, I run snakemake from my home directory, which is automatically bound by snakemake + singularity (it binds $HOME), but I wanted it to also have access to my scratch user directory where my data and results are stored.

To do this, I ran: `snakemake --use-singularity --use-conda --singularity-args "--bind /scratch/<myusername>/`

This gives singularity read/write permissions to my scratch folder and solved my problems

**Comment by nickp60** [comment]
Thanks @rdenham and @jksull .  What I've learned is that (a) linking works sometimes but is prone to fail on certain architectures found on HPC systems, and (b) the binding needs to be in place for all external files outside the home directory or the working directory.

I wish there was a CLI flag to auto-bind all remote files; this seems like a pretty common occurrence. But there are probably considerations I am unaware of...
