### ISSUE TITLE
Paramspace.instance_patterns is converting int types to float

### ISSUE THREAD

**Issue by vietdhoang** [snakemake/snakemake#1574]
**Snakemake version**

7.3.7

**Describe the bug**

When all the parameters in the parameter space are a mixture of floats and ints, `Paramspace.instance_patterns` will turn all ints into a float (i.e 3 -> 3.0). As such, the string representation of an instance of the parameter space will contain only numbers that have decimal points.

**Minimal example**

```python
import pandas as pd
from snakemake.utils import Paramspace

d = {'param1': [1, 2, 3], 'param2': [1.1, 1.2, 1.3], 'param3': [1, 2, 3]}
paramspace = Paramspace(pd.DataFrame(d))
print([*paramspace.instance_patterns])
```
This is what is printed:
```
['param1~1.0/param2~1.1/param3~1.0', 'param1~2.0/param2~1.2/param3~2.0', 'param1~3.0/param2~1.3/param3~3.0']
```
In the first element of the list, `param1` should be 1, not 1.0. Same for `param3`.

**Additional context**

If `param2` is removed, then everything works correctly (`param1` and `param3` do not get converted into a float). It is also interesting to note that if you add a fourth parameter (e.g `param4`) that is neither a float or an int, everything works! This is extremely odd.
```python
d = {'param1': [1, 2, 3], 'param2': [1.1, 1.2, 1.3], 'param3': [1, 2, 3], 'param4': ['a', 'b', 'c']}
paramspace = Paramspace(pd.DataFrame(d))
print([*paramspace.instance_patterns])
```
This is what is printed:
```
['param1~1/param2~1.1/param3~1/param4~a', 'param1~2/param2~1.2/param3~2/param4~b', 'param1~3/param2~1.3/param3~3/param4~c']
```

**Comment by SichongP** [comment]
This is because [dataframe is iterated using `iterrows()`](https://github.com/snakemake/snakemake/blob/fe50b5ca4580a0210343bfcee559831888e80a87/snakemake/utils.py#L689)

from [Pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html):
>Because iterrows returns a Series for each row, it does not preserve dtypes across the rows (dtypes are preserved across columns for DataFrames)

Switching to `itertuples` should fix this problem. I'll work on a PR tomorrow.

**Comment by vietdhoang** [comment]
> This is because [dataframe is iterated using `iterrows()`](https://github.com/snakemake/snakemake/blob/fe50b5ca4580a0210343bfcee559831888e80a87/snakemake/utils.py#L689)
> 
> from [Pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html):
> 
> > Because iterrows returns a Series for each row, it does not preserve dtypes across the rows (dtypes are preserved across columns for DataFrames)
> 
> Switching to `itertuples` should fix this problem. I'll work on a PR tomorrow.
