### ISSUE TITLE
osx-arm64 404 failed

### ISSUE THREAD

**Issue by romeopenheiro** [snakemake/snakemake#1585]
Hello, 

I tried to download snakemake using the [protocol mentioned in the website](https://snakemake.readthedocs.io/en/stable/tutorial/setup.html#running-the-tutorial-on-your-local-machine) for MacOS with ARM/M1 architecture. I experienced issues in Step 3 of the installation. Here, I am not able to download the required packages (see screenshot below).

<img width="1010" alt="Screen Shot 2022-04-15 at 8 25 23 AM" src="https://user-images.githubusercontent.com/50489128/163866688-e2713bd9-359f-475b-ac31-373da22d1026.png">

To get around the problem, I went through the installation process again for MacOS with x86_64 architecture. Here, I didn't experience the same issue - I was able to download the packages. However, the installation process did not run completely. The process stalled at the following step (see screenshot below):

<img width="1032" alt="Screen Shot 2022-04-17 at 9 32 59 AM" src="https://user-images.githubusercontent.com/50489128/163867328-8f16acbe-483d-4dec-aef8-c7ea288754da.png">

Is there a work around that I can perform to be able to download snakemake so I am able to do the tutorial on my local machine? I am new to this, so a step-by-step guide would be very helpful.

Thanks,
Romeo

**Comment by romeopenheiro** [comment]
I realized that I didn't do the steps in the [installation page](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html) so I was getting an error. It's now been resolved.

**Comment by dkabaub** [comment]
Hi @romeopenheiro I experienced the same error. Could you please help me?

**Comment by RedQuark-lab** [comment]
Same error

**Comment by RedQuark-lab** [comment]
Exactly the same error, I redo all the installation procedures but still facing the same error. It seems not resolved. I'm using M1 Macbook.

**Comment by budofia** [comment]
This is written in the requirement section of the documentation "**Currently, the setup currently only works for Intel based machines (x86_64), not ARM based machines like the new Apple M1/2/3 architecture**".
