### ISSUE TITLE
Additional methods to declare local rules

### ISSUE THREAD

**Issue by troycomi** [snakemake/snakemake#1591]
**Is your feature request related to a problem? Please describe.**
This is related to issue #945 and a post I made on [stackoverflow](https://stackoverflow.com/questions/71912278/named-rules-and-local-rules).  Basically the current implementation of listing all `localrules` in a separate directive is challenging for modules and using "anonymous" rules that are named with the `name` directive.

**Describe the solution you'd like**
Adding another rule directive would address both issues:
```python
for key, url in config['urls'].items():
    rule:
        name: f'download_{key}'
        localrule: True
        output: config['paths'][key]
        params: url=url
        shell: # do download

# example with modules
use rule some_task from other_workflow as other_some_task with:
    output:
        "results/some-result.txt"
    localrule: True
```

In either case, placing the information that a rule is local closer to the actual rule makes the workflow more readable in my opinion. The current `localrules` directive should remain for compatibility and as a separate method to set localrules. 

**Describe alternatives you've considered**
You can list local rules that don't exist, so both issues can be worked around.  In the case of anonymous rules, you need to give them a name and manually add it to the `localrules` list.  You can modify the `workflow._localrules`, but that's bad form.

**Additional context**
The `name` directive isn't very clearly presented in the docs and should probably be expanded.

**Comment by fgvieira** [comment]
`localrule` directive added on #2180. Can you test if it works for you?

**Comment by troycomi** [comment]
Nice, thank you!  Can you also add it to the syntax files for vim and nano?
