### ISSUE TITLE
/bin/bash: concatenate.py: command not found

### ISSUE THREAD

**Issue by B-1991-ing** [snakemake/snakemake#1597]
Dear vamb support team,

I am running the VAMB snakemake workflow using the command line below.
module load tools
module load miniconda3/4.12.0
module load snakemake/6.15.3
module load vamb/3.0.3b
module load python36
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 2 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 10 --cluster "qsub -l walltime=12:00:00 -l nodes=2:ppn=24 -l mem=100gb" --quiet
But, error "/bin/bash: concatenate.py: command not found". **Could I specify the location of the concatenate.py in the snakemake command line?**
My snakemake file is in the directory: /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py.
The concatenate.py is in the directory: /services/tools/vamb/3.0.3b/vamb/src.

**Snakemake version**
snakemake/6.15.3

**Describe the bug**
/bin/bash: concatenate.py: command not found

**Logs**
[snakejob.cat_contigs.7.sh.e35589072.txt](https://github.com/snakemake/snakemake/files/8546900/snakejob.cat_contigs.7.sh.e35589072.txt)

Best,

Bing

**Comment by SichongP** [comment]
You may want to post this to https://github.com/RasmussenLab/vamb instead.

**Comment by B-1991-ing** [comment]
Dear snakemake support team,

Sorry for the "vamb support team". Thank you very much for you reply. 

**Update**

The error may be cause by the parameter  **--cluster "qsub -l walltime=12:00:00 -l nodes=2:ppn=24 -l mem=100gb" --quiet**. When I deleted it, at least it can run first several steps. 

**The snakemake vamb workflow command line:**
module load tools
module load miniconda3/4.12.0
module load vamb/3.0.3b
module load samtools/1.14
module load minimap2/2.6
module load snakemake/6.0.4
configuration_file=/home/projects/env_10000/people/binson/Current_pipeline/binning/vamb/config.json
snakemake --jobs 4 --configfile ${configuration_file} --snakefile /services/tools/vamb/3.0.3b/vamb/workflow/vamb.snake.conda.py --latency-wait 10

Also, I used snakemake/6.0.4 instead of the newest version (snakemake/6.15.3 with python3.10). As vamb 3.0.3b requires **python3.7** instead of python3.10. Some module confliction between python3.7 and python3.10 as shown below.
<img width="1356" alt="Screenshot 2022-04-26 at 11 44 50" src="https://user-images.githubusercontent.com/54441633/165272261-08ff49c3-a5a3-4a75-937a-3100ccec5303.png">

Warning from vamb:
**Please note and check the following:

  * The Python version is: Python3.7 from "/services/tools/vamb/3.0.3b/bin/python"
  * The NumPy version is: "1.22.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'**

Best,

Bing
