### ISSUE TITLE
conda environments get hashed names assigned which are different for the same .yaml

### ISSUE THREAD

**Issue by macieksk** [snakemake/snakemake#160]
**Snakemake version**
```
$ snakemake --version
5.8.1+5.g47451f3
```
5.8.1 with a few small patches.

**Describe the bug**

In our pipelines we reuse `.snakemake/conda` folder for different sample folders, so that same environments are not unnecessarily created over and over again.
However, this happens regardless because of the way snakemake assigns hashed names to yaml environments. (<s>Are these hashed names based on a modification date of a file?</s> No, it seems this depends on symlinking to the same .yaml file from two different directories).

Currently we get something like this:
```
/.snakemake/conda $ find *yaml | parallel sha256sum | sort
538e45677632ca7c11cca53cebbdcf7a53a4c4eae1fda04a5327c73a5e462f48  7c606258.yaml
8c8f448fb762cb5e908594e49aeea7bc484bbe2d71a98b92c8d902a55d8baec3  61b41b35.yaml
8c8f448fb762cb5e908594e49aeea7bc484bbe2d71a98b92c8d902a55d8baec3  ebabcffe.yaml
f2c8d5e1c7fdc63c1729f58b82897aa88ca587e9d2ef2b59bc473c5d11f86ff2  3954d749.yaml
f2c8d5e1c7fdc63c1729f58b82897aa88ca587e9d2ef2b59bc473c5d11f86ff2  44cc551f.yaml
f2c8d5e1c7fdc63c1729f58b82897aa88ca587e9d2ef2b59bc473c5d11f86ff2  8f1cabe3.yaml
f2c8d5e1c7fdc63c1729f58b82897aa88ca587e9d2ef2b59bc473c5d11f86ff2  fbd6d8aa.yaml
```

Can this be changed so that hashed name depends only on the content of the .yaml file?

**Minimal example (updated)**
1. Create a simple rule dependent on a conda environment accessed through a symlinked directory:
```bash
$ mkdir test_dir1
$ cd test_dir1
test_dir1 $ ln -s /data/dir/with/yaml/files/envs ./
test_dir1 $ cat Snakefile 
rule make_A:
    output: "A.out"
    conda: "envs/rclone.yaml"
    shell:"""
            touch "{output}"  ## Creates an empty file
    """
test_dir1 $ snakemake --use-conda A.out 
[...]
Activating conda environment: ~/workspace/snakemake_issues/test_dir1/.snakemake/conda/54f2b88b
[...]
# The hash of conda env used is 54f2b88b
```
2. Now create a second directory in hope to reuse the already created conda envs.
```bash
test_dir1 $ cd ..
$ mkdir -p test_dir3/.snakemake
$ cp -P test_dir1/* test_dir3/
## Now test_dir3/envs points to the same directory as test_dir1/envs
$ ln -sr test_dir1/.snakemake/conda test_dir3/.snakemake/conda
$ cd test_dir3
test_dir3 $ snakemake --use-conda A.out -f
[...]
Activating conda environment: ~/workspace/snakemake_issues/test_dir3/.snakemake/conda/0e467436
[...]
# The hash of conda env used is 0e467436
```
The newly built and activated environment hash is different than in the step 1, in spite of `conda: "envs/rclone.yaml" ` directives in both test directories pointing to the same `rclone.yaml` file through symlinked `envs` directories. It seems that, maybe, the symlinked path is used in the creation of conda env hash. Isn't the most appropriate to use only content of a file to create this hash?

**Comment by SichongP** [comment]
I just tried a minimal example but couldn't replicate this problem. (5.8.1)

**Comment by macieksk** [comment]
Sorry @SichongP I rushed with the previous minimal example, can you try with the updated one above? 

It seems that symlinking to the same .yaml file from two different directories produces different hashes (touching, i.e. date of the .yaml file is irrelevant).

**Comment by SichongP** [comment]
I see. So the reason seems to be that snakemake uses both the path of the env file and its content to hash. The reason for this, as stated in the code, is:
>          # Include the absolute path of the target env dir into the hash.
>          # By this, moving the working directory around automatically
>          # invalidates all environments. This is necessary, because binaries
>          # in conda environments can contain hardcoded absolute RPATHs.

I suppose this could be a problem in your use case as well.

**Comment by macieksk** [comment]
Aha, then in my case the `.snakemake/conda` directory, where environments are created is also symlinked (in fact symlinked to `~/miniconda3/envs/`) thus hardlinks within environments are not a problem. In fact, the logic in the comment you cited would be more correct if the `.snakemake/conda` absolute **real** path was used in the creation of the hash. This should be fixed this way, don't you think? To fix that I need to know which variable contains a path to `.snakemake/conda`, or how such path can be constructed.

**Comment by SichongP** [comment]
I'm not very familiar with how conda handles its binaries. Perhaps @johanneskoester has a better answer.

**Comment by macieksk** [comment]
Here is a patch so that conda env yaml hash is computed based content and .snakemake/conda absolute real path. There is also another small patch at the end for conda info json I found necessary for conda to work.
This fixes my problem, thanks @SichongP , maybe @johanneskoester can weight on merging this into main, I could issue a pull request.

```diff
diff --git a/snakemake/conda.py b/snakemake/conda.py
index 041e15d..924880e 100644
--- a/snakemake/conda.py
+++ b/snakemake/conda.py
@@ -48,6 +48,9 @@ class Env:
         self._env_dir = dag.workflow.persistence.conda_env_path
         self._env_archive_dir = dag.workflow.persistence.conda_env_archive_path
 
+        self._conda_dir = os.path.abspath(os.path.realpath(
+                           os.path.join(os.getcwd(),".snakemake","conda"))) # for conda env hash
+
         self._hash = None
         self._content_hash = None
         self._content = None
@@ -74,7 +77,10 @@ class Env:
             # invalidates all environments. This is necessary, because binaries
             # in conda environments can contain hardcoded absolute RPATHs.
             assert os.path.isabs(self._env_dir)
-            md5hash.update(self._env_dir.encode())
+            # Update hash from conda directory, not from environment directory.
+            assert os.path.isabs(self._conda_dir)
+            #md5hash.update(self._env_dir.encode())
+            md5hash.update(self._conda_dir.encode())
             if self._singularity_img:
                 md5hash.update(self._singularity_img.url.encode())
             md5hash.update(self.content)
@@ -349,7 +355,7 @@ class Conda:
             singularity_img = singularity_img.path
         self.singularity_img = singularity_img
         self._check()
-        self.info = json.loads(shell.check_output(self._get_cmd("conda info --json")))
+        self.info = json.loads(shell.check_output(self._get_cmd("conda info --json")).decode('utf-8'))
 
     def _get_cmd(self, cmd):
         if self.singularity_img:
```

**Comment by macieksk** [comment]
@jinwang0611 points out in #185 that `--conda-prefix` can solve the problem, too.

**Comment by johanneskoester** [comment]
Thank you! Should be fixed now in master (by using realpath).
