### ISSUE TITLE
conditional temp output

### ISSUE THREAD

**Issue by sneuensc** [snakemake/snakemake#1602]
**Is your feature request related to a problem? Please describe.**
It would be great to have a conditional temp() for the output. I am developing a pipeline which allows to skip modules. The skipping is done using symlinks (ln -s). This works great if all output is kept. However, my files are too large, so I need to clean up all intermediate files, but the output of the last step which is referred to with a symlink in the final rule (ln -s foo.bam final.bam).  The function temp() is great, however, does not allow to make it conditional, i.e. just keep the output of the last step.

**Describe the solution you'd like**
Ideal would be to have (simple) functions allowed in the output, e.g.:
```
rule foo:
  output:
    if FINAL_STEP == "foo":
      "foo.bam"
    else:
      temp("foo.bam")
```

**Describe alternatives you've considered**
My current implementation uses an if else around the entire rule definition (doubling the rule) which is ugly, difficult to read and thus dangerous, but luckily works, e.g.:
```
if FINAL_STEP == "foo":
  rule foo:
    output:
      "foo.bam"
    ...
else:
  rule foo:
    output:
      temp("foo.bam")
    ...
```

**Comment by gshiba** [comment]
I too would love to have a feature like this.

Idea: Can the `temp` function accept a callable that returns a boolean, with the signature `lambda wildcards:...` (similar to input functions)?

```
FINAL_STEP = ... 

rule foo:
    output: temp("{name}.{ext}", lambda w: FINAL_STEP != "foo")
```

Other examples:

```
rule x:
    # Delete if prefix == "foo"
    output: temp("{prefix}.{ext}", lambda w: w.prefix == "foo")

rule y:
    # Delete if my flag is passed in from CLI like: snakemake [...] -C my_temp_flag=2
    output: temp("file", lambda w: int(config.get("my_temp_flag", 0)) > 2)
```

**Comment by sneuensc** [comment]
Closing this in favour of https://github.com/snakemake/snakemake/pull/1969 which can achieve the same goals with more generalisation and less argument clutter.
