### ISSUE TITLE
Workflow error in module when using a prefix and 'expand' in a rule input

### ISSUE THREAD

**Issue by RomainFeron** [snakemake/snakemake#1614]
**Snakemake version**
7.3.8

**Describe the bug**

I have an issue when using a workflow as module in another workflow with a prefix. Rules from the module that are using 'expand' as input generate a WorkflowError (see below). This does not occur when removing the prefix in the module definition.

**Logs**

```
WorkflowError in line 15 of /home/romain/work/test/wfA/Snakefile:
Flags in file patterns given to expand() are invalid. Flags (e.g. temp(), directory()) have to be applied outside of expand (e.g. 'temp(expand("plots/{sample}.pdf", sample=SAMPLES))').
  File "/home/romain/work/test/wfB/Snakefile", line 5, in <module>
  File "/home/romain/work/test/wfA/Snakefile", line 15, in <module>
```

**Minimal example**

Two simple workflows with the following structure:
```
.
├──  wfA
│   └── Snakefile
└── wfB
    ├── a.txt
    ├── b.txt
    └── Snakefile
```

*wfa/Snakefile:*
```

WILDCARDS = ['a', 'b']

rule copy_data:
    input:
        '{x}.txt'
    output:
        'results/data/{x}.txt'
    shell:
        'cp {input} {output}'


rule test:
    input:
        expand(rules.copy_data.output, x=WILDCARDS)
    output:
        'results/test_wfA.txt'
    shell:
        'cat {input} > {output}'
```

*wfB/Snakefile:*
```
module wfA:
    snakefile: '../wfA/Snakefile'
    prefix: 'results/wfA'

use rule * from wfA as wfA_*

rule test:
    input:
        rules.wfA_test.output
    output:
        'results/test_wfB.txt'
    shell:
        'cp {input} {output}'
```

*Snakemake command ran from wfB:*
`snakemake -j1 -n results/test_wfB.txt`

**Additional context**

The example above generates the logs I posted but it works when commenting the "prefix" line in "module wfA". I'm not sure if it's a bug or if I missed something in modules.

**Comment by fgvieira** [comment]
I am having the same issue on version `v8.10.6`, but when the input file is a `temp` (in your case, if `copy_data.output`  was `temp(copy_data.output)` ).

I think the issue might be around:
https://github.com/snakemake/snakemake/blob/293bc056b6c44f17340543b2678f8a59e808a5a6/snakemake/path_modifier.py#L55

If the path is changed (like when you add a prefix) then it adds a `PATH_MODIFIER_FLAG` flag to the file, and this might be causing the `expand` to fail:
https://github.com/snakemake/snakemake/blob/293bc056b6c44f17340543b2678f8a59e808a5a6/snakemake/io.py#L1250-L1255

Not sure how best to fix it, but maybe we need to change the `expand` code to ignore the `PATH_MODIFIER_FLAG` flag.
