### ISSUE TITLE
A rule to evaluate the input data according to certain thresholds and exclude bad samples

### ISSUE THREAD

**Issue by MostafaYA** [snakemake/snakemake#1636]
I want to set  a rule in snakemake that evaluate the input data according to certain thresholds and only process samples above these thresholds. 
For example, if the sequencing depth of fastq data above 30x, then perfrom assembly and call variants.

**Comment by weber8thomas** [comment]
Hi @MostafaYA 
I suggest you to redirect your thread to either stackoverflow channel (https://stackoverflow.com/questions/tagged/snakemake) or discord (https://discord.gg/gas4cAW) as you are asking for a methodological help rather than raising an issue

**Comment by MostafaYA** [comment]
Thanks for the advice!
