### ISSUE TITLE
tibanna container image is hardcoded

### ISSUE THREAD

**Issue by rvalieris** [snakemake/snakemake#166]
**Snakemake version**
5.8.2

**Describe the bug**
https://github.com/snakemake/snakemake/blob/138720fbca54f88a962c564f2adc5b43149e206a/snakemake/executors.py#L1855
this points to the latest docker build instead of the current version. it also ignores the `--container-image` argument.

**Comment by johanneskoester** [comment]
Fixed by your PR. Thanks!
