### ISSUE TITLE
ModuleNotFoundError: No module named 'snakemake.deployment'

### ISSUE THREAD

**Issue by pb-cdunn** [snakemake/snakemake#168]
**Snakemake version**
`5.9.0` latest from pypi
Note the Snakemake version for which you experience the bug.
Always make sure to try out the latest version before creating a new bug report.

**Describe the bug** 
`ModuleNotFoundError` inside **snakemake** code itself.

**Logs**

```py
error	20-Dec-2019 09:35:35	Traceback (most recent call last):
error	20-Dec-2019 09:35:35	  File "/var/lib/bamboo/bamboo-agent-home/xml-data/build-dir/SAT-IPA85-JOB1/LOCAL/bin/snakemake", line 5, in <module>
error	20-Dec-2019 09:35:35	    from snakemake import main
error	20-Dec-2019 09:35:35	  File "/var/lib/bamboo/bamboo-agent-home/xml-data/build-dir/SAT-IPA85-JOB1/LOCAL/lib/python3.7/site-packages/snakemake/__init__.py", line 21, in <module>
error	20-Dec-2019 09:35:35	    from snakemake.workflow import Workflow
error	20-Dec-2019 09:35:35	  File "/var/lib/bamboo/bamboo-agent-home/xml-data/build-dir/SAT-IPA85-JOB1/LOCAL/lib/python3.7/site-packages/snakemake/workflow.py", line 30, in <module>
error	20-Dec-2019 09:35:35	    from snakemake.shell import shell
error	20-Dec-2019 09:35:35	  File "/var/lib/bamboo/bamboo-agent-home/xml-data/build-dir/SAT-IPA85-JOB1/LOCAL/lib/python3.7/site-packages/snakemake/shell.py", line 16, in <module>
error	20-Dec-2019 09:35:35	    from snakemake.deployment import singularity
error	20-Dec-2019 09:35:35	ModuleNotFoundError: No module named 'snakemake.deployment'
```
**Additional context**
It was working fine until this upgrade. We have temporarily pinned to a previous version. (Someone told me `4.8.x`, but I have not verified that yet.)

I'll do more experimenting this weekend...

**Comment by pb-cdunn** [comment]
We're pinned to `5.8.1` now, which is working.

**Comment by pb-cdunn** [comment]
Co-workers installed things wrong. Nvm. `5.9.0` is fine. Happy holidays!

**Comment by pb-cdunn** [comment]
Dang it! Spoke too soon.

Verified that `5.8.1` works fine, but `5.9.0` fails.

**Comment by MLKaufman** [comment]
Can confirm that 5.9.0 fails with ModuleNotFoundError: No module named 'snakemake.deployment'. Fresh conda installation, using the following command in windows:
conda install -c conda-forge -c bioconda snakemake-minimal

**Comment by kpj** [comment]
Try out snakemake `5.9.1` (it's already on PyPi), this should have the required fix.
