### ISSUE TITLE
7.8.0 fails when touch used in python rule

### ISSUE THREAD

**Issue by jtressle** [snakemake/snakemake#1684]
**Snakemake version**
7.8.0

**Describe the bug**

Running a python rule using a touch() output file brings up error: "reason: Missing output files:"  This occurs on my first rule which does not have an input file, and has no temp file written.  

```
rule python_rule:
	threads: 8
	output:
		touch("file_output")
	run:
		python_script with no output
```

**Logs**

```
rule python_rule:
    output: /file_output
    jobid: 7
    reason: Missing output files: /file_output
    resources: tmpdir=/tmp
```

**Minimal example**
Run a python rule with a touch() temp file.

**Additional context**
This works in 7.70 and no longer works.  What is the correct way of handling this issue?  This rule has never been run, so there is no previous file in place.

**Comment by johanneskoester** [comment]
I don't see an error here though. Your log just says that the rule will be or is executed, there is no error message. The printed reason is not an error but a change in how Snakemake 7.8 reports which rules it wants to run (it now always prints the reason for the decision). Also, I have tried this locally and it executes the rule as expected. Can you maybe further explain what goes wrong and what you would have expected instead?

**Comment by jtressle** [comment]
@johanneskoester thanks for the clarification.  I verified my pipeline still works.  I'll close this issue.
