### ISSUE TITLE
exception tracebacks in `run:` blocks are sent to /dev/null, making rules hard to debug

### ISSUE THREAD

**Issue by grahamgower** [snakemake/snakemake#1698]
**Snakemake version**

7.8.1

**Describe the bug**

When calling python code in a `run:` block, an uncaught exception will cause the job to fail. As it should. However, the stack trace isn't captured so its not possible to track down the cause of the exception!

**Minimal example**

```
$ cat Snakefile
rule all:
    input:
        "test-output"

rule test:
    output:
        "test-output"
    run:
        raise Exception("Hello? Is anybody out there?")
```

```
$ snakemake -c1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
test         1              1              1
total        2              1              1

Select jobs to execute...

[Fri Jun  3 15:40:47 2022]
rule test:
    output: test-output
    jobid: 1
    reason: Missing output files: test-output
    resources: tmpdir=/tmp

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-03T154046.915828.snakemake.log
```
```
$ cat .snakemake/log/2022-06-03T154046.915828.snakemake.log
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
test         1              1              1
total        2              1              1

Select jobs to execute...

[Fri Jun  3 15:40:47 2022]
rule test:
    output: test-output
    jobid: 1
    reason: Missing output files: test-output
    resources: tmpdir=/tmp

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-03T154046.915828.snakemake.log
```

**Comment by dariober** [comment]
I was going to report the same just now! Hope it can be fixed soon since it does make it quite difficult to debug.

**Comment by dweindl** [comment]
The problem is the `all` here: https://github.com/snakemake/snakemake/blob/c8d81d03de2885d5d0473084141e9f6abc5de445/snakemake/executors/__init__.py#L469

This was introduced in https://github.com/snakemake/snakemake/commit/c8d81d03de2885d5d0473084141e9f6abc5de445#diff-438f3317205fd7130727d0589d2fc1a6c2e1f6fc48c2c04d354a8a09b91ba2f4

Last unaffected version is `v7.6.2`.

**Comment by sverchkov** [comment]
> in combination with the early return in
> https://github.com/snakemake/snakemake/blob/c8d81d03de2885d5d0473084141e9f6abc5de445/snakemake/logging.py#L433-L435
> 

Am I missing something or would simply removing the early return fix this?

**Comment by grzanka** [comment]
I suffer the same issue, is there any hope for a fix?

**Comment by cademirch** [comment]
Still an issue on 7.12.

**Comment by cclienti** [comment]
Hello,

The regression is due to the commit:

  **feat: new directive "retries" for annotating the number of times a job shall be restarted after a failure (#1649)**
 c8d81d03de2885d5d0473084141e9f6abc5de445

If I revert the following in snakemake/executors/__init__.py:

```python
     def get_job_args(self, job, **kwargs):
-        return f"{super().get_job_args(job, **kwargs)} --quiet"
+        return f"{super().get_job_args(job, **kwargs)} --quiet all"
```

The exceptions are correctly printed. I think that the "quiet" behavior has changed, and the executor subprocess does not have the correct command line option. IMO, the solution would be to correctly configure the "quiet" option in the subprocess.

**Comment by SilasK** [comment]
Is there a way to transfer the error and trace back to a log file? One can do that by mounting a whole logging structure but this is probably too much for a simple run directive. 

Ideally, errors should go directly to a log if one is provided.

**Comment by sverchkov** [comment]
> Is there a way to transfer the error and trace back to a log file? One can do that by mounting a whole logging structure but this is probably too much for a simple run directive.
> 
> Ideally, errors should go directly to a log if one is provided.

All error printing and logging (both to standard output/error and snakemake's default log files) is already being done with a logging structure. The problem here is that the subprocess for the run block is being run with `--quiet all` which configures the logger to log nothing.

**Comment by SilasK** [comment]
In addition the log is printed to the stdout but not in the main snakemake logfile

**Comment by SilasK** [comment]
> In addition the log is printed to the stdout but not in the main snakemake logfile

Can we reopen this issue?

**Comment by frazane** [comment]
This appears to be still an issue in snakemake 9.9.0.

**Comment by cademirch** [comment]
The exception is emitted to stderr:

```bash
❯ snakemake --version
9.13.3.dev14
❯ snakemake -c1 > stdout.txt 2> stderr.txt
```

stderr.txt:
```
Assuming unrestricted shared filesystem usage.
host: Cades-MacBook-Pro.local
Building DAG of jobs...
Using shell: /opt/homebrew/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
all          1
test         1
total        2

Select jobs to execute...
Execute 1 jobs...

[Wed Nov  5 08:06:27 2025]
localrule test:
    output: test-output
    jobid: 1
    reason: Missing output files: test-output
    resources: tmpdir=/var/folders/my/jsr5cvy94dn5lz1qssmw4f080000gn/T
RuleException:
Exception in file "/Users/cade/dev/sandbox/snaketest/Snakefile", line 10:
Hello? Is anybody out there?
  File "/Users/cade/dev/sandbox/snaketest/Snakefile", line 10, in __rule_test
Exiting because a job execution failed. Look below for error messages
WorkflowError:
At least one job did not complete successfully.
Traceback (most recent call last):

  File "/Users/cade/dev/snakemake-dev/snakemake/src/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^

  File "/Users/cade/dev/snakemake-dev/snakemake/.pixi/envs/default/lib/python3.13/subprocess.py", line 421, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /Users/cade/dev/sandbox/snaketest && /Users/cade/dev/snakemake-dev/snakemake/.pixi/envs/default/bin/python3.13 -m snakemake --snakefile '/Users/cade/dev/sandbox/snaketest/Snakefile' --target-jobs 'test:' --allowed-rules test --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --no-hooks --nolock --ignore-incomplete --rerun-triggers params input code mtime software-env --conda-frontend 'conda' --shared-fs-usage input-output sources storage-local-copies persistence software-deployment source-cache --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'ilp' --local-storage-prefix .snakemake/storage --scheduler-solver-path '/Users/cade/dev/snakemake-dev/snakemake/.pixi/envs/default/bin' --runtime-source-cache-path '/Users/cade/Library/Caches/snakemake/snakemake/source-cache/runtime-cache/tmpb8uxytlv' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/cade/dev/snakemake-dev/snakemake/.pixi/envs/default/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/Users/cade/dev/snakemake-dev/snakemake/src/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
    ~~~~~~~~^^^^^^^

  File "/Users/cade/dev/snakemake-dev/snakemake/src/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Wed Nov  5 08:06:29 2025]
Error in rule test:
    message: None
    jobid: 1
    output: test-output
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Wed Nov  5 08:06:29 2025]
Error in rule test:
    message: None
    jobid: 1
    output: test-output
Complete log(s): /Users/cade/dev/sandbox/snaketest/.snakemake/log/2025-11-05T080627.776146.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

Because `run` (also `script`/`wrapper`) directives are executed in subprocesses (a _Snakemake subprocess_), the exception raised in the `run` block can't bubble up directly to the main Snakemake process. All the main Snakemake process can do is report that the subprocess failed via `SpawnedJobError` and by extension `CalledProcessError`.

I agree this is less than ideal for debugging, and I'm open to ideas to improve it. Unfortunately, logging with subprocesses is tricky because they compete for terminal output. One idea I've considered is to only allow the main Snakemake process to write to the terminal and have all jobs write their stdout/stderr to log files (to the path specified by the rule's `log` directive, or to auto-generated file(s) if `log` is omitted). This would make error information more accessible and organized, though it would be a significant change to the current behavior.
