### ISSUE TITLE
Deterministic DOT output for --dag/--rulegraph

### ISSUE THREAD

**Issue by standage** [snakemake/snakemake#1709]
When I run `snakemake --dag | dot` or `snakemake --rulegraph | dot` multiple times on the same workflow, I get diagrams with identical layout but different colors for the various nodes. I'm investigating how feasible it would be to make the output from `snakemake --dag` and `snakemake --rulegraph` deterministic.

Unless I've missed or misunderstood something, the code for coloring nodes in the `DAG._dot` method is deterministic.

https://github.com/snakemake/snakemake/blob/cc6c9986271738dfa8394fc45720a4d756af9d0a/snakemake/dag.py#L1976-L1981

Being unfamiliar with Snakemake internals, if I had to guess, I'd assume that the non-deterministic behavior comes when iterating over `self.jobs`, which happens both for `--dag` and `--rulegraph` modes.

https://github.com/snakemake/snakemake/blob/cc6c9986271738dfa8394fc45720a4d756af9d0a/snakemake/dag.py#L1962

https://github.com/snakemake/snakemake/blob/cc6c9986271738dfa8394fc45720a4d756af9d0a/snakemake/dag.py#L1937-L1938

Am I on the right track here? Would it be possible with a reasonable amount of effort to generate DOT output deterministically for these modes?

**Comment by tbooth** [comment]
PR accepted. Closing issue.

**Comment by standage** [comment]
Great, thank you!
