### ISSUE TITLE
Setting `--profile` from the `snakemake` function

### ISSUE THREAD

**Issue by lauren-mak** [snakemake/snakemake#1712]
OS: Red Hat Enterprise Linux Server release 6.3 (Santiago)
conda version: 4.12.0
Snakemake version: 7.3.7

**Is your feature request related to a problem? Please describe.**
While the command-line version of Snakemake has the option to set `profile` (i.e.: `snakemake --profile P ...` works), the function version does not (i.e.: doing `snakemake(profile = P, ...`) from a Python script does not work). I've been using a Click-based wrapper to streamline Snakemake parameters and conditions and it would be really useful to be able to be able to switch between Slurm and bash profiles from the wrapper as well. 

**Describe the solution you'd like**
Ability to set profiles like `snakemake(profile = P, ...`).

**Describe alternatives you've considered**
My current workaround involves setting the the environment variable `SNAKEMAKE_PROFILE` within the wrapper by using `os.environ['SNAKEMAKE_PROFILE']`. Not a lot of extra code but the suggestion would make it cleaner.

**Comment by pvandyken** [comment]
See here #1488 for why this isn't super viable right now and for other workarounds.

**Comment by lauren-mak** [comment]
Understood! Thanks for the explanation. Could you provide an example of setting the `profile` parameter using `snakemake.main(["arg1", "arg2", etc...])`? I went through `__init__.py` to see how `main()` is implemented but I'm still a little confused as to how to set parameters using `main()`'s arguments.

**Comment by pvandyken** [comment]
Exactly the same way you call from the cli


```
snakemake.main(["--profile", "profile_name", "other_arg", "other_arg2", ...])

```
