### ISSUE TITLE
Developper Documentation

### ISSUE THREAD

**Issue by MatheoDumont** [snakemake/snakemake#1724]
Hi everyone, 

My goal is  ... to generate a simple GUI, not to build Workflows using snakemake, but realy just to generate a GUI based on a snakefile that would represent the workflow.

My first attempt was to use snakemake itself :

```python 


from snakemake.workflow import Workflow

import os
snakefile = os.path.abspath("Snakefile")
rerun_trigger = ["mtime", "params", "input", "software-env", "code"]
wf = Workflow(snakefile, rerun_trigger)
wf.include(
    snakefile,
    overwrite_default_target=True,
    print_compilation=False,
)


print([r.name for r in wf.rules])

```

Im running this script with the snakefile of the *hello-world* example.
So my questions are : 
- " Is there a better way to do this ?"
- " Is is recommanded or not ?"
- " Does the source code changes often ?" 
- " What could go wrong ?"

Thanks in advance

**Comment by pvandyken** [comment]
None of the internals of Snakemake are public api, only whatever is explicitly documented. So things can definitely change. There are folks who will make direct class to the `snakemake()` function, and this would be a lot safer than calling `Workflow` directly, which has a very complicated interface you would be responsible for understanding if you want to use it. The [snakebids](https://github.com/akhanf/snakebids) approach (a snakemake neuroimaging wrapper I'm involved with), is to call `snakebids.__init__.main()` and just pass CLI commands directly. This for now is the safest approach.
