### ISSUE TITLE
"Missing files after 5 seconds" but files already exist; strange snakemake tmp file included

### ISSUE THREAD

**Issue by rovertsnisuoc** [snakemake/snakemake#1734]
I have a strange error that I require assistance with; I believe it may be a bug.

I have a set of existing files which snakemake will take as input. As a wildcard I have the variable 'sample', which takes values in ['english', 'french', 'german']. For each of these samples there is a folder with a set of mhs files. As a skeletal example, the directory structure is like this:
-/home/trevor/genomes/{sample}/mhs
     -chrom1.mhs
     -chrom2.mhs
     -chrom3.mhs
     ...
     -chrom22.mhs
for sample in ['english', 'french', 'german']

As an input for my rule, i need the path and file for each of these .mhs files. I have a very simple Snakefile for this:

def files_names(wildcards):
    path = f'/home/trevor/genomes/{wildcards.sample}/mhs/'  
    files_in_dir = os.listdir(path)
    files = [path + file for file in files_in_dir if '.mhs' in file and "X" not in file]
     return files

samples = ['english', 'french', 'german']

rule all:
    input:
        [f'/home/trevor/genomes/{sample}/mhs/ ' for sample in samples]

rule inference:
    input:
        files_names
    output:
        outfolder = directory('/home/trevor/genomes/{sample}/analysis/ ')
    log:
       ' /home/trevor/genomes/{sample}/analysis/log.log'
    run:
        shell(
            f'python /home/trevor/genome_analysis.py -in {" ".join(files_names(wildcards))} -o {output.outfolder} > {log}'
        )

Now for the curious part. If i run locally with "snakemake --cores 1" this finishes absolutely fine, no problem. If i submit to my cluster with "snakemake --jobs 4 --cluster "sbatch -A <account_name> -t 35:59:59 -p <cluster>" then I get a very curious error. If my sample was 'french', then the error says:

Waiting at most 5 seconds for missing files.
Missing files after 5 seconds:
['/home/trevor/snakemake_analysis_220403/.snakemake/tmp.j7xt53nx', '/home/trevor/genomes/french/mhs/chrom1.mhs', '/home/trevor/genomes/french/mhs/chrom2.mhs', '/home/trevor/genomes/french/mhs/chrom3.mhs',...]

I know that the mhs files exist; I can even nano the printed file paths from the above to verify there is no mistake. So the problem is this file '/home/trevor/snakemake_analysis_220403/.snakemake/tmp.j7xt53nx' that somehow get's appended to my input files. As the files already exist before running snakemake, it is not a problem with latency as described in this question https://groups.google.com/g/snakemake/c/upwycZU9auk .

So my question is, why is this file getting appended when I submit to the cluster? There is nothing I can see that would add this, in the function files_names() or the shell command line. It's strange that this comes up as a problem when submitting to the cluster but not when running locally. Maybe this is not a snakemake problem per se, but a problem with the cluster I am using. Does anyone have any ideas, or better ways to write this script?

Note that my cluster uses sbatch as a job management system and when i submit my snakemake, I do it from the directory /home/trevor/snakemake_analysis_220403/

Thanks and best wishes,

Trevor

Note: I asked this question on Google groups here: https://groups.google.com/g/snakemake/c/1tILX2Ui02g but repost here.

**Comment by chrarnold** [comment]
You should increase the time to at least 30 seconds on shared and cluster file systems, 5 seconds is simply not enough. Does this solve your issue?

**Comment by rovertsnisuoc** [comment]
No, it is not a problem with latency as the files exist already. The problem is this strange 'tmp' file that get's appended. Further, this only occurs as a bug in the "input" section; when snakemake is checking the input files, this file gets added. If I have the same command executed in the "run" section with shell, then this problem does not occur. 

Any ideas?

**Comment by Ulthran** [comment]
Getting the same issue, runs fine locally but run on the cluster it can't seem to find files that do exist:

```
Missing files after 240 seconds:
['.../.snakemake/tmp.ma7p_g42', '.../file1.tsv', '.../file2.tsv', ..., '.../.snakemake/35b1a59432df46a3d73d60a235fc4710']
```

It's happening for 3 separate rules in our pipeline:

```
rule kraken2_biom:
    input:
        expand(str(CLASSIFY_FP/'kraken'/'{sample}-taxa.tsv'),
               sample=Samples.keys())
    conda:
        "../../envs/classify.yml"
    output:
        str(CLASSIFY_FP/'kraken'/'all_samples.biom')
    shell:
        """
        kraken-biom --max D -o {output} {input}
        """
```

```
rule preprocess_report:
    """Combines the information from multiple preprocessing steps"""
    input:
        trim_files = expand(
            str(QC_FP/'log'/'trimmomatic'/'{sample}.out'),
            sample=sorted(Samples.keys())),
        decontam_files = expand(
            str(QC_FP/'log'/'decontam'/'{sample}_1.txt'),
            sample=sorted(Samples.keys())),
        komplexity_files = expand(
            str(QC_FP/'log'/'komplexity'/'{sample}.filtered_ids'),
            sample=sorted(Samples.keys())),
    output:
        str(QC_FP/'reports'/'preprocess_summary.tsv')
    conda:
        "../../envs/reports.yml"
    script:
        "../../scripts/reports/preprocess_report.py"
```

```
rule fastqc_report:
    """ make fastqc reports """
    input:
        files = expand(
            str(QC_FP/'reports'/'{sample}_{rp}_fastqc/fastqc_data.txt'),
            sample=Samples.keys(),rp=Pairs)
    output:
        str(QC_FP/'reports'/'fastqc_quality.tsv')
    conda:
        "../../envs/reports.yml"
    script:
        "../../scripts/reports/fastqc_report.py"
```

**Comment by rovertsnisuoc** [comment]
Hi Charlie,

I believe this problem is a bug. I solved it by updating to new version of snakemake. Version 7.8.5 works for me now. I believe the problem was with version 7.3.2.

Hope it helps.

Trevor

**Comment by Ulthran** [comment]
> Hi Charlie, I believe this problem is a bug. I solved it by updating to new version of snakemake. Version 7.8.5 works for me now. I believe the problem was with version 7.3.2.

Thanks Trevor, updating the version does fix this. We had originally downgraded from 7.8 to 7.3.2 to fix an issue with sym links not being recognized as inputs so now we'll have to find a version that fixes both of these. So far 7.15.1 is looking promising.
