### ISSUE TITLE
--profile doesn't take absolute path correctly

### ISSUE THREAD

**Issue by lyj95618** [snakemake/snakemake#1738]
**Snakemake version**

snakemake version: snakemake-7.8.3
python version: 3.8.0

**Describe the bug**

the `--profile`  option doesn't take the absolute path that I am providing. I tried to run the snakemake command outside the working directory where the Snakefile and slurm_profile folder are. Since I am providing everything with the absolute path, I thought that should be fine. It seems like instead of using the provided absolute path, snakemake is looking for the slurm_profile folder in the directory that the command is being executed.

My input and the error message are below:

`snakemake --jobs 10 -s /srv/shared/pipelines/clinical_pipeline/Snakefile --configfile /srv/shared/analyses/RNAseq/test_2022_06_23_ID123/config.yaml --config sample_file=/srv/shared/analyses/RNAseq/test_2022_06_23_ID123/test_2022_06_23_ID123.txt root_dir=/srv/shared/analyses/RNAseq/test_2022_06_23_ID123 --profile /srv/shared/pipelines/clinical_pipeline/slurm_profile`

```
Traceback (most recent call last):
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/bin/snakemake", line 11, in <module>
    load_entry_point('snakemake==7.8.3', 'console_scripts', 'snakemake')()
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/lib/python3.8/site-packages/snakemake/__init__.py", line 2828, in main
    success = snakemake(
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/lib/python3.8/site-packages/snakemake/__init__.py", line 419, in snakemake
    configs = [load_configfile(f) for f in cluster_config]
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/lib/python3.8/site-packages/snakemake/__init__.py", line 419, in <listcomp>
    configs = [load_configfile(f) for f in cluster_config]
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/lib/python3.8/site-packages/snakemake/io.py", line 1696, in load_configfile
    config = _load_configfile(configpath)
  File "/srv/shared/pipelines/clinical_pipeline/python_venv/lib/python3.8/site-packages/snakemake/io.py", line 1661, in _load_configfile
    obj = open(configpath_or_obj, encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'slurm_profile/slurm-config.yaml'
```

Thanks!
Laur

***

**Update on Jun23**

I was able to run the above snakemake command in the destinated output directory after I copied the whole slurm_profile folder from my working directory to the destinated output directory. I think this confirms that the `--profile`  option isn't taking the provided absolute path in the command. Hope this helps!

Laur

**Comment by chrarnold** [comment]
I agree, if an absolute path is specified, it should work, I didnt try by myself yet. If one specifies a "global" profile that is shared across projects, specifying an absolute path seems like the way to go

**Comment by pvandyken** [comment]
Is this still an issue on the latest versions of snakemake? I'm unable to reproduce

**Comment by lyj95618** [comment]
> Is this still an issue on the latest versions of snakemake? I'm unable to reproduce

It was an issue back in the snakemake-7.8.3. If you can't reproduce it now I guess it has been fixed? Thanks!

**Comment by pvandyken** [comment]
Okay, I'll close then. Feel free to reopen if you come across it again
