### ISSUE TITLE
Snakemake 7.9.0 may fail with "Error recording metadata for finished job: File name too long"

### ISSUE THREAD

**Issue by GianlucaFicarelli** [snakemake/snakemake#1771]
**Snakemake version**: 7.9.0

**Describe the bug**

Snakemake 7.9.0 may fail with "Error recording metadata for finished job: File name too long"

**Logs**

Relevant error message (after replacing the base dir and the base64 encoding):

```
WorkflowError:
Error recording metadata for finished job ([Errno 36] File name too long: '/path/to/workdir/.snakemake/metadata/tmp<base64_encoding>'). Please ensure write permissions for the directory /path/to/workdir/.snakemake
```

**Minimal example**

```
rule test:
    output: "012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678"
    shell: "echo 'ok' > {output}"
```

Command failing with Snakemake 7.9.0, succeeding with Snakemake 7.8.5:
```
snakemake -c1
```

**Additional context**

The issue doesn't happen with snakemake 7.8.5. It could have been introduced by https://github.com/snakemake/snakemake/pull/1745 in https://github.com/snakemake/snakemake/blob/6968fe7cfa3ec2f1e01862c5b270622d0ecbc2b0/snakemake/persistence.py#L436

Here, the tmpfile is built with `suffix=os.path.basename(recpath)`, but the resulting name may be longer than 255 characters.

**Comment by gemygk** [comment]
I get the same error with Snakemake 7.9.0

```
Failed to set marker file for job started ([Errno 36] File name too long: '/xxx/.project-scratch/2/2fcbfbef-13aa-451e-b420-00e21e2a35c3/xxx/Analysis/xxx/test/run1/.snakemake/incomplete/tmpo9grzin1L2VpLy5wcm9qZWN0LXNjcmF0Y2gvMi8yZmNiZmJlZi0xM2FhLTQ1MWUtYjQyMC0wMGUyMWUyYTM1YzMvQ0ItUFBCRlgtMTAzNF9Ub3plcl9FSV9MU19FTlEtNDgzOV9BXzAxL0FuYWx5c2lzL2VpZ2F0ay0xLjAuMV9DQkcvdGVzdC9ydW4xL291dHB1dC9zYW1wbGVzL0E2Nzg3MV8xL0E2Nzg3MV8xLmJ3YV9tZW0uY29tcGxldGVk'). Snakemake will work, but cannot ensure that output files are complete in case of a kill signal or power loss. Please ensure write permissions for the directory /xxx/.project-scratch/2/2fcbfbef-13aa-451e-b420-00e21e2a35c3/xxx/Analysis/xxx/test/run1/.snakemake
WorkflowError:
Error recording metadata for finished job ([Errno 36] File name too long: '/xxx/.project-scratch/2/2fcbfbef-13aa-451e-b420-00e21e2a35c3/xxx/Analysis/xxx/test/run1/.snakemake/metadata/tmpi6pulmb1L2VpLy5wcm9qZWN0LXNjcmF0Y2gvMi8yZmNiZmJlZi0xM2FhLTQ1MWUtYjQyMC0wMGUyMWUyYTM1YzMvQ0ItUFBCRlgtMTAzNF9Ub3plcl9FSV9MU19FTlEtNDgzOV9BXzAxL0FuYWx5c2lzL2VpZ2F0ay0xLjAuMV9DQkcvdGVzdC9ydW4xL291dHB1dC9zYW1wbGVzL0E2Nzg3MV8xL0E2Nzg3MV8xLmJ3YV9tZW0uY29tcGxldGVk'). Please ensure write permissions for the directory /xxx/.project-scratch/2/2fcbfbef-13aa-451e-b420-00e21e2a35c3/xxx/Analysis/xxx/test/run1/.snakemake
```

**Comment by johanneskoester** [comment]
Thanks, and sorry! Will  be fixed with PR #1780

**Comment by gemygk** [comment]
Thanks a lot @johanneskoester

**Comment by ctr26** [comment]
I think I'm experiencing a similiar error on windows, snakemake version is 7.32.3
    snakemake.exceptions.WorkflowError: Error recording metadata for finished job ([WinError 3] The system cannot find the path specified: 'C:\\Users\\Administrator\\Downloads\\**************************************\\.snakemake\\metadata\\tmpwwx1rojg.QzovVXNl' -> 'C:\\Users\\Administrator\\Downloads\\**************************************\\.snakemake\\metadata\\QzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb3dubG9hZHMvT25lRHJpdmVfMV84LTI5LTIwMjMvQW5ub3RhdGlvbnMvSEktVGVhbS1EZWVwTGVhcm5pbmctSEUtZnJvbS1EQVBJLUUyMi04ODhfcHJlZC5wbmcuYW5ub3RhdGlvbnMueG1s'). Please ensure write permissions for the directory C:\Users\Administrator\Downloads\\**************************************\\.snakemake
    
Path length is well over the 256 windows default
