### ISSUE TITLE
Order jobs in the job stats table by depth in the DAG

### ISSUE THREAD

**Issue by tedil** [snakemake/snakemake#1774]
Currently, the job stats table lists jobs in lexicographical order. This makes it easy to find specific rules if you know the names. However, I think that in many cases it might be more convenient and helpful to list the jobs by depth in the DAG first.

Not sure if that has to be yet another cli option or could just replace the default behaviour.

**Comment by svenrahmann** [comment]
good idea! should get priority.

**Comment by tedil** [comment]
> Is this a duplicate of #1767? and possibly of another issue I vaguely remember?

Yes, this seems to be the case; I will close this issue then in favour of #1767.
