### ISSUE TITLE
multiext and cache fail if suffixes to not start with dot

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#1808]
**Snakemake version**

`v7.12.1`

**Describe the bug**

There seems to be an issue when using `multiext` with suffixes that do not start with a `.`, and `--cache`.

When running example 1 with:
- `snakemake results/data/worldcitiespop.csv --jobs 1 --cache`: OK
- `snakemake results/data/worldcitiespop.csv --jobs 1`: OK
- `snakemake results/data/worldcitiespop_csv --jobs 1 --cache`: FAIL
- `snakemake results/data/worldcitiespop_csv --jobs 1`: OK

When running example 2 with:
- `snakemake results/data/worldcitiespop.csv --jobs 1 --cache`: FAIL
- `snakemake results/data/worldcitiespop.csv --jobs 1`: OK
- `snakemake results/data/worldcitiespop_csv --jobs 1 --cache`: FAIL
- `snakemake results/data/worldcitiespop_csv --jobs 1`: OK

**Logs**

`ValueError: Invalid suffix '_csv'`

**Minimal example**

EXAMPLE 1:
```
rule download_data1:
    output:
        multiext("results/data/worldcitiespop", ".csv", ".tsv"),
    cache: True
    shell:
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[0]};"
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[1]};"

rule download_data2:
    output:
	multiext("results/data/worldcitiespop", "_csv", "_tsv"),
    cache: True
    shell:
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[0]};"
	"curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[1]};"
```
EXAMPLE 2:
```
rule download_data3:
    output:
        multiext("results/data/worldcitiespop.", "csv", "tsv"),
    cache: True
    shell:
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[0]};"
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[1]};"

rule download_data4:
    output:
	multiext("results/data/worldcitiespop_", "csv", "tsv"),
    cache: True
    shell:
        "curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[0]};"
	"curl -L https://burntsushi.net/stuff/worldcitiespop.csv > {output[1]};"
```

**Additional context**

I think the problem is in [pathlib](https://github.com/python/cpython/blob/7da4937748eb588bb0e977839061ce76cab1b252/Lib/pathlib.py#L641-L642), since they require the suffixes to start with `.`. However I do not think this constraint makes sense in `snakemake`.

**Comment by niekwit** [comment]
I have the exact same issue:
```Python
rule salmon_index:
    input:
        sequences="resources/gentrome.fasta",
        decoys="resources/decoys.txt",
    output:
        multiext(
            "resources/transcriptome_index/",
            "complete_ref_lens.bin",
            "ctable.bin",
            "ctg_offsets.bin",
            "duplicate_clusters.tsv",
            "info.json",
            "mphf.bin",
            "pos.bin",
            "pre_indexing.log",
            "rank.bin",
            "refAccumLengths.bin",
            "ref_indexing.log",
            "reflengths.bin",
            "refseq.bin",
            "seq.bin",
            "versionInfo.json",
        ),
    cache: True
    log:
        "logs/salmon/index.log"
    threads: 12
    params:
        # optional parameters
        extra="",
    wrapper:
        "v3.7.0/bio/salmon/index"
```
It works with `cache: False`, but not with `cache: True`. Tested on both Snakemake v7.32.4 and v8.10.6.

Error:
```shell
ValueError: Invalid suffix 'complete_ref_lens.bin'
```

**Comment by fgvieira** [comment]
@niekwit just made a PR that tries to fix this. Can you check if it works in your case?
