### ISSUE TITLE
Prebuild conda env does not activate in "script:" rule

### ISSUE THREAD

**Issue by Jahysama** [snakemake/snakemake#1811]
**7.12.1**

**Bug**
Prebuild conda env won't activate if  python `script:` is used in rule.

**Logs**
```
Traceback (most recent call last):
  File "/home/kosar/.snakemake/scripts/tmp2b81whnx.test.py", line 5, in <module>
    import luigi
ModuleNotFoundError: No module named 'luigi'
[Mon Aug 15 14:36:04 2022]
Error in rule test:
    jobid: 1
    output: output.txt
    conda-env: test

RuleException:
CalledProcessErrorin line 13 of /home/kosar/Snakefile:
Command 'set -euo pipefail;  /home/kosar/miniconda3/envs/snakemake/bin/python /home/kosar/.snakemake/scripts/tmp2b81whnx.test.py' returned non-zero exit status 1.
  File "/home/kosar/Snakefile", line 13, in __rule_test
  File "/home/kosar/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-08-15T143603.846897.snakemake.log

```

**Minimal example**
Prebuild conda env does not activate in `script:` rule. A simple example files to reproduce:
```
rule all:
    input:
        o='output.txt'
        
rule test:
    input:
        i='input.txt'
    output:
        o='output.txt'
    conda:
        'test'
    script:
        'test.py'
```
test.py:
```
import luigi

with open('output.txt', 'w') as file:
	file.write("something")
```
You also need to create a conda env named `test` with luigi in it (I'm using luigi, but it can be any package not installed in your base env):
```
conda create --name test python=3.9
conda activate test
pip install luigi
```

**Additional context**
I'm considering using argparse with python scripts inside `shell:` to get rid of this error. It works with `.yaml/.yml` defined envs in `conda:`. I'm using prebuild envs, because i need to speed up my initial pipeline working time.

**Comment by moritzschaefer** [comment]
Can we close this (fixed by 7.30.1 #1812/#2332)?

**Comment by tgelafr-btx** [comment]
I continue to have this problem even with Snakemake version 7.30.1, using the same minimal example provided above. For me, though, it also doesn't work from a yaml.

**Comment by Janzulene** [comment]
got the same error in Snakemake version 8.25.5, when allocating my own exists conda environment, is runs command like "source <conda-env>; set -euo pipefail; <snakemake-python> <script.py>", which should use <conda-env-python> instead of <snakemake-python>.
