### ISSUE TITLE
Snakefile creates empty Batch script when submitted with `sbatch` 

### ISSUE THREAD

**Issue by lauren-mak** [snakemake/snakemake#1830]
**Snakemake version**: 7.8.5

**Describe the bug**

I get the error `sbatch: error: Batch script is empty!` after submitting the Snakefile to a compute cluster using `sbatch`. However, this error does not occur locally and the entire Snakefile runs fine. I've tried each of the individual commands in the `shell` section too and they run fine as well. Running `snakemake` with `--verbose` didn't give me more any more details about the error.

**Minimal example**

Snakefile: 
```Python
rule all:
    input: 
        expand(join('1_cmseq', '{sample}', 'report.csv'), sample = SAMPLES)

rule rename_fasta:
    input:
        join('{sample}', '{bin_num}.fa'),
    output:
        join('1_cmseq', '{sample}', '{bin_num}.fa'),
    params:
        bin_num = '{bin_num}',
        out_dir = join('1_cmseq', '{sample}'),
    shell:
        """
        echo {input}
        echo {output}
        echo {params.out_dir}
        mkdir -p {params.out_dir}
        cat {input} > {output}
        """


def get_bin_nums(s, d):
    tmp = open(join(d, str(s) + '.out'), 'r').readlines()
    print(*[i.strip() for i in tmp])
    return [i.strip() for i in tmp]


rule aggregate_fasta:
    input:
        lambda wildcards: expand(rules.rename_fasta.output, bin_num = get_bin_nums(wildcards.sample, './'), sample = wildcards.sample)
    output:
        join('1_cmseq', '{sample}', 'report.csv'),
    run:
        with open(str(output), 'a') as f_out:
            for i in input:
                f_out.write(str(i) + '\n')
```

Submission command:
```Bash
snakemake   --snakefile /home/lam4003/bin/Snakefile \
            --config "samples"="1_ASM131464v1_genomic" \
            --jobname "{wildcards}.{rulename}.{jobid}" \
            --cluster "sbatch -n {cluster.nCPU} --mem {cluster.mem}"
```

**Comment by rschauner** [comment]
Are you writing `sbatch /home/lam4003/bin/Snakefile` or do you run something like `sbatch submit.sh`? If you are doing the former (`sbatch /home/lam4003/bin/Snakefile`), that might explain it since slurm relies on shell scrips for submission. You might also consider using a [snakemake profile for slurm](https://github.com/Snakemake-Profiles/slurm) instead of using the old `--cluster` option.

***submit.sh***
```bash
#SBATCH COMMANDS
snakemake   --snakefile /home/lam4003/bin/Snakefile \
            --config "samples"="1_ASM131464v1_genomic" \
            --jobname "{wildcards}.{rulename}.{jobid}" \
            --cluster "sbatch -n {cluster.nCPU} --mem {cluster.mem}"
```

**Comment by lauren-mak** [comment]
I'm actually trying an `sbatch` hack by using `snakemake.main()` inside a Python script instead of submitting a shell script. So what's actually happening is:

On the command line:
```
python /path/to/cli.py --slurm
    -w /path/to/Snakefile \
    -d /work/dir \
    -s samples.csv
```

The `--slurm` flag calls the following function from within `cli.py`:
```
main([
    '--snakefile',      /path/to/Snakefile, 
    '--config',        vars,
    '--use-conda',
    '--conda-frontend', 'conda',
    '--cluster-cancel', 'scancel',
    '--cluster',        "sbatch -J {wildcards}.{rulename}.{jobid} \
                         -n {threads} --mem {resources.mem_mb} -o {log}"
])
```

Is there something in this setup that is messing with the `sbatch` submission command?

**Comment by rschauner** [comment]
It looks like you're just trying to make a wrapper script for some default options all running on a submission (login) node, let me know if this isn't right. 

If that's the case, an easier way may just to be to use the slurm profile option (https://github.com/Snakemake-Profiles/slurm), and use subprocess to start snakemake, so you would have a python script like this:
```python
import subprocess
import argparse

# get arguments using argparse
argv = parser.parse_args()

# I like to build command in chunks
cmd = ["snakemake", "--snakefile", argv.snakefile, ...] # keep going through rest of arguments
slurm_prof = [ "--profile", "slurm"]
if argv.slurm:
    # Allows unnesting of commands
    cmd = [cmd, slurm_prof]
    cmd = [val for sublist in cmd for val in sublist]
subprocess.run(cmd, check=True, stdout=subprocess.STDOUT, stderr=subprocess.STERR)
```
You should be able to use other python code you have in `cli.py` to create your subprocess command. You could likely do this using a standard shell script. The `--cluster-config` interface is deprecated in favor of profiles, and it looks like you have several options here in your cluster command. I've used this specific profile, but there's another here (https://github.com/jdblischak/smk-simple-slurm) that you can use too. If it works with the profile, but not with your `--cluster` flag options, I'm pretty sure it's just set up improperly then.

**Comment by lauren-mak** [comment]
Honestly, I would have started with something like that, or even wrapped the whole command in some kind of bash script. However, the way my CLI organizes parameters (three variables- see `cfg_*` below- and two YAML config files) makes it very annoying to format in both `subprocess.run(cmd,...)` or Bash script format. The line `'--config', vars` actually expands to:
```
'--config',         *{cfg_wd, cfg_sp, cfg_ey},
'--configfiles',    *[pyaml, ryaml],
```
It's almost unnecessarily complex, but from endless testing, it's easier for setup to keep different categories of variables separate. 

So as you can see, the full command is a pain to write out, whether it's in list format for `subprocess.run()` or in Bash. Moreover, when I've tried to write full commands in the past, each successive variable would overwrite the previous one. For example, the value of `cfg_ey` would overwrite the value of `cfg_sp` even from inside a dictionary, and any values in `ryaml` would overwrite any values in `pyaml`. 

With a complex variable and YAML management system, what would you recommend I do?

**Comment by rschauner** [comment]
Have you tried just using `--profile slurm` instead of using `--cluster`?

**Comment by lauren-mak** [comment]
I've briefly explored Snakemake profiles but held off on using them because I'm not familiar with how it differs from `--cluster` which I thought I was familiar with. How does the implementation of `--profile` differ from `--cluster`? Will I still have access to other flags like `--config`, `--configfiles`, and `--conda`?

**Comment by rschauner** [comment]
In short, yes. Here's the command I use:

```
snakemake \
    --quiet \
    --cores all \
    --use-conda \
    --use-singularity \
    --profile slurm
```

**Comment by lauren-mak** [comment]
I customized the simple Slurm profile `config.yaml` with basically all of the same things I was doing with `--cluster` and for reasons unknown it worked like a charm! Thanks again.
