### ISSUE TITLE
Unable to detect txt files

### ISSUE THREAD

**Issue by GiangLeN** [snakemake/snakemake#1838]
I was testing out the lambda function and came across a strange behavior from Snakemake (version 7.12.1).
Here is a minimum example of the bug

```
touch aba.txt bcb.txt cdc.txt aba.tsv bcb.tsv cdc.tsv
````

Snakefile1:

```
FILENAME = {'one':"aba.txt", "two":"bcb.txt", "three":"cdc.txt"}

rule all:
    input:
        expand("{number}.txt", number = FILENAME.keys())

rule check:
    input:
        lambda wildcards: FILENAME[wildcards.number]
    output:
        "{number}.txt"

    shell:
        """
        echo {input}
        """
```

The error generated by Snakemake:

```
InputFunctionExceptionin line 9 of /home/vdsa/gdata/rd_fun/Snakefile:
Error:
  KeyError: 'aba'
Wildcards:
  number=aba
Traceback:
  File "/home/vdsa/gdata/rd_fun/Snakefile", line 11, in <lambda>
```

When txt is changed to tsv, the error is no longer there.

Snakefile2:

```
FILENAME = {'one':"aba.tsv", "two":"bcb.tsv", "three":"cdc.tsv"}

rule all:
    input:
        expand("{number}.txt", number = FILENAME.keys())

rule check:
    input:
        lambda wildcards: FILENAME[wildcards.number]
    output:
        "{number}.txt"

    shell:
        """
        echo {input}
        """
```

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count    min threads    max threads
-----  -------  -------------  -------------
all          1              1              1
check        3              1              1
total        4              1              1

Select jobs to execute...

[Sun Aug 28 20:11:43 2022]
rule check:
    input: cdc.tsv
    output: three.txt
    jobid: 3
    reason: Missing output files: three.txt
    wildcards: number=three
    resources: tmpdir=/tmp

cdc.tsv
Waiting at most 5 seconds for missing files.
```

It seems like Snakemake could not detect the txt file.

**Comment by dariober** [comment]
I cannot reproduce the issue:

```
cat Snakefile 
FILENAME = {'one':"aba.tsv", "two":"bcb.tsv", "three":"cdc.tsv"}

rule all:
    input:
        expand("{number}.txt", number = FILENAME.keys())

rule check:
    input:
        lambda wildcards: FILENAME[wildcards.number]
    output:
        "{number}.txt"

    shell:
        """
        echo {input}
        """

snakemake -p -n -j 1 -s Snakefile 
Building DAG of jobs...
MissingInputException in rule check in line 7 of /home/dario/Downloads/Snakefile:
Missing input files for rule check:
    output: one.txt
    wildcards: number=one
    affected files:
        aba.tsv

snakemake -v
7.12.1
```

**Comment by GiangLeN** [comment]
> I cannot reproduce the issue:
> 
> ```
> cat Snakefile 
> FILENAME = {'one':"aba.tsv", "two":"bcb.tsv", "three":"cdc.tsv"}
> 
> rule all:
>     input:
>         expand("{number}.txt", number = FILENAME.keys())
> 
> rule check:
>     input:
>         lambda wildcards: FILENAME[wildcards.number]
>     output:
>         "{number}.txt"
> 
>     shell:
>         """
>         echo {input}
>         """
> 
> snakemake -p -n -j 1 -s Snakefile 
> Building DAG of jobs...
> MissingInputException in rule check in line 7 of /home/dario/Downloads/Snakefile:
> Missing input files for rule check:
>     output: one.txt
>     wildcards: number=one
>     affected files:
>         aba.tsv
> 
> snakemake -v
> 7.12.1
> ```

What you did above is the expected behavior from snakemake.
If you change *tsv* to *txt* in your Snakefile

```
FILENAME = {'one':"aba.txt", "two":"bcb.txt", "three":"cdc.txt"}
```

and run the Snakefile with:

```
snakemake -p -j 1 -s Snakefile
```

This is what I got:

```
Building DAG of jobs...
InputFunctionExceptionin line 7 of /home/vdsa/gdata/rd_fun/Snakefile:
Error:
  KeyError: 'aba'
Wildcards:
  number=aba
Traceback:
  File "/home/vdsa/gdata/rd_fun/Snakefile", line 9, in <lambda>
```

**Comment by dariober** [comment]
I think I see the issue now (maybe)... Why doesn't it work with *.txt and why does snakemake try to use `aba` as a wildcard value?  

If it helps, adding this before rule `all` recovers the expected behavior:

```
wildcard_constraints:
    number='|'.join([re.escape(x) for x in FILENAME.keys()])
``` 

As an aside, in my opinion is always better to constrain wildcards to the expected list of values rather than relying on unclear pattern mathing - one can always relax the constraints later.
