### ISSUE TITLE
piped jobs fail and workflow stalls with no error message

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#1846]
**Snakemake version**

`7.14.0`

**Describe the bug**

I have three rules that work fine when run independently. If I pipe the outputs, they are launched as a group but only the first rule is executed and the groups fail, leaving the first job hanging and the pipeline stalled. Maybe related to #1822.
With version `7.3.2` all works fine but not with `7.3.3`.

Could it be that these lines are typos?

https://github.com/snakemake/snakemake/blob/90ae44943a6b7712d46677364752bf0a7cf91806/snakemake/common/__init__.py#L26

https://github.com/snakemake/snakemake/blob/90ae44943a6b7712d46677364752bf0a7cf91806/snakemake/common/__init__.py#L175

**Logs**

All log files are empty.

**Minimal example**

**Additional context**

**Comment by pdagosto** [comment]
I'm seeing something similar with snakemake 7.14.0. I have two pipelines that are using pipes demarcated by wildcards, e.g. rule1_R1, rule1_R2, rule2_R1, rule2_R2, etc. that should execute in parallel (see [975](https://github.com/snakemake/snakemake/issues/975) for a minimal example). Sometimes it runs without problems. Other times only one of the pipelines (R1 or R2) starts to execute but hangs and the other pipeline fails to even start. This is local execution in a Docker container so no cluster or cloud involved.

**Comment by fgvieira** [comment]
@pdagosto did you try running your workflow with `snakemake` version `7.3.2` and `7.3.3`? Did you get the same problems with either of them?

**Comment by pdagosto** [comment]
Yes - same problem with 7.3.2

**Comment by fgvieira** [comment]
It seems for me the problem is in the lines:
https://github.com/snakemake/snakemake/blob/77975952ce7df346729f76a767ad4f475b385306/snakemake/common/tbdstring.py#L11-L12

No idea why but, if I delete these lines, all works fine.
@johanneskoester any insight?
@pdagosto can you check if it also fixes your issue?

**Comment by johanneskoester** [comment]
Ok, could be that the __getattribute__ interferes with accessing flags on the TBDString. In any case, the method is not needed and should indeed be removed.
