### ISSUE TITLE
`--immediate-submit` have no effect on `--cluster` in recent versions

### ISSUE THREAD

**Issue by Hocnonsense** [snakemake/snakemake#1865]
**Snakemake version**  7.12.0 or later

**Describe the bug**
These days I'm confused about submitting jobs to slurm system.

Snakemake's doct says that snakemake can figure out the dependence of each jobs, submit each single jobs and get *jobid* for following jobs that depend on it. After submit all jobs, snakemake will exist without error.

However, after my test, snakemake can not work as expected and it act like this:

param|`--submit-immediate`|submit with dependence
-----|--------------------|------
`--cluster`|no effect     |can
`--cluster-sync`|no effect|cannot

However, snakemake works well in version 5.26.0. After comparing code difference, I notice this PR https://github.com/snakemake/snakemake/commit/41a5071#diff-74aa6da2e2c2c68332a739fc6147912376a9ecf5ee995f40f54eaf9fa3f6824fL214-L222 may cause this problem.

This submit keep `self._submit_callback` as `pass`
https://github.com/snakemake/snakemake/blob/dc45ccb9ee94e8fcdf386c8598bbae57e319ba10/snakemake/scheduler.py#L152-L153
and make `--immediate-submit` only effect on https://github.com/snakemake/snakemake/blob/dc45ccb9ee94e8fcdf386c8598bbae57e319ba10/snakemake/scheduler.py#L212-L216
These four parameters are only called in `self._finish_jobs`, which is waiting for `self._open_jobs` to be released
https://github.com/snakemake/snakemake/blob/dc45ccb9ee94e8fcdf386c8598bbae57e319ba10/snakemake/scheduler.py#L419-L423
However, `self._open_jobs` can only be released in 
https://github.com/snakemake/snakemake/blob/dc45ccb9ee94e8fcdf386c8598bbae57e319ba10/snakemake/scheduler.py#L581-L594
which can be called ONLY after job finished https://github.com/snakemake/snakemake/blob/dc45ccb9ee94e8fcdf386c8598bbae57e319ba10/snakemake/scheduler.py#L557-L565

**Logs**

**Minimal example**
I've wrote a test to descripe this question:
[test_immediate_submit](https://github.com/Hocnonsense/snakemake/tree/main/tests/test_immediate_submit)

**Additional context**

**Comment by johanneskoester** [comment]
Thanks! Fixed with #1851.
