### ISSUE TITLE
How to set a default value of params in a rule?

### ISSUE THREAD

**Issue by lijinbio** [snakemake/snakemake#1873]
I want to set a default value of one parameter under "snakemake@params". Right now, a parameter defined under "snakemake@params" is required and its value should be entered in the config.yaml. However, default values will shorten the config.yaml a lot. Could you please help suggest how to specify a default value of a parameter? Thanks.

**Comment by dariober** [comment]
You could do something like this:

```
if 'some_param' not in config:
    config['some_param'] = 'some-default-value'

rule one:
    params:
        some_param=config['some_param']
```

NB: Questions like this about usage of snakemake are better asked on stackoverflow

**Comment by lijinbio** [comment]
Thanks, @dariober. Your solution works perfectly. Yes, I will ask the usage questions on StackOverflow next time. Thanks.
