### ISSUE TITLE
'Code has changed' activates persistently on links to some filetypes

### ISSUE THREAD

**Issue by alfredsimkin** [snakemake/snakemake#1927]
Thank you for creating snakemake!! It is completely changing my life.

**Snakemake version:** 7.16.0

**Bug**: sequential runs of snakemake code (without making any changes to code in between) activate the 'code has changed' scenario when the task is a script that creates soft links to a file that was created with 'touch'. This means that steps that have already completed on snakemake will execute every time (code is always flagged as 'changed'), and that if these linking steps occur early in a pipeline, the entire pipeline runs every time code is executed.

(snakemake) alfred@marvel:$ snakemake -s linking.smk --cores 10

**Minimal example:**

At command line:
touch some_file.txt (where some_file.txt is a new file that has never existed before)

snakemake code:
rule link_file:
	output:
		output_file='new_file.fq'
	script:
		'linking.py'

python code (linking.py):
import subprocess
subprocess.call(['ln', '-s', '-T', 'some_file.txt', 'new_file.fq'])

**Logs:**

(snakemake) alfred@marvel:$ snakemake -s linking.smk --cores 10
[Sun Oct 23 12:30:20 2022]
rule link_file:
    output: new_file.fq
    jobid: 0
    reason: Code has changed since last execution
    resources: tmpdir=/tmp
[Sun Oct 23 12:30:20 2022]
Finished job 0.
1 of 1 steps (100%) done
Complete log: .snakemake/log/2022-10-23T123020.486655.snakemake.log

(snakemake) alfred@marvel:$ snakemake -s linking.smk --cores 10
[Sun Oct 23 12:30:21 2022]
rule link_file:
    output: new_file.fq
    jobid: 0
    reason: Code has changed since last execution
    resources: tmpdir=/tmp
[Sun Oct 23 12:30:22 2022]
Finished job 0.
1 of 1 steps (100%) done
Complete log: .snakemake/log/2022-10-23T123021.753082.snakemake.log

Note that only one second has passed between the first run and the second run - the code has not been modified, yet snakemake detects modified code and reruns things from the beginning.

**Additional info:**
This problem only appears if an empty file is created with (e.g.) 'touch' - as soon as the file is opened and data is stored in it, snakemake runs appropriately - running once and then recognizing that nothing needs to be done the second time. The problem also doesn't occur if the linking happens in a 'shell' invocation (rather than a 'script' invocation). This is still an issue for me though, because it also affects sshfs mounted remote file systems that hold fastq files that do contain data - snakemake seems to be treating them similarly to the empty 'touch' files and re-running them every time.

I will run snakemake with the --rerun-triggers mtime while this bug is around, but would love to have snakemake still be able to check for modified code when it runs on these problematic types of files in the future.

Thanks again for any help that can be provided in fixing this bug

**Comment by asimkinbrown** [comment]
Thanks for this Nate! You're absolutely right! In my case, I have some sequencing fastq files that were created some time ago, that I want to preserve as 'read only' files (to avoid having people accidentally corrupt them) but the files were poorly named, with no internal consistency. I have a snakemake script that first makes softlinks with standardized names, then another script that operates on these links as if they were input files.

It sounds like snakemake is seeing that my symlinking script is newer than the files that my symlinks point to, and is therefore saying that the 'output' of the symlinking script is newer than the input.

Maybe a workaround (given that I want the link targets to be read only) might be for me to have a 'dummy' file that gets created as the official output of the rule, and list the output links as parameters. Thanks again for your thoughtful help with this! Also, do you know of a 'snakemake user forum' I could use for similar questions in the future? I have several that I'm trying to work out, and have been looking around locally for an experienced snakemake buddy.

**Comment by ndwarshuis** [comment]
You are welcome

> Also, do you know of a 'snakemake user forum' I could use for similar questions in the future?

See the [docs](https://snakemake.readthedocs.io/en/stable/)
