### ISSUE TITLE
When a "comment" following an "include", it may occur an error with confusing message

### ISSUE THREAD

**Issue by DawnEve** [snakemake/snakemake#1943]
**Snakemake version**
```
$ snakemake --version
6.4.1

A friend tested on  version 7.16.0, the error remains, but with another error message.
```

**Describe the bug**
When a "#" in the next line of "include" and is the last line, the error occur.

**Logs**
```
SyntaxError in line 6 of /data/jinwf/wangjl/chenxi/pipeline/test/merge.smk:
unexpected EOF while parsing
```

**Minimal example**

```
1. fies under test/
.
├── merge.smk
└── tmp
    ├── a.txt
    ├── b.txt
    └── t1.smk

Where a.txt and b.txt can be anything.


2. The same file:
$ cat tmp/t1.smk 

rule merge:
    input: "tmp/a.txt", "tmp/b.txt"
    output: "tmp/c.txt"
    shell: "cat {input} > {output}"


3. the trick is merge.smk

When it only have 5 lines:
$ cat merge.smk
rule all:
    input:"tmp/c.txt"

include: "tmp/t1.smk" 
#include: "tmp/t2.smk" $ snakemake -s merge.smk -j 1 -p 
SyntaxError in line 5 of /data/jinwf/wangjl/chenxi/pipeline/test/merge.smk:
unexpected EOF while parsing


4. When I delete the last line(now 4 lines), it works.

$ rm tmp/c.txt
$ cat merge.smk 
rule all:
    input:"tmp/c.txt"

include: "tmp/t1.smk" [wangjl@biosrv test]$ snakemake -s merge.smk -j 1 -p
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	merge
	2
...




6. Or when I add a blank line below the "#" line, it works

$ rm tmp/c.txt
$ cat merge.smk 
rule all:
    input:"tmp/c.txt"

include: "tmp/t1.smk" 
#include: "tmp/t2.smk"
[wangjl@biosrv test]$ snakemake -s merge.smk -j 1 -p
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	merge
	2
...


```

**Additional context**
It would save me a lot of time if the error message here is more meaningful in this condition.
I want to elliminate this error Or give a more meaningful error hint. Thank you.

**Comment by pvandyken** [comment]
I'm able to reproduce. To add some context, it needs to be a comment, following an include, with no further lines following.

**Comment by pvandyken** [comment]
So the full problem here is that when the last item being processed a `KeywordState`, and when that item has no special `end()` conditions, meaning it uses the default:
```
	def end(self):
		yield ")"
```

and when the last line processed by this `KeywordState` is a comment, and when there is no newline beyond the comment, the final `)` gets added to the end of the commented line, leading to a syntax error.

For example, the example given in this issue compiles to:

```
@workflow.rule(name='all', lineno=1, snakefile='/home/knavynde/projects/nimi/test/merge.smk')

@workflow.input( "tmp/c.txt"
)

@workflow.norun()
@workflow.run
def __rule_all(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook, conda_base_path, basedir, runtime_sourcecache_path, __is_snakemake_rule_func=True):
        pass
workflow.include( "tmp/t1.smk"
#include: "tmp/t2.smk" )
```

Note the final parentheses is on the commented line.

Because this implicates any basic `TokenAutomaton`, I can create an equivalent bug using the following example:

```
rule foo:
    output: 
        'tmp/c.txt'
        #foo
```

I'm able to fix the issue with the following patch, which just adds a newline before the final parentheses:

```
diff --git a/snakemake/parser.py b/snakemake/parser.py
index 766e9d37..c77adea3 100644
--- a/snakemake/parser.py
+++ b/snakemake/parser.py
@@ -142,6 +142,7 @@ class KeywordState(TokenAutomaton):
         return self.__class__.__name__.lower()[len(self.prefix) :]

     def end(self):
+        yield "\n"
         yield ")"

     def decorate_end(self, token):
```

However, fixing this issue is ultimately beyond my ability, as parsing is a core function and a mistake could have many downstream consequences. @johanneskoester, assistance would be appreciated.

**Comment by johanneskoester** [comment]
@pvandyken thanks a lot for the proposed fix. This is indeed how it should be done, ideally with a comment referring to this issue, such that we don't remove the additional newline in the future.

**Comment by johanneskoester** [comment]
Can you create a PR (if possible including one of the mentioned test cases) and PM me via discord? I'll try to merge ASAP.
