### ISSUE TITLE
Improve documentation and sample examples

### ISSUE THREAD

**Issue by henrykironde** [snakemake/snakemake#1960]
After going through this tool's doc and trying several setups. I strongly recommend that the team look into enhancing the documentation.
I would also reduce the wording and emphasize simple explanations. Both the simplified and extended doc versions need some attention.

It would be nice to actually add the [documentation](https://github.com/snakemake/snakemake/labels/documentation) tag to all the document-related issues. It looks like the document-related issues cover almost 50% of the total issues. This would make working on these issues simple.

**Comment by pvandyken** [comment]
Specific suggestions to improving the docs would be welcome (especially PRs)! I'm closing this meantime, as it's too non-specific
