### ISSUE TITLE
Cluster jobs won't run when --set-resource-scopes is used

### ISSUE THREAD

**Issue by tbooth** [snakemake/snakemake#1968]
**Snakemake version**
7.18.2+0.ga5c35239.dirty

**Describe the bug**
Bug in `get_resource_scopes_args()` in `snakemake/executors/__init__.py` line 117 - and as far as I can see this method does nothing useful and should be removed entirely.

**Logs**
After running:
```
$ snakemake --drmaa --set-resource-scopes foo=local
```

The main workflow starts but all cluster jobs fail on startup with an error like this in the log:
```
$ cat ~/tmp/slurm_job.GROUP.3572731.err
Invalid resource scopes: entries must be defined as RESOURCE=SCOPE pairs, where SCOPE is either 'local', 'global', or 'excluded' (Unparseable value: 'foo')
```
Adding a `set -x` line to the jobscript confirms that the local invocation of snakemake does indeed include `--set-resource-scopes foo` when the original command correctly said `--set-resource-scopes foo=local`.

**Diagnosis**

The function `get_resource_scopes_args(self)` in `snakemake/executors/__init__.py` simply says:

```
return format_cli_arg(
            "--set-resource-scopes", self.workflow.overwrite_resource_scopes
        )
```
`format_cli_arg()` in turn calls `format_cli_pos_arg(value)` which performs the test `isinstance(value, dict)` (at `snakemake/executors/common.py` line 15). It looks like `workflow.overwrite_resource_scopes` should pass this test and thus be formatted as `key=value` pairs but in fact it's an instance of `<class 'snakemake.resources.ResourceScopes'>` which inherits from `collections.UserDict` and does not pass the `isinstance(value, dict)` test. Therefore it gets formatted as regular iterable (ie. only the keys are added) and we get the error described above.

So the most obvious fix is to alter the test in `snakemake/executors/common.py` to say:

```
if isinstance(value, dict) or isinstance(value, collections.UserDict):
```

But I don't think this is right; just passing the original resource scopes down to the job is incorrect. From the perspective of the individual cluster job (be it a job to run a single rule or a group job) all resources are global resources, so passing `--set-resource-scopes foo=local` into the job makes no sense. In the case of my workflow, removing the call to the `get_resource_scopes_args()` method entirely yields the expected behaviour.

So you should consider simply removing this method and the single line that calls it, but this may break other use cases I don't understand.

TIM

**Comment by pvandyken** [comment]
Thanks for the report, it's not the first time the `UserDict != dict` has caught me. I think your final conclusion is correct, but I'll take a look again through the code to be sure.

**Comment by tbooth** [comment]
Thanks @pvandyken . I've used another approach in the end for my workflow as the resources mechanism ultimately wasn't doing what I needed.

Possibly the more robust approach for the code in `common.py` is to `try` the first option that uses `value.items()` and then handle the exception, rather than having an `if isinstance()` test - following the Python principle of [EAFP](https://realpython.com/python-lbyl-vs-eafp/).

**Comment by pvandyken** [comment]
I looked over the conversation in #1218 again, and can confirm that there's no current need to pass resource scopes to a subworkflow (because, as you say, all resources so passed are 'global' anyway), but we did make the explicit decision to do so in case it's useful in the future.

I agree with your comments on the `try` block. I'll go ahead and implement that now
