### ISSUE TITLE
README batch says only Python 3.7 supported, is this true?

### ISSUE THREAD

**Issue by corneliusroemer** [snakemake/snakemake#1990]
The Python badge in the README says only Python 3.7 is supported. Is this true? I don't think so.

It'd probably be better to either fix or remove the version - rather than state something that's incorrect.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/25161793/205502267-6b1436ae-dc73-43fd-b7f8-275fb4612b35.png">

**Comment by pvandyken** [comment]
Closed by #2020
