### ISSUE TITLE
Cleanup metadata exit too fast

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2000]
**Snakemake version**

7.18.2

**Describe the bug**

By running 
```bash
snakemake --cleanup-metadata  <(snakemake --profile slurm -p --rerun-incomplete -s pipeline.smk -n --list-code-changes) -s pipeline.smk 
```

When there are too many steps and snakemake need some time to build the graph. The command will exit with error.

**Logs**

```
Failed to clean up metadata for the following files because the metadata was not present.
If this is expected, there is nothing to do.
Otherwise, the reason might be file system latency or still running jobs.
Consider running metadata cleanup again.
Files:
/proc/self/fd/11
```

**Comment by pvandyken** [comment]
`--clear-metadata` takes a space separated list of files, not a file of file names. Does it work if you run the `--list-code-changes` call as a subshell `$(...)` rather than a file descriptor `<(...)`?

**Comment by y9c** [comment]
Thanks @pvandyken
