### ISSUE TITLE
when conda with --conda-prefix is used, previously created environments interfere with the later snakemake workflow runs

### ISSUE THREAD

**Issue by tinavisnovska** [snakemake/snakemake#201]
**Snakemake version**
5.9.1

**Describe the bug**
When I run a snakemake workflow with --use conda --conda-prefix /home/userX and there are no conda environments in /home/userX from previous runs of the workflow, everything goes fine -- the environments are created and used and the workflow works just fine. 

However, when I run the same workflow another time with the same value of --conda-prefix and the needed environments are already present in /home/userX, suchlike run of the workflow will end up with an error saying "(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)" Also, the creation time of the environment folders does not get updated during the most recent workflow run, so I think conda tries to prevent overwriting of the existing environments and that causes the non-zero exist status in some way.

When I remove the enviroments from /home/userX and let the workflow create them again on the same location using --conda-prefix parameter, the workflow works again as expected. 

Is this intentional behaviour?

**Comment by Fedorov113** [comment]
Hmm, I don't experience this.

**Comment by SichongP** [comment]
I can't reproduce this either. Can you provide a minimal reproducible code? 
Also what is the output if you run with `--verbose`?

**Comment by tinavisnovska** [comment]
Hi, sorry for taking me ages to respond. 

The problem seems to be related to my not too careful user switching with `su` and to the way in which conda modifies `PATH`. 

Imagine the following two scenarios:

1.
1a) user_A is logged with activated conda environment X
1b) `su user_B`
1c) conda activate Y

2. 
2a) user_A is logged with activated conda environment X
2b) conda deactivate
2c) `su user_B`
2d) conda activate Y

The resulting `PATH` variables are not the same in my case which surely had some impact on the snakemake behaviour further down. Thanks for your time and feedback, closing the issue now.
