### ISSUE TITLE
Allow a ratio to be set for slurm jobs where memory and cores are locked to a certain ratio, taking the necessary amount of cores to satisfy both thread and mem resource needs.

### ISSUE THREAD

**Issue by zjnolen** [snakemake/snakemake#2022]
**Is your feature request related to a problem? Please describe.**
I've worked on a couple clusters where memory reservations are made exclusively through core count, with each core reserving a set amount of memory, and both mem-per-cpu and mem in slurm scripts being discouraged. For snakemake, this means that when writing workflows under this system, the thread counts I set for high memory, but single threaded, rules will be considerably higher than necessary on systems that don't have this ratio lock. And for workflows written without this ratio in mind, I have to adjust thread resources on all rules that require high memory when running on my system.

**Describe the solution you'd like**
I would like an additional slurm CLI interface option of the nature `--slurm_mem_mb_cpu_ratio FLOAT`, where users can input their schedulers memory per CPU. Then, when submitting the slurm jobs, the executor would submit the job with the number of cores needed to meet specified threads for the rule or needed to meet specified memory reserved, whichever is greater.

I think this could be implemented [here](https://github.com/snakemake/snakemake/blob/e03a3b42eea89d512290bf98ee7d77ce2e17447c/snakemake/executors/slurm/slurm_submit.py#L242) by changing this to the equivalent of asking for the highest value between (1) requested threads and (2) requested memory divided by the ratio and rounded up to the nearest integer. This would be limited to the max_threads command line option if given. This would allow workflow writers to give defaults for threads and memory that would be sensible regardless of if memory and cpus are linked or independent on the user's system.

If this seems like a suitable solution, I would be glad to give implementing it a try. There might be some issues with transparency of how many cores will be used - for instance, I imagine that the threads listed in the log will match what's written in the snakefile rather than what they are submitted with, as making the thread change would only happen at job submission.

**Describe alternatives you've considered**
One would be that users must adapt the workflow resources to their system if this is not a common enough use case for native support. I've had this system configuration at two universities in Sweden (both using the same nationwide system) and on one small cluster I used that was local to a university in Germany, so it seems common enough to me, but I'm not sure if its just chance of where I've worked. Another would be that if workflow writers want to incorporate this adaptability, a function could be used to do the same thing when defining threads in a rule, using a ratio in the config file, though this would still leave users relying on workflow writers being aware of these slurm configurations. It also might be that I'm simply missing some way this is already possible to resolve!

**Additional context**
I think one thing that might be difficult here is that this option could easily get confused with the slurm option mem_per_cpu, though they aren't related in this case.

**Comment by pvandyken** [comment]
In this case it might be better to go back to the old profile system (e.g. adapt this https://github.com/Snakemake-Profiles/slurm). The only thing you'd miss is job steps, but at least in my experience that's not the end of the world. I worry the feature just makes things too complicated.

Maybe a better way is to start by implementing the feature as a profile, and if it gets enough use it could be worked into core?

**Comment by cmeesters** [comment]
I believe that could be implemented. However, currently when omitting `mem` and `mem_per_cpu` the cluster defaults kick in. This is already part of the solution. You will get a warning, though, as it is a little un-orthodox.

How would `--slurm_mem_mb_cpu_ratio FLOAT` as an `sbatch` flag for you? Could you point to the relevant bits of documentation on your cluster? Perhaps even indicate a colleague to contact?

**Comment by zjnolen** [comment]
Thanks for the replies, both! I had not considered implementing as a profile first, but that would be a good idea to start to avoid adding unneeded complications to the main implementation.

The [relevant bits are in the 'Details about the "core" and "node" partitions' section here](https://www.uppmax.uu.se/support/user-guides/rackham-user-guide/). Essentially, memory on a job is capped at 6.4GB x reserved cpus. So, the memory flag will still limit the memory if it is <6.4GB/cpu, but will not ask for any extra cpus if the mem flag exceeds 6.4GB/cpu, and this leads to it being limited to the memory that the reserved cpus allocate. This leads to a need to set a lot of custom resources to get workflows running.

In general, they recommend leaving out `--mem` and to use `--cpus-per-task` to allocate memory and threads, setting it to whatever is needed to meet both thread and mem needs. If `--slurm_mem_mb_cpu_ratio FLOAT` were to be implemented, it would translate directly into the `--cpus-per-task` flag, essentially saying, `--cpus-per-task=job.threads` unless `mem_mb > job.threads * slurm_mem_mb_cpu_ratio`, in which case `--cpus-per-task=mem_mb / slurm_mem_mb_cpu_ratio`. I've managed to test implementing something like this on a fork and it has worked thus far, but I could imagine that in some situations default resources or certain CLI options might not combine properly with this.

This is a bit of an un-orthodox cluster configuration as you mention, so it may not be sensible to put it into the main slurm executor. Maybe it's better as an option in the slurm profile project or as a fork of that profile aimed at this cluster in particular.

**Comment by cmeesters** [comment]
Then, I do not understand the demand: We already have the `mem_mb_per_cpu` resource specification. A more human-friendly version, allowing for more units might come soon-ish. Meanwhile, the graining is MB, only.

That said, there already is a mapping from `sbatch` featuring `-c/--cpus-per-task` and `--mem-per-cpu`. And it is already compliant to the distinction between the `core` and `node` partition in your case:

```
rule foo:
   ...
   threads: 4
   resources:
        partition: "core"
        mem_mb_per_cpu: 1200
  
 ```
would do the job already (the figures are just an example, you would get 4800 MB). The canonical snakemake way is to specify `threads` for smp ("shared memory process" or in your case "core") tasks. Alternatively, you might specify `cpus_per_task` as a resource, in which case you lose portability. 

Also, note that `slurm_extra` as a resource allows you to use the `-C/--constraint` flag to request your "fat" nodes, too.
 
It is possible to have a default memory per reserved CPU in SLURM. Your link does not mention these defaults, though. Yet, deducing the number of CPUs/threads and omitting `threads` from the requested memory would not only violate snakemake's philosophy - it contradicts most benchmarking experiences as well: A number of tools will scale to a certain number of CPUs on a given architecture, regardless of input whilst the memory consumption for many will depend on scalability as well as input size. Hence, implementing a heuristic is tempting (to say the least).

Does this help? Perhaps you should ask your cluster admins about the memory allocation with respect to the requested number of CPUs and the use of `--mem-per-cpu` as the page leaves this out entirely.

**Comment by zjnolen** [comment]
Thank you, that clarifies quite a few things in regards to the ways memory and threads will interact with the slurm options!

I've reached out to our cluster admins about the `--mem-per-cpu` option on our system, and it seems in general the cluster configuration (and they say that of all clusters belonging to Sweden's National Infrastructure for Computing) does not allow users to set any memory related slurm flags, so neither `--mem` or `--mem-per-cpu` will work as expected if at all when submitting jobs. According to them, the only modifiable option we have to control memory is through `--cpus-per-task`, where reserving a CPU is a proxy for reserving 6.4GB. This unfortunately seems to mean that memory resources in Snakemake will not have an effect on job submissions in our system. Instead, their standing suggestion for Snakemake users on our system is overriding the threads in rules when memory needs exceed what the threads defined in the rule would reserve on our system.

For reference, the situation that made me start looking for a solution to this is that I am trying to write rules for software that only ever uses 1 thread, but that does use a decent amount of memory - usually based on file size like you mention. I'd like to write the rule so that it works on our system, but is portable to others. If I wanted to write a rule like this that I would expect to work on most clusters, I would write something akin to:

```
rule foo:
    ...
    threads: 1
    resources:
        mem_mb=lambda input: 1.1*input.size
```

However, say the input file was 10000 MB, and our system has its current configuration, where the only way to allot memory is to reserve a CPU for every 6400 MB of memory desired. In this case, the rule would fail and the threads in this rule would need to be set to 2, not for any fault of Snakemake, but because of our cluster ignoring the way it (and most slurm configurations, I assume) allocates memory. If file size is variable and can get quite large, then on our system, I would either need to set high threads or a function of input size on threads. This would be problematic on other systems, where this would needlessly reserve CPUs. On our system, there's no penalty for this as long as we saturate the memory we get with that CPU reservation, but on others I've worked on this would have been a problem.

Currently, in situations like these I write workflows to be compatible with our system, at the expense of portability, or write them in a more portable way and use substantial thread overrides for any memory intensive rules when running on our system. Am I missing some way that you can see that might make a rule like this general and portable, but also working without overrides on our system?

**Comment by cmeesters** [comment]
When designing, we envisioned a number of rather unorthodox so-called spank-plugins. Hence, the introduction of `slurm_extra` as catch all for unknown flags.

However, when you have a tool and invoke `man <tool>` or `<tool> --help` and you get your manual, you as a user may expect that the tool is supposed to work in the fashion the manual explains to you, right? So, if my colleagues in Sweden choose to "simplify" things by overriding (or "outconfiguring") functionality, this was not only not to anticipate, but we can hardly start coding exceptions or adaptions for every corner case which is due to admins wanting to deviate from SchedMD's standards, wouldn't you agree? 

6400 MB per CPU are rather generous as an average. (We for example have 1800. Mainly, because we have more cores per node. But we also provide some big mem nodes for special needs.)

When you have a tool, where you know that the memory requirement depends on the input size and can code a heuristic for its scaling, then I would even argue, that coding a function to get the input size and employing a factor like you showed with your lambda function is _the way to go_, and it would even be portable.

Alas, for you only specifying `threads` - and presumably sometimes oversubscribing in order to get sufficient memory - seems the only way to go. Here, working with the native snakemake > v7.19.1 or the plugin resp. profile will not make any difference.

**Comment by cmeesters** [comment]
OK, when I close this thread? Or is there anything left to say?

**Comment by zjnolen** [comment]
Yes, I definitely agree, it's best not to code edge cases like this in, especially when, as you point out, it deviates considerably from the general intended usage of slurm. I'll keep moving forward with specifying only threads, and oversubscribing when needed. Thank you for looking into this! I'll go ahead and close this.
