### ISSUE TITLE
Allow a custom argument to the signature of the callable function within resources

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#2024]
While I really like this solution here:

```
def get_mem_mb(wildcards, attempt):
    return attempt * 100

rule:
    input:    ...
    output:   ...
    resources:
        mem_mb=get_mem_mb
    shell:
        "..."
```

, this becomes overly repetitive when having many rules and having to define different memory thresholds. Re-defining this with different values for the base memory (here: 100) is of course an option, but if the signature of the callable function could be extended to allow a last (optional) custom argument, then one could do something like this:

```
def get_mem_mb(wildcards, attempt, baseMemory):
    return attempt * baseMemory

rule:
    input:    ...
    output:   ...
    resources:
        mem_mb=get_mem_mb(wildcards, attempt, 100)
    shell:
        "..."
```

But neither the signature allows this currently nor using `wildcards` and `attempt `within the resources section.

**Comment by pvandyken** [comment]
This is easy enough if you use a function that returns a function:

```
def get_mem_mb(baseMemory):
    def inner(wildcards, attempt):
        return attempt * baseMemory

rule:
    input:    ...
    output:   ...
    resources:
        mem_mb=get_mem_mb(100)
    shell:
        "..."
```

**Comment by chrarnold** [comment]
Thanks , that is an interesting solution indeed if it works! Will test thanks!

**Comment by pvandyken** [comment]
I'm closing this for now, but feel free to continue the thread if you run into any issues!
