### ISSUE TITLE
High memory usage with many input files

### ISSUE THREAD

**Issue by JoshLoecker** [snakemake/snakemake#2030]
**Snakemake version**

6.15.5 (Latest release on 6.x, I can update to 7.x if my issue can be fixed there more easily)

**Describe the bug**

When running snakemake with many input files, lots of memory/RAM is required in order to build the DAG. As a result, the job is killed on a cluster. I have requested up to 20 gigabytes of RAM, and this was still not enough memory. I'm wondering if there is a way to reduce the memory usage for my workflow when building the DAG on the login node of a cluster.

**Logs**

I have no logs

**Minimal example**

My example has ~165 input samples and a total of 26 rules (two of those are checkpoints). I'm not sure how I should provide an example other than the entire workflow. I can do this if needed

I appreciate any help!

**Comment by dariober** [comment]
I would try the latest version of snakemake in case it has some improvement.

Is there any chance that your pipeline is not doing what you think? I mean, >20 GB seems really a lot, perhaps it's getting into some horrible loops that should not be there.

**Comment by JoshLoecker** [comment]
Yes, my issue seems to be fixed by updating to the newest version of snakemake

Marking this as closed
