### ISSUE TITLE
Add option to define source_cache directory

### ISSUE THREAD

**Issue by LukaP-BB** [snakemake/snakemake#2031]
**Is your feature request related to a problem? Please describe.**
When executing workflows on a cluster environment, space on the /home directory can be pretty limited.

Since snakemake stores it's source cache in /home/$USER/.cache/snakemake/source-cache ([source code of snakemake here](https://github.com/snakemake/snakemake/blob/v6.0.3/snakemake/sourcecache.py#L24)) ([underlying appdirs code here](https://github.com/ActiveState/appdirs/blob/master/appdirs.py#L313)) , it can run out of space in some cases, which creates unintelligible errors (mostly due to corrupted json files)

**Describe the solution you'd like**
A simple solution would be to overwrite the default location with an environment variable, for exemple `export SOURCE_CACHE=/work/$USER/.cache`

**Comment by pvandyken** [comment]
Does the `XDG_CACHE_HOME` variable already do this for you? https://github.com/ActiveState/appdirs/issues/163

**Comment by LukaP-BB** [comment]
I haven't tested but I'm pretty sure it does because it's the variable accessed by the appdirs function.
So basically, only the documentation needs an update to make people aware of this option.

**Comment by pvandyken** [comment]
If you're able to make that PR, that would be really helpful. I can't think of a super ideal place to put it, but probably within the "Command line interface" section following "Profiles", we could have a little section about how snakemake honours the `XDG_CACHE_HOME` variable when caching data

**Comment by LukaP-BB** [comment]
I can give it a try, I never had the occasion to create a PR.
Give me a hot moment to see how all of this work.

**Comment by pvandyken** [comment]
Great, thanks! Make sure your commit is prefixed with `docs: `; that will save you some grief from the github checks. It may take some time for the PR to actually be reviewed and processed... nothing personal, there's just a backlog

**Comment by LukaP-BB** [comment]
I see I see, no problem.
Just to be sure, I wonder if setting this environment variable might have undesired side effects.
Since I'm in the process of creating the PR, wouldn't it be more safe to define a new environment variable specific to snakemake, that I would look for in the linked function of my first post ?
Something like 
```py
class SourceCache:
    cache_whitelist = [
        "https://raw.githubusercontent.com/snakemake/snakemake-wrappers/\d+\.\d+.\d+"
    ]  # TODO add more prefixes for uris that are save to be cached

    def __init__(self, runtime_cache_path=None):
        if os.environ.get("SNAKEMAKE_SOURCE_CACHE") is not None :
            self.cache = Path(os.environ.get("SNAKEMAKE_SOURCE_CACHE"))
        else :
            self.cache = Path(
                os.path.join(get_appdirs().user_cache_dir, "snakemake/source-cache")
            )
```
And then suggest to set this environment variable in the docs

**Comment by pvandyken** [comment]
The side effect would be to change the cache dir for all apps that respect `XDG_CACHE_HOME`. I don't see that as a problem, I think that's the point.

Adding a new variable might be fine, but that's up to @johanneskoester. And it would be more consistent for snakemake to add a cli parameter controlling it, rather than a environment variable (but of course, we could also do both). So it just makes for a bit of a can of worms, whereas documenting that we respect `XDG_CACHE_HOME` is easy (the only real question is where to put it).

But since the patch is super simple, by all means go ahead and make the PR and see what @johanneskoester thinks.

**Comment by pvandyken** [comment]
Note that it would be:

```python
    def __init__(self, runtime_cache_path=None):
        if os.environ.get("SNAKEMAKE_SOURCE_CACHE") is not None :
            self.cache = Path(os.environ.get("SNAKEMAKE_SOURCE_CACHE"), "snakemake/source-cache")

**Comment by johanneskoester** [comment]
I think it is reasonable to not introduce something new since XDG_CACHE_HOME is the standard way to define such things. Here is a PR that adds documentation: https://github.com/snakemake/snakemake/pull/2057
