### ISSUE TITLE
docs issue or regression? retries ignored

### ISSUE THREAD

**Issue by ptrebert** [snakemake/snakemake#2047]
**Snakemake version**
7.19.1

**Describe the bug**
The rule-specific `retries` directive is ignored.

**Minimal example**
```
rule foo:
    output:
        "foofile.txt"
    retries: 0
    run:
        print("running")
```
Running the above with
```
snakemake -c1 -d wd/ --restart-times 5
```
will restart the failed rule 5 times.

**Additional context**
The way I understand the documentation ...
```
Note that it is also possible to define retries globally (via the --retries command line option). The local definition of the rule thereby overwrites the global definition.
```
the `retries` directive in a rule should always take precedence.

This is related to #1649 (and somewhat to #367 and #500)

**Comment by pvandyken** [comment]
This is a bug. The current implementation is not correctly handling `retries: 0`. Compare to an identical reprex where retries is set to 1.

Interestingly, such an experiment reveals a second bug, specifically related to the use of the `run` directive. Snakemake evaluates such rules in a subsnakemake instance, but the `retries` directive is getting honoured both within the parent and child snakemake instances, leading to 3 retries in total.

I'll create a new issue for the second bug, using the adapted minimal example.
