### ISSUE TITLE
temp function with tempdir 

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2087]
I am trying to write all the temp files of the workflow into a specific directory, and I define the directory with TEMPDIR variable, so I can change it into different partitions quickly.

Because of this, I have to repeat this snippet multiple times.

```
temp(os.path.join(TEMPDIR, "step1/file1.txt"))
```
Thus I define a function tempit for this. 

```
def tempit(f):
    return temp(os.path.join(TEMPDIR, f))
```

However, I can only use this one in the output section, but not the input section. Could I customize the fuction to make it work in both input and output section.

In the input section, I still have to write `os.path.join(TEMPDIR, "step1/file1.txt")`

Thank you!

**Comment by y9c** [comment]
I would like to know if there is API to detect output blocks? If the function is in output block, add temp modifier?

```
def tempit(f):
    ### if in ouput:
        return temp(os.path.join(TEMPDIR, f))
    return os.path.join(TEMPDIR, f)
```

**Comment by pvandyken** [comment]
In my own workflows, I use pathlib for the same purpose:
```py
from pathlib import Path
work = Path("/tmp")

rule my_rule:
    input: work / "path/to/file.txt"
    output: temp(work / "path/to/output.txt")
```

I think this is a reasonably concise way of solving the problem. I'm closing the issue on that accord, but let me know if you have any additional questions.

**Comment by y9c** [comment]
Hi @pvandyken, when using Pathlib package in snakemake, do you also have trouble in using wildcards? I wonder if snakemake can support Pathlib out of box?  
https://github.com/snakemake/snakemake/issues/2307
