### ISSUE TITLE
Remove input and output from properties in jobscript

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#2097]
**Is your feature request related to a problem? Please describe.**

Currently, the properties injected into the jobscript include `input` and `output`

https://github.com/snakemake/snakemake/blob/512e49b778261467dd8a31b5caa087a378ec32a3/snakemake/jobs.py#L998-L1010

When running a job that has thousands of input or output files this creates a problem on slurm. Slurm's default script size if 4MB. I have an example of a job that takes 44,000 input files and the jobscript is 4.6MB. As such, it fails submission to slurm.

**Describe the solution you'd like**

Do `input` and `output` need to be in the properties injected into the jobscript? The slurm and lsf profiles dont use these properties, is there other things using it?

If not, can we just remove them?

**Additional context**

This has arisen in the slurm profile before also - see https://github.com/Snakemake-Profiles/slurm/issues/87

**Comment by johanneskoester** [comment]
I suggest to keep them unless there are too many (also for backwards compatibility). Let's say, if more than 100, they are omitted and None is put there, indicating that they aren't available. This behavior should be documented of course. Happy to merge a corresponding PR!
