### ISSUE TITLE
maximum number of jobs option disregarded

### ISSUE THREAD

**Issue by annahake** [snakemake/snakemake#21]
**Snakemake version**
snakemake=5.4.5

**Describe the bug**
Hi, 
I call snakemake in a drmaa environment with the following cluster settings: 
```
local-cores: 2
jobs: 200
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 2
```
Though I have set the job option to 200, I manage to exceed the max. allowed job count of 300. 
`drmaa.errors.TryLaterException: code 16: job rejected: only 300 jobs are allowed per user (current job count: 300)`

Is it possible, that if jobs are restarted, this happens in addition to the already started 200 jobs?

**Comment by johanneskoester** [comment]
Thanks for reporting. It should not be like that. Can you create a minimal example so that I can try to reproduce the error?

**Comment by johanneskoester** [comment]
Just looking at the code, I think this case is properly handled.

**Comment by annahake** [comment]
I can't reproduce it currently. Maybe it occurred because there were undetected jobs running from a previous call which was killed (#22). If the code handles the restarting and the file latency correctly, you can close the issue. Thanks for looking into it.

**Comment by johanneskoester** [comment]
Ok, thanks! Feel free to reopen if it reoccurs.
