### ISSUE TITLE
touch raises misleading exception on non-existant directory

### ISSUE THREAD

**Issue by ptrebert** [snakemake/snakemake#211]
Hi,
I am using Snakemake v5.9.1, and the following error has been bugging me for quite some time.

In a workflow where certain rules have `directory()` as output, updating the state of the workflow with `--touch` fails if the respective directory does not exist. That alone seems like a bug, but the exception raised is an `ImproperOutputException`, presenting the wrong diagnosis for what went wrong (i.e., the output directory is correctly flagged with `directory()`). The following example reproduces the error:

```Python

rule master:
    input:
        'output/finish/testA/done.txt'

rule init:
    output:
        'output/init/{scenario}_foo.txt'
    run:
        with open(output[0], 'w') as foo:
            _ = foo.write('init\n')


rule intermediate:
    input:
        'output/init/{scenario}_foo.txt'
    output:
        folder = directory('output/intermediate/{scenario}/directory'),
        file = 'output/intermediate/{scenario}/complete.txt'
    run:
        os.makedirs(output.folder, exist_ok=True)

        with open(output.file, 'w') as dump:
            _ = dump.write('folder created')

rule finish:
    input:
        'output/intermediate/{scenario}/complete.txt'
    output:
        'output/finish/{scenario}/done.txt'
    run:
        with open(output[0], 'w') as dump:
            _ = dump.write('done\n')
```

After running the above, remove the intermediate directory (`rm -rf output/intermediate/testA/directory`), and the result (`rm output/finish/testA/done.txt`), and rerun with `--touch`. The following error message appears:

```
ImproperOutputException in line 14 of /<PATH>/smk_exception/Snakefile:
Outputs of incorrect type (directories when expecting files or vice versa). Output directories must be flagged with directory(). for rule intermediate:
output/intermediate/testA/directory
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Best, 
Peter

**Comment by vid1998** [comment]
I experimented exactly the same problem with snakemake 5.20.1

**Comment by lculibrk** [comment]
Experiencing the same issue on 6.1.1

**Comment by Aiswarya-prasad** [comment]
I see the same issue on v6.15.5

**Comment by valentynbez** [comment]
Same in 7.18.2

**Comment by pvandyken** [comment]
After all this time, the fix seems to be fairly straightforward. If folks could test the PR in their own environment, that would be helpful #2051
