### ISSUE TITLE
Percentage calculation could be more accurate

### ISSUE THREAD

**Issue by pmb59** [snakemake/snakemake#2115]
Hi,
I am getting
```
Finished job 1661.
1762 of 1766 steps (100%) done
```
with Snakemake 6.6.1. Percentage calculation could be calculated more accurately.

**Comment by troycomi** [comment]
This seems to have been addressed in [version 6.7.0](https://github.com/snakemake/snakemake/releases/tag/v6.7.0).  In the current version, your values would display `99.8%`.

**Comment by pmb59** [comment]
thanks @troycomi  Probably time for an update..
