### ISSUE TITLE
Extremely slow DAG building

### ISSUE THREAD

**Issue by mweberr** [snakemake/snakemake#2126]
Snakemake version 7.22

I have only two rules download and process. But I run this pipeline for 1Million samples, therefore the first step, the DAG building process takes hours and cannot be accelerated by the number of cores. Would it be possible to simplify the DAG building in case of very simple rule dependencies ?

rule download:
  output:
     {sample}.fasta

rule process:
  input:
   {sample}.fasta
  output:
    {sample}.report

Best ,
Michael

**Comment by maarten-k** [comment]
This should be mitigated by https://github.com/bioconda/bioconda-recipes/pull/39729.  This patch is available in snakemake v7.24.0
