### ISSUE TITLE
Lot of time spend on toposort in a large workflow

### ISSUE THREAD

**Issue by maarten-k** [snakemake/snakemake#2134]
**Snakemake version**
7.19.1

**Describe the bug**
I have a  large workflow with a total of 720.000 jobs. This workflow also includes checkpoints. It takes a long time to before submitting jobs. Also, I noticed that no new jobs were submitted after sending off the first jobs and the detection of finished jobs was severely delayed. Multiple other issues on GitHub might be related to this topic. for example #2091, #1700

 To check what was casual to the delay, I used `faulthandler` to take multiple peaks inside where snakemake was spending time on. (a normal profiler would generate too much data to handle with ease). 

I was a bit surprised that after checking the presents of files, it took an awfully long time in the toposort function. This function is an external dependency.  I found on the toposort gitlab a [ merge request](https://gitlab.com/ericvsmith/toposort/-/merge_requests/4) that sound like it addresses the problem, implemented this (dirty hack), and snakemake seems to be more responsive. However, I have a hard time benchmarking only this part of the pipeline, so I am not sure if the is a placebo effect.  I will try to gather some dry-run in the future.

**Additional context**

***about faulthandeler***
I added into `$(which snakemake)` the following lines:
```
import faulthandler
import signal
faulthandler.register(signal.SIGUSR1.value)
```

Run snakemake,fetch  the PID  and while running call

```kill -s SIGUSR1 $PID```

will output where snakemake is spending time at the moment in the Snakemake terminal (watch out for selection bias!).

**Comment by maarten-k** [comment]
I did some dryrun testing with the latest main under python 3.11.0:

With merge request mentioned earlier, it took:
"""
34.45user 4.17system 0:41.05elapsed 94%CPU (0avgtext+0avgdata 751224maxresident)k
0inputs+32outputs (7major+203591minor)pagefaults 0swaps
34.81user 4.25system 0:41.83elapsed 93%CPU (0avgtext+0avgdata 751172maxresident)k
0inputs+32outputs (22major+202950minor)pagefaults 0swaps
34.73user 4.37system 0:41.26elapsed 94%CPU (0avgtext+0avgdata 751280maxresident)k
0inputs+32outputs (30major+203034minor)pagefaults 0swaps
"""

With the original toposort it took:
"""
45.71user 4.28system 0:52.26elapsed 95%CPU (0avgtext+0avgdata 751296maxresident)k
0inputs+312outputs (25major+201887minor)pagefaults 0swap
47.03user 4.17system 0:53.46elapsed 95%CPU (0avgtext+0avgdata 750200maxresident)k
0inputs+32outputs (49major+202875minor)pagefaults 0swaps                       6              1              1
46.11user 4.50system 0:52.91elapsed 95%CPU (0avgtext+0avgdata 751416maxresident)k
0inputs+32outputs (13major+203858minor)pagefaults 0swaps
"""

For the sake of testing, I tried it again with the merge request and it seems stable.
"""
34.40user 4.40system 0:41.38elapsed 93%CPU (0avgtext+0avgdata 751424maxresident)k
0inputs+312outputs (52major+201945minor)pagefaults 0swaps
"""

In this particular case took about 10 seconds of the complete runtime(wallclock). User time it is 30% faster.

This seems like a reasonably easy fix, but what is the best way to implement this? Ask the maintainer of the toposort package to release a new version with the patch would be the royal way.  Should additional testing be done upfront?

**Comment by dlaehnemann** [comment]
Thanks for investigating this and tracking down the `toposort` merge request. I also just did some benchmarking of just that code on the dag of a large snakemake workflow and added my two cents at the merge request. So let's hope that this gets merged and released and can be used in snakemake.

Alternatively, one could switch to [`graphlib.TopologicalSort`](https://docs.python.org/3.9/library/graphlib.html) that is available from `python 3.9` onwards. It doesn't seem to be as quick as the fixed `toposort` (with a 200x speedup), but seems to provide a 75x speedup. But as this is not as quick, I think this is only an option in case the merge request doesn't get addressed in the `toposort` package.

**Comment by dlaehnemann** [comment]
One additional point that might speak for `graphlib.TopologicalSort`, is that it can be parallelized. Should the goal eventually be to parallelize DAG handling, this could be advantageous.

**Comment by maarten-k** [comment]
Thanks for the additional comments on GitLab. Looks like the author is willing to help. It should also be possible to "patch" older installations with newer packages of `toposort`.

`graphlib.TopologicalSort` returns a flattened list instead of a levelled one. I do not know if this is in problem, but good to know. Paralisation is not the first go-to solution to make things faster (Amdahl's law can kick in hard).

Also `networkx`, to be complete, networkx has a non-flatted toposort implementation. There are probably many more, but `toposort` is a small package without other dependencies

**Comment by ericvsmith** [comment]
I have released toposort 1.10 which should fix this. Please check.

**Comment by maarten-k** [comment]
Should we add a restriction on conda/pip that at least version 1.10 of toposort is needed to prevent users runing into the same version again?

**Comment by ericvsmith** [comment]
Once it's been tested, I don't see any reason not to. There aren't any meaningful changes to toposort in the last few years.

**Comment by dlaehnemann** [comment]
Thanks again for tracking this down, @maarten-k !

**Comment by fgvieira** [comment]
Have to run a workflow with ~1M jobs and found this post where @maarten-k states that the biggest bottleneck when building very large DAGs is the `toposort` function. To get some numbers, I decided to compare `toposort`, `graphlib` and `networkx`.

1. toposort
```
from toposort import toposort
```

2. graphlib:
```
def toposortg(graph):
    from graphlib import TopologicalSorter
    sorter = TopologicalSorter(graph)
    sorter.prepare()
    sorted = list()
    while sorter.is_active():
        ready=set()
        for task in sorter.get_ready():
            ready.update(str(task))
            sorter.done(task)
        sorted.append(ready)
    return sorted
```

3. networkx:
```
import networkx as nx
```

On a very small graph, `toposort` is the fastest (`toposort` < `graphlib` < `networkx`):
```
graph_small = {"D": ["B", "C"], "C": ["A"], "B": ["A"]}

In [151]: timeit.timeit(lambda: list(toposort(graph_small)), number=10000)
Out[151]: 0.07187884813174605

In [152]: timeit.timeit(lambda: toposortg(graph_small), number=10000)
Out[152]: 0.09578052815049887

In [153]: timeit.timeit(lambda: list(nx.topological_generations(nx.DiGraph(graph_small).reverse())), number=10000)
Out[153]: 0.5287932688370347
```

However, if we simulate a very large DAG with 1M nodes:
```
import timeit
from random import random, seed
seed(10)
N=1000000
graph_large = {}
for node1 in range(1,N):
    graph_large[node1] = []
    for node2 in range(node1+1,N):
        if random() < 10/N:
            graph_large[node1].append(node2)
```

`graphlib` seems to be the fastest (`graphlib` < `toposort` < `networkx`), although not by much:
```
In [161]: timeit.timeit(lambda: list(toposort(graph_large)), number=10)
Out[161]: 101.54673631861806

In [164]: timeit.timeit(lambda: toposortg(graph_large), number=10)
Out[164]: 86.88519050600007

In [165]: timeit.timeit(lambda: list(nx.topological_generations(nx.DiGraph(graph_large).reverse())), number=10)
Out[165]: 265.3101162966341
```

Also tried to look for how to parallelize the topological sorting, but could not find it. @dlaehnemann do you know how it could be done?

**Comment by maarten-k** [comment]
@fgvieira, I also made some benchmarks with Toposort and TopologicalSorter and had the same findings.

I was planning to implement TopologicalSorter into snakemake and remove the toposort dependency to mitigate the issue, but could not find time yet.

**Comment by fgvieira** [comment]
Cool! I guess since `graphlib` is part of python's standard library, it makes sense to make the switch. Did you figure out if/how `TopologicalSorter` can be parallelized?

**Comment by ericvsmith** [comment]
As the author of `toposort`, I agree that switching to `graphlib` is the right thing to do.

**Comment by fgvieira** [comment]
@maarten-k let me know if you need help implementing `graphlib`.
