### ISSUE TITLE
WorkflowError: Cannot parse runtime value into minutes for setting runtime resource: 00:30:00

### ISSUE THREAD

**Issue by ncherric** [snakemake/snakemake#2154]
**Snakemake version**

7.24.0

**Describe the bug**

I have been including ``runtime`` in the ``resources`` directive in each of my rules in my workflows for batch submission. I format the time in ``hh:mm:ss`` e.g. ``runtime="00:30:00"`` for 30 minutes. This works as of snakemake version 7.19.0, however, in a recent install with snakemake version 7.24.0, I get the following error when attempting a dry-run:

```
$ snakemake --version
7.24.0
$ snakemake -np
Building DAG of jobs...
WorkflowError:
Cannot parse runtime value into minutes for setting runtime resource: 00:30:00
$
```

**Additional context**

Looking at the [changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id14), it appears this likely occurred from a feature added in 7.20.0:

> allow for human friendly resource definitions (e.g. mem=”5GB”, runtime=”1d”) ([#1861](https://github.com/snakemake/snakemake/issues/1861)) ([24610ac](https://github.com/snakemake/snakemake/commit/24610ac75849d543fc38c83fb2454fa4f9b42075))

I hope this helps with possibly including a revision to still accommodate the ``hh:mm:ss`` runtime format feature in future minor version updates. If the intent is to deprecate this format just let me know. 

Thank you!
Noah

**Comment by dlaehnemann** [comment]
Thanks for reporting this, and this has [also been reported in the respective pull request you cite](https://github.com/snakemake/snakemake/pull/1861#issuecomment-1405205135). I've also run into the same problem, so I feel your pain, here.

But there's a good reason not to allow this kind of specification, which is portability of snakemake workflows. Namely, the time format `runtime="00:30:00"` was previously just passed on as is to slurm, and slurm understands this. However, any other cluster system might or might not understand this time format. Thus, the same workflow would not execute on another cluster system and would thus not be portable.

So, as annoying as this might seem with your current error, I'd suggest to simply move to the new timespan specification syntax and take the extra workflow portability as a useful extra.

Also, the new (portable) specification is based on an external library that consistently parses time spans, see:
https://humanfriendly.readthedocs.io/en/latest/api.html?highlight=parse_timespan#humanfriendly.parse_timespan
This library distinguishes between the specification of timespans as `<number><time_unit>` and actual timepoints during a day as `<hour>:<minute>:<seconds>`, so there's a finer nit-picking point to be made, here, as well... :sweat_smile:

**Comment by ncherric** [comment]
Thanks David! I will go ahead and adapt my workflows for the new specification since it will add portability for users that submit to slurm and/or other job schedulers on clusters. It might be helpful to add a line in the changelog for future readers about how the new human friendly resource definition unintentionally deprecated the old time format ``hh:mm:ss``, but moving away from the old time format is actually advantageous because of the new time format ``30m`` portability for various job schedulers and cluster systems.

**Comment by dlaehnemann** [comment]
Putting that info in the changelog is a very good idea! Would you be willing to put in a pull request that quickly explains this in one or two sentences right here:
https://github.com/snakemake/snakemake/blob/1fb3cef54dfe877c944b8f38cf4ca78ebe91ebe9/CHANGELOG.md?plain=1#L113

**Comment by nickp60** [comment]
Hi all, I'm piggybacking off this issue as it is related.  With the change from 7.19 to 7.20 I get a similar issue but for cases where I don't define a runtime:
```
Building DAG of jobs...
WorkflowError:
Cannot parse runtime value into minutes for setting runtime resource: <TBD>
```
I think this is because the default resources only define mem_mb, disk_mb, and tmp.

I'm on LSF, so not sure if this is related to that or to core Snakemake but I'm mentioning it here as the lsf snakemake-profile repo lacks maintainers.  

Is there a solution to this other than setting a default with `--default-resources`?

**Comment by nickp60** [comment]
**Correction** -- The error I am getting with 7.20 that I wasn't getting with 7.19 is due to using a lambda function in the resources.  Is there a workaround?

**Comment by dlaehnemann** [comment]
Can you describe the problem in more detail? Does your lambda function return an integer (specifying the runtime in minutes)?

**Comment by dlaehnemann** [comment]
Unless you resolved this, it might also make sense to open a separate issue for providing a more detailed account of the problem (and then hopefully a resolution). You can always mention the comments over here.
