### ISSUE TITLE
Using a for loop to access inputs in snakemake for arguments that don't accept lists

### ISSUE THREAD

**Issue by kevin-wamae** [snakemake/snakemake#2168]
I want to use the `gatk MakeVcfSampleNameMap` to generate a tab-delimited file that maps sample names to the corresponding VCF files in a Snakemake workflow:

**_output - > (sample_name_map.txt)_**

```
input/vcf1.vcf.gz	control5-a
input/vcf2.vcf.gz	control5-c
```

`gatk MakeVcfSampleNameMap` accepts a single `--INPUT` argument at a time, so I pass multiple VCF files to it in the form:
- `--INPUT {input.vcfs[0]}`
- `--INPUT {input.vcfs[1]}`, etc.

_**snakemake rule**_:

```
rule MakeVcfSampleNameMap:
    input:
        vcfs=["input/vcf1.vcf.gz", "input/vcf2.vcf.gz"],
    output:
        "sample_name_map.txt",
    shell:
        "gatk MakeVcfSampleNameMap \
        --INPUT {input.vcfs[0]} \
        --INPUT {input.vcfs[1]} \
        --OUTPUT {output}"
```

This becomes cumbersome when there are many input files. How can I use a loop in the Snakemake rule to access all the VCF files?

**Comment by kevin-wamae** [comment]
I found a workaround using a python script [my StackOverflow solution](https://stackoverflow.com/a/75703791/6539898).

Can Snakemake do something similar without calling external Python scripts?

**Comment by troycomi** [comment]
WDL has a [sep argument](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#example-4-bwa-mem) to its parameter expansion but I'm not aware of anything similar in snakemake.  It's not that extreme of a param function and honestly I think this is more readable:
```
rule MakeVcfSampleNameMap:
    input:
        vcfs=["input/vcf1.vcf.gz", "input/vcf2.vcf.gz"],
    output:
        "sample_name_map.txt",
    params:
        input_list=lambda wildcards, input: " --INPUT ".join(input)
    shell:
        "gatk MakeVcfSampleNameMap \
        --INPUT {params.input_list} \
        --OUTPUT {output}"
```

Otherwise you should mark this as an enhancement and change the title to something more descriptive, like "Add separator parameter to input expansions"

**Comment by kevin-wamae** [comment]
Thanks, @troycomi, worked like a charm 👏🏾
