### ISSUE TITLE
I'd like to make a case for `--lu` not always listing `config.yml` as an untracked file

### ISSUE THREAD

**Issue by hepcat72** [snakemake/snakemake#2185]
https://github.com/snakemake/snakemake/blob/2558ea53ecc116faaa6b515d452a1fde3fa2b400/snakemake/dag.py#L2396-L2416

*If issues are supposed to have a template, I used **reference in new issue** from the code linked above, which doesn't supply the template, so I didn't delete it - it's just wasn't here...*

I'm new to `snakemake` and I was confused by the output of `--lu`/`--list-untracked`.  It always outputs my `config.yml` file.  My workflow requires that file.  It would error without it.  [I asked about it on stack](https://stackoverflow.com/questions/75794729/why-does-snakemake-list-untracked-list-the-config-yaml-file-in-its-out?noredirect=1#comment133716587_75794729).  While I acknowledge that the linked method is intended to be used to reveal files in the context of the dag, I would say that if a file is known to be unrelated to the dag, it should be ignored, i.e. not output when this method is called.  Listing a file as having run afoul of the dag should tell the developer that they should either delete it or include it as an accounted for input/output.

That said, *should* I be including my config file in the **all** rule as an input if it is required to run the workflow?  I noted that if I do, then `--lu` does not output that file.  However, a user on stack replied saying that doing so is bad practice, though I'm unclear as to why.  `--lu`'s output seems to imply it should be included.

Also, as a linting issue, should one strive to clean up the output of `--lu`?  (On a related note, since I added `config.yml` as an **all** rule input, running `snakemake --lint` without a working `--directory`, complains that the `config.yml` is missing - so that would counter-indicate that I should include it in my workflow...)

**Comment by tgbrooks** [comment]
Another reason why including `config.yml` as an input to the `all` rule is bad practice is that then no one can run your pipeline with the `--configfile` option set to a different file. That's also a reason why it might not make sense to have it excluded form --list-untracked: the config file could be under a different name or location.

**Comment by hepcat72** [comment]
Well, it turned out that I wasn't using the conventional directory structure - so the only output I was seeing was that config file, which I think made me misinterpret the intended utility of `--lu`.  Now I see a bunch of files such as the env files, docs, the snakefile, etc..  So my suggestion in that context makes no sense.  Closing.  Though that said, it seems like there should be a way to distinguish unaccounted for input/output files from the components of the workflow, so that one can more easily identify (for example) outputs they've overlooked.  That was, there could be a linter that ensures there aren't unaccounted-for output files. Again - I'm a noob, so I may be completely off.
