### ISSUE TITLE
jobs still running though snakemake terminated with an error

### ISSUE THREAD

**Issue by annahake** [snakemake/snakemake#22]
**Snakemake version**
snakemake=5.4.5=0

**Describe the bug**
I have encountered several times in a cluster environment that though snakemake terminated with an error either from snakemake itself or from the cluster environment, not all running jobs were deleted. Shouldn't all jobs be deleted as soon as any error is encountered and snakemake is terminating?

**Comment by elsherbini** [comment]
In the cluster environment I use at least, if the error is a time-limit or memory error or some other cluster error, the job gets cancelled but snakemake keeps going. These sort of cluster errors aren't handled by snakemake. Here is an issue that might explain this better: [https://bitbucket.org/snakemake/snakemake/issues/427/detect-killed-jobs-in-cluster-environment](https://bitbucket.org/snakemake/snakemake/issues/427/detect-killed-jobs-in-cluster-environment)

In the case of a normal error like a script having a syntax error or something, snakemake should stop submitting new jobs to the cluster but it waits for all the jobs it already submitted to finish. it doesn't know how to cancel jobs.

**Comment by openpaul** [comment]
What cluster system are you using? I know this issue from LSF and would be cool to see better handling from snakemake.

**Comment by johanneskoester** [comment]
When using --cluster, Snakemake is not able to kill jobs when it is cancelled. This is only supported with --drmaa currently. For using DRMAA, your admins need to set it up, but in most distributions that should be fairly simple.

**Comment by johanneskoester** [comment]
Please reopen if I misunderstood you.

**Comment by annahake** [comment]
I am using the `-drmaa` option on a drmaa cluster. 
I observed this when I received an drmaa error and snakemake was cancelled, but there were still jobs running when I checked with `qstat`.
