### ISSUE TITLE
Allow include directive to accept a Path object

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#220]
**Is your feature request related to a problem? Please describe.**
I love the introduction of the `input` and `output` directives taking `Path` objects. One other place I would really like to see this same functionality is in the `include` directive - when including other snakefiles.

**Describe the solution you'd like**
Allow `include` to accept/handle a `pathlib.Path` object.

Something like this would be an example use case:
```py
from pathlib import Path
rules_dir = Path("rules")
include: rules_dir / "map.smk"
```

**Describe alternatives you've considered**
Currently, I just turn the `Path` object into a `str` when passing it to the `include` directive:
```py
from pathlib import Path
rules_dir = Path("rules")
include: str(rules_dir / "map.smk")
```

**Additional context**
It looks as though the code that would need to be altered to allow this is the `snakefile` parameter in this function: https://github.com/snakemake/snakemake/blob/af722a1b827160a5bc5b81f46b2990f6c327028b/snakemake/workflow.py#L892-L931

A very simple solution (hack) would be to just turn the `snakefile` into a `str` in the first line of the function. However, this probably isn't the best long-term solution?  
Outside of that, this function looks to be doing a lot of auxiliary things and so  I don't know if I should be going in and fiddling.  

One comment I would make is having a path object would allow you to easily confirm the existence of the snakefile the user is asking to include and then provide a helpful error message. In the past, I have found that when this include directive fails for that exact reason it usually takes me a while to track down where it is coming from.

**Comment by engenegr** [comment]
It could be connected to https://github.com/snakemake/snakemake/issues/206

I'd like to see snakemake taking care of absolute paths for the rules inside included Snakefiles.
