### ISSUE TITLE
User friendly HPC scheduling using persistent workers

### ISSUE THREAD

**Issue by kendonB** [snakemake/snakemake#2201]
**Is your feature request related to a problem? Please describe.**
My (possibly wrong) first impression of snakemake coming from R targets is that the ease of getting work going on an HPC is not quite as nice.

**Describe the solution you'd like**
Gain inspiration from the targets interface to HPCs and implement a nice solution.

**Describe alternatives you've considered**
Sticking with R ;)

**Additional context**
[Relevant part of the targets manual](https://books.ropensci.org/targets/hpc.html#clustermq)

**Comment by SichongP** [comment]
Snakemake already supports HPC via [cluster execution](https://snakemake.readthedocs.io/en/stable/executing/cluster.html). Can you be more specific with what is not sufficient about the current cluster support and what exact enhancements you want?

**Comment by kendonB** [comment]
Looking again, it doesn't look that bad to run things. Thanks!
