### ISSUE TITLE
advanced tutorial - reasoning behind using an input function instead of expand() in the bwa_map rule

### ISSUE THREAD

**Issue by kimsjune** [snakemake/snakemake#2221]
Hi,

I am struggling to understand the logic behind using an input function for the bwa_map rule instead of expand() function as in the bcftools_call rule. The tutorial explains that due to the nature of three phases, the directories of FASTQ files cannot be determined using an expand function within the rule. However, the following rule, 

rule bwa_map:
    input:
        fa="data/genome.fa",
        fast=expand("data/samples/{sample}.fastq", sample=config["samples"])
    output:
        "mapped_reads/{sample}.bam"
    threads:8
    shell:
        "bwa mem  -t {threads} {input.fa} {input.fast} | samtools view -Sb - > {output}"

gets evaluated to (in a dry run)

rule bwa_map:
    input: data/genome.fa, data/samples/A.fastq, data/samples/B.fastq, data/samples/C.fastq
    output: mapped_reads/C.bam
    jobid: 8
    reason: Forced execution
    wildcards: sample=C
    resources: tmpdir=/tmp

This eventually fails to actually run, and aligning all three FASTQ files into one is wrong anyway. But, I'm still wondering if this has anything to do with how "... we cannot determine the FASTQ paths for rule bwa_map from the config file in this phase, because we don’t even know which jobs will be generated from that rule." It seems like the output of expand() is merely a list, so a proper, recursive DAG can't be generated by expand(). Conversely, the reason why expand() is okay for bcftools_call is because the shell command should combine all three files together into a vcf file. Does it also mean that expand() and wildcards are evaluated in the initialization and DAG phase, respectively?

I would appreciate any feedback. Thank you.

**Comment by troycomi** [comment]
I agree the tutorial is a bit too contrived to show the utility of input functions and you could get away without using one.  This was also discussed on [stackoverflow](https://stackoverflow.com/questions/72794939/how-to-quickly-identify-if-a-rule-in-snakemake-needs-an-input-function/72803467#72803467) which has some discussion as well.

**Comment by kimsjune** [comment]
Fantastic. Thank you!
