### ISSUE TITLE
Output files saved in Jupyter notebook are marked as incompleted

### ISSUE THREAD

**Issue by senbaikang** [snakemake/snakemake#2232]
**Snakemake version**

Snakemake: 7.25.0 from conda
Python: 3.11.3

**Describe the bug**

I have a file declared as output in a rule containing `notebook`. When the interactive Jupyter notebook is open, I saved the output file in local. However, the workflow is then blocked by an `IncompleteFilesException` error.

Command line that I used: `snakemake --cores 1 --use-conda --edit-notebook results/step_1/FLAG`

**Logs**

```
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
results/step_1/FLAG
```

**Minimal example**

See the attached compressed file below.
[test.tgz](https://github.com/snakemake/snakemake/files/11332439/test.tgz)

**Additional context**

**Comment by SilenWang** [comment]
Is this issue resolved? I encountered the same issue while using Snakemake version 8.12.0
