### ISSUE TITLE
Question regarding multithreading in rules

### ISSUE THREAD

**Issue by fanavarro** [snakemake/snakemake#2236]
Hi, I am currently using snakemake 7.16.0, and I have a question regarding multithreading in rules.

I've been using previous versions of snakemake, in which the number of cores to use was set through a parameter called "cores" in the config file, and this value is used in the "shell" section of the rules by injecting them with `{config[cores]}` when the corresponding shell statement accepts a parameter indicating the number of threads to use. For example, the shell section of a rule can be the following, where unicycler has the '-t' option to set the number of threads to use:

`unicycler -1 {input.R1} -2 {input.R2} -l {input.reads} -o {params.outdir} -t {config[cores]} --existing_long_read_assembly {input.longasm}`

Recently I updated snakemake to v7.16.0, and I noticed that the parameter `--cores` was mandatory in the command line, so I started to set the --cores option in the command line with the same value that I had in the config file. I also noticed the `threads` section in the rule to set the number of threads for that rule, but I did not use it. I thought that, with this configuration, my rules will continue executing with multi-threading.

Nonetheless, I had to use an application in my rule that checks the number of available cores before executing its stuff, and this application is seeing that only 1 core is available (my computer has 64). This application uses the command `nproc` to check the maximum number of cores to use. I have prepared a very simple rule to exemplify this:

```
rule test:
    output:
        out="nproc.txt"
    shell:
        """
        echo $(nproc)
        nproc > {output.out}
        """
```
To execute the rule, supposing that it is saved in 'workflow.snk':
`snakemake -F --cores 25 --snakefile workflow.snk nproc.txt`

Here, nproc returns a number of 1 core available. Nonetheless, if I use the threads option, nproc returns the minimum value between threads and cores; for example, with the following rule:
```
rule test:
    output:
        out="nproc.txt"
    threads: 15
    shell:
        """
        echo $(nproc)
        nproc > {output.out}
        """
```

nproc returns 15.

So, my question is, are the number of threads limited to only 1 if the `threads` statement is not set in the rule? And, what happens if I am executing an application, such as unicycler, that accepts the `-t` option to set the threads to use, but the rule does not have the threads declaration? There will be a single thread dealing with all the work?

Thanks in advance,
Francisco Abad.

**Comment by SichongP** [comment]
The `--cores` command line argument sets total number of cores this workflow can use. The `threads:` key word in a rule sets number of threads each job spawned from that rule is allowed to use. `threads` for each rule is, by default, 1. That's why you see 1 in your first example and 15 in your second example.
The total number of threads used by all jobs concurrently running in a workflow cannot exceed the number specified by `--cores`.

**Comment by fanavarro** [comment]
Hi @SichongP, thanks for your quick answer!

So, in my example with unicycler, I should use the threads keyword in the rule to execute it in parallel actually, right? I understand that otherwise, there will be a single thread moving between tasks generated by the -t option of unicyler.

**Comment by SichongP** [comment]
Yes, you can use `-t {threads}` instead of `-t {config[cores]}`

**Comment by fanavarro** [comment]
Ok, everything is clear for me, thanks so much @SichongP!
