### ISSUE TITLE
slurm hang in SLURM mode

### ISSUE THREAD

**Issue by Zepeng-Mu** [snakemake/snakemake#2280]
**Snakemake version**
Snakemake 7.26.0

**Describe the bug**
When using `--slurm` for snakemake execution includes more than one rule, it hangs after the first rule is finished. In fact, snakemake cannot detect job completion and hang there. I have to use Control-C to interrupt snakemake and execute again.

**Additional context**
`--cluster` still works as before. Some other issues offered various solutions, but did not seem to work for me. From a user perspective, I would like the behavior of `--slurm` the same as `--cluster`, as slurm is a new command, at least it did not exist in 7.14.0, which is the version I was using before.

**Comment by cmeesters** [comment]
Sorry for looking into this so late - the [snakemake executor for slurm now has its own repo](https://github.com/snakemake/snakemake-executor-plugin-slurm).

Please update and test again. If the issue persists, report it in the dedicate repo. Be sure to include your SLURM version (available when running `sinfo --version`) and the output of `sacct -X --parsable2 --noheader --format=JobIdRaw,State -u $USER`.
