### ISSUE TITLE
Type check for `cpus_per_task` does not work

### ISSUE THREAD

**Issue by FFroehlich** [snakemake/snakemake#2281]
**Snakemake version**

7.26.0

**Describe the bug**

`TypeError: '>' not supported between instances of 'str' and 'int'` error message

**Logs**

**Minimal example**

specify

```
resources:
        cpus_per_task="1",
```

for any rule and use the slurm scheduler

**Additional context**

I believe 

https://github.com/snakemake/snakemake/blob/95b8dfefdb19945aaa038da387d6eadd653bffcd/snakemake/executors/slurm/slurm_submit.py#L252 

is not doing it's intended job. This type check will only works for `job.threads`, but not `job.resources.cpus_per_task`. Also the error message probably wouldn't be too helpful as it does not distinguish between `"1"` and `1`.

**Comment by SichongP** [comment]
Looks like the `if` statement should come after the line below it. Should be an easy fix

**Comment by cmeesters** [comment]
sorry for looking up this thread so late - since Snakemake >=8 we adopted the plugin scheme. Please use the [slurm executor plugin](https://github.com/snakemake/snakemake-executor-plugin-slurm/)
