### ISSUE TITLE
Slurm resource allocation and usage

### ISSUE THREAD

**Issue by ftabaro** [snakemake/snakemake#2317]
We can submit jobs to the Slurm scheduler via the `--slurm` argument. This is great. By default we have Slurm log files in `.snakemake/slurm_logs/`. We can implement fallible rule and dynamic resource allocation on a per-rule basis with `retries` and  `resources` directives. What is missing in the Slurm logs is the resources assigned to each rule, can we make this info emerge in the log files?

Second, question. HPC resources allocation is notoriously a bit of a try and error process, especially with poorly documented/experimental tools. Reasonably recent Slurm versions offer the `seff` script to assess the efficiency of a job. Can we consider running it on a per-job basis, collect some statistics and make them available to the users either in the `slurm_logs` or in the Snakemake report if required? Maybe organize the `slurm_logs` folder into two subfolders one holding the current jobs logs and the other jobs statistics.

**Comment by ftabaro** [comment]
OK I just figured out that resource allocation is reported in the `slurm_logs` files :) 

I still think it would be nice to have the info of resources utilization efficiency somewhere. As a bonus, one could also get the reason why some jobs fail (timeout, oom etc) becasue `seff` reports it. Probably a similar result could be achieved with `sacct` and some calculation on the Snakemake side, the advantage of `sacct` is that is older and present in earlier Slurm versions.

**Comment by fgvieira** [comment]
Have you tried `snakemake`'s [benchmarks](https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#benchmarking)? It provides info on time, memory, load, etc...

**Comment by cmeesters** [comment]
closing this issue - meanwhile snakemake >=v8 supports the [slurm executor plugin](https://github.com/snakemake/snakemake-executor-plugin-slurm) and the benchmark feature works just fine. 

Relying on `seff` might be severely misleading: SLURM samples the job, however snakemake submits itself and then - upon request - will benchmark your applications. If using `seff` this overhead will be considered, too. If working on a slow file system, this will lead to lousy figures.
