### ISSUE TITLE
Slurm account names with spaces in result in "The given account {account} appears to be invalid"

### ISSUE THREAD

**Issue by benjeffery** [snakemake/snakemake#2320]
**Snakemake version**
7.29.0

**Describe the bug**
When the user's slurm account has spaces in, the error 'The given account {account} appears to be invalid' is raised.
This is due to line https://github.com/snakemake/snakemake/blob/f1b8342757fc5554eb7a9ed5d393c376e9089c3c/snakemake/executors/slurm/slurm_submit.py#L51 where the string list of accounts is `split`.
If this is bypassed an additional problem comes on line https://github.com/snakemake/snakemake/blob/f1b8342757fc5554eb7a9ed5d393c376e9089c3c/snakemake/executors/slurm/slurm_submit.py#L159 when there are no quotes around the account name when it is used on the command line.

**Comment by cmeesters** [comment]
Hi,

Sorry, I overlooked this issue - since snakemake v8 the [executor code code for slurm lives in its own repository](https://github.com/snakemake/snakemake-executor-plugin-slurm).

Now, the bug probably persists: We did not anticipate a SLURM account to contain whitespace of any kind, though any byte seems to be valid for SLURM.

I _think_ I can code a fix. Would you be so kind to paste the output of 

```Python
import os
import subprocess

cmd = f'sacctmgr -n -s list user "{os.environ["USER"]}" format=account%256'
accounts = subprocess.check_output(
                cmd, shell=True, text=True, stderr=subprocess.PIPE
            )
```
here in the thread?

**Comment by cmeesters** [comment]
You can also try and see whether the proposed fix (see the link about in this thread) fixes the issue, already.

**Comment by benjeffery** [comment]
Many thanks for looking into this.

@savitakartik Could you run the above code on the cluster?

**Comment by savitakartik** [comment]
> Hi,
> 
> Sorry, I overlooked this issue - since snakemake v8 the [executor code for SLURM lives in its own repository](https://github.com/snakemake/snakemake-executor-plugin-slurm).
> 
> Now, the bug probably persists: We did not anticipate a SLURM account to contain whitespace of any kind, though any byte seems to be valid for SLURM.
> 
> I _think_ I can code a fix. Would you be so kind to paste the output of
> 
> ```python
> import os
> import subprocess
> 
> cmd = f'sacctmgr -n -s list user "{os.environ["USER"]}" format=account%256'
> accounts = subprocess.check_output(
>                 cmd, shell=True, text=True, stderr=subprocess.PIPE
>             )
> ```
> 
> here in the thread?
> 
> PS The idea is, of course, that people forget to specify an account on a cluster, where this is mandatory, but may have several. And, alas, `sacctmgr` spits out every account with a new line and has little wiggle room for formatting.

Thanks for looking into this, @cmeesters. The output I get looks like this:
                                                                                                                                                                                                                                                         `109 genetics coe \n                                                                                                                                                                                                                                                                                        109 genetics coe \n                                                                                                                                                                                                                                                              109 genetics coe \n`

**Comment by cmeesters** [comment]
Huh? Ok, my fix ought to work for accounts containing whitespace. But here it would assume, that your account is literally `115 genetics coe`. That is a bit ... peculiar. Or is it really your SLURM account?

The thing is: We try to cover all cluster quirks, but some admins are really creative when it comes to implementing exceptions. You could always write

```YAML
default-resources:
   slurm_account: "genetics coe"
   slurm_partition: "<your default partition, if necessary>"
   
set -resources:
    non_local_rule_deviating_from_default:
         runtime: "1h"
         slurm_partition: "<some other partition>"
         cpus_per_task: 64
         mem_mb_per_cpu: 3600
```
or whatever else you need and deviates from the guess - or specify the same stuff on the command line, yet right now the assumption is `115 genetics coe` is your account.

**Comment by areleu** [comment]
I get the same error message when the accounts consist only of numbers, should I raise a different issue for this?

**Comment by cmeesters** [comment]
@benjeffery @areleu Please note: The mentioned version is outdated. If any issue persists, please update to the recent version combination of Snakemake and the executor plugin. If it still persists, please open an issue report at the plugin repo: https://github.com/snakemake/snakemake-executor-plugin-slurm/issues
