### ISSUE TITLE
Job continuation. Keep output files

### ISSUE THREAD

**Issue by ale94mleon** [snakemake/snakemake#2357]
**Is your feature request related to a problem? Please describe.**
Let's consider that one rule generate three files `a.ext1`, `a.ext2`, `a.ext3` which are also declared as output of the rule and that this rule is expensive (in finish in around 3 days). The workflow is launched in a HPC cluster. Because of the usual time restriction (let say 2 days) that we have on a HPC cluster, this rule will be killed before it finish.  This is not a problem because the running program in the rule is able to restart based on the information of the three mentioned files.
Even when I set `retries` to 3 (for example), when the rule restart it delete the files `a.ext1`, `a.ext2`, `a.ext3`, and then the program start from scratch. I understand this feature prevents of possible corrupted output files but in my case I am sure that they are not corrupted and I need them to restart properly the calculation. I tried with the flag `-keep-incomplete`. But this only work if the rule fails, but that is not the case here, usually what you get in a workload manager when you exceed the time of the partition is a TER signal.

**Describe the solution you'd like**
Some flag or parameter defined in the rule itself that specify what to do with the output files in case of restart. I tried to find in the documentation but I did not find anything like this.

**Comment by Hocnonsense** [comment]
Can you handle outputs trickly?
You can write a rule like this:
```
rule xx:
    output: xx.finish
    params: a.ext1, a.ext2, a.ext3
    shell: "bash finish_your_job {params[1]} {params[2]} {params[3]}; touch {output}"
```
or
```
rule xx:
    output: a.ext1, a.ext2, a.ext3
    params: temp=temp
    shell: "mkdir {params.temp}; bash finish_your_job {params.temp}{{{params[1]},{params[2]},{params[3]}}}; mv {prams.temp}/* ."
```

**Comment by ale94mleon** [comment]
Hi, thanks. That makes a lot of sense! With the following function I could achieve such behaviour.

```python
import os
from typing import Union, List

def paths_exist(paths:List, raise_error:bool = False, out:Union[str, None] = None) -> None:
    """Check that the paths exist

    Parameters
    ----------
    paths : List
        A list of paths
    raise_error : bool, optional
        If True will raise a RuntimeError when any path doe snot exist, by default False
    out : Union[str, None], optional
        In case that all files exist and out is st to some file; the existence of this file could be 
        used as a check that all paths exist (useful for sanekemake), by default None

    Raises
    ------
    RuntimeError
        In case some path does not exist and rasie_error = True
    """
    check = True
    for path in paths:
        if not os.path.exists(path):
            check = False
            msg = f"Missing path/file: {path}"
            if raise_error:
                raise RuntimeError(msg)
            else:
                print(msg)
    if out and check:
        open(out, "w").close()
```

Now I have to test on my workflow ;-)

**Comment by ale94mleon** [comment]
The idea works. Thanks @Hocnonsense!
