### ISSUE TITLE
FTP.remote fails to download file.

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#2363]
**Snakemake version**

`7.30.1`

**Describe the bug**

`snakemake` fails when downloading a file with `FTP.remote`, even thouh it works fine with `HTTP.remote`.

**Logs**

```
$ snakemake -j 10 out/nt/v5/nt.fas.gz
Building DAG of jobs...
MissingInputException in rule download_ncbi_nt in file ./Snakefile, line 6:
Missing input files for rule download_ncbi_nt:
    output: out/nt/v5/nt.fas.gz
    wildcards: version=5
    affected files:
        ftp.ncbi.nlm.nih.gov/blast/db/v5/FASTA/nt.gz.md5
```

**Minimal example**

```
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
FTP = FTPRemoteProvider()


rule download_ncbi_nt:
    input:
        md5 = FTP.remote("ftp.ncbi.nlm.nih.gov/blast/db/v{version}/FASTA/nt.gz.md5"),
    output:
        ref = "out/nt/v{version}/nt.fas.gz",
    log:
        "logs/nt/v{version}/nt.log",
    threads: 1
    shell:
        "aria2c --max-concurrent-downloads {threads} --file-allocation none --retry-wait 5 --console-log-level warn --log-level notice --log {log} --out {output.ref} ftp://ftp.ncbi.nlm.nih.gov/blast/db/v{wildcards.version}/FASTA/nt.gz > /dev/null"
```

**Additional context**

The path is correct, since `wget` works fine:
```
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/v5/FASTA/nt.gz.md5
```

**Comment by maarten-k** [comment]
There is something odd with the FTP server. It is not possible to list the files of this particular folder via FTP. 

 I advise you to use the HTTP version of the site  (https://ftp.ncbi.nlm.nih.gov/blast/db/) and download it with the Read-only web (HTTP[S]): snakemake.remote.HTTP)

It is possible to solve this case, but I am not sure it is good practice to make a workaround for a N=1 case.

**Comment by fgvieira** [comment]
Do you think is is something to do with this specific server? But `wget` works fine...

**Comment by maarten-k** [comment]
> Do you think is is something to do with this specific server? But `wget` works fine...
You can read the technical discussion at https://todo.sr.ht/~sschwarzer/ftputil/156#event-252738 

I will try to fix this error without a significant performance hit, but I am not sure at the moment if that is possible.
