### ISSUE TITLE
SLURM: Do not test empty account

### ISSUE THREAD

**Issue by jindrahelcl** [snakemake/snakemake#2378]
So far I was not able to configure my SLURM account to be empty without snakemake trying to first guess, then test it, and then finally settling for the empty account. The problem is that in our environment the slurm commands used in guessing and testing are not properly configured and take a long time before failing.

Is there way how I can specify explicitly that I want to use the empty account without performing any of these additional actions?

https://github.com/snakemake/snakemake/blob/384d0066c512b0429719085f2cf886fdb97fd80a/snakemake/executors/slurm/slurm_submit.py#L163

**Comment by cmeesters** [comment]
should be solved long ago. Please submit slurm related issues [over at the plugin repo](https://github.com/snakemake/snakemake-executor-plugin-slurm). I am sorry for overlooking this issue, have been a maintainer for a short time, only.

There is, however a similar issue, a fix for when SLURM gives '(null)' as a feedback is pending review.
