### ISSUE TITLE
Apptainer not recognised

### ISSUE THREAD

**Issue by RenscoHogers** [snakemake/snakemake#2380]
**Snakemake version**
7.31.0

**Describe the bug**
I am trying to run a snakemake pipeline which includes a container, however, when I try to run it with apptainer it does not recognise it. I have tried to alias Apptainer as singularity, but this has not resolved the issue. I am running Apptainer version 1.2.0. Do I need to include a different variable in my config file, as opposed to "use-singularity: true"?

**Logs**
Building DAG of jobs...
WorkflowError:
The singularity command has to be available in order to use singularity integration.

**Comment by gipert** [comment]
Thumbs up for Apptainer support! Should be easy to adapt the existing code. Apptainer has more or less the same command line interface.

**Comment by maarten-k** [comment]
Apptainer should be supported. Snakemake looks for the singularity program. Apptainer (used) to create symbolic link to the apptainer executable with the name singularity.

**Comment by maarten-k** [comment]
Apptainer still creates a symlink from singularity to Apptainer. Can you create a symlink in your $PATH to Apptainer and check if it works?

**Comment by RenscoHogers** [comment]
I have created a symlink which seams to work perfectly outside of snakemake. Do I need to include something in my snakefile in order to make sure it uses the aliases?

**Comment by maarten-k** [comment]
By default, apptainer makes a symlink named singularity to apptainer. So I wonder if the installation is done right. 

Can you give the output of

```ls -la $(which singularity)```

and ```apptainer --version```

**Comment by RenscoHogers** [comment]
I updated the apptainer version from 1.2.0 to 1.2.2 and snakemake from 7.31.0 to 7.32.3 and it seems to work now.
Our SLURM server is quite crowded so it takes a while before a job goes from pending to running, so whether manages to run the container remains to be seen. But it at least recognises apptainer.

Thanks for helping out!
