### ISSUE TITLE
Is there a way to run a snakemake rule only after another rule has finished without linking them by input/output?

### ISSUE THREAD

**Issue by LukaLmelias** [snakemake/snakemake#2384]
I have two rules; rule A produces many files; rule B takes in all the files of rule A and produce a single file.

So rule B must be run only after rule A is finished;

I know i can put the outputs of rule A as the inputs of rule B so that it can wait, if i do this i get an error that Wildcards in input files cannot be determined from output files, which is true because the output of rule B is only a single directory.

My question:

is there no a flag that i can ask rule B to wait for rule A to finish?

Many thanks for your help!

**Comment by cademirch** [comment]
Can you provide an example of your rule A and rule B? It should make it clear why you're running into a wildcard error.

**Comment by LukaLmelias** [comment]
hi touch founction seems to solve my problem ( https://snakemake.readthedocs.io/en/master/snakefiles/rules.html)  so this can be closed
