### ISSUE TITLE
`TypeError` exception thrown with `--wms-monitor` pointing to Panoptes server

### ISSUE THREAD

**Issue by gipert** [snakemake/snakemake#2390]
Panoptes version: 0.2.0
Snakemake version: 7.31.0

```console
> panoptes --port 5000 &
 * Serving Flask app 'panoptes.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://128.55.64.45:5000
Press CTRL+C to quit
> snakemake --wms-monitor http://127.0.0.1:5000
Using profile workflow/profiles/default for setting default command line arguments.
127.0.0.1 - - [03/Aug/2023 06:55:48] "GET /api/service-info HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/global/common/software/m2676/sims/.conda/envs/snakemake/bin/snakemake", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/global/common/software/m2676/sims/.conda/envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 3092, in main
    wms_logger = logging.WMSLogger(
                 ^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m2676/sims/.conda/envs/snakemake/lib/python3.11/site-packages/snakemake/logging.py", line 139, in __init__
    self.create_workflow()
  File "/global/common/software/m2676/sims/.conda/envs/snakemake/lib/python3.11/site-packages/snakemake/logging.py", line 178, in create_workflow
    "snakefile": os.path.join(workdir, self.metadata.get("snakefile")),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by fgypas** [comment]
I wonder if this PR has to do with it: https://github.com/snakemake/snakemake/pull/2347

@bilgehannevruz Any idea if there is some change needed on the server side?

**Comment by fgypas** [comment]
@gipert  Can you please provide a path to the Snakefile via `--snakefile`? 

`snakemake --wms-monitor http://127.0.0.1:5000 --snakefile Snakefile` for example

**Comment by fgypas** [comment]
So what happened in this case is that the snakefile of the metadata dictionary in this line: https://github.com/snakemake/snakemake/blob/main/snakemake/logging.py#L179  contained a `None` value. So the `os.path.join` would not work. If you specify a snakefile via the `--snakefile` argument I think that it will work. @gipert Please let me know if this fixes the issue for you.

**Comment by gipert** [comment]
It fixes it, yes. Still a bug though?

**Comment by fgypas** [comment]
Hm not sure. Did the default behaviour of snakemake change? Where should be the default Snakefile be stored?

**Comment by gipert** [comment]
`workflow/Snakefile` is also supported as default location.

**Comment by bilgehannevruz** [comment]
Hello, sorry for my late response.

This one https://github.com/snakemake/snakemake/pull/2347 has no relation with raised typeerror.

I also have encountered this error and indeed providing `--snakefile` from command-line solved the issue.
If you don't provide --wms-monitor, you don't get the error. I didn't fully trace how it occurs
