### ISSUE TITLE
Wildcards change for every rule

### ISSUE THREAD

**Issue by freekvh** [snakemake/snakemake#240]
**Snakemake version**
5.10

**Describe the bug**
During pipeline execution Snakemake reports different wildcards for each rule. Example: Expected wildcard sample: 0053_P2017BB3S20R_S2, becomes: 0053_P2017BB3S20R_S2_R or 0053_P2017BB3S20R_S2_ depending on he rule.

**Minimal example**
I construct the input/output names from the samples table, a read and a fastq_file_extension list like this:

```
samples = pd.read_csv('samples.tsv', sep='\t').set_index('samples', drop=False)
reads = ['R1', 'R2']
fastq_file_extension = _001.fastq.gz
```

Two rules from my pipeline are:

```
rule fastqc:
    input:
        os.path.join(config['Directories']['fastq_raw_dir'], '{sample}_{read}' + fastq_file_extension)
    output:
        html=os.path.join(config['Directories']['fastqc_dir'], '{sample}_{read}_fastqc.html'),
        zip=os.path.join(config['Directories']['fastqc_dir'], '{sample}_{read}_fastqc.zip')
    wrapper:
        "0.49.0/bio/fastqc"
```

and

```
rule trim_galore_pe:
    input:
        [os.path.join(config['Directories']['fastq_raw_dir'], '{sample}' + read + fastq_file_extension) for read in reads]
    output:
        fastq_read1 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.1_val_1.fq.gz'),
        fastq_read2 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.2_val_2.fq.gz'),
        report_read1 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.1.fastq.gz_trimming_report.txt'),
        report_read2 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.2.fastq.gz_trimming_report.txt')
    params:
        extra="--retain_unpaired"
    wrapper:
        "0.49.0/bio/trim_galore/pe"
```

During execution both rules report different wildcards and so the process goes wrong, the output filenames are not as expected:

For the fastqc rule you can see that it pulled the R to the sample wildcard and added an _.
```
[Fri Feb 21 12:39:57 2020]
rule fastqc:
input: fastq_raw/0053_P2017BB3S20R_S2_R1_001.fastq.gz
output: qc/fastqc/0053_P2017BB3S20R_S2_R1_fastqc.html, qc/fastqc/0053_P2017BB3S20R_S2_R1_fastqc.zip
jobid: 10
wildcards: sample=0053_P2017BB3S20R_S2_R, read=1
```

For the trim_galore_pe rule you can see that it added and extra _ to the sample wildcard
```
[Fri Feb 21 12:39:57 2020]
rule trim_galore_pe:
input: fastq_raw/0053_P2017BB3S20R_S2_R1_001.fastq.gz, fastq_raw/0053_P2017BB3S20R_S2_R2_001.fastq.gz
output: fastq_trimmed/0053_P2017BB3S20R_S2_.1_val_1.fq.gz, fastq_trimmed/0053_P2017BB3S20R_S2_.2_val_2.fq.gz, qc/trim_galore/0053_P2017BB3S20R_S2_.1.fastq.gz_trimming_report.txt, qc/trim_galore/0053_P2017BB3S20R_S2_.2.fastq.gz_trimming_report..txt
jobid: 7
wildcards: sample=0053_P2017BB3S20R_S2_
```

I also tried to add the _ to the read parameter, like so: `reads = ['_R1', '_R2']`, actually I prefer this because some files do not use _ as a coupling between the sample name and read indicator and I can change it in 1 place.
But then Snakemake will also add another extra _ behind the sample wildcard (notice the two _'s after S1) and the pipeline ends immediately:

```
Building DAG of jobs...
MissingInputException in line 1 of /home/nlv24077/temp/RNASeqPairedEnd/rules/trim_galore_pe.smk:
Missing input files for rule trim_galore_pe:
fastq_raw/0053_P2017BB3S19R_S1__R2_001.fastq.gz
fastq_raw/0053_P2017BB3S19R_S1__R1_001.fastq.gz   
```

Is there a way to prevent Snakemake from altering the wildcards in any way? Why does it do it anyway? Is there something I should change?

Oh and one more thing, is this the primary home for Snakemake or bitbucket? Where do you want me to post issues? Thanx for the great software by the way! I'm very happy with it.

**Comment by troycomi** [comment]
Welcome!  Github is the primary home for snakemake, though for questions like this [stackoverflow](https://stackoverflow.com/questions/tagged/snakemake) is a better place to post.

The issue with your pipeline is that you aren't quite matching the inputs of trim_galore with the outputs of fastqc.
```python
input:
        [os.path.join(config['Directories']['fastq_raw_dir'], '{sample}' + read + fastq_file_extension) for read in reads]
# becomes
    'dir/{sample}R1_001.fastq.gz', 'dir/{sample}R2_001.fastq.gz', 
 ```
Which is missing the underscore between sample and read.  I find it easier use a variable for each file and then reuse that between rules to eliminate these kind of errors.  If you place those in your config yaml then all the filenames are in one place.  
```python
fastq_file = os.path.join(config['Directories']['fastq_raw_dir'], '{sample}_{read}' + fastq_file_extension)

rule fastqc:
    input:
        fastq_file
    output:
        html=os.path.join(config['Directories']['fastqc_dir'], '{sample}_{read}_fastqc.html'),
        zip=os.path.join(config['Directories']['fastqc_dir'], '{sample}_{read}_fastqc.zip')
    wrapper:
        "0.49.0/bio/fastqc"

rule trim_galore_pe:
    input:
        expand(fastq_file, read=reads, allow_missing=True)  # allow missing keeps sample as {sample}
    output:
        fastq_read1 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.1_val_1.fq.gz'),
        fastq_read2 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.2_val_2.fq.gz'),
        report_read1 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.1.fastq.gz_trimming_report.txt'),
        report_read2 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.2.fastq.gz_trimming_report.txt')
    params:
        extra="--retain_unpaired"
    wrapper:
        "0.49.0/bio/trim_galore/pe"
```
Or just change your input:
```python
input:
        [os.path.join(config['Directories']['fastq_raw_dir'], '{sample}_' + read + fastq_file_extension) for read in reads]
# becomes
    'dir/{sample}_R1_001.fastq.gz', 'dir/{sample}_R2_001.fastq.gz', 
 ```

**Comment by freekvh** [comment]
Hi thanx for your response, I did what you said:

```
fastq_file = os.path.join(config['Directories']['fastq_raw_dir'], '{sample}_{read}' + fastq_file_extension)

rule trim_galore_pe:
    input:
        expand(fastq_file, read=reads, allow_missing=True)
    output:
        fastq_read1 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.1_val_1.fq.gz'),
        fastq_read2 = os.path.join(config['Directories']['fastq_trimmed_dir'], '{sample}.2_val_2.fq.gz'),
        report_read1 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.1.fastq.gz_trimming_report.txt'),
        report_read2 = os.path.join(config['Directories']['trim_galore_qc_dir'], '{sample}.2.fastq.gz_trimming_report.txt')
    params:
        extra="--retain_unpaired"
    wrapper:
        "0.49.0/bio/trim_galore/pe"
```

It still crashes:

```
Building DAG of jobs...
MissingInputException in line 1 of /home/nlv24077/temp/RNASeqPairedEnd/rules/trim_galore_pe.smk:
Missing input files for rule trim_galore_pe:
fastq_raw/0053_P2017BB3S19R_S1__R2_001.fastq.gz
fastq_raw/0053_P2017BB3S19R_S1__R1_001.fastq.gz  
```

There is still an extra _ coming from somewhere, right??

**Comment by troycomi** [comment]
Are you still doing this:
>I also tried to add the _ to the read parameter, like so: `reads = ['_R1', '_R2']`, actually I prefer this because some files do not use _ as a coupling between the sample name and read indicator and I can change it in 1 place.
If that's how you want your reads then remove the underscore from the first rule.

**Comment by freekvh** [comment]
> 
> 
> Are you still doing this:
> 
> > I also tried to add the _ to the read parameter, like so: `reads = ['_R1', '_R2']`, actually I prefer this because some files do not use _ as a coupling between the sample name and read indicator and I can change it in 1 place.
> 
> If that's how you want your reads then remove the underscore from the first rule.

No, I removed it from there. Somewhere Snakemake adds it again. Is there a way to see what all wildcards at every step? Is there way to just say to Snakemake: Please don't change my wildcards, just use whatever is provided in the samples.tsv and the snakefile? I feel that there is a lot going on "under the hood" regarding in and output, which I have a hard time grasping.

**Comment by troycomi** [comment]
Try running with `--verbose` and `--debug-dag`.  Snakemake doesn't just change wildcards, but the regular expression and directive code can be hard to grasp.  Using `rules.trim_galore_pe.output.read1` is fine and I think the rules you shared look ok.  

From your initial outputs:
```
# rule fastqc
wildcards: sample=0053_P2017BB3S20R_S2_R, read=1
# rule trim_galore_pe
wildcards: sample=0053_P2017BB3S20R_S2_
```
so already the sample and read aren't being parsed the way you think.  It could be a rule upstream is also ill-formed and the effect is cascading to these rules at the start of your pipeline.

If debug and verbose don't help I can look at your Snakefile to provide more feedback.  If you can put it on github we can move the conversation to that repo.

**Comment by freekvh** [comment]
> 
> 
> Try running with `--verbose` and `--debug-dag`. Snakemake doesn't just change wildcards, but the regular expression and directive code can be hard to grasp. Using `rules.trim_galore_pe.output.read1` is fine and I think the rules you shared look ok.
> 
> From your initial outputs:
> 
> ```
> # rule fastqc
> wildcards: sample=0053_P2017BB3S20R_S2_R, read=1
> # rule trim_galore_pe
> wildcards: sample=0053_P2017BB3S20R_S2_
> ```
> 
> so already the sample and read aren't being parsed the way you think. It could be a rule upstream is also ill-formed and the effect is cascading to these rules at the start of your pipeline.
> 
> If debug and verbose don't help I can look at your Snakefile to provide more feedback. If you can put it on github we can move the conversation to that repo.

I have gotten it to work, indeed by cleanly separating the wildcards. I believe at least some of my grief was caused by that. The rest was by my wrong definition in sample.tsv.

This can be closed and I thank you for your help.

**Comment by tbooth** [comment]
I'll close this issue since @freekvh has said so.

Possibly a little more hand-holding for users when debugging a DAG like this could be added, as a future enhancement to Snakemake, but I don't think that is a reason to keep this particular bug live.
