### ISSUE TITLE
Singularity limit with long command line calls

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#242]
**Snakemake version**
all

**Describe the bug**
See here: https://github.com/sylabs/singularity/issues/5057. Essentially, Singularity has a hard-coded limit of around 120.000 characters (131072 bytes to store the configuration in JSON format). For pipelines with many files that are aggregated in a rule, this limit can be reached. This is mainly because of using absolute file names rather than relative ones.

**Logs**
`FATAL: Failed to initialize runtime engine: engine "" is not found error
`
**Minimal example**
Just construct a rule with >120.000 characters and run it inside a Singularity container

**Additional context**
Since this limitation is not going to be changed soon according to the reply from the Singularity maintainers (see above), Snakemake should check whether the command exceeds this length and if so, gracefully exit with an informative error message. I am not sure about solutions, though, the only thing that comes into my mind now is to replace absolute by relative paths.

**Comment by mberacochea** [comment]
This was addressed in Singularity, I think version 3.7 solves this https://github.com/hpcng/singularity/issues/5057.
