### ISSUE TITLE
Frequency of workflow catalogue stats updates

### ISSUE THREAD

**Issue by franciscozorrilla** [snakemake/snakemake#2428]
Just curious regarding how frequently the stats on the workflow catalogue are updated? Seems like its been a few weeks now :)

**Comment by DavideBrex** [comment]
I was thinking the same!

**Comment by DavideBrex** [comment]
I think the issue is related to the github actions..the catalogue is not correctly updated:
https://github.com/snakemake/snakemake-workflow-catalog/actions

![errorCatalog](https://github.com/snakemake/snakemake/assets/48018596/54324548-6bf8-47e2-a55c-6efcea9e9983)

**Comment by franciscozorrilla** [comment]
Good catch, I checked the logfile and it looks like the error might be related to some rate limit being exceeded?

https://github.com/snakemake/snakemake-workflow-catalog/actions/runs/6045587868/job/16405876863#step:4:2439-L2441

**Comment by DavideBrex** [comment]
Yes, indeed, probably related to this: [rate limit](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/rate-limits-for-github-apps#about-rate-limits-for-github-apps)
Hope they fix it soon.
