### ISSUE TITLE
snakemake parse a wrong int like parameter.

### ISSUE THREAD

**Issue by conanyangqun** [snakemake/snakemake#2431]
**Snakemake version**
7.32.2

**Describe the bug**
when run snakemake using `--config s_id="2023023902_2", snakemake got "20230239022"`。
**Logs**

**Minimal example**
a Snakefile is:
```python
s_id = config['s_id']

print(s_id)
```

run it using:

```bash
snakemake --cores --config s_id="2023023902_2"
```

the terminal output is "20230239022".

**Comment by pecholleyn** [comment]
(To me) It's not a bug, it's a feature! See https://peps.python.org/pep-0515/
If you want to keep the "_ " (and get a type str instead of an integer) you can run the pipeline using:
```
--config s_id="'2023023902_2'"
```

**Comment by conanyangqun** [comment]
> (To me) It's not a bug, it's a feature! See https://peps.python.org/pep-0515/ If you want to keep the "_ " (and get a type str instead of an integer) you can run the pipeline using:
> 
> ```
> --config s_id="'2023023902_2'"
> ```

This is my fault. I haven't mastered this Python feature, thank you for pointing it out.
