### ISSUE TITLE
Add zsh completion

### ISSUE THREAD

**Issue by Janzulene** [snakemake/snakemake#2433]
**Is your feature request related to a problem? Please describe.**
Zsh is my default working shell environment, and it would be nice to have a zsh completion like bash. I often use snakemake to create and execute complex pipelines of tasks, and I would like to have a better user experience with zsh.

**Describe the solution you'd like**
I want to provide a similar completion to bash, which can complete the snakemake options, rules, and files in a smart and efficient way. I think this would benefit many users who use both snakemake and zsh, and improve their productivity and satisfaction.

**Describe alternatives you've considered**
I have considered using the bash completion scripts with `bashcompinit`, but it does not work at all. The code I tried is below:

```zsh
autoload -Uz compinit && compinit
autoload -U +X bashcompinit && bashcompinit

complete -C snakemake-bash-completion snakemake%
```

**Comment by coroa** [comment]
I was thinking about that yesterday as well, and found that snakemake's help output is structured enough that you can just use:

```bash
compdef _gnu_generic snakemake
```
as described at https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#completing-generic-gnu-commands .

**Comment by coroa** [comment]
Maybe that could be put somewhere into the documentation, because it really helps you navigate the amazing number of command line args that snakemake offers.

**Comment by Janzulene** [comment]
Thank you @coroa! I will give it a try.
Also, I found an amazing repository that solves my problem now - [zsh-completions-bio](https://github.com/yamaton/zsh-completions-bio). It is very comprehensive and contains nearly all the zsh completions I need for my bioinformatics work, I would highly recommend it for every bioinformatician who using zsh.
