### ISSUE TITLE
Datrie causing installation failures

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#246]
When running `pip3 install snakemake` using python3.7 or python3.8, the installation fails with an error relating to `datrie`.  

This is **not a bug with snakemake**, but a known issue with [`datrie`](https://github.com/pytries/datrie/issues/73). There is a [PR](https://github.com/pytries/datrie/pull/76) currently open which solves this problem, but until it is merged, the following solutions should work.

A [previous issue on bitbucket](https://bitbucket.org/snakemake/snakemake/issues/934/installation-failed-in-python-37) has dealt with this for python3.7.

https://github.com/snakemake/snakemake/issues/130 may be caused by the same problem, although the log in that error does not seem to mention `datrie`.

### Python3.7
```
pip3 install git+https://github.com/pytries/datrie.git
pip3 install snakemake
```
### ~~Python3.8~~
```
pip3 install "git+https://github.com/ashwinvis/datrie.git@python3.8"
pip3 install snakemake
```

**EDIT**: https://github.com/pytries/datrie/pull/78 seems to supersede the Python3.8 branch above.

### Python3.8

```
pip3 install "git+https://github.com/ashwinvis/datrie.git@python3.8-cythonize"
pip3 install snakemake
```

**Comment by johanneskoester** [comment]
This is really a pity. Any suggestion for a stable package we could use instead?

**Comment by mbhall88** [comment]
Yeah, it is unfortunate. I do feel sorry for the maintainers though, they're getting some very unwarranted abuse.  

The only other thing I could find that seems to be maintained is https://github.com/mina86/pygtrie which is a fork of Google's repo. They're pushing to the pypi releases, but I'm not sure if it is comparable to `datrie`.

**Comment by tacaswell** [comment]
datrie 0.8.2 should support py38 and was just pushed to pypi.

**Comment by tacaswell** [comment]
> they're getting some very [unwarranted abuse](https://github.com/pytries/datrie/pull/76#issuecomment-577339188).

I agree and left comments to that effect.

**Comment by johanneskoester** [comment]
Thanks a lot to everybody looking into this!
