### ISSUE TITLE
Debugging snakemake in PyCharm not working

### ISSUE THREAD

**Issue by WagnerNils** [snakemake/snakemake#247]
Hi all,
I'm trying to debug my snakemake script with Pycharm. Therefore I set up the following run configuration:
![image](https://user-images.githubusercontent.com/51838901/75357289-71355e00-58b1-11ea-9b98-5d2f7891ceeb.png)
`snakemake --debug -j1`
However, as soon as the script starts a job, it can't be stopped by the PyCharm debugger.
Is there a fix to this problem? Thanks in advance
Best, Nils

**Comment by johanneskoester** [comment]
Snakemake's --debug is not meant to work in combination with a debugger like the one in PyCharm. It is just a mode for running single threaded such that you can avoid concurrent output during manually setting the pdb debugger.
