### ISSUE TITLE
Python 3.12 break f string inside Snakemake

### ISSUE THREAD

**Issue by DrYak** [snakemake/snakemake#2480]
**Snakemake version**
Tested with snakemake 7.34.2
(older version are affected, too. Tested down to 7.18.2)

Affected Python version: 3.12.0
(Last known good: Python 3.11.6)

**Describe the bug**

When snakemake is installed with python version 3.12.0, f-strings get unexpected extra space.

For example:
```python
output: f'{PREFIX}.txt'
```
will produce...

**Logs**

...this output in the log (note the unexpected extra spaces):
```text
Building DAG of jobs...
File path ' SID23454678 .txt ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path ' SID23454678 .txt ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
```
When run on python 3.12.0

**Minimal example**

UnitTest.smk:
```python
#!/usr/bin/env python3
PREFIX = 'SID23454678'
rule unit1:
 input:
 output:
  f'{PREFIX}.txt'
 run:     
   "sleep 1"
```

Running with:
```shell
snakemake --dry-run -s UnitTest.smk --cores 1
```

In this environment... :
```shell
mamba create -n snake-test -c conda-forge -c bioconda snakemake-minimal=7.32.4 python=3.11
```
...everything work as expected:
```text
[Thu Oct 12 15:55:02 2023]
rule unit1:
    output: SID23454678.txt
    jobid: 0
    reason: Missing output files: SID23454678.txt
    resources: tmpdir=/tmp
```

But in that environment...:
```shell
mamba create -n snake-test -c conda-forge -c bioconda snakemake-minimal=7.32.4 python=3.12
```
...the bug is triggered:
```text
Building DAG of jobs...
File path ' SID23454678 .txt ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
File path ' SID23454678 .txt ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
```

**Additional context**

Apparently, the f-string have been [completely overhauled as part of python 3.12](https://realpython.com/python312-f-strings/). I suspect the new f-string parser somehow clashes with the parse of snakemake files.

**Comment by DrYak** [comment]
Big thanks to @JohannesGawron who helped in finding this one.

**Comment by johanneskoester** [comment]
What happens if you put a pdb statement directly after the PREFIX definition and manually invoke `f'{PREFIX}.txt'` in the debugger console. Does it also contain that whitespace around the value?

**Comment by JohannesGawron** [comment]
No it doesn't.

**Comment by DrYak** [comment]
@JohannesGawron did test it yesteday.

No whitespace in the debugger's interface.
Whitespaces if we add a `print()` in the snakemake file.

![Screenshot 2023-10-12 at 13 56 54](https://github.com/snakemake/snakemake/assets/11413679/4d7b2ef5-2375-4cb0-9b7e-6e72b7cac391)

**Comment by DrYak** [comment]
> No it doesn't.

Haha, you were faster than my screenshot upload. :-)

**Comment by DrYak** [comment]
@johanneskoester stupid question: when you say [in the documentation](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#snakefiles-and-rules):

> Inside the shell command, all local and global variables, especially input and output files can be accessed via their names in the [python format minilanguage](https://docs.python.org/py3k/library/string.html#formatspec).

Are you actually calling into the python format library? Is it possible that the special extensions to the format that snakemake does when expanding `run:` (properly separating arrays of arguments with spaces, e.g. `cat {inputs} > {output.final}`) accidentally badly interacts with the new python 3.12 f-string handler and breaks f-string in `input:` and `output:` ?

**Comment by Hocnonsense** [comment]
I test with param "--print-compilation" and that is output:
```python
#!/usr/bin/env python3
PREFIX = 'SID23454678'
@workflow.rule(name='unit1', lineno=3, snakefile='/home/hwrn/Templates/test.smk')

@workflow.input(

)

@workflow.output(
        f' { PREFIX } .txt '

)
@workflow.run
def __rule_unit1(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook, conda_base_path, basedir, runtime_sourcecache_path, __is_snakemake_rule_func=True):
                "sleep 1"

```

It is not caused by f-string but snakemake compilation

**Comment by DrYak** [comment]
@Hocnonsense Thanks for helping pin-point that.

**Comment by Hocnonsense** [comment]
further test on a simplifier snakefile:
```snakefile
#!/usr/bin/env python3
PREFIX = 'SID23454678'
if 1:
  f'{PREFIX}.txt'
```
```python
from snakemake import parser
import tokenize


class Snakefile:
        def __init__(self, snakefile, rulecount=0):
            self.path = snakefile
            self.file = open(self.path)
            self.tokens = tokenize.generate_tokens(self.file.readline)
            self.rulecount = rulecount
            self.lines = 0

        def __next__(self):
            return next(self.tokens)

        def __iter__(self):
            return self

        def __enter__(self):
            return self

        def __exit__(self, *args):
            self.file.close()

with Snakefile("snakefile", rulecount=0) as snakefile:
        automaton = parser.Python(snakefile)
        linemap = dict()
        compilation = list()
        for t, orig_token in automaton.consume():
            print(t, orig_token)
            l = parser.lineno(orig_token)
            linemap.update(
                dict(
                    (i, l)
                    for i in range(
                        snakefile.lines + 1, snakefile.lines + t.count("\n") + 1
                    )
                )
            )
            snakefile.lines += t.count("\n")
            compilation.append(t)
    compilation_ = "".join(parser.format_tokens(compilation))
    if linemap:
        last = max(linemap)
        linemap[last + 1] = linemap[last]
    print(compilation_, linemap, snakefile.rulecount)
```

and the key proble happened here:
```
f' TokenInfo(type=61 (FSTRING_START), string="f'", start=(4, 2), end=(4, 4), line="  f'{PREFIX}.txt'\n")
{ TokenInfo(type=55 (OP), string='{', start=(4, 4), end=(4, 5), line="  f'{PREFIX}.txt'\n")
PREFIX TokenInfo(type=1 (NAME), string='PREFIX', start=(4, 5), end=(4, 11), line="  f'{PREFIX}.txt'\n")
} TokenInfo(type=55 (OP), string='}', start=(4, 11), end=(4, 12), line="  f'{PREFIX}.txt'\n")
.txt TokenInfo(type=62 (FSTRING_MIDDLE), string='.txt', start=(4, 12), end=(4, 16), line="  f'{PREFIX}.txt'\n")
' TokenInfo(type=63 (FSTRING_END), string="'", start=(4, 16), end=(4, 17), line="  f'{PREFIX}.txt'\n")
```

**Comment by Hocnonsense** [comment]
So the key question happened here:
https://github.com/snakemake/snakemake/blob/8332d2d28af0900724f7a56aa0e394a99f48d9e0/snakemake/parser.py#L1248-L1254

**Comment by DrYak** [comment]
So what's the different between Python 3.12 and 3.11.6?
Tokenizer works differently?

**Comment by Hocnonsense** [comment]
I do think so. 
Before 3.12, tokenize.generate_tokens will yield the whole f-string like f"{PREFIX}.txt". 
Since 3.12, tokenize.generate_tokens will yield the whole f-string like 'f"', '{', 'PREFIX', '}', '.txt'. '"'

This is reporte in [pep-0701](https://peps.python.org/pep-0701/#new-tokens)

**Comment by DrYak** [comment]
So if I'm not mistaken, the line 1251 should be changed to recognize these new tokens from python 3.12, and not insert spaces around `F_STRING_BEGIN`, `F_STRING_MIDDLE` and `F_STRING_END` tokens?

**Comment by johanneskoester** [comment]
A PR would be very welcome!

**Comment by johanneskoester** [comment]
Thanks a lot for the detective work!

**Comment by dlaehnemann** [comment]
Just to quickly document a workaround for anybody who might land here with the same problem:

As I expect most users will follow the [recommended installation route via `mamba`/`conda`](https://snakemake.readthedocs.io/en/latest/getting_started/installation.html#installation-via-conda-mamba). With that in place, you can simply do:

```
mamba activate snakemake
mamba install python=3.11
```

This will activate the snakemake environment and will ensure that the python version used is `3.11`, the minor version before the breaking change described here.

**Comment by johanneskoester** [comment]
The bioconda package has been updated to require python<3.12 until we have fixed this.

**Comment by vinisalazar** [comment]
Just reporting that I'm experiencing this same problem as of today. Creating a fresh environment with Snakemake seems to install Python 3.12.

**Comment by JosephCottam** [comment]
Running python 3.12.0 and snakemake 7.32.4, I am seeing the extra spaces in f-strings.

```
rule:
    input: "{option}.in"
    output: "{option}.out"
    params: temp = lambda wildcards, output: f"{output}.temp"
    run: 
       print(params.temp)
       print(f"before_{wildcards.option}_after")
```

Printed results are:
```
 test.out .temp 
 before_ test _after 
```

**Comment by mfansler** [comment]
Doing just `mamba create -n smk_7 snakemake=7` still ends up with Python 3.12. That is, it simply ignores the latest `snakemake-minimal` build that added the `python <3.12` constraint. The repodata for `snakemake-minimal` should be patched on previous builds to properly address this.

**Comment by lparsons** [comment]
I'm still running into this issue, it's not clear if this is fixed for an upcoming release, or if this is indeed still broken.

**Comment by mfansler** [comment]
@lparsons right now, it's fixed for newer builds (`snakemake>=8.`). For anything v7 or lower, you must explicitly declare `python <3.12`.

We need to patch the metadata on Bioconda to add `python <3.12` to all pre-v8 builds.

**Comment by lparsons** [comment]
Thanks @mfansler. However, there are two issues and I'm not which are resolved:

1. Snakemake's incompatibility with python 3.12
2. The bioconda package workaround specifying `<3.12` in the bioconda recipies

I believe that the workaround is not yet in place for `snakemake<8` but is in place for `snakemake>=8`.

However, what is less clear is the status of the snakemake's compatibility with python 3.12.

**Comment by dlaehnemann** [comment]
The original problem should be fixed, by the pull request that the closing message of this issue cites:
https://github.com/snakemake/snakemake/issues/2480#event-11028552730

So, starting with snakemake `8.0.0`, the underlying incompatibility with python `3.12` is fixed, and no workaround should be necessary.

Same for snakemake version `7.32.4` (from build number `1` onwards). Here the bioconda recipe has been adjusted to never use python `3.12`:
https://github.com/bioconda/bioconda-recipes/pull/43716/files

For snakemake version before that, we would have to patch the repodata. Not sure if anybody has done this.

**Comment by lparsons** [comment]
Thanks for the clarification @dlaehnemann, and thanks for getting this resolved so quickly. My apologies, I thought I had tested `8+` and `3.12`, but  it seems that this issue is fixed. I was running into a second issue. When I used `8` it requires the use of storage plugins where I'm facing a different issue (#2564).

**Comment by sdruskat** [comment]
> The original problem should be fixed, by the pull request that the closing message of this issue cites: [#2480 (comment)](https://github.com/snakemake/snakemake/issues/2480#event-11028552730)
> 
> So, starting with snakemake `8.0.0`, the underlying incompatibility with python `3.12` is fixed, and no workaround should be necessary.

@dlaehnemann I'm not sure that this is fixed, as I've run into the added whitespace issue again.

I've installed Snakemake v8.2.3 (the latest currently available in bioconda) and Python 3.12 via `conda create -n snakemake8 -c bioconda -c conda-forge python=3.12 snakemake=8.2.3`.

Running the `Snakefile` below with `snakemake -c 1` yields and error, and the output still shows additional whitespaces:

```python
NAME = 'test'
OUTDIR = "out/"

rule all:
    output:
        f"{OUTDIR}{NAME}.out"
    shell:
        'echo "SUCCESS!" > {output}'
```

Output:

```shell
Building DAG of jobs...
Retrieving input from storage.
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
all          1
total        1

Select jobs to execute...
Execute 1 jobs...

[Thu Jan 25 13:24:27 2024]
localrule all:
    output: out/ test.out
    jobid: 0
    reason: Missing output files: out/ test.out      <---------------- Added whitespace
    resources: tmpdir=/tmp

/usr/bin/bash: line 1: out/: Is a directory      <---------------- Actual error
[Thu Jan 25 13:24:27 2024]
Error in rule all:
    jobid: 0
    output: out/ test.out      <---------------- Added whitespace
    shell:
        echo "SUCCESS!" > out/ test.out      <---------------- Added whitespace
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-01-25T132427.614936.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

```bash
(snakemake8) stephan@host:~/tmp$ python --version
Python 3.12.1
(snakemake8) stephan@host:~/tmp$ snakemake --version
8.2.3
```

Is this a different issue? Should I open this as a new issue for Snakemake 8?

**Comment by Hocnonsense** [comment]
Yes, it's indeed a bug that wasn't noticed in the last few fixations.

**Comment by Hocnonsense** [comment]
> Thanks for the confirmation :). Is this already tracked somewhere, or should I open a new issue to track this?

No, I'm just noticed from your comment, and a more robust fixation for f-string should be make.
