### ISSUE TITLE
Job names in slurm mode too cryptic

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#2494]
**Snakemake version**
newest as of today

**Describe the bug**
When using --slurm, job names are hashes or similarly cryptic characters that make it hard to understand what is running, like this example: JobName=e94f44ef-c1bf-466b-9406-537b0e9afa76

Would be good to have the rule name as job name, ideally with a wildcard assignment. Or is there already a way to encode that into a profile?

**Comment by chrarnold** [comment]
If I do this in the profile config, the job name is changed but as expected, `{rule}` is not resolved:

> set-resources:
>    je_demultiplex:
>     mem_mb: 30000
>     runtime: "48h"
>     slurm_extra: "--job-name=SUMseq.{rule}"

**Comment by chrarnold** [comment]
Is there a way to allow certain variables, such as `{rule}` and `{wildcards}`, in the config to make this more flexible, in analogy to how it used to work with the cluster config files in which this was also possible? @johanneskoester

**Comment by Hocnonsense** [comment]
You can just skip --slurm, but instead use --cluster.
I just use a profile/config.yaml to store these params:

```yaml
cluster: mkdir -p logs/{rule} &&
  bash src/slurm/get_jobid.sh
  '--partition={resources.partition}
  --ntasks-per-node={threads}
  --job-name=smk-{rule}-{wildcards}
  --nodes={resources.nodes}'
  '{rule}' '{wildcards}' '{dependencies}'
cluster-cancel: scancel
```

in get_jobid.sh:
```bash
sbatch_params=$1
rule=$2
wildcards=$3
dependencies=$4
script=$5

wildcards=${wildcards//\//--}
logs="--output=logs/${rule}/${rule}-${wildcards}-%j.out --error=logs/${rule}/${rule}-${wildcards}-%j.err"

if [[ ! -z $dependencies ]]
then
    depend="--depend="
    for dependency in $dependencies
    do
        depend="$depend"afterok:"$dependency"","
    done
    depend=${depend%,}
fi

#echo "$dependencies" >&2

sbr="$(sbatch $sbatch_params $logs $depend $script )"
if [[ "$sbr" =~ Submitted\ batch\ job\ ([0-9]+) ]]; then
    echo "${BASH_REMATCH[1]}"
    exit 0
else
    echo "sbatch failed"
    exit 1
fi
```

I think it may help you use slurm with snakemake.

**Comment by chrarnold** [comment]
Thanks for the reply, but I want to use --slurm and I think it works nicely in general, and the job name issue hopefully can be addressed again - it is simpler and less custom than the alternatives.

**Comment by Hocnonsense** [comment]
Now these code are move to [another reposity](https://github.com/snakemake/snakemake-executor-plugin-slurm) as a plugin, and related code to submit job is here:
https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/d0d342d64ff6ca9eb161ee710bb9e319eee12fbe/snakemake_executor_plugin_slurm/__init__.py#L82
and the feature `run_uuid` is defined here:
https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/d0d342d64ff6ca9eb161ee710bb9e319eee12fbe/snakemake_executor_plugin_slurm/__init__.py#L50

So, you can either: (1. pull request at [this reposity](https://github.com/snakemake/snakemake-executor-plugin-slurm)) or (2. fock an reposity, change the code, and install it)

I've found related commit for you:
https://github.com/snakemake/snakemake/commit/0bb69e429e161bf68b1f3e0b8f6fe3cbd6ed4dae#diff-d1b47826c1fc35806df72508e2f5e7f1d0424f9b2f7b9124810b051f5fe97f1bL210

**Comment by y9c** [comment]
Thank you @Hocnonsense, 

I checked the uuid of a series of jobs submitted by slurm executor and found that most of the uuid is identical although these jobs are defined by different rules and run on different nodes. Do you know why uuid is not 'unique'? And is there any solution to show rule name into `job-name` in the latest version (8.0.1)?

![image](https://github.com/snakemake/snakemake/assets/5415510/24da901c-1d1a-4b3c-aae3-ec64c9d4fc41)

**Comment by y9c** [comment]
I found a quick solution by edit the jobname, but still need some work to store the job id to limit the query output of `sacct` command

https://github.com/snakemake/snakemake-executor-plugin-slurm/compare/main...y9c:snakemake-executor-plugin-slurm:main

**Comment by Hocnonsense** [comment]
@y9c In snakemake >=8.0, you should use `--executor` to submit non-local jobs.

`--executor` accept a value such as `local` (default) and `touch`, for previous "cluster" job, you can choose `cluster-generic`.

Before you use `--executor cluster-generic`, you should install it via pip: `pip install snakemake-executor-cluster-generic`
Then you can use `--cluster-generic-submit-cmd`, `--cluster-generic-cancel-cmd` and so on to submit to slurm as you like.

---
In my `config.yaml`:
```yaml
cluster-generic-submit-cmd: mkdir -p logs/{rule} &&
  bash src/slurm/get_jobid.sh
  '--partition={resources.partition}
  --ntasks-per-node={threads}
  --job-name=smk-{rule}-{wildcards}
  --nodes={resources.nodes}'
  '{rule}' '{wildcards}' '{dependencies}'
```

in my `src/slurm/get_jobid.sh`:
```bash
sbatch_params=$1
rule=$2
wildcards=$3
dependencies=$4
script=$5

wildcards=${wildcards//\//--}
logs="--output=logs/${rule}/${rule}-${wildcards}-%j.out --error=logs/${rule}/${rule}-${wildcards}-%j.err"

if [[ ! -z $dependencies ]]
then
    depend="--depend="
    for dependency in $dependencies
    do
        depend="$depend"afterok:"$dependency"","
    done
    depend=${depend%,}
fi

#echo "$dependencies" >&2

sbr="$(sbatch $sbatch_params $logs $depend $script )"
if [[ "$sbr" =~ Submitted\ batch\ job\ ([0-9]+) ]]; then
    echo "${BASH_REMATCH[1]}"
    exit 0
else
    echo "sbatch failed"
    exit 1
fi
```

**Comment by y9c** [comment]
Thank you @Hocnonsense for providing this solution. It is very helpful. I am trying to fix this on the slurm executor repo, but I'm not sure if the plugin is under active maintained.

**Comment by tdido** [comment]
For completeness, see snakemake/snakemake-executor-plugin-slurm/pull/16 for a solution to this. In short, the rule name is included in the "COMMENT" field. You can display this field by using the `--format` argument of `squeue` and providing the `%k` argument.

An example: `squeue --format="%.18i %.9P %.8j %.8k %.8u %.2t %.10M %.6D %.20R %Q"`.

Closing the issue as I assume this solves the problem. Feel free to reopen.
