### ISSUE TITLE
Bug with storage interface: 'Plugin' object has no attribute 'validate_settings'

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#2500]
**Snakemake version**

latest from main branch here, and for the plugin interfaces too.

I'm trying to run / test the storage interface, and I'm getting a bug that 

```
  File "<string>", line 20, in __init__
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/workflow.py", line 187, in __post_init__
    self._storage_registry = StorageRegistry(self)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/storage.py", line 42, in __init__
    self._default_storage_provider = self.register_storage(
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/storage.py", line 77, in register_storage
    plugin.validate_settings(final_settings)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Plugin' object has no attribute 'validate_settings'
```

I tried adding this to my storage plugin, but got the same error, so it must be something in snakemake here. Let me know @johanneskoester what you'd like to do. Thank you!

**Comment by vsoch** [comment]
I can't seem to work on the regular executor anymore either (I also pulled the updated executor base functions). Providing these via command line or environment they aren't registered:

```
$ snakemake --jobs 1 --executor googlebatch --googlebatch-bucket snakemake-cache-dinosaur --googlebatch-region us-central1 --googlebatch-project llnl-flux 
WorkflowError:
The following required arguments are missing for plugin googlebatch: --googlebatch-region, --googlebatch-bucket.
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_interface_common/plugin_registry/plugin.py", line 159, in validate_settings
```
So I think there was something that changed / happened with validate_settings in both places so it is possibly broken?

**Comment by johanneskoester** [comment]
It is here: https://github.com/snakemake/snakemake-interface-common/blob/97a71c76857c8828e30487ece3bf41b52f5ead60/snakemake_interface_common/plugin_registry/plugin.py#L149

And that is already released in snakemake-interface-common 1.14.1. Can you make sure that you use >=1.14.1 in your dev environment?

**Comment by johanneskoester** [comment]
The second error can only occur if validate_settings is actually there, so indeed something seems odd there.

**Comment by johanneskoester** [comment]
Debugging this right now

**Comment by johanneskoester** [comment]
Fix is released as snakemake-interface-common 1.14.2

**Comment by vsoch** [comment]
okay getting closer! I am back to this error where the prefix is incorrectly parsed:

```
$ snakemake --jobs 1 --executor googlebatch --googlebatch-bucket snakemake-cache-dinosaur --googlebatch-region us-central1 --googlebatch-project llnl-flux --default-storage-provider gs --storage-gs-project llnl-flux
/gs:/snakemake-cache-dinosaur/hello-world/hello/world.txt
WorkflowError:
StorageQueryValidationResult: query /gs:/snakemake-cache-dinosaur/hello-world/hello/world.txt is invalid: must start with gs (gs://...)
  File "<string>", line 6, in __init__
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/example/hello-world/Snakefile", line 3, in <module>
```
I saw this bug earlier and reported it, but I can't find it now.

**Comment by vsoch** [comment]
I'm going to artificially say it doesn't need remote storage to get around these errors for now. E.g.,

```
common_settings = CommonSettings(
    pass_envvar_declarations_to_cmd=True,
    non_local_exec=False,
    implies_no_shared_fs=False,
)
```

**Comment by johanneskoester** [comment]
Ok, I will have a look as soon as possible, but I cannot guarantee that I will be able to check this tomorrow.

**Comment by johanneskoester** [comment]
Why don't you test with the minio s3 storage, like in the kubernetes executor though?

**Comment by vsoch** [comment]
> Ok, I will have a look as soon as possible, but I cannot guarantee that I will be able to check this tomorrow.

Thank you! And this doesn't have to even be in the next few days, just sooner than later is better so we don't get stuck.

> Why don't you test with the minio s3 storage, like in the kubernetes executor though?

Developing the Google Storage backend is on the queue for the work we need to do, and given I have complete access to Google Storage I'd like it to be working. Most of the bugs seem to be coming from the various plugin interfaces, and we'd need to figure those out anyway. In terms of s3, I don't have an account I could use with Snakemake.

**Comment by johanneskoester** [comment]
Look at this PR: https://github.com/rse-ops/snakemake-executor-plugin-googlebatch/pull/6

It activates testing with S3. No need for an account, the credentials are public and hardcoded in the test suite class that I inherit from in the PR.

The reason I insist on this is the following: 
1. I want to make sure that executors stay independent of particular storage plugins. Having this tied together is not necessary.
2. It is better to test one thing at a time. If we always test a new storage plugin together with a new executor plugin, it will be much harder to get both running.

**Comment by vsoch** [comment]
That's OK with me, we can likely close this - it's
