### ISSUE TITLE
Help: empty conda env folder

### ISSUE THREAD

**Issue by liangyong1991** [snakemake/snakemake#2512]
Hi everyone, I am new to using Snakemake with the single-cell pipeline, which creates the work environment using the yaml files. And run the `snakemake --use-conda --cores 100 --conda-frontend mamba` and it did ceate an conda env folder in `.snakemake`, but it was empty. Does anyone know what happened here?

```
$tree .snakemake/conda
.snakemake/conda
├── 2302e8a2b24957448bdd9a074a70606c
│   └── env_setup_start
├── 2302e8a2b24957448bdd9a074a70606c.yaml
├── 4138873ee150fa652aa292eb478f8587
│   ├── env_setup_done
│   └── env_setup_start
├── 4138873ee150fa652aa292eb478f8587.yaml
├── af96026330a10a8a6c5149fc72afc917
│   ├── env_setup_done
│   └── env_setup_start
├── af96026330a10a8a6c5149fc72afc917.yaml
├── f692e1767dd3079f910a2a94deffb51d
│   ├── env_setup_done
│   └── env_setup_start
└── f692e1767dd3079f910a2a94deffb51d.yaml

4 directories, 11 files
```

**Comment by kbseah** [comment]
You could delete the empty conda environment folders, and try creating them again with the `--conda-create-envs-only` and `--verbose` options to see the error messages from Conda.

**Comment by liangyong1991** [comment]
> You could delete the empty conda environment folders, and try creating them again with the `--conda-create-envs-only` and `--verbose` options to see the error messages from Conda.

Thank you @kbseah ! I have solved this problem by building the singularity image first instead of using conda.
