### ISSUE TITLE
Wildcards could not read special characters

### ISSUE THREAD

**Issue by RichChang963** [snakemake/snakemake#2513]
**Snakemake version**
7.11.0

**Describe the bug**
In the wildcards execution, if the wildcard naming contains `.` or `_`, the input files could not be read correctly.

I created a simple [testing repository](https://github.com/RichChang963/snakemake_testing/) to express the details in the following section. The wildcards are used in `nodes`, and there are four nodes in this testing example: 
["DEU_131", "FRA.141", "NOR_141", "SWE_21471"]
, and a comparison nodes without any special characters: 
["DEU131", "FRA141", "NOR141", "SWE21471"]

The reading input file of nodes can be controlled in `config.yaml["node_file"]`.

**Minimal example**
In the case of `four_nodes_comparison`, the snake rules worked well. While in the case of `four_nodes` (with special characters), the logs information are listed below:
 
```text
Building DAG of jobs...
MissingInputException in line 49 of `snakemake_testing\Snakefile`:
Missing input files for rule test_all_wildcards:
    affected files:
        results/networks/lcoh_DEU_131.csv
        results/networks/lcoh_NOR_141.csv
        results/networks/lcoh_SWE_21471.csv
```

**Comment by cademirch** [comment]
I couldn't figure out how to run your workflow in the repo you linked, but could this be just because your `wildcard_constraints` does not allow for underscores?

**Comment by RichChang963** [comment]
Hi @cademirch,

I guess I did not notice this constraints earlier. It works well now!

Thanks for helping out!
