### ISSUE TITLE
Issue with the conda install step

### ISSUE THREAD

**Issue by Unaimend** [snakemake/snakemake#2518]
**Snakemake version**
4.0.0

**Describe the bug**
Executing the snakefile is stuck at the conda install step 
`Creating conda environment environment.yaml...
`
Installing the environment with the command 
`mamba env create --file environment.yaml -n test3
` takes mere seconds. 
**Logs**
No logs to report 
**Minimal example**
For a minimal example I provided the environment.yaml and the snakefile down below.
The snakefile was executed like this `snakemake --cores 1 --use-conda
`
**Additional context**
Git hub complained over the yaml file ending so I added .txt to both files 
[environment.yaml.txt](https://github.com/snakemake/snakemake/files/13380147/environment.yaml.txt)
[Snakefile.txt](https://github.com/snakemake/snakemake/files/13380148/Snakefile.txt)
[df_MAGabundances_20210907.txt](https://github.com/snakemake/snakemake/files/13380164/df_MAGabundances_20210907.txt)

**Comment by cademirch** [comment]
Your snakemake version is super out of date... latest is `7.32.4`.  


Using 7.32.4,  I timed the env creation:

Snakemake:
```
❯ /usr/bin/time snakemake --use-conda --conda-create-envs-only -c1

        6.96 real         3.13 user         3.24 sys
```


Mamba:
```
❯ /usr/bin/time mamba env create --file env.yaml -n test3 

      5.65 real         2.30 user         3.00 sys
```

**Comment by Unaimend** [comment]
Wow, weird. Thanks for pointing that out. I just ran `mamba update` again in my snakemake environment and  since nothing got updated I assumed that I have the latest version. That was obviously not true

**Comment by Unaimend** [comment]
Ok, I just freshly installed it and got again version 4.0.0 that IS weird

**Comment by cademirch** [comment]
> Ok, I just freshly installed it and got again version 4.0.0 that IS weird

Strange. Are you following the install instructions in the docs?

**Comment by Unaimend** [comment]
Nope. I just figured out the problem: I ran `mamba install -c bioconda snakemake` instead of `mamba create -c conda-forge -c bioconda -n snakemake snakemake`. Leaving out the conda-forge channel apparently changes a lot.

**Comment by Unaimend** [comment]
Thanks four you help @cademirch
