### ISSUE TITLE
strings get extra whitespaces

### ISSUE THREAD

**Issue by Gutorm** [snakemake/snakemake#2540]
**Snakemake version**
7.32.4
**Describe the bug**
(EDIT: Turns out this could be a python incompability and not a snakemake bug)
Variables get whitespaces before and after them.
This creates all kind of problems since all paths build from config-file variables are invalid.

** Minimal snakemakefie**
foo = "foo"
print (f"foo is '{foo}'")

**Logs**
$ python3 --version
Python 3.12.0
$ snakemake -c1 --version
7.32.4
$ snakemake -c1
 foo is ' foo ' 
Building DAG of jobs...
Nothing to be done (all requested files are present and up to date).
Complete log: .snakemake/log/2023-12-08T175422.428593.snakemake.log

***Here is output form another version of python***
$ python3 --version
Python 3.10.13
$ snakemake -c1 --version
7.32.4
$ snakemake -c1
foo is 'foo'
Building DAG of jobs...
Nothing to be done (all requested files are present and up to date).
Complete log: .snakemake/log/2023-12-08T183128.604350.snakemake.log

**Comment by Gutorm** [comment]
There is no way this is a snakemake bug, but the ticket could be useful if someone encounter this most peculiar behaviour.

**Comment by fvdborre** [comment]
It seems I have the same problem. 

f"{prev_month}{current_year}"

returns  ' Nov 2023 ' instead of 'Nov2023'

Snakemake 7.32.4
Python 3.12.0

**Comment by cbp44** [comment]
This is a known issue with Python 3.12.0 and Snakemake (see issue https://github.com/snakemake/snakemake/issues/2480)

To work around, downgrade to Python 3.11 as described: https://github.com/snakemake/snakemake/issues/2480#issuecomment-1765902814
