### ISSUE TITLE
The project homepage, https://snakemake.github.io/, is empty

### ISSUE THREAD

**Issue by ning-y** [snakemake/snakemake#2548]
**Snakemake version**

https://snakemake.github.io/ as accessed on Thu 21 Dec 2023 03:16:48 AM +08 is empty.

**Describe the bug**

Screenshot of the empty page:

![image](https://github.com/snakemake/snakemake/assets/22320312/940c725a-d3f1-4109-8563-e98138d24211)

**Logs**

None.

**Minimal example**

None.

**Additional context**

Just thought the team would like to know.

**Comment by corneliusroemer** [comment]
Came here to say that, thanks for reporting!

**Comment by johanneskoester** [comment]
You are fast! Check it out again, it is not empty anymore, but has a hopefully pleasant new appearance :-)

**Comment by corneliusroemer** [comment]
works!
<img width="1004" alt="image" src="https://github.com/snakemake/snakemake/assets/25161793/28bb4d68-853e-4b21-a015-54ff8ced12ca">
