### ISSUE TITLE
FastQ_Screen Snakemake Wrapper Error

### ISSUE THREAD

**Issue by StephenRicher** [snakemake/snakemake#255]
Hi,

Currently the FastQ_Screen wrapper defines the prefix after removing only the '.fastq' extension from the input file.

However, as shown below, fastq_screen also looks for other extensions ('.seq', '.txt' and '.fq')

Line 358 of fastq_screen: 
- $outfile =~ s/\.(txt|seq|fastq|fq)$//i;

This means the wrapper will fail for FASTQ files ending in .fq, .txt or .seq as there will be a filename mismatch between the actual fastq_screen output and the anticipated output based on the prefix.

Thanks,
Stephen

**Comment by johanneskoester** [comment]
Thanks! May I ask you to refile this issue on the snakemake-wrappers repository?
