### ISSUE TITLE
`--conda-create-envs-only` causes an `AttributeError`

### ISSUE THREAD

**Issue by jlanga** [snakemake/snakemake#2556]
**Snakemake version**
8.0.1

**Describe the bug**
The `--conda-create-envs-only` causes an `AttributeError`

**Logs**
```
Traceback (most recent call last):
  File "/home/jlanga/.miniconda3/envs/snake8/lib/python3.12/site-packages/snakemake/cli.py", line 1948, in args_to_api
    dag_api.conda_create_envs()
  File "/home/jlanga/.miniconda3/envs/snake8/lib/python3.12/site-packages/snakemake/api.py", line 636, in conda_create_envs
    self.workflow_api._workflow.conda_create_envs()
  File "/home/jlanga/.miniconda3/envs/snake8/lib/python3.12/site-packages/snakemake/workflow.py", line 981, in conda_create_envs
    ignore_incomplete=self.execution_settings.ignore_incomplete,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ignore_incomplete'
```

**Minimal example**

```bash
snakemake --conda-create-envs-only
```

**Additional context**
Happens in Python 3.12 and 3.11. Doesn't happen in Snakemake 7.20.0.
Happens also when using the `snakemake/snakemake-github-action`.

**Comment by mdrago98** [comment]
I was able to replicate the same issue calling the --dags flag on snakemake 8.0.1 python version 3.11. Assuming something happened to the self.execution_settings.ignore_incomplete attribute and will affect all flags referencing this attribute

**Comment by jlanga** [comment]
Fixed for me in 8.1.0

**Comment by gdrolet** [comment]
I have the same error as OP using 8.1.0. 

Reverting back to my old version (7.22), the error is gone.

**Comment by johnne** [comment]
I have the same error on 8.0.0, and 8.1.2.

**Comment by Nicolas-Fernandez** [comment]
Hi dear all,
Same in 8.0.0 to 8.2.0. I need to revert to  7.xxx
Thank for your help, have a nice day,
Best,
Nicolas
