### ISSUE TITLE
Version 8.0 no longer support python 3.10?

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake#2569]
Python 3.10 has been removed in commit (https://github.com/snakemake/snakemake/commit/8da62939e0a62a5ff27dd628f53e275c10fb1457). Does it mean python 3.10 is no longer supported?

**Comment by y9c** [comment]
snakemake dependence and plugins required python >= 3.11. But this plugin can be installed under python 3.10 when compiling from source code.

- https://github.com/snakemake/snakemake-interface-executor-plugins
- https://github.com/snakemake/snakemake-interface-storage-plugins

- https://github.com/snakemake/snakemake-executor-plugin-slurm

**Comment by cmeesters** [comment]
right. The need stems from features not being available in lower versions of Python. When installing current releases of Snakemake and/or the mentioned plugins, conda/mamba will ensure providing the right versions of Python.
