### ISSUE TITLE
Wrong error line numbers reported in version 8.0.1

### ISSUE THREAD

**Issue by yardimcilab** [snakemake/snakemake#2574]
**Snakemake version** 8.0.1

**Describe the bug**
As described in [this issue](https://github.com/snakemake/snakemake/issues/1256), Snakemake reports incorrect line numbers for errors.

**Minimal example**
1. Create the following "Snakefile":
```
rule all:
    input:
        "complete"

rule start:
    output:
        "complete"
    params:
        a = 1    # Edit - this syntax error (the missing comma) is deliberate, generating the erroneous line number in the error message.
        b = 2
    shell:
        "touch complete"
```
2. run snakemake --cores 1

This generates the error:
`SyntaxError in file [path]/Snakefile, line 20:
invalid syntax. Perhaps you forgot a comma? (Snakefile, line 20)`

It is the fact that the error message states "line 20" rather than "line 9" or "line 10" that is the issue I am pointing out.

The file is only 12 lines long and the SyntaxError actually occurs on line 9/10 with the deliberately introduced "forgotten" comma, which is meant to generate the SyntaxError for illustrative purposes.

**Comment by Hocnonsense** [comment]
sure, a comma is required after `a＝1`

In fact, these several lines will be wrapped as something like `workflow.params(a＝1,b＝2)`

**Comment by yardimcilab** [comment]
The syntax error is deliberately introduced to illustrate that snakemake is giving an erroneous line number. The erroneous line number is the bug, not the illustrative syntax error.

**Comment by dariober** [comment]
I confirm the issue has resurfaced and I reopened #1256. It would be good to have a test checking for this bug. If I get a bit of time I'll try to submit a PR with it.

@yardimcilab your link to issue #1256 seems to be broken, can you fix it?

**Comment by dariober** [comment]
I suppose this issue can be closed now with version 8.1.0?

**Comment by y9c** [comment]
This bug still exists in the latest version (8.2.0)

**Comment by dariober** [comment]
@y9c : Version 8.2.0 works fine with the simple test file below from #1256. Can you provide an example reproducing the bug?

---

```
rule all:
    input:
        'done.txt',
        
rule trim_transcripts:
    output:
        done.txt,
    run:
        if 1 = 2:  # Syntax error: It should be 1 == 2
            print('foo')
```

```
snakemake -v
8.2.0

snakemake -p -n -j 1
SyntaxError in file /home/dario/Downloads/Snakefile, line 9:
cannot assign to literal here. Maybe you meant '==' instead of '='? (Snakefile, line 9)
```

**Comment by y9c** [comment]
Hi @dariober 

Could you help me test this example?

```
configfile: "config.yaml"


X = config["unexisting_key"]

print(1)
print(2)
print(3)
```

---

$ snakemake --version
**8.2.1**

$ python --version
**Python 3.12.1**

**Comment by y9c** [comment]
Thank you @dariober

**Comment by alpha-beta-soup** [comment]
I'm getting this error in v8.5.4 with quite a complicated Snakefile including sub-files (i.e. I'm struggling to make a concise reproduction). However it is a really significant bug, it's taking me a really long time to find some really small errors, and `snakemake --lint` exhibits the same issue.
