### ISSUE TITLE
f-strings no longer accepted in shell commands

### ISSUE THREAD

**Issue by tsnorri** [snakemake/snakemake#2586]
**Snakemake version**
8.0.1, also tested the main branch. Snakemake 7.32.4 does not have the bug.

**Describe the bug**
Passing an f-string to the shell command results in an error message similar to the following one:

```
SyntaxError in file /Users/tsnorri/snakemake-bug-test/Snakefile, line 7:
unterminated f-string literal (detected at line 7) (Snakefile, line 7)
```

**Minimal example**
```
rule all:
	shell:	f"echo 'test'"
```

Snakemake 8.0.1 accepts the input if the f-string is changed to a plain one.

**Additional context**
The second example on the page [Snakefiles and Rules](https://snakemake.readthedocs.io/en/v8.0.1/snakefiles/rules.html) in Snakemake’s documentation demonstrates the use of an f-string with the shell command.

**Comment by Hocnonsense** [comment]
yes，it's indeed a bug. For a quick fix, you may change the single quote " to the longer one """
