### ISSUE TITLE
`snakemake.workflow` circular import error

### ISSUE THREAD

**Issue by ebete** [snakemake/snakemake#2596]
**Snakemake version**

v8.1.0

**Describe the bug**

When importing `snakemake.workflow`, I get an error that it cannot be imported due to a likely circular import.

**Logs**

```
Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snakemake.workflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py", line 123, in <module>
    from snakemake import api, sourcecache
  File "$HOME/miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/api.py", line 48, in <module>
    from snakemake.workflow import Workflow
ImportError: cannot import name 'Workflow' from partially initialized module 'snakemake.workflow' (most likely due to a circular import) ($HOME/miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/workflow.py)
```

**Minimal example**

```sh
python -c "import snakemake.workflow"
```

**Additional context**

I'm not directly importing this module myself, but a python script generated in `.snakemake/scripts/tmpXXX.wrapper.py` does and causes the pipeline to crash.

**Comment by Hocnonsense** [comment]
Yes, you may import snakemake.cli prior other modules in snakemake.

**Comment by ebete** [comment]
@Hocnonsense Okay? But that does not address the issue here. Especially considering I have no control on how snakemake generates these wrapper scripts.

**Comment by ebete** [comment]
I finally found the culprit. It was due to an entry in the `config` dict that was not a simple type (e.g., int, bool, str, ...), but instead an instance of a class defined in the pipeline. As `config` get pickled and unpickled when using the `wrapper` directive, it probably caused some interesting problems once `pickle.loads` tried to resolve the classes [here](https://github.com/snakemake/snakemake/blob/v8.2.0/snakemake/script/__init__.py#L455) from the script generated [here](https://github.com/snakemake/snakemake/blob/v8.2.0/snakemake/script/__init__.py#L561-L572).

Anyway, changing the config value to a serializable type resolved the issue.
