### ISSUE TITLE
ImportError from snakemake.executors.flux (no 'sleep' in snakemake_interface_executor_plugins.utils)

### ISSUE THREAD

**Issue by musicinmybrain** [snakemake/snakemake#2598]
**Snakemake version**

`8.1.0`, currently aligned with `main`

**Describe the bug**

Importing `snakemake.executor.flux` fails with an `ImportError` because it attempts to import `sleep` from `snakemake_interface_executor_plugins.utils`, but there is no such name in that module:

https://github.com/snakemake/snakemake-interface-executor-plugins/blob/v8.1.3/snakemake_interface_executor_plugins/utils.py

**Logs**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ben/src/forks/snakemake/snakemake/executors/flux.py", line 13, in <module>
    from snakemake_interface_executor_plugins.utils import sleep
ImportError: cannot import name 'sleep' from 'snakemake_interface_executor_plugins.utils' (/home/ben/src/forks/snakemake/_e/lib64/python3.12/site-packages/snakemake_interface_executor_plugins/utils.py)
```

**Minimal example**

```
python3 -m venv _e
. _e/bin/activate
pip install snakemake
python -c 'import snakemake.executors.flux'
```

**Additional context**

I’m working on updating the [`snakemake` package in Fedora Linux](https://src.fedoraproject.org/rpms/snakemake), which is why I’m validating importability.

**Comment by johanneskoester** [comment]
THanks for reporting! The flux module is actually supposed to be moved into a plugin and has no connection to the rest of the code anymore. @vsoch, how is the status of the flux plugin? Do we have it, is it ready to be released?

**Comment by johanneskoester** [comment]
We can in any case just remove that old code from here now, as it is not functional anyway and should be in the plugin.

**Comment by johanneskoester** [comment]
See PR https://github.com/snakemake/snakemake/pull/2599

**Comment by vsoch** [comment]
Testing is welcome - it is technically the exact code we have here https://github.com/snakemake/snakemake-executor-plugin-flux/

**Comment by vsoch** [comment]
I likely need to do one more test, because it was last updated 3 months ago (and lots of changes have happened for the executor plugin interfaces since then).

**Comment by vsoch** [comment]
Hi @johanneskoester @musicinmybrain!

I can tell you with certainty the plugin needs to be updated. However, I'm not able to work on it soon because of this issue. https://github.com/snakemake/snakemake/issues/2590. There is no easy way I've figured out (spent a lot of time today) to get a working flux alongside that new version of Python, unless I rebuild everything from scratch after the fix in that repo which (imho) is really hard to maintain because I'd need to do it every time. We provide flux base containers with ubuntu jammy and I think that needs to work. The plugin interface with a more reasonable versioned python (jammy has 3.10). 

```
# python3 --version
Python 3.10.12
```

Thanks!

**Comment by vsoch** [comment]
hi @musicinmybrain - I was able to write a Dockerfile that brought a new python 3.12 into the container and built the entirety of flux from source to use it. Because of this complexity I had to disable tests (that rely on being able to quickly install into our fluxrm/flux-sched:jammy base) but I did test in the container and the dummy workflow functioned. Here is the Dockerfile, for your enjoyment (lol):

```dockerfile
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
        libfftw3-dev libfftw3-bin pdsh libfabric-dev libfabric1 \
        dnsutils telnet strace cmake git g++ openmpi-bin \
        openmpi-common wget curl unzip libopenmpi-dev \
        software-properties-common gpg-agent build-essential

RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update && \
    apt install -y python3.12 python3.12-dev

RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python3.12 1 && \
    update-alternatives --install /usr/bin/python python3 /usr/bin/python3.12 1

RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py

RUN pip3 install -U git+https://github.com/snakemake/snakemake-interface-common@main && \
    pip3 install -U git+https://github.com/snakemake/snakemake-interface-executor-plugins && \
    pip3 install -U git+https://github.com/snakemake/snakemake-interface-storage-plugins@main && \
    pip3 install -U git+https://github.com/snakemake/snakemake-storage-plugin-s3@main && \
    pip3 install -U git+https://github.com/snakemake/snakemake-storage-plugin-gcs@main && \
    pip3 install -U git+https://github.com/snakemake/snakemake@main

# This first section from src/test/docker/bionic/Dockerfile in flux-core
# https://github.com/flux-framework/flux-core/blob/master/src/test/docker/bionic/Dockerfile
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        apt-utils && \
    rm -rf /var/lib/apt/lists/*

# Utilities
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        locales \
        ca-certificates \
        curl \
        wget \
        man \
        git \
        flex \
        ssh \
        sudo \
        vim \
        luarocks \
        munge \
        lcov \
        ccache \
        lua5.2 \
        mpich \
        valgrind \
        jq && \
    rm -rf /var/lib/apt/lists/*

# Compilers, autotools
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        build-essential \
        pkg-config \
        autotools-dev \
        libtool \
	libffi-dev \
        autoconf \
        automake \
        make \
        cmake \
        clang \
        clang-tidy \
        gcc \
        g++ && \
    rm -rf /var/lib/apt/lists/*

# Other deps
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        libsodium-dev \
        libzmq3-dev \
        libczmq-dev \
        libjansson-dev \
        libmunge-dev \
        libncursesw5-dev \
        liblua5.2-dev \
        liblz4-dev \
        libsqlite3-dev \
        uuid-dev \
        libhwloc-dev \
        libmpich-dev \
        libs3-dev \
        libevent-dev \
        libarchive-dev \
        libpam-dev && \
    rm -rf /var/lib/apt/lists/*

# Testing utils and libs
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        faketime \
        libfaketime \
        pylint \
        cppcheck \
        enchant-2 \
        aspell \
        aspell-en && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8

# NOTE: luaposix installed by rocks due to Ubuntu bug: #1752082 https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082
RUN luarocks install luaposix


# Install openpmix, prrte
WORKDIR /opt/prrte
RUN git clone https://github.com/openpmix/openpmix.git && \
    git clone https://github.com/openpmix/prrte.git && \
    ls -l && \
    set -x && \
    cd openpmix && \
    git checkout fefaed568f33bf86f28afb6e45237f1ec5e4de93 && \
    ./autogen.pl && \
    PYTHON=/usr/bin/python3 ./configure --prefix=/usr --disable-static && make -j 4 install && \
    ldconfig && \
    cd .. && \
    cd prrte && \
    git checkout 477894f4720d822b15cab56eee7665107832921c && \
    ./autogen.pl && \
    PYTHON=/usr/bin/python3 ./configure --prefix=/usr && make -j 4 install && \
    cd ../.. && \
    rm -rf prrte

ENV LANG=C.UTF-8

# This is from the docker check script (run interactively during a test)
# https://github.com/flux-framework/flux-core/blob/master/src/test/docker/checks/Dockerfile
ARG USER=fluxuser
ARG UID=1000
ARG GID=1000

# Install flux-security by hand for now:
#
WORKDIR /opt
RUN git clone --depth 1 https://github.com/flux-framework/flux-security && \
    cd flux-security && \
    ./autogen.sh && \
    PYTHON=/usr/bin/python3 ./configure --prefix=/usr --sysconfdir=/etc && \
    make && \
    make install && \
    cd .. && \
    rm -rf flux-security

# Add configured user to image with sudo access:
#
RUN set -x && groupadd -g $UID $USER && \
    useradd -g $USER -u $UID -d /home/$USER -m $USER && \
    printf "$USER ALL= NOPASSWD: ALL\\n" >> /etc/sudoers

# Setup MUNGE directories & key
RUN mkdir -p /var/run/munge && \
    dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key && \
    chown -R munge /etc/munge/munge.key /var/run/munge && \
    chmod 600 /etc/munge/munge.key

# Build flux core
RUN python3 -m pip install cffi ply
RUN git clone https://github.com/flux-framework/flux-core && \
    cd flux-core && \
    ./autogen.sh && \
    PYTHON=/usr/bin/python3 PYTHON_PREFIX=PYTHON_EXEC_PREFIX=/usr/lib/python3.12/site-packages ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --with-systemdsystemunitdir=/etc/systemd/system \
        --localstatedir=/var \
        --with-flux-security && \
    make clean && \
    make && \
    sudo make install

# This is from the same src/test/docker/bionic/Dockerfile but in flux-sched
# Flux-sched deps
RUN sudo apt-get update
RUN sudo apt-get -qq install -y --no-install-recommends \
	libboost-graph-dev \
	libboost-system-dev \
	libboost-filesystem-dev \
	libboost-regex-dev \
	libyaml-cpp-dev \
	libedit-dev

ENV LD_LIBRARY_PATH=/opt/conda/lib:$LD_LIBRARY_PATH

# Build Flux Sched	
# https://github.com/flux-framework/flux-sched/blob/master/src/test/docker/docker-run-checks.sh#L152-L158
RUN git clone https://github.com/flux-framework/flux-sched && \
    cd flux-sched && \
    git fetch && \
    ./autogen.sh && \
    PYTHON=/usr/bin/python3 ./configure --prefix=/usr --sysconfdir=/etc \
       --with-systemdsystemunitdir=/etc/systemd/system \
       --localstatedir=/var && \
    make && \
    sudo make install && \
    ldconfig

WORKDIR /home/fluxuser/plugin
COPY . /home/fluxuser/plugin

RUN pip install .
```
I can tell you off the bat that you will have issues running this with most traditional flux installs, because the python bindings compiled to work with flux will need to be where you install snakemake, and likely your center / resource is not going to have Python 3.12. You can either use the testing container / example for now (details in the README here https://github.com/snakemake/snakemake-executor-plugin-flux) or you can try to create a python 3.12 environment, and then install our python bindings to it https://github.com/flux-framework/flux-python (and note you need to match the version of the bindings with the version of flux). Either way - good luck! If you have futher issues please open an issue on the plugin repository - I'll do my best to help but I'm having quite a bit of trouble developing using poetry and this very new python.

**Comment by musicinmybrain** [comment]
> hi @musicinmybrain - I was able to write a Dockerfile that brought a new python 3.12 into the container and built the entirety of flux from source to use it. […]

Thanks for posting all this detail here. I am sure it will be very useful to someone (who knows, maybe to me at some point). I do want to make it clear that my *personal* goal here is to simply update the [`snakemake` package](https://src.fedoraproject.org/rpms/snakemake) in Fedora Linux to version 8.x, and then package as many of the optional plugins as is practical. I probably won’t take that as far as attempting to package https://github.com/flux-framework/ for Fedora, although I might consider a collaboration if there is someone who has a use case for flux there.

**Comment by vsoch** [comment]
We have had requests for rpm packages in the past (so it's not impossible)! If you decide to go that route (or want to try) please open an issue on https://github.com/flux-framework/flux-core and mention you'd like for flux-sched as well.

**Comment by vsoch** [comment]
It looks like #2599 is closed, so I'm going to close the issue here. Let us know if there is anything else we can help with @musicinmybrain!

**Comment by musicinmybrain** [comment]
Thanks! https://github.com/snakemake/snakemake/pull/2599 looks reasonable to me.
