### ISSUE TITLE
Add method to automatically choose an appropriate `RemoteProvider`

### ISSUE THREAD

**Issue by kpj** [snakemake/snakemake#260]
When specifying remote input files, one needs to pay attention to the URL scheme (e.g. `http` vs `ftp`) and select an appropriate `RemoteProvider`.

It would be nice to have a wrapper which automatically chooses the correct provider.
An (incomplete) implementation could look something like this:
```python
from urllib.parse import urlparse

from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider

HTTP = HTTPRemoteProvider()
FTP = FTPRemoteProvider()

def auto_remote(url):
    o = urlparse(url)
    if o.scheme in ('http', 'https'):
        return HTTP.remote(url)
    elif o.scheme == 'ftp':
        return FTP.remote(url)
    else:
        raise RuntimeError(f'Invalid url: "{url}"')
```

At the moment I manually implement this method in my `Snakemake` files.

**Comment by cclienti** [comment]
I agree, the method is very interesting and I think there is a clean way to do this by creating a proxy provider in snakemake.remote.

I looked in the code and each RemoteProvider child class implements an "available_protocol" method that returns a list of protocol prefixes. For instance ['ssh://', "sftp://"] for the SFTP remote provider. I would be easy to use that method for all schemes supported by the proxy provider.

I'm not a snakemake maintainer, but I'm interested in adding such a feature.
