### ISSUE TITLE
Snakemake conda recipe broken due to a pulp dependency update

### ISSUE THREAD

**Issue by axbazin** [snakemake/snakemake#2606]
Hi Snakemake team

**Snakemake version**

Tested with 8.1.1, 8.1.0, 8.0.1, and 7.32.4 and the bug was reproduced.

**Describe the bug**

I installed snakemake following the instructions in the documentation, in a fresh miniconda installation, then installing and using mamba.

An error from pulp is displayed when trying to show the help, or call the snakemake version, instead of whatever would be expected

**Logs**

```
(snake) adelme@adelme-VirtualBox:~$ snakemake                                                                                       

Traceback (most recent call last):                                                                                                  

  File "/home/adelme/dev/miniconda3/envs/snake/lib/python3.12/site-packages/snakemake/cli.py", line 2037, in main                   

    parser, args = parse_args(argv)                                                                                                 

                   ^^^^^^^^^^^^^^^^                                                                                                 

  File "/home/adelme/dev/miniconda3/envs/snake/lib/python3.12/site-packages/snakemake/cli.py", line 1629, in parse_args             

    parser = get_argument_parser()                                                                                                  

             ^^^^^^^^^^^^^^^^^^^^^                                                                                                  

  File "/home/adelme/dev/miniconda3/envs/snake/lib/python3.12/site-packages/snakemake/cli.py", line 770, in get_argument_parser     

    lp_solvers = pulp.list_solvers(onlyAvailable=True)                                                                              

                 ^^^^^^^^^^^^^^^^^                                                                                                  

AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?       
```                                 

**Minimal example**

`snakemake --help`
or
`snakemake --version`

both display said problem.

**Additional context**

I believe that this is linked to a pulp 2.8.0 recipe being available on conda-forge, even though their latest stable release is 2.7.0.
I forced the pulp version as such:

`mamba create -n snake -c bioconda -c conda-forge snakemake pulp=2.7.0`

And in this case the bug did not display, so It looks like this pulp 2.8.0 recipe introduced a breaking change, which "breaks" your conda recipe.

Adelme

**Comment by axbazin** [comment]
Duplicate of #2607, looks like we were synchronized.

**Comment by ebete** [comment]
Just beat me to it :)

Yes the release of pulp 2.8.0 removed previously deprecated API's, including `list_solvers`. Pinning to 2.7.0 will mitigate this for now.

**Comment by axbazin** [comment]
Resolved in https://github.com/snakemake/snakemake/pull/2610.
