### ISSUE TITLE
AttributeError: module 'pulp' has no attribute 'list_solvers'

### ISSUE THREAD

**Issue by ebete** [snakemake/snakemake#2607]
v8.1.1

**Describe the bug**
Running snakemake now throws the error: `AttributeError: module 'pulp' has no attribute 'list_solvers'`.

**Logs**

```
Traceback (most recent call last):
  File "/.../miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/cli.py", line 2037, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/.../miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/cli.py", line 1629, in parse_args
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/.../miniforge/envs/snakemake/lib/python3.11/site-packages/snakemake/cli.py", line 770, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
                 ^^^^^^^^^^^^^^^^^
AttributeError: module 'pulp' has no attribute 'list_solvers'
```

**Minimal example**
Any invocation of `snakemake` when `pulp >=2.8.0` is installed.

**Additional context**
`pulp` published a new release a few hours ago, removing deprecated API's. This includes `pulp.list_solvers`, which was replaced by `pulp.listSolvers`.

**Comment by ebete** [comment]
`pulp.listSolvers` was added in pulp v2.3.1.

**Comment by laudmt** [comment]
https://github.com/coin-or/pulp/commit/e602a40f42f479c08f223517d1ef04631032dcc2

They actually removed in their last version the alias that enabled to use list_solver.

**Comment by corneliusroemer** [comment]
Yep, I just also got that error when running with bioconda installed snakemake 8.1.1

**Comment by corneliusroemer** [comment]
I've opened a bioconda PR to include the constraint <2.8, anyone with bioconda approve rights can approve

**Comment by ferrarimarco** [comment]
> Maybe good to pin dependencies more tightly in general? Removal of this happened at a minor version bump of pulp so would have been hard to prevent in any case :/

I think this is discussed in #1989 :)

**Comment by ebete** [comment]
Resolved in #2610.

**Comment by smilesun** [comment]
it looks like pip install can not find the latest version https://pypi.org/project/snakemake/

the one installed via pip is 7.32.4
@ebete, do you know a way to install #2610 ?

**Comment by ebete** [comment]
@smilesun snakemake 8.1.2 is available on pip, but you'll need python >=3.11 to install it.

**Comment by smilesun** [comment]
@ebete https://github.com/marrlab/DomainLab/actions/runs/7530315974/job/20496412693, 
3.11 seems to have the same problem

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/pull/743/commits/76e0a0fd1b50b375a0cb3fb0d2952f74a5b14b3a

**Comment by ebete** [comment]
@smilesun Yes because the runner is using python 3.10.7:

https://github.com/marrlab/DomainLab/actions/runs/7530315974/job/20496412693#step:3:3

**Comment by hkmztrk** [comment]
also got this error on `python 3.8 `with `snakemake==7.14.0` and ` pulp==2.8.0 `and downgrading `pulp==2.7.0` fixed it for me.

**Comment by DavidAustinNix** [comment]
pip3 install pulp==2.7.0   fixed it for me too.

**Comment by mmcguffi** [comment]
I just hit this on `7.32.4` -- Im not sure if I understand, are there plans to fix this for previous major number releases of snakemake? There are a number of breaking changes in `8.*` that would require a fair bit of labor to allow our pipelines to function properly

**Comment by ebete** [comment]
@mmcguffi I don't think snakemake does backports. But you can add a version pin to your conda environment file.

**Comment by mfouesneau** [comment]
This issue is still existing with fresh pip installation. How do we fix it?

**Comment by stephenshank** [comment]
@mfouesneau  [Downgrading pulp as suggested above](https://github.com/snakemake/snakemake/issues/2607#issuecomment-1948732242) has been working for me.

**Comment by ernstki** [comment]
Hi all, I appreciate the work here. Just want to add that Python 3.8 is [still receiving security updates](https://devguide.python.org/versions/), and may be the newest Python that some folks (like me) can get, _e.g._ in the official repositories for a "Long Term Support" Linux distro.

Indeed, the workaround of `pip install 'pulp<2.8'` _does_ work; however, it's a bit of a letdown to `pip install snakemake` with a still-supported Python version, eager to get started with a new tool, only to have it crash right away.

That said, I _do_ understand the need to move forward and focus meager developer resources on Python releases with a longer service lifetime. Certainly, Python 3.8 isn't long for this world.

**Comment by AngCamp** [comment]
Wanted to add that I to am experiencing this issue and I agree with the above poster it is a bit of a let down.  The fix pip install 'pulp<2.8' works for me  as well.  We are running python 3.9.19 here.  Still would prefer to not have had to spend time googling this.

**Comment by powelleric** [comment]
Just my two cents, here, but I think the definitive solution is to install snakemake with [pipx](https://pipx.pypa.io/stable/).  That is really what pipx is for.  

Everyone in this thread is running the snakemake CLI, not importing the snakemake python modules into their own python code.  So, the whole issue of python versioning is moot; Use pipx to install snakemake using the best available python version and continue to use whatever python version you already use for your own python code.

**Comment by alemanac** [comment]
@powelleric I installed snakemake via pipx and still received the same error. While I could downgrade pulp, has anyone resolved the issue with pipx? Shouldn't pipx resolve the dependency issue via its container isolation when installing snakemake?
