### ISSUE TITLE
parsing fstring with if else on params

### ISSUE THREAD

**Issue by sravel** [snakemake/snakemake#2657]
**Snakemake version 8.4.0**
**Python 3.12.1**

**Describe the bug**
SyntaxError in file Snakefile, line 20:
expected 'else' after 'if' expression (Snakefile, line 20)

**Minimal example**
```
from collections import defaultdict
from pprint import pp
config = defaultdict(defaultdict)

output_dir="."
config['params']['SMARTDENOVO'] = {}
config['params']['SMARTDENOVO']['KMER_SIZE'] = 10
config['params']['SMARTDENOVO']['OPTIONS'] = "zmo"
config['CIRCULAR'] = False

pp(config)
################################ SMARTDENOVO ####################################
rule test:
    threads: 1
    input:
        fastq = "/shared/home/sravel/glp701/sandbox/test_snake8/Data-Xoo-sub/refBAI3.fasta"
    params:
        prefix = "SMART",
        kmersize = f"16 " if f"{config['params']['SMARTDENOVO']['KMER_SIZE']}" == '' else f"{config['params']['SMARTDENOVO']['KMER_SIZE']}",
        out_tmp = f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART.{'zmo' if 'zmo' in config['params']['SMARTDENOVO']['OPTIONS'] else 'dmo'}.cns"
    output:
        fasta = f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/assembly2Circ.fasta" if config['CIRCULAR'] else f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/assembly.fasta"
    shell:
        "smartdenovo.pl -t {threads} -k {params.kmersize} -p  {params.prefix} -c 1 {input.fastq} 1>{params.mak}"
```

**Additional context**
`snakemake --show-failed-logs -p -s Snakefile  --lint`

**Comment by dariober** [comment]
```
f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART.{'zmo' if 'zmo' in config['params']['SMARTDENOVO']['OPTIONS'] else 'dmo'}.cns"
^^^                                                                                                                                        ^^^
```

I suspect this line is not right since everything is contained in double quotes.

**Comment by sravel** [comment]
the code works in a python console but snakemake raises an error:
![image](https://github.com/snakemake/snakemake/assets/11534773/52c63c5b-ff97-44cb-99e7-38eea195b806)

**Comment by sravel** [comment]
I use code reduce to:
```python
from collections import defaultdict
from pprint import pp
config = defaultdict(defaultdict)

output_dir="."
config['params']['SMARTDENOVO'] = {}
config['params']['SMARTDENOVO']['KMER_SIZE'] = 10
config['params']['SMARTDENOVO']['OPTIONS'] = "zmo"
config['CIRCULAR'] = False

model = f'{output_dir}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART{"zmo" if "zmo" in config["params"]["SMARTDENOVO"]["OPTIONS"] else "dmo"}.cns'
print(model)

pp(config)
```
then test with:
```bash
> snakemake --version
8.4.6

> snakemake -s Snakefile --lint
SyntaxError in file /shared/ifbstor1/projects/glp701/sandbox/test_snakemake8/Snakefile, line 11:
expected 'else' after 'if' expression (Snakefile, line 11)

> python --version
Python 3.12.1

> python Snakefile
./ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMARTzmo.cns
defaultdict(<class 'collections.defaultdict'>,
            {'params': defaultdict(None,
                                   {'SMARTDENOVO': {'KMER_SIZE': 10,
                                                    'OPTIONS': 'zmo'}}),
             'CIRCULAR': False})



```

**Comment by sravel** [comment]
> ```
> f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART.{'zmo' if 'zmo' in config['params']['SMARTDENOVO']['OPTIONS'] else 'dmo'}.cns"
> ^^^                                                                                                                                        ^^^
> ```
> 
> I suspect this line is not right since everything is contained in double quotes.

This line work on snakemake version 7.32.x, and also on python terminal

**Comment by dariober** [comment]
@sravel Ok, I see. You may be right that there is a bug there. However, I think the line `f"{output_dir}...` is quite involved and I would replace it with an input function for readability.

**Comment by vincentczhou** [comment]
> > ```
> > f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART.{'zmo' if 'zmo' in config['params']['SMARTDENOVO']['OPTIONS'] else 'dmo'}.cns"
> > ^^^                                                                                                                                        ^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I suspect this line is not right since everything is contained in double quotes.
> 
> This line work on snakemake version 7.32.x, and also on python terminal

Seconding this, I'm able to reproduce the bug on version `8.4.6`.

**Comment by SichongP** [comment]
f string has been [overhauled in Python 3.12](https://realpython.com/python312-f-strings/). There has another bug caused by this change (#2480) and I suspect this may have to do with python 3.12 as well.

Can you downgrade Python to a previous version and try again?

**Comment by sravel** [comment]
this script work on python 3.12
https://github.com/snakemake/snakemake/issues/2657#issuecomment-1931449649

**Comment by sravel** [comment]
![image](https://github.com/snakemake/snakemake/assets/11534773/39fc1e54-7178-464a-8752-87d84a6c3c62)

the code on Snakefile:
```python

string_test = "a line test for fstring"

model = f'/path/file/{"zmo" if "fstring" in string_test else "dmo"}.txt'
print(model)

```

**Comment by sravel** [comment]
I search on snakeamke code and found the probleme is the code evaluate:
The parse_fstring() methode remove space like this: `model = f"/path/file/{'zmo'if'fstring'instring_testelse'dmo'}.txt"`
So fail when you compile code with `exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)`

**Comment by sravel** [comment]
I confirm probleme is parse_fstring() method !!!
I modify like this and working !!!
``` python
    def parse_fstring(self, token: tokenize.TokenInfo):
        # only for python >= 3.12, since then python changed the
        # parsing manner of f-string, see
        # [pep-0701](https://peps.python.org/pep-0701)
        isin_fstring = 1
        t = token.string
        for t1 in self.snakefile:
            if t1.type == tokenize.FSTRING_START:
                isin_fstring += 1
                t += t1.string
            elif t1.type == tokenize.FSTRING_END:
                isin_fstring -= 1
                t += t1.string
            elif t1.type == tokenize.FSTRING_MIDDLE:
                t += t1.string.replace("{", "{{").replace("}", "}}")
            elif t1.type == tokenize.OP and t1.string == "{":
                t += t1.string
            elif t1.type == tokenize.OP and t1.string == "{":
                t += t1.string
            else:
                t += " "+t1.string
            if isin_fstring == 0:
                break
        if hasattr(self, "cmd") and self.cmd[-1][1] == token:
            self.cmd[-1] = t, token
        return t
```

**Comment by sravel** [comment]
according to https://peps.python.org/pep-0701/
we cans used `RBRACE` or `LBRACE` but when I test tokenize haven't this....

**Comment by julieaorjuela** [comment]
Hello!! it could be really cool to correct this problem of parse_fstring() !

**Comment by Hocnonsense** [comment]
> I confirm probleme is parse_fstring() method !!! I modify like this and working !!!
> 
> ```python
>     def parse_fstring(self, token: tokenize.TokenInfo):
>         # only for python >= 3.12, since then python changed the
>         # parsing manner of f-string, see
>         # [pep-0701](https://peps.python.org/pep-0701)
>         isin_fstring = 1
>         t = token.string
>         for t1 in self.snakefile:
>             if t1.type == tokenize.FSTRING_START:
>                 isin_fstring += 1
>                 t += t1.string
>             elif t1.type == tokenize.FSTRING_END:
>                 isin_fstring -= 1
>                 t += t1.string
>             elif t1.type == tokenize.FSTRING_MIDDLE:
>                 t += t1.string.replace("{", "{{").replace("}", "}}")
>             elif t1.type == tokenize.OP and t1.string == "{":
>                 t += t1.string
>             elif t1.type == tokenize.OP and t1.string == "{":
>                 t += t1.string
>             else:
>                 t += " "+t1.string
>             if isin_fstring == 0:
>                 break
>         if hasattr(self, "cmd") and self.cmd[-1][1] == token:
>             self.cmd[-1] = t, token
>         return t
> ```

Great, I think this may solve it in most cases! You can fix the code and pull a request for it.

However, can this line be changed to
```python
    out_tmp=f"{output_dir}{{fastq}}/ASSEMBLERS/SMARTDENOVO/ASSEMBLER/SMART."
    + ("zmo" if "zmo" in config["params"]["SMARTDENOVO"]["OPTIONS"] else "dmo")
    + ".cns",

```
and I think that it is eazier to read and fix bugs
