### ISSUE TITLE
script directive: explicit error message when file is not found

### ISSUE THREAD

**Issue by bdelepine** [snakemake/snakemake#2669]
Hi everyone,

As a new snakemake user (v7.25.0), I had trouble using the `script` directive due to fact that it handles path differently than the `shell` directive. This is clearly explained in the documentation, but I missed the part when its says that "the script path is always relative to the Snakefile **containing** the directive" ([here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#snakefiles-external-scripts)): I believed the path should refer to the main Snakefile and ended up with an error message when I moved my script-containing rules to a "rules/" folder (as in [recommended workflow file hierarchy](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#distribution-and-reproducibility)).
Error message:
```
Error in rule foo:
    jobid: 13
    input: input.txt
    output: output.txt
    log: logs/foo.log (check log file(s) for error details)

Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-00-000000000.snakemake.log
```
Of course, the logs were of no use as the script was not found in the first place.

I think the error message could be improved to explicitly state that the problem is that the script file was not found.
I suggest to add something like "Script was not found at XXX. Is the path relative to the Snakefile containing the script directive?"

HTH, best,

**Comment by cademirch** [comment]
On Snakemake `8.4.0`, it seems the error message is relatively informative?:

Directory structure:
```
.
└── workflow
    ├── Snakefile
    ├── rules
    │   └── test.smk
    └── scripts
        └── test.py
```

Snakefile
```
include: "rules/test.smk"


rule all:
    input:
        "test.txt",

```

rules/test.smk:
```
rule test:
    output:
        "test.txt",
    script:
        "scripts/test.py"
```

Running `snakemake -c 1`:
```
[Fri Feb  2 13:08:20 2024]
localrule test:
    output: test.txt
    jobid: 1
    reason: Missing output files: test.txt; Code has changed since last execution
    resources: tmpdir=/var/folders/3k/ffyrjn4x7px101x_wvrk5q9h0000gn/T

RuleException:
WorkflowError in file /Users/cade/dev/sandbox/snakemake_issue2669/workflow/rules/test.smk, line 5:
Failed to open source file /Users/cade/dev/sandbox/snakemake_issue2669/workflow/rules/scripts/test.py
FileNotFoundError: [Errno 2] No such file or directory: '/Users/cade/dev/sandbox/snakemake_issue2669/workflow/rules/scripts/test.py'
```

**Comment by bdelepine** [comment]
Hi @cademirch,

Thank you for looking into it and taking the time to make a example. I can confirm the error message of v8.4.3 is perfectly clear and would have put me on the right track. I will close the thread as solved.

Best regards,
