### ISSUE TITLE
Cluster Configuration Rule Missing

### ISSUE THREAD

**Issue by komorn** [snakemake/snakemake#2672]
Hi, I was trying to run my pipeline but I am encountering this error:

```
MissingRuleException:
No rule to produce --cluster=sbatch --partition={resources.partition} -n {threads} --mem={params.memory}GB -o {log}.slurm.out -e {log}.slurm.err --time={resources.time} --parsable (if you use input functions make sure that they don't raise unexpected exceptions).
```
The pipeline doesn't start running at all, I run it using this command `snakemake --profile profiles/ "$@"`.
I have never encountered this kind of error before and I also didn't change anything in the configuration file `config.yaml` nor the `Snakefile` used to run the pipeline. This error started occuring on Thursday and when I ran the pipeline on Wednesday everything worked just fine.

**Snakemake version**
I am currently using version 8.4.3 (the newest one), but I also tried it with different older versions: 8.2.3, 8.2.1, 7.32.1, 7.28.1

**config.yaml file**
```
# example profile config.yaml for slurm cluster
# partition names will be different on different clusters

cluster:
  sbatch
    --partition={resources.partition}
    -n {threads}
    --mem={params.memory}GB
    -o {log}.slurm.out 
    -e {log}.slurm.err 
    --time={resources.time}
    --parsable

# specifying resources for jobs which require different resources - trinity_inchworm_chrysalis, trinity_final, rnaspades, align_reads
set-resources:
  - trinity_inchworm_chrysalis:partition="a36_768_long"
  - trinity_inchworm_chrysalis:time="12:00:00"
  - trinity_final:partition="a36_768_long"
  - trinity_final:time="12:00:00"
  - rnaspades:partition="a36_768_long"
  - rnaspades:time="12:00:00"
  - align_reads:partition="a36_192_long"
  - align_reads:time="12:00:00"

default-resources:
  - partition="a36_any" 
  - time="4:00:00"
restart-times: 1
latency-wait: 60
jobs: 5000
rerun-incomplete: True
conda-frontend: "conda"
use-conda: True
```

I define the memory parameters individually for each rule in the Snakefile.

Could you please help me resolve this problem?

Thank you

**Comment by suhartobanerjee** [comment]
I also got the same issue. My current workaround is to downgrade to 7.25.4, now it works.

**Comment by komorn** [comment]
> I also got the same issue. My current workaround is to downgrade to 7.25.4, now it works.
@suhartobanerjee 

If I downgrade to 7.25.4 I get a different error: 
```
Traceback (most recent call last):
  File "/home2/komornikova/mambaforge/envs/Lana/bin/snakemake", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home2/komornikova/mambaforge/envs/Lana/lib/python3.11/site-packages/snakemake/__init__.py", line 2628, in main
    parser = get_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/komornikova/mambaforge/envs/Lana/lib/python3.11/site-packages/snakemake/__init__.py", line 1542, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
                 ^^^^^^^^^^^^^^^^^
AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?
```
😀

**Comment by suhartobanerjee** [comment]
Ohh, not aware of that error unfortunately. 😅

**Comment by komorn** [comment]
> If I downgrade to 7.25.4 I get a different error:
> 
> ```
> Traceback (most recent call last):
>   File "/home2/komornikova/mambaforge/envs/Lana/bin/snakemake", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home2/komornikova/mambaforge/envs/Lana/lib/python3.11/site-packages/snakemake/__init__.py", line 2628, in main
>     parser = get_argument_parser()
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "/home2/komornikova/mambaforge/envs/Lana/lib/python3.11/site-packages/snakemake/__init__.py", line 1542, in get_argument_parser
>     lp_solvers = pulp.list_solvers(onlyAvailable=True)
>                  ^^^^^^^^^^^^^^^^^
> AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?
> ```
> 

I solved this with downgrading pulp to an older version (2.2) if somebody has the same problem.

**Comment by atotickov** [comment]
I have the same problem.

**Comment by aryakaul** [comment]
The `--cluster` option is deprecated. Took me a while to figure out the issue as well, as I don't think the docs reflect the current status of options post v8. What I believe (but not 100% sure) is now the preferred method is to use plugins (i.e. [cluster-generic-plugin](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/cluster-generic.html))

1. `pip install snakemake-executor-plugin-cluster-generic`
2. `snakemake --executor cluster-generic --cluster-generic-submit-cmd sbatch ...`

You can see the changelog for v8 [here](https://snakemake.readthedocs.io/en/stable/getting_started/migration.html).

**Comment by AndHerr** [comment]
Hi,

I love Snakemake, it's awesome! Unfortunately, I'm facing the same issues after reinstalling it:

Using profile slurm_cclake for setting default command line arguments.
Config file config/config.yaml is extended by additional config specified via the command line.
Assuming unrestricted shared filesystem usage.
host: login-q-3
Building DAG of jobs...
MissingRuleException:
No rule to produce --cluster=sbatch $(/home/XXX/Programs/snakemake_config/parseJobID.sh {dependencies}) --job-name={params.job_name} --account=XXX --partition=cclake --time={resources.time_min} --nodes=1 --ntasks={resources.cpus} --mail-type=FAIL --output="./log/{params.job_name}-%j.out" --error="./log/{params.job_name}-%j.err" (if you use input functions make sure that they don't raise unexpected exceptions).

This slum config file has been working without any problem until previously. it's a fresh Snakemake installation (8.20.3, with Mamba). Any hint is more than welcome. 

Many thanks,
Andrés

**Comment by mfouesneau** [comment]
Same here. What is the solution? Or this issue should remain open?

**Comment by quentinblampey** [comment]
Same issue here too, with a fresh `snakemake==8.25.3` install

**Comment by mat10d** [comment]
Also having this issue. Doesn't seem to occur in 7.32.4, but isn't working in 8.25.3.

**Comment by mat10d** [comment]
I am still parsing through the slurm executor [here](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html), but @aryakaul is 100% correct that we need to make those changes. After installing the executor plugin:

`pip install snakemake-executor-plugin-slurm
`

My snakemake call looks generally like this:

`# Set the path to the main Snakefile and the config file
BRIEFLOW_PATH="../"
CONFIG_FILE_PATH="config/config.yml"
PROFILE_FILE_PATH="slurm/"

# Run only the preprocess rules with cluster configuration
snakemake --use-conda --executor slurm \
    --workflow-profile "$PROFILE_FILE_PATH" \
    --snakefile "${BRIEFLOW_PATH}workflow/Snakefile" \
    --configfile "$CONFIG_FILE_PATH" \
    --until all_preprocess`
    
And I have a config.yaml file in the PROFILE_FILE_PATH that looks like this:

`default-resources:
    slurm_partition: 20
    slurm_account: wibrusers
    mem_mb: 6000
jobs: 20
`

My previous setup, in snakemake 7.32.4, looked like this:

`cluster: sbatch -p 20 --parsable --ntasks 1 --cpus-per-task {resources.cpus} --mem {resources.mem_mb}M --output=merge_3/snakemake-output/merge_3-%j.out
default-resources:
  - cpus=3
  - mem_mb=6000
jobs: 100`

I am still working out some of the details of switching between 7->8, because the documentation is a bit confusing, but this may help others.
