### ISSUE TITLE
Update docs 

### ISSUE THREAD

**Issue by cademirch** [snakemake/snakemake#2698]
There have been a number of StackOverflow and Discord posts regarding deprecated options in the docs, particularly cluster execution. Just wanted to start the issue to identify places in the docs that need updating so we can tackle them in a relatively organized way. If you find any, please reply here with a link to docs and what is outdated.

1. [`--cluster` in the tutorial](https://snakemake.readthedocs.io/en/stable/tutorial/additional_features.html#cluster-execution)

**Comment by blaiseli** [comment]
There is a rather not really helpful link in the following section of de documentation:

https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration-not-supported-anymore

If you click on the link regarding profiles, you get there:

https://snakemake.readthedocs.io/en/stable/getting_started/migration.html#profiles

But this section basically says to look at some documentation about profiles, with a link to the section itself (https://snakemake.readthedocs.io/en/stable/getting_started/migration.html#profiles).

**Comment by cmeesters** [comment]
I am currently updating the [docs for the SLURM executor plugin](https://github.com/snakemake/snakemake-executor-plugin-slurm) and want to discuss how to merge the (hopefully updated docs) into the main docs, soon.

**Comment by pdimens** [comment]
The snakemake API is also missing from the 8.X docs

**Comment by blaiseli** [comment]
This section refers to `--cluster`, so likely needs some update: https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#job-properties
