### ISSUE TITLE
laest version can not be installed via conda

### ISSUE THREAD

**Issue by ALFLAG** [snakemake/snakemake#272]
Hi,
I tried to install te latest version 5.10 of snakemake via conda
```conda install -c bioconda snakemake```
but its the version 3.3 which was installed.

**Comment by SichongP** [comment]
Is it possible some other existing packages' dependencies prevent you from installing 5.10?

What happens when you install snakemake in a fresh conda env?

**Comment by ALFLAG** [comment]
In a fresh conda environment, when I run ```conda install -c bioconda snakemake``` it is the version 3 that is installed, with all dependencies.

When I run ```conda install snakemake=5.10``` no package are found, even in the bioconda channel or conda-forge channel.

I upgrade my conda version but it did not change anything.

**Comment by SichongP** [comment]
Can you paste output of `conda search snakemake` and `conda info`?

**Comment by ALFLAG** [comment]
```
conda search snakemake
Loading channels: done
No match found for: snakemake. Search: *snakemake*
PackagesNotFoundError: The following packages are not available from current channels:

  - snakemake

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

```
conda info
     active environment : snakes_last
    active env location : /home/aflageul/miniconda3/envs/snakes_last
            shell level : 1
       user config file : /home/aflageul/.condarc
 populated config files : /home/aflageul/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /home/aflageul/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aflageul/miniconda3/pkgs
                          /home/aflageul/.conda/pkgs
       envs directories : /home/aflageul/miniconda3/envs
                          /home/aflageul/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-17763-Microsoft ubuntu/18.04.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by mbhall88** [comment]
In my experience,  this is normally due to your [channels not being set up correctly](https://bioconda.github.io/user/install.html#set-up-channels).

Could you try running 
```sh
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -n snakemake snakemake
```
and see what snakemake version it installs?

**Comment by ALFLAG** [comment]
Thanks a lot, it worked.

Isn't it strange that when specifiyng the channel via the -c argument of the conda command, it did not worked ?

Again, thank you!

**Comment by johanneskoester** [comment]
Well, you were missing the conda-forge channel in your argument. See the current docs (maybe you have seen some outdated instructions somewhere?):
https://snakemake.readthedocs.io/en/stable/getting_started/installation.html#installation-via-conda
