### ISSUE TITLE
Ability to configure workflow using TOML in addition to currently supported YAML and JSON

### ISSUE THREAD

**Issue by wjs20** [snakemake/snakemake#2769]
**Is your feature request related to a problem? Please describe.**
The TOML configuration format is becoming more popular and for many (including me) it is more readable than yaml. It is a shame snakemake only allows configuration using YAML and JSON. 

**Describe the solution you'd like**
I would like to add TOML as a valid configuration file format for Snakemake, in addition to the currently supported YAML and JSON

**Describe alternatives you've considered**
YAML and JSON are perfectly valid configuration formats already supported. It would just be nice to give people the choice of using one TOML too if they prefer that format.

**Additional context**
I am happy to try to implement this myself. Just wanted to get some feedback as to what the community thought about this addition.

**Comment by nick-ulle** [comment]
Was this feature ever added? I see this issue is marked as completed, but the documentation makes no mention of TOML support.
