### ISSUE TITLE
wrapper-prefix doesn't work with local clone

### ISSUE THREAD

**Issue by ManavalanG** [snakemake/snakemake#277]
**Snakemake version**
Affected - All versions >=5.5.4

**Describe the bug**
Use of `--wrapper-prefix` option with local clone of wrapper repository results in error.

**Logs**
```sh
Error in rule tabix:
    jobid: 1
    output: test.vcf.gz.tbi
    conda-env: /xxx/.snakemake/conda/918d6849

RuleException:
TypeError in line 16 of /xxx/Snakefile:
a bytes-like object is required, not 'str'
  File "/xxx/Snakefile", line 16, in __rule_tabix
  File "//anaconda3/lib/python3.7/tempfile.py", line 481, in func_wrapper
  File "//anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
```

**Minimal example**

```py
rule all:
    input:
        "test.vcf.gz.tbi"

rule tabix:
    input:
        "{prefix}.vcf.gz"
    output:
        "{prefix}.vcf.gz.tbi"
    params:
        "-p vcf"
    wrapper:
        "0.49.0/bio/tabix"
```

Command to run:

```sh
snakemake -p --use-conda --wrapper-prefix git+file://xxx/snakemake-wrappers --verbose
```

**Additional context**
Tested several versions of snakemake, and this bug affects versions >=5.5.4 (including v5.10.0).

**Comment by ManavalanG** [comment]
On the related note, I became interested in using local clone of wrappers, when usage of default wrappers from github resulted in snakemake freezing forever. Snakemake doesn't spit out any error and it doesn't always happen either. As internet connection was reliable, I suspect wrapper retrieval times out at some point, but this exception is not caught. I haven't done any debugging to check if this suspicion is indeed the cause.

**Comment by ManavalanG** [comment]
My pipeline intermittently fails with error `HTTPError: HTTP Error 429: too many requests` when it attempts to connect to snakemake-wrappers. Here is the complete error:

```sh
RuleException:
WorkflowError in line 12 of  /xxx/rules/calling.smk:
HTTPError: HTTP Error 429: too many requests
  File " /xxx/rules/calling.smk", line 12, in __rule_call_variants
  File "/share/Python/3.6.6-foss-2018b/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by ManavalanG** [comment]
My pipeline intermittently fails with error `HTTPError: HTTP Error 429: too many requests` when it attempts to connect to snakemake-wrappers. Here is the complete error:

```sh
Building DAG of jobs...
WorkflowError:
Failed to open environment file https://github.com/snakemake/snakemake-wrappers/raw/0.27.1/bio/gatk/haplotypecaller/environment.yaml:
HTTPError: HTTP Error 429: too many requests
  File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 198, in create
  File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 70, in content
  File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 37, in content
```

**Comment by ManavalanG** [comment]
*Another related error:*
Local wrapper works as expected when used with `file:`. (To be clear, `git+file` still doesn't work). According to [documentation](https://snakemake.readthedocs.io/en/stable/executing/cli.html#BEHAVIOR), local wrapper can be supplied using

` --wrapper-prefix file://path/to/your/local/clone`

This ends with error for me due to wrong filepath. Instead adding a slash in the front as shown in [changelog for v5.2.4](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id73) works as expected. That is, it instead needs to be

` --wrapper-prefix file:///path/to/your/local/clone`

I suppose this is just a documentation error?

*Tested with:*
Snakemake - 5.9.1
Mac OS Mojave 10.14.6

**Comment by odenas** [comment]
this should solve the `git+file` case 

https://github.com/snakemake/snakemake/pull/430

**Comment by johanneskoester** [comment]
> My pipeline intermittently fails with error `HTTPError: HTTP Error 429: too many requests` when it attempts to connect to snakemake-wrappers. Here is the complete error:
> 
> ```shell
> Building DAG of jobs...
> WorkflowError:
> Failed to open environment file https://github.com/snakemake/snakemake-wrappers/raw/0.27.1/bio/gatk/haplotypecaller/environment.yaml:
> HTTPError: HTTP Error 429: too many requests
>   File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 198, in create
>   File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 70, in content
>   File "/share/software/snakemake/5.9.1-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 37, in content
> ```

We could easily put the wrapper retrieval code behind a rate limiter. I just never found documentation on the request limits of github (except for their API, but that is 5000 per hour, which clearly should not be the issue here). Maybe many other users at your institution also have plain http requests to github, and this sums up to hitting that limit...

**Comment by johanneskoester** [comment]
I think what we can do is catching that error, wait a bit and try again.

**Comment by ManavalanG** [comment]
> I think what we can do is catching that error, wait a bit and try again.

Yes, that would be helpful. Better fix, if possible, could be to keep a local cache of the wrappers used instead of downloading it everytime.

**Comment by johanneskoester** [comment]
Yes, and the local caching of wrappers is now implemented as well. Sorry for the late response. Snakemake is currently entering a stabilization phase and I want to ideally tackle all open bugs.
