### ISSUE TITLE
Resources flag giving TypeError

### ISSUE THREAD

**Issue by snunzi** [snakemake/snakemake#278]
I wrote the following rule, called on the command line by ``snakemake  --resources load=2 -n``

I keep getting a Type Error as a result of the resources  ``'Series' object is not callable``

This command used to work on older versions of Snakemake, is this a bug or did I code this wrong?

```
rule map_coverage:
        input:
                forward_paired = "trimmed/{sample}_forward_paired.fq.gz",
                reverse_paired = "trimmed/{sample}_reverse_paired.fq.gz",
                spades_assembly = "spades_assembly/{sample}_scaffolds_500bp.fasta"
        output:
                "spades_assembly/{sample}_assembly_coverage.txt"
        log:"log/bbmap/{sample}.log"
        resources: load=1
        shell:
                "bbmap.sh t=10 in={input.forward_paired} in2={input.reverse_paired} ref={input.spades_assembly} nodisk covstats={output} 2>&1 | tee {log}"
```

**Comment by SichongP** [comment]
Can you post full error message?

**Comment by snunzi** [comment]
``TypeError in line 37 of /home/sonunziata/pipeline_development/HLB_assembly_pipeline/rules/assembly_QC.smk:
'Series' object is not callable
  File "/home/sonunziata/pipeline_development/HLB_assembly_pipeline/Snakefile", line 39, in <module>
  File "/home/sonunziata/pipeline_development/HLB_assembly_pipeline/rules/assembly_QC.smk", line 37, in <module>``

**Comment by SichongP** [comment]
It doesn't seem related to `resources`. Does this error still occur if you run without the flag?

If possible, could you post the rule that caused this error? It should be around line 37 of `assembly_QC.smk` module.

**Comment by snunzi** [comment]
The rule that causes this error is posted above. I know the error is coming from how resources is given in the rule. Every time I add resources to any rule it causes an error, even when I run without the flag. Maybe my syntax is wrong?

**Comment by SichongP** [comment]
I don't think your syntax is wrong.

Can you run with `--verbose` and then post full error message? Also which version of snakemake are you running?

**Comment by troycomi** [comment]
My first thought was that load was silently reserved and used elsewhere in the snakemake code, but this minimal example works:
```
rule all:
    input: expand('test_{id}.txt', id=range(3))

rule map_coverage:
    output: touch('test_{id}.txt')
    resources: load=1
    shell: 'echo {wildcards.id}'
```
My guess is you are defining `load` or another variable using pandas elsewhere (hence the series).
I'm not sure why it only recently appeared if you've made no other changes.
