### ISSUE TITLE
Use profile to send jobs on different partition (slurm cluster)

### ISSUE THREAD

**Issue by KevinMer** [snakemake/snakemake#2783]
Hi,

I tried to find an answer to my question looking at the docs and the issues but I didn't find. I apologize if I missed something.

I'm working with snakemake 7.32.4 on a slurm cluster.
I have a pipeline with some steps working on gpu and some steps which don't need a gpu.
I use a profile file which looks like this :

> use-singularity: true
> singularity-args: '-B /some/path/ --cleanenv'
> singularity-prefix: "sing_path/"
> jobs: 100
> latency-wait: 36000
> keep-going: True
> verbose: True
> rerun-incomplete: True
> printshellcmds: True
> cluster: 'sbatch -t {resources.time} --mem={resources.mem_gb}G -c {threads} -o logs_cluster/${{USER}}_{rule}_{wildcards}.cluster -e logs_cluster/${{USER}}_{rule}_{wildcards}.cluster -p dev'
> default-resources: [cpus=8, mem_gb=50, time='100:00:00']
> resources: [cpus=100, ram=500]

I would like to know, is there a way to specify gpu partition for some rules to the sbatch command ? And keep the partition dev for the others ?

I think I could bypass this issue by launching my pipeline with --until option specifiying a gpu profile and then launch the rest of the pipeline but I was wondering if there is a more "elegant" way to define specific partition for specific rules.

Thanks a lot for your help.

Best regards,

Kevin

**Comment by cademirch** [comment]
You can use the argument `set-resources` to specify certain rules to use a specific partition, covered [here](https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles) in the docs. 

For example in your profile you could have:
```yaml
# ... rest of your profile
default-resources:
  slurm_partition: "normal"

set-resources:
  gpu_rule:
    slurm_partition: "gpu"
```
With this profile, "gpu_rule" will be run on the "gpu" partition, and all other rules will be run on "normal".

**Comment by KevinMer** [comment]
Thanks a lot @cademirch for your help !
Everything is fine now.

Have a nice day,

Kevin
