### ISSUE TITLE
offline snakemake --report

### ISSUE THREAD

**Issue by erblast** [snakemake/snakemake#282]
I am often working in an offline environment and I would still like to generate reports for my snakemake runs. Currently it seems that the reports need to pull css files from a cdn server. 

it would be great if I could simply download the css files and pass the path to the report command. For example like this.

```
snakemake --report docs/report.html -css docs/css
```

**Comment by engenegr** [comment]
Not only CSS. Such a feature is very welcome by me.

https://github.com/snakemake/snakemake/issues/347

**Comment by engenegr** [comment]
Apparently offline reporting could be a very useful feature.

Today issue might be related to Cloudflare problems.

On the step 
```
Downloading resources and rendering HTML.
```

Jinja can't connect to Cloudflare servers to download some scripts and CSS files.

```

Traceback (most recent call last):
  File "/home/ilya/.virtualenvs/snakemake/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ilya/.virtualenvs/snakemake/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/ilya/.virtualenvs/snakemake/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/ilya/.virtualenvs/snakemake/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/ilya/.virtualenvs/snakemake/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1056)
```

**Comment by qifei9** [comment]
I really need the "offline report" feature.

**Comment by markusrehm2** [comment]
Dear all - we also have an offline cluster environment and I am not able to make use of the report generation feature. Please add the option to generate support without downloading additional content.

**Comment by ronaldlehnigk** [comment]
I played a bit with version 7.9, the error appears now when fetching the Snakemake LICENSE.md file. We could also make real good use of this feature if there is a way.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 726, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.8/dist-packages/snakemake/workflow.py", line 920, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/__init__.py", line 859, in auto_report
    packages = data.get_packages()
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/packages.py", line 17, in get_packages
    "snakemake": Package(
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/packages.py", line 75, in __init__
    self.license = get_resource_as_string(license_url)
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/common.py", line 12, in get_resource_as_string
    r = requests.get(path_or_uri)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by johanneskoester** [comment]
Yes, rendering reports offline should be not a problem. We can simply include the required files as assets while building the Snakemake package for pypi. PRs would be very welcome of course, if you want to speed this up.

**Comment by penglbio** [comment]
> I played a bit with version 7.9, the error appears now when fetching the Snakemake LICENSE.md file. We could also make real good use of this feature if there is a way. It would be great if a Snakemake developer could look into this! Thanks so much!
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
>     conn = self._new_conn()
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
>     retries = retries.increment(
>   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 726, in snakemake
>     success = workflow.execute(
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/workflow.py", line 920, in execute
>     auto_report(dag, report, stylesheet=report_stylesheet)
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/report/__init__.py", line 859, in auto_report
>     packages = data.get_packages()
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/packages.py", line 17, in get_packages
>     "snakemake": Package(
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/packages.py", line 75, in __init__
>     self.license = get_resource_as_string(license_url)
>   File "/usr/local/lib/python3.8/dist-packages/snakemake/report/data/common.py", line 12, in get_resource_as_string
>     r = requests.get(path_or_uri)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /snakemake/snakemake/main/LICENSE.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f05236a13d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> ```

Did you solve this problem? If yes, can you tell me the method?

**Comment by johanneskoester** [comment]
We can compile all the online resources into the Snakemake package. It just has to be implemented by somebody. I can do that, but if anybody needs this fast, I suggest to create a PR.

**Comment by penglbio** [comment]
> 

Ok, Thanks.

**Comment by markusrehm2** [comment]
Could one of the developers provide a little guidance what is necessary to integrate the resources to the package and make them available offline? I am not a python developer but I am willing to learn and push this topic. Thank'S in advance.

**Comment by fs82** [comment]
I will give it a try in the next week. Not sure when exactly I will find the time to work on it, but I put it on my table.

**Comment by fs82** [comment]
Ok, I had some time today and gave it a try. Waiting for review and feedback
