### ISSUE TITLE
--cluster-config BsubInvocation Error

### ISSUE THREAD

**Issue by suhridbuddha** [snakemake/snakemake#2828]
I created a cluster.json file to use exclusive nodes on lsf cluster:

```
{
    "__default__": {
        "queue": "normal",
        "nodes": "lz-gpu lf-gpu ln-gpu lx-gpu ly-gpu ll-gpu",
        "extra": "",
        "threads": 4  # Default thread count, can be overridden per rule
    }
}
```

**Snakemake version**
7.32.4

Please only report bugs of the **latest stable release of Snakemake**.
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bsub -M 200 -n 1 -R 'select[mem>200] rusage[mem=200] span[hosts=1]' -W 300 -o "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.out" -e "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.err" -J "patch_segmentation_baysor.index=53" -q normal /lila/data/chanjlab/ryanr2/sopa/workflow/.snakemake/tmp.5z0azw4k/snakejob.patch_segmentation_baysor.55.sh' returned non-zero exit status 255.

raise BsubInvocationError(error)
__main__.BsubInvocationError: Command 'bsub -M 200 -n 1 -R 'select[mem>200] rusage[mem=200] span[hosts=1]' -W 300 -o "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.out" -e "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.err" -J "patch_segmentation_baysor.index=53" -q normal /lila/data/chanjlab/ryanr2/sopa/workflow/.snakemake/tmp.5z0azw4k/snakejob.patch_segmentation_baysor.55.sh' returned non-zero exit status 255.
Error submitting jobscript (exit code 1):

**Describe the bug**
its an error in the lsf_submit. Do I need to change the snakefile as well?

**Comment by cmeesters** [comment]
Should this rather be addressed in the corresponding profiles repo? see https://github.com/Snakemake-Profiles/lsf
