### ISSUE TITLE
Mandatory --cores option in 5.11

### ISSUE THREAD

**Issue by tsibley** [snakemake/snakemake#283]
**Snakemake version**
5.11.

**Describe the bug**
Running `snakemake` version 5.11.0 and higher on an existing workflow fails immediately with:

    Error: you need to specify the maximum number of CPU cores to be used at the same time with --cores.

With version 5.10.0 and lower, running `snakemake` works fine. 

The [changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html) indicates that `--cores` was intentionally made a required option. This choice immediately breaks countless usages of Snakemake and does so in a minor version bump from 5.10 to 5.11 which many people would consider to generally be a "safe" upgrade.

**Logs**
See above.

**Minimal example**
```sh
mkdir /tmp/regression
cd /tmp/regression
echo 'print("hello")' > Snakefile
snakemake
```

**Comment by johanneskoester** [comment]
I am sorry for letting this happen in a minor release. So far, I only considered language changes worth a major upgrade. But I agree that this policy should also be applied for the CLI in the future. Again, sorry for that. Still, the change is very important, in particular for the thousands of beginners that raised questions asking why their workflow does not run in parallel.

**Comment by HDembinski** [comment]
I also stumbled over this, as will countless others.

Here is a compromise: make cores=all the default. This anyway what you usually want. The desire to limit the number of cores is one step further. This is how ninja does it.

**Comment by mbhall88** [comment]
I am also a little unhappy with `--cores` now being mandatory. What was the reasoning behind this decision @johanneskoester ?   

I know you already addressed this, but this should have been a major version bump. It might be a good idea to bump the major version now and specify in the docs that `snakemake<5.11` is the best option for those who want backwards compatibility?

However, I disagree with @HDembinski 's statement in #308 
> The default for --cores should be "all", like in ninja.

I feel that the default should be 1 for *any* program. Programs which silently steal all threads have caused myself and other users many problems in the past. If I want more than one thread I should have to ask for it.

**Comment by frankier** [comment]
https://en.wikipedia.org/wiki/Convention_over_configuration

**Comment by johanneskoester** [comment]
@frankier: one could also cite Pythons "explicit is better than implicit" here. The amount of paralelism is something one can easily expect people to think about before running a workflow. This is preferable over requiring people to know how Snakemake would behave by default.

**Comment by tedtoal** [comment]
There is no way to get back the old behavior.  I use an executable pipeline file to invoke snakemake using #! /.../snakemake -s in the first line.  I have users who know how to run it as it was, I don't want to retrain them to include -j 1 when they don't want to use the -j option.  I want it to default to -j 1 if not specified, which is what it used to do.  Is there any way to make it do that?  How about adding --cores_default option.  If not specified, user must include -j.  If specified, it is the default -j value if -j is not specified.  Then I can do #! /.../snakemake --cores_default 1 -s in the first line.

**Comment by marco-brandizi** [comment]
Hi all. I'm not getting if this is still considered a bug or a new way to work and, in the former case, if it was fixed (I'm using the 5.24.0).

**Comment by mbhall88** [comment]
> Hi all. I'm not getting if this is still considered a bug or a new way to work and, in the former case, if it was fixed (I'm using the 5.24.0).

It was never a bug. It is an API change.

**Comment by marco-brandizi** [comment]
Thanks, @mbhall88, I was hoping a default was eventually decided, I'll have to introduce it in my environment with something like `alias snakemake='snakemake --cores all'`.

**Comment by tedtoal** [comment]
Here is the solution I came up with.  I have the following file (choose your filename) in a PATH directory set to +x, so the user can execute this file instead of snakemake, using exactly the same arguments:

```
#!/bin/bash

# Absolute path to snakemake binary to use.
SNAKEMAKE=/share/carvajal-archive/PACKAGES/local/miniconda/miniconda3_perl/envs/snakemake/bin/snakemake

# Run snakemake.  Arguments are:
#   1. -j1
#           Snakemake now REQUIRES the -j argument.  We supply -j1, user is
#           free to add an additional -j argument that will override it since the
#           last occurrence is the one finally used.
#   2. $@
#           The arguments specified by the user following "./<this file>"

$SNAKEMAKE -j1 $@
```

**Comment by KasperThystrup** [comment]
How about defaulting to 1 (better safe than sorry), and then print a warning at the beginning of each execution? (Setting `--cores 1` manually should of course not print a warning)

**Comment by smac89** [comment]
I get that this option is now mandatory, but why can't we set a default for it even in the configfile?

Snakefile:
```
configfile: "config.yml"

print ("Hello")
```

config.yml
```
cores: 1
```
Even with the above, `snakemake` still asks for the cores option to be set. Why?
