### ISSUE TITLE
shell command cannot use python keywords

### ISSUE THREAD

**Issue by goi42** [snakemake/snakemake#287]
**Snakemake version**
5.11.2

**Describe the bug**
The shell command does not have access to rule keywords (e.g., `input`, `output`, etc.) as python variables.

**Logs**
```bash
NameError in line 6 of </path/to/directory/>Snakefile:
name 'output' is not defined
  File "</path/to/directory/>Snakefile", line 6, in <module>
```

**Minimal example**
The `output` variable is available to the `run` command, but not to the `shell` command.
This Snakefile works without problems:
```python
rule all:
     input: ['hi_out.txt']

rule create_file:
     output: '{somename}_out.txt'
     run:
         with open(str(output), 'w') as ff:
             pass
```
whereas this one fails with the error given above:
```python
rule all:
     input: ['hi_out.txt']

rule create_file:
     output: '{somename}_out.txt'
     shell: f'touch {output}'
```

**Comment by SultanOrazbayev** [comment]
This is not a bug. If you remove `f` from your script, then it will run without problems. The issue is that f-string would be evaluated at the time of processing the snakefile (as opposed to at the time of processing the rule commands).

```
rule all:
     input: ['hi_out.txt']

rule create_file:
     output: '{somename}_out.txt'
     shell: 'touch {output}'
```

**Comment by goi42** [comment]
Thanks for the clarification @SultanOrazbayev, but the simple reproducer above is not a true use-case. Suppose I want to change the shell command based on the output string:
```python
rule all:
     input: ['hi_out.txt']


def thing_to_print(nm):
    if 'hi' in nm:
        return 'hello'
    else:
        return 'there'


rule create_file:
     output: '{somename}_out.txt'
     shell: f'echo {thing_to_print(output)} && touch {{output}}'
```

**Comment by SultanOrazbayev** [comment]
Two ways to achieve what you are after:

1. Put the conditional in you shell command (the code I wrote shows that shell correctly shows `output`, so a conditional can be used inside the shell script instructions.
2. Anonymous rules (see https://bitbucket.org/snakemake/snakemake/issues/976/how-to-use-anonymous-rules-or-how-to-avoid).

**Comment by goi42** [comment]
Thanks for the clarification. Sorry to have brought this up as a bug rather than on the forums. I have made a [PR](https://github.com/snakemake/snakemake/pull/288) to clarify this in the docs.

**Comment by SultanOrazbayev** [comment]
Maybe this is something that will help, but you can also use `params: lambda wildcards: thing_to_print(wildcards. somename)` as part of your rule definition, which can be accessed with `{params}` in shell script.

**Comment by goi42** [comment]
Ah that’s a good idea! Thanks.
