### ISSUE TITLE
Runnning multiple instance of workflow on slurm causes  Denial-of-Service

### ISSUE THREAD

**Issue by shashwatsahay** [snakemake/snakemake#2899]
**Snakemake version**
7.32.4

Running multiple instance of snakemake on slurm using --slurm hangs the workflow for hours with no respite

I have to run a workflow on 1000 samples individually runnnig it with slurm causes ddos on the slurm controller is there a workaround for this

**Comment by johanneskoester** [comment]
You can restrict the number of jobs in the queue via --jobs. The number depends on what your cluster is capable to handle. Also consider using Snakemake >=8, where the cli changes slightly.
