### ISSUE TITLE
Invalid choice: 'slurm-jobstep' (choose from 'local', 'd ryrun', 'touch')

### ISSUE THREAD

**Issue by radaniba** [snakemake/snakemake#2905]
**Snakemake version**
8.12.0

**Describe the bug**
Hello everyone
I am trying to execute a Snakemake pipeline on a slurm cluster but I get this error
"error: argument --executor/-e: invalid choice: 'slurm-jobstep' (choose from 'local', 'dryrun', 'touch')"
I am using the latest version of snakemake and also using an older version (unfortunately cannot upgrade) of slurm (~19)
Locally everything seems to work Ok but when I use executer slurm in my profile this error occur in all my log files (the jobs I mean)
Any idea ?
Is Snakemake 8.12 supporting slurm by default ? I  installed snakemake-executor-plugin-slurm-jobstep  and this is the only way snakemake can see my cluster but yet it crashes when I specify the executor slurm 

**Logs**
"error: argument --executor/-e: invalid choice: 'slurm-jobstep' (choose from 'local', 'dryrun', 'touch')"

**Comment by cademirch** [comment]
You need to use `--executor slurm` after installing `snakemake-executor-plugin-slurm`. Read more in the docs: https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html
