### ISSUE TITLE
Snakemake check output before the end of jobs

### ISSUE THREAD

**Issue by Martoyl** [snakemake/snakemake#2916]
**Snakemake version**
snakemake v8.13.0
slurm executor v0.6.0

**Describe the bug**
I migrate recently from an sge cluster to a slurm cluster and I try to adapt my snakemakes to work on it. 
I think I manage it to work using snakemake 8.13 and the slurm executo 0.6 but only if I use the immediate-submit option. If I do not use --immediate-submit option, my snakemake sends the first jobs to the cluster and keeps running  without sending any other jobs even if the first ones are finiched (and successful).
When using the immediate-submit option, after all jobs are send to the cluster, snakemake checks for output direclty (even if I increase the wait-latency option).
On the sge cluster, I used to run my command from nodes using qlogin. From the slurm cluster, I launch snakemake using srun.

**Logs**
Here's my logs (I remove the file path and the command line)
```
Using profile profile/ for setting default command line arguments.
Building DAG of jobs...
SLURM run ID: 7ccd55d8-7cfe-4c1b-9830-d29ff86c16eb
Using shell: /bin/bash
Provided remote nodes: 167
Conda environments: ignored
Job stats:
job            count
-----------  -------
Fastqc_trim        2
total              2

Select jobs to execute...
Execute 2 jobs...

[Fri Jun 14 08:53:13 2024]
rule Fastqc_trim:
    input: xx
    output: xx
    log: xx
    jobid: 858
    reason: Missing output files: xx, xx
    wildcards: sample=IMO_018
    resources: mem_mb=1000, mem_mib=954, disk_mb=9571, disk_mib=9128, tmpdir=<TBD>, slurm_extra='--qos=short', slurm_account=cr2ti, slurm_partition=standard, runtime=60


		fastqc 
		fastqc 
		
Job 858 has been submitted with SLURM jobid nautilus (log: xx).

[Fri Jun 14 08:53:14 2024]
rule Fastqc_trim:
    input: xx
    output: xx
    log: xx
    jobid: 917
    reason: Missing output files: xx, xx
    wildcards: sample=IMO_083
    resources: mem_mb=1000, mem_mib=954, disk_mb=12566, disk_mib=11984, tmpdir=<TBD>, slurm_extra='--qos=short', slurm_account=cr2ti, slurm_partition=standard, runtime=60


		fastqc 
		fastqc 
		
Job 917 has been submitted with SLURM jobid nautilus (log: xx).
Waiting at most 200 seconds for missing files.
MissingOutputException in rule Fastqc_trim in file totRNA_Preprocess.smk, line 50:
Job 858  completed successfully, but some output files are missing. Missing files after 200 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
```

In the job log file:
```
Waiting at most 200 seconds for missing files.
MissingOutputException in rule Fastqc_trim in file totRNA_Preprocess.smk, line 50:
Job 0 completed successfully, but some output files are missing. Missing files after 200 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:

[...]
Removing output files of failed job Fastqc_trim since they might be corrupted:
"outputfile"
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Storing output in storage.
WorkflowError:
At least one job did not complete successfully.

[...]
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Storing output in storage.
WorkflowError:
At least one job did not complete successfully.
```

**Minimal example**
my profile file
```
---
snakefile: Snakefile
latency-wait: 200
show-failed-logs: True
printshellcmds: True
rerun-incomplete: True
keep-going: True

until: Fastqc_trim



immediate-submit: True
notemp: True
jobs: 167

executor: slurm


default-resources:
    - slurm_extra="'--qos=short'"
    - slurm_account="xxx"
    - slurm_partition="standard"
    - mem_mb=1000
    - runtime="1h"
```
I run snakemake like this:
`srun --job-name=P03_Snakemake --qos=long --clusters=nautilus --time=24:00:00 --output=logs_gen/%x_%j.o.txt --error=logs_gen/%x_%j.e.txt snakemake --profile profile/  `

**Additional context**

**Comment by cmeesters** [comment]
The idea is not to run Snakemake in a job context in the first place. It leads to all sorts of unexpected behaviour. You can trigger your workflow on a login or head node and monitor the progress. All rules are submitted according to your profile - except local rules, of course. Does this "bug" disappear, if you let Snakemake submit jobs without being in a job?

**Comment by Martoyl** [comment]
Ok ! I tried lauching snakemake from the login node and it worked well. 
I'm not just a big fan of launching snakemake via the login node but if it works.
Big thanks

**Comment by cmeesters** [comment]
> I'm not just a big fan of launching snakemake via the login node but if it works.

Thing is, that SLURM jobs inherit environments. If a SLURM job submits another job, this potentially leads to conflicts (which may be different from cluster to cluster). Suprressing the inheritance would lead to a situation where we cannot guarantee for Snakemake to find its basic environment.

Only if running on a login node you can immediately see if something goes wrong. Otherwise your development and debugging cycle is longer considerably obfuscated.

Anyway, I hope you understand the design decision and am glad it now works for you.
