### ISSUE TITLE
Issue with unlocking directory

### ISSUE THREAD

**Issue by n318162971** [snakemake/snakemake#2919]
**Snakemake version** 6.3.0

**Describe the bug**

Snakemake is called by `spacemake run` (link: https://spacemake.readthedocs.io/en/latest/index.html). 
Upon attempting to run I get the error message:

> Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory: `my_dir`
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

Therefore I run `snakemake --unlock` as suggested, which yields:

> Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.

And the alleged directory lock remains as it is. What could cause this lock?

**Comment by cmeesters** [comment]
Hi,

Apparently, you are using a wrapper around Snakemake - and an outdated version of Snakemake. Please update and try again. If it fails, you might want to address the developers of your wrapper?

**Comment by hsggdj** [comment]
Hi,

I am running `spacemake run` and encountered the same issue. I got the lock from a loss of connection of my laptop to the remote server I am running the command on. 

I couldn't resolve the issue with the `--unlock` argument after many tries. So I went on deleting the `.snakemake` directory. But I don't think this is the ideal way of solving such issues. Would love to see other solutions.

**Comment by cmeesters** [comment]
Which version of Snakemake are you using? Run `snakemake --version`. Snakemake version v6.x is gone for years.

If it is a current version of Snakemake - what is the error you receive with `--unlock`? Are you running Snakemake on the remote server? Or is the server file system mounted on your machine?

**Comment by hsggdj** [comment]
Spacemake has the following dependencies `snakemake>=5.32.0,<6.4.0`. I agree that the version of snakemake might be the cause to the issues here. I will try contacting the developer for Spacemake for this. 

Thank you!

**Comment by cmeesters** [comment]
Alright. If the such issues come up again, please report relevant meta information (everything which might help to pinpoint the assumed bug).
