### ISSUE TITLE
onstart handler documentation

### ISSUE THREAD

**Issue by cefect** [snakemake/snakemake#2923]
The only information I can find on this feature is:

> Snakemake 3.6.0 adds an onstart handler, that will be executed before the workflow starts. Note that dry-runs do not trigger any of the handlers.

Is this meant to be included in rules as a directive? or a special function name at the head of the snakefile? Seems like a cool feature, but difficult to use without some more information or an example. Or maybe I'm missing something...

**Comment by pdimens** [comment]
Pretend it's a rule:
```python
#### START OF SNAKEFILE####
foo = config["inputs"]

onstart:
  thismany = len(foo)
  print(f"Starting now and theres a total of {thismany} files")

rule do_stuff:
  input: xxxx
  output: yyyy
..... 

```

**Comment by cefect** [comment]
Awww.. this makes sense. Thank you for the tip.
