### ISSUE TITLE
wildcards from `patterns=` expression in `report( directory() )` empty in rendered report caption

### ISSUE THREAD

**Issue by dlaehnemann** [snakemake/snakemake#299]
**Snakemake version**
`5.13.0`

**Describe the bug**
The [docs on including directories in reports](https://github.com/snakemake/snakemake/blob/master/docs/snakefiles/reporting.rst) state, that all wildcards used in a `patterns=[{wildcard1}.{wildcard2}.txt]` expression should be available as `{{ snakemake.wildcards.wildcard1 }}` etc. when parsing the respective `caption=report/caption.rst` file. However, when generating a report, the respective spot is just left empty, with no text replacing the jinja template.

**Logs** / **Minimal example**
For example try the following snakemake workflow with the testing data in its `.test`-subfolder, and see that the caption of output of `rule plot_bootstrap`  uses `{{ snakemake.wildcards.transcript }}`:
https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth/pull/21

When the report is generated, what should be in wildcards.transcript is not substituted in...

**Additional context**

**Comment by johanneskoester** [comment]
Fixed in master. Thanks!
