### ISSUE TITLE
Keep-incomplete for a single rule

### ISSUE THREAD

**Issue by willboulton** [snakemake/snakemake#3011]
I have a relatively large workflow which occasionally fails on certain steps. In particular I have an assembly step which sometimes doesn't run to completion - but I can tack --continue onto my command and try again, if I am using --keep-incomplete. 
But my other rules typically don't like to clobber existing files, so for those I am happy with snakemake's default behaviour of cleaning up outputs if the rule appears to go wrong. 

I'd like to be able to run --keep-incomplete just for a set of rules - preferably putting that into my config file. Is this possible?

Sorry if this is already acheiveable but I am just too dumb to find it. From the CLI documentation it didn't seem like --keep-incomplete comes with any option to list rules.

**Comment by Hocnonsense** [comment]
There are some tricks that may help you.
For example, you can manually handle a cache:
```snakemake
rule hard_job:
    output:
        "{somewhere}/{hard_job}.out"
    params:
        "{somewhere}/{hard_job}-tempdir"
    run:
        if not Path(params).is_dir():
            shell("mkdir {params}")
            shell("commond -o {params}/out")
        else:
            shell("command -o {params}/out --continue")
        shell("mv {params}/out {output}")
        if you_like:
            shell("rm {params}")
        """
```

**Comment by willboulton** [comment]
Thanks! I'll try this
