### ISSUE TITLE
conditionnal rules depending of output file content

### ISSUE THREAD

**Issue by ALFLAG** [snakemake/snakemake#302]
Hi,

Here the problem I'm facing.
one rule is outputing a file in which the content can take two alternative value strings:
    "output_A"    or    "output_B"

depending on the result "output_A" or "output_B" the next rules would be different
How can I do such a thing ?

The first thing I tried to do is writing a rule that check the content of the file, and then set a flag that could be use to run conditionnal rules.
I tried something like that: (the output file here is a decoy file to force the succession of the next rule)
```
rule check_content:
    input:
        "input_file"
    output:
        "decoy"
    run:
        import os
        with open(input[0], "r") as filin: lines = filin.readlines()
        if lines[0] == "output_A": next = "A"
        else: next = "B"
        shell("touch output[0]")

if next == "A"
    rule A ...
elif next == "B"
    rule B....
```
the problem is I can't have access to the variable next that is set in the check_content rule. Any Idea ?
The other way I think to do it is by generating alternative output files depending on the content of the input files, something like this:

```
rule check_content:
    input:
        "input_file"
    output:
        alternative("output1"),
        alternative("output2")
    run:
        import os
        with open(input[0], "r") as filin: lines = filin.readlines()
        if lines[0] == "output_A": shell("touch output[0]")
        else: shell("touch output[1]")
```
and then launching conditionnal rule dépending on the output file that were produced.
Any idea how to do that ?

**Comment by SichongP** [comment]
Check out `checkpoint` directive [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html)

**Comment by ALFLAG** [comment]
That's excellent, it works perfectly.
Thank you!

Alex
