### ISSUE TITLE
Ability to choose cluster or shell execution per rule

### ISSUE THREAD

**Issue by gracilis** [snakemake/snakemake#309]
In the cluster I use, certain commands (e.g. wget) are enabled only on the login node. In snakemake, you can choose to have jobs submitted to the cluster with the --cluster command, but whatever your choice is, it applies to all jobs that are submitted by that snakemake command.

 I would like the ability to choose how jobs are submitted on a rule-by-rule basis, so that some rules can be run on the login shell, and others can be submitted to the cluster.

**Comment by SichongP** [comment]
Can you use `localrules`?

**Comment by gracilis** [comment]
Yes, I think that will work! Thank you.

Grace Hansen
*she/her/hers*
MD/PhD Candidate | University of Chicago
gthansen@uchicago.edu

**Comment by tbooth** [comment]
I believe this means the issue can be closed, so I'll close it.

Note that you can have multiple `localrules:` declarations, so for clarity you can put `localrules: foo` right next to your `foo` rule you don't have to list all the local rules together in one place.

I've done a similar thing to this where the files to transfer were large and I found it useful to use resources to limit the number of `wget` instances to only one at a time, and also I made that rule high priority so if there was some file to be fetched then Snakemake would always start fetching it right away.

**Comment by gracilis** [comment]
I used localrules and it worked perfectly--thanks to you all for
anticipating our needs :) Thanks for the other tips,

      Grace.


Grace Hansen
*she/her/hers*
MD/PhD Candidate | University of Chicago
gthansen@uchicago.edu
