### ISSUE TITLE
Snakemake stops if job fails also with --keep-going=true

### ISSUE THREAD

**Issue by castaway1990** [snakemake/snakemake#328]
Hi,
I'm currently running WES pipeline using snakemake. And I found snakemake stops everything after detecting an error in independent rules , which should be prevented by "--keep-going=true" 
If I re-launch the workflow with very same run command it goes ahed until end/another unrelated job fail.

Snakemake version: 5.5.2

run command:
`snakemake 
--use-singularity --singularity-args '-B /WesTestIV/'
--cluster-config /WesTestIV/config.json 
--cluster '{cluster.cluster} select=1:ncpus={cluster.ncpus}:mem={cluster.mem} 
-l walltime={cluster.time} -N {cluster.jobname} -o ./clusterLogs/ -e ./clusterLogs/' -j 15 
--latency-wait 60 
-s /WesTestIV/Snakefile 
--keep-going=true 
--config $configs
`

out message:
.  
.
.
Error executing rule MANTA on cluster (jobid: 47, external: 251305.hpcfe01, jobscript: /WesTestIV/.snakemake/tmp.fr3d51s1/snakejob.MANTA.47.sh). For detailed error see the cluster log.  
[Wed Apr 15 19:23:06 2020]  
Finished job 72.
61 of 129 steps (47%) done  
[Wed Apr 15 19:30:46 2020]  
Finished job 121.  
62 of 129 steps (48%) done  
[Wed Apr 15 19:32:27 2020]  
Finished job 92.  
63 of 129 steps (49%) done  
[Wed Apr 15 19:43:07 2020]  
Finished job 25.  
64 of 129 steps (50%) done  
[Wed Apr 15 19:54:48 2020]  
Finished job 40.  
65 of 129 steps (50%) done  
[Wed Apr 15 20:11:29 2020]  
Finished job 89.  
66 of 129 steps (51%) done  
[Wed Apr 15 21:47:15 2020]  
Finished job 15.  
67 of 129 steps (52%) done  
[Wed Apr 15 22:12:57 2020]  
Finished job 17.  
68 of 129 steps (53%) done  
[Wed Apr 15 23:03:30 2020]  
Finished job 16.  
69 of 129 steps (53%) done  
Shutting down, this might take some time.  
Exiting because a job execution failed. Look above for error message  
Complete log: /WesTestIV/.snakemake/log/2020-04-15T072906.120131.snakemake.log  

Maybe just wrong --keep-going synthax?
Thanks for the attention.

attached here my graph.txt and dag.pdf
[dag.pdf](https://github.com/snakemake/snakemake/files/4485187/dag.pdf)
[graph.txt](https://github.com/snakemake/snakemake/files/4485190/graph.txt)

**Comment by chrarnold** [comment]
Just --keep-going is sufficient, maybe your =true messes it up. All binary switches don't need a boolean value after as a general rule

**Comment by castaway1990** [comment]
Ok, i'm going to try it thanks!

**Comment by tbooth** [comment]
If I try to run `$ snakemake --keep-going=true` I get an immediate error from argparse:

```
snakemake: error: argument --keep-going/-k: ignored explicit argument 'true'
```

So the command quoted by @castaway1990 shouldn't even run, as far as I can see. Unless this is a bug in ArgumentParser in an older version of the Python library.

@castaway1990 did you fix your issue? I'm wondering if we can close this bug report or if it needs further investigation. Cheers.

**Comment by castaway1990** [comment]
Sorry for late answer, Indeed I am not receiving any argument error. And after some try the pipeline is running till the end with just --keep-going flag if independent rules fails, so the issue can be closed for me. 

Thank you very much!
