### ISSUE TITLE
A formatter such as black

### ISSUE THREAD

**Issue by Emiller88** [snakemake/snakemake#36]
Coming from a word where there's a linter and formatter for everything, and then there's not one for Snakemake

Integration into black or another formatter for Snakemake files.

We could just suffer through, but I noticed that you forked black, so there may be work going on already for this.

**Comment by johanneskoester** [comment]
Yes, I forked black for exactly this. Unfortunately, everything is quite deeply integrated, so it is not just writing a module or so. I have currently not the time to do this. However, if anybody would like to give it a try, that person would be the next big Snakemake hero!

**Comment by johanneskoester** [comment]
And of course she or he would be co-author of the next Snakemake paper that we will hopefully soon start drafting ;-).

**Comment by SultanOrazbayev** [comment]
@Emiller88 : co-authorship sounds very good, so even though I don't use linters I would like to give this enhancement a try. Kindly let me know if you plan pursuing and/or would like to split some work.

**Comment by Emiller88** [comment]
This all sounds good. To clarify I'm interested in a formatter more so than a linter. I think `snakemake` itself does a good job of giving errors.

@johanneskoester If you have any more info on the issues you ran into with black I would appreciate it before I go down the same deadends.

We might be better off making the fork of black, or starting from scratch on a seperate formatter, rather than trying to get it integrated upstream.

**Comment by endrebak** [comment]
@johanneskoester When do you hope to send out the new paper?

**Comment by chris-rands** [comment]
+1 I had similar thoughts in this bitbucket issue: https://bitbucket.org/snakemake/snakemake/issues/1242/making-snakemake-work-with-black

@johanneskoester I guess the plan is to start fresh here on github rather than migrate the bitbucket issues?

**Comment by mbhall88** [comment]
So it seems the best way to approach this is to write a program (or snakemake submodule) that uses [black to parse the python code](https://black.readthedocs.io/en/stable/reference/reference_functions.html#black.format_str) and then we can format the Snakemake syntax code.  

Generally, it seems like code formatters heavily leverage the [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) for the language. @johanneskoester is there some kind of AST for Snakemake? It looks like all the parsing is done in [here](https://github.com/snakemake/snakemake/blob/master/snakemake/parser.py) so we can leverage this. Then I guess the next things are to decide on the "style" we would like to output. i.e. do we want to be "opinionated", like black, and not allow any flexibility in format style.  

The other big question is whether you want this bundled with Snakemake (either as a subcommand or a flag) or whether you would prefer it to be a separate project.

**Comment by mbhall88** [comment]
Update: I have made a start on this with a colleague - https://github.com/mbhall88/snakefmt

Would be great to speak with you about this when you're back @johanneskoester

**Comment by bricoletc** [comment]
Dear @johanneskoester, regarding this project we have made decent progress!

I would like to ask what you might consider for integration into Snakemake. Do you want a formatter much like your team's recent linter, meaning i)A set of modules directly under snakemake/ and ii)Directly callable as `--format` ?

This project has its own parser for Snakefiles- I found it too challenging to use the existing snakemake parser.py. This causes the obvious annoyance, if doing the above integration, of having two parsers. One option to work on is I think we could have our parser compile the same code as your parser.py, but I'm not sure if that is of interest to you or relevant in this scope.

Kind regards!

**Comment by johanneskoester** [comment]
Good question. On the one hand, having an intergrated formatter would be nice in terms of enforcing a certain style. On the other hand, it might bloat snakemake too much. Let us keep it separate for now, but I am happy to move it into the snakemake organization (of course with admin rights for you).

Does it also format the python parts of the snakefile? Does it move into includes?

**Comment by mbhall88** [comment]
It formats the python code using black.  

It doesn't move into `includes`, but I have set it up to (by default) to search for snakefiles the same way black searches for python files. The [default include pattern](https://github.com/mbhall88/snakefmt/blob/308429c179e8185baf4b127885a736c5a9fb8281/snakefmt/snakefmt.py#L20) is `r"(\.smk$|^Snakefile)"`. But if someone were to explicitly pass the files they wanted formatted; then only those files will be formatted.   

I was also thinking it might be nice to allow for [setting the formatting configuration (line length etc.) from a `pyproject.toml`](https://black.readthedocs.io/en/stable/pyproject_toml.html). This way black settings and snakefmt settings can be set simultaneously. Something like
```toml
[tool.black]
line_length = 88

[tool.snakefmt]
line_length = 90
include = '(\.smk$|^Snakefile|\.mysnakefileext$)'
```

**Comment by johanneskoester** [comment]
> It formats the python code using black.

Great!

> 
> It doesn't move into `includes`, but I have set it up to (by default) to search for snakefiles the same way black searches for python files. The [default include pattern](https://github.com/mbhall88/snakefmt/blob/308429c179e8185baf4b127885a736c5a9fb8281/snakefmt/snakefmt.py#L20) is `r"(\.smk$|^Snakefile)"`. But if someone were to explicitly pass the files they wanted formatted; then only those files will be formatted.

That makes sense.

> I was also thinking it might be nice to allow for [setting the formatting configuration (line length etc.) from a `pyproject.toml`](https://black.readthedocs.io/en/stable/pyproject_toml.html). This way black settings and snakefmt settings can be set simultaneously. Something like
> 
> ```toml
> [tool.black]
> line_length = 88
> 
> [tool.snakefmt]
> line_length = 90
> include = '(\.smk$|^Snakefile|\.mysnakefileext$)'
> ```

So, actually, I'd prefer to enforce line_length = 80 and `r"(\.smk$|^Snakefile)"`. The goal of this is standardization, so it would be nice to keep it non-configurable. But if that feels to strict for you, I am also fine with allowing a config file like that.

**Comment by mbhall88** [comment]
I was effectively just trying to mirror black with the settings. The default line length is 88 (same as black).   
I guess this is where the line between strict and opinionated arises. I think it is fine to allow people to change the include regex if they like. However, I doubt too many people would do that. For example, I am lazy, and I would prefer just to change my file extension than have to mess around with a regex 😅
As of this current moment, this is what the CLI options are. Let me know if you feel anything should be added/removed

```
$ snakefmt --help
Usage: snakefmt [OPTIONS] [SRC]...

  The uncompromising Snakemake code formatter.

Options:
  -l, --line-length INTEGER  [default: 88]
  --include TEXT             A regular expression that matches files and
                             directories that should be included on recursive
                             searches.  An empty value means all files are
                             included regardless of the name.  Use forward
                             slashes for directories on all platforms
                             (Windows, too).  Exclusions are calculated first,
                             inclusions later.  [default: (\.smk$|^Snakefile)]
  --exclude TEXT             A regular expression that matches files and
                             directories that should be excluded on recursive
                             searches.  An empty value means no paths are
                             excluded. Use forward slashes for directories on
                             all platforms (Windows, too). Exclusions are
                             calculated first, inclusions later.  [default: (\
                             .snakemake|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\
                             .tox|\.venv|\.svn|_build|buck-out|build|dist)]
  -h, --help                 Show this message and exit.
  -V, --version              Show the version and exit.
  -v, --verbose              Turns on debug-level logging.
```

**Comment by johanneskoester** [comment]
That is of course right. Ok, if you feel like, I am fine with the toml possiibility. I have just tried it out, and found an issue: https://github.com/mbhall88/snakefmt/issues/17

**Comment by bricoletc** [comment]
This now exists! https://github.com/snakemake/snakefmt
Should we close issue?
