### ISSUE TITLE
Empty caption breaks the html report

### ISSUE THREAD

**Issue by juliovbc** [snakemake/snakemake#363]
**Snakemake version**
5.16.0

**Describe the bug**
When not passing the caption parameter to `report`, the corresponding JSON object in `results` has no object assigned to the attribute `caption` instead of an empty string:

```
var results = {
            "reports/figures/p16/myfig.png": {
              name: "myfig.png",
              path: "reports/figures/p16/myfig.png",
              size: "417.2 kB",
              caption: ,
              ...
```

This triggers the following error in the browser console: `SyntaxError: expected expression, got ','`

**Comment by johanneskoester** [comment]
Good catch!

**Comment by johanneskoester** [comment]
Mhm, weird, the code does not look like it currently has this problem.

**Comment by johanneskoester** [comment]
The caption is dumped as json, which would be `""` in that case.

**Comment by johanneskoester** [comment]
Ok, just checked. Aparently this must have been fixed recently. Code as it is now is indeed fine.
