### ISSUE TITLE
Missing attribute exception even though Shell command is commented out

### ISSUE THREAD

**Issue by genomics-kl** [snakemake/snakemake#388]
Hello,

I'm sure this is expected behavior but was hoping to get some insight about why this unintuitive behavior (at least to me) exists. I could not find anything relevant in the usage guides (maybe I missed it...I was just searching for related keywords).

The code below leads to a RuleException: `'Params' object has no attribute 'nohits'`. The offending line of code is the last line below, where a commented out shell command uses `{paras.nohits}`.

```
rule all:
    input:"analysis/fastq_screen/sample1.tagged_filter.fastq.gz"

rule fastq_screen:
    input: "analysis/trim_reads/{fq_pref}.fq.gz"
    output:
        html="analysis/fastq_screen/{fq_pref}_screen.html",
        filtered="analysis/fastq_screen/{fq_pref}.tagged_filter.fastq.gz",
        tagged=temp("analysis/fastq_screen/{fq_pref}.tagged.fastq.gz")
    params:
        wd="analysis/fastq_screen",
    log:
        stdout="logs/fastq_screen/{fq_pref}.o",
        stderr="logs/fastq_screen/{fq_pref}.e"
    threads: 16
    resources:
        mem_mb=120000
    shell:
        """
        module load bbc/fastq_screen/fastq_screen-0.14.0
        #module load bbc/pigz/pigz-2.4

        fastq_screen --threads {threads} --nohits --outdir {params.wd} {input} 1> {log.stdout} 2> {log.stderr}

        #pigz --processes {threads} {params.nohits} 1>> {log.stdout} 2>> {log.stderr}
        """

```

**Comment by blaiseli** [comment]
The shell section has to be expanded into a shell command at the Python level, independently of its logic at the shell level. So Python tries to expand variables even inside shell-level comments.

**Comment by genomics-kl** [comment]
Thanks for the insight. I saw this a while back but forgot to close.
