### ISSUE TITLE
"script" path is not relative to directory snakemake is executed in

### ISSUE THREAD

**Issue by sappjw** [snakemake/snakemake#393]
**Snakemake version**
5.16.0

**Describe the bug**
The [documentation](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html?highlight=path#configure-working-directory) states:

> All paths in the snakefile are interpreted relative to the directory snakemake is executed in.

This does not seem to apply to paths in the `script` directive.

**Logs**
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 0 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1

[Wed May 13 12:59:24 2020]
rule all:
    output: output.txt
    jobid: 0
    reason: Missing output files: output.txt
    threads: 0

[Wed May 13 12:59:24 2020]
Error in rule all:
    jobid: 0
    output: output.txt

RuleException:
URLError in line 3 of ~/src/snakemake/tests/test_workflow_path/workflow/Snakefile:
<urlopen error [Errno 2] No such file or directory: '~/src/snakemake/tests/test_workflow_path/workflow/scripts/test.py'>
```

**Minimal example**
*Directory structure*:
```
.:
scripts  workflow

./scripts:
test.py

./workflow:
Snakefile
```

*Contents of `scripts/test.py`*:
```
with open(snakemake.output[0], 'wt+') as out:
    out.write('blah')
```

*Contents of `workflow/Snakefile`*:
```
rule all:
    output: 'output.txt'
    script: 'scripts/test.py'
```

**Additional context**
Run `snakemake -j0 all` in the topmost directory to reproduce.  It works if you change the `script` directive to be `../scripts/test.py`, but this is not ideal.  If I decide to reorganize my rules into a `workflow/rules` directory for example, I would have to change paths in rules.  This seems to go against the Snakemake philosophy of relative path locations.

**Comment by nhartwic** [comment]
Quote from the docs concerning the script rule type...

> The script path is always relative to the Snakefile (in contrast to the input and output file paths, which are relative to the working directory).

https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#external-scripts

**Comment by sappjw** [comment]
I missed that section when searching.  Thanks for the pointer.

**Comment by sappjw** [comment]
I took a closer look and it may be worth clarifying that the Snakefile the script path is relative to is the one containing the rule, not the "main" one.  For example, if I have this file structure and put the rule in `workflow/rules/subrule.smk`, the `scripts` directive needs to be `script: '../../scripts/test.py'`:

```
.:
scripts  workflow

./scripts:
test.py

./workflow:
rules  Snakefile

./workflow/rules:
subrule.smk
```

So maybe something like this would be useful:
> The script path is always relative to the Snakefile containing the directive...

**Comment by johanneskoester** [comment]
Thanks! Clarified in master.
