### ISSUE TITLE
Confused by change in documentation

### ISSUE THREAD

**Issue by elliothershberg** [snakemake/snakemake#397]
Hi,

I'm a big fan of snakemake, and have found it to be invaluable in my research. When I re-visited the documentation recently, I noticed a change that I was confused by.

It looks like all the way up to version 5.82, the recommended directory structure was this:
![image](https://user-images.githubusercontent.com/19295181/82106550-a5f9ca00-96d6-11ea-848c-d9dd3c7b42cb.png)

[link](https://snakemake.readthedocs.io/en/v5.8.2/snakefiles/deployment.html#distribution-and-reproducibility)

From 5.9 on, the recommend directory structure for distribution switched to:

![image](https://user-images.githubusercontent.com/19295181/82106594-ec4f2900-96d6-11ea-8989-eb961e639cb4.png)

[link](https://snakemake.readthedocs.io/en/v5.9.0/snakefiles/deployment.html#distribution-and-reproducibility)

I'm having a hard time making sense of the new recommended structure, and it seems like there are several more advanced concepts being used, especially compared to the tutorial in the docs. It is tough to interpret for me to interpret how this works, and I can't seem to find other parts of the docs where rules are defined in separate .smk files.

I'm proposing that some additional documentation be added to make it clear how this project structure works, and what the benefits are. I'm happy to help if pointed in the right direction.

Thanks for an amazing framework!

**Comment by nhartwic** [comment]
smk is just an extension to signify that its a Snakefile. I think it stands for 'snakemake'. There are a couple different ways to use multiple snakefiles. You can read more about them in 'modularization'

https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#includes

The docs could probably be elaborated upon.

**Comment by elliothershberg** [comment]
That makes sense. Yeah, looking at the examples in the [snakemake-worfklows repo](https://github.com/snakemake-workflows/docs), your explanation definitely matches with the techniques used. It seems like there is a gulf in the documentation between the tutorial in the docs, and this suggested project structure and the snakemake-workflow repos. Maybe needs an additional 'Advanced workflows' tutorial?

The typos you mentioned do also already make the docs more clear when they are fixed.

**Comment by johanneskoester** [comment]
Good points raised here, I am now fixing the description and also add more details. Sorry for the hassle. Watch out for the next release :-).

**Comment by johanneskoester** [comment]
Fixed in commit 601afb83.

**Comment by elliothershberg** [comment]
Awesome, thanks for the additional details! I think that makes things a lot more clear.

**Comment by elliothershberg** [comment]
Hey @johanneskoester, I don't want to belabor the point here, but it would be worth adding the previous project structure back in to the docs? For helping people get up and running w/ Snakemake, this is often the initial structure I recommend, and point them back to the previous docs.

For example:

A basic project structure is:

[previous]

A more modular/advanced project structure is:

[new]

Then, a workflow can be deployed... etc.
