### ISSUE TITLE
request to not ignore exceptions in S3Helper

### ISSUE THREAD

**Issue by arjanvandervelde** [snakemake/snakemake#404]
Hi!

I'm troubleshooting some intermittent failures with rules involving S3 downloads. It took me a while to figure out that these were S3 download errors, which are silently ignored by snakemake. It'd be great if you could raise the exception or at least print a warning when a S3 download fails....

see: https://github.com/snakemake/snakemake/blob/master/snakemake/remote/S3.py#L280-L292 

Thanks!

**Comment by johanneskoester** [comment]
Fixed with commit 889f2630.

**Comment by arjanvandervelde** [comment]
awesome. thanks!
