### ISSUE TITLE
--edit-notebook does not respect the --no-browser jupyter notebook option

### ISSUE THREAD

**Issue by akhanf** [snakemake/snakemake#407]
**Snakemake version**
5.18.1;  also tested latest commit 59cc5e397ce99502240238101b7e7ccf4cdad560

**Describe the bug**
The `--edit-notebook` option uses the `--no-browser` option when launching jupyter notebook, but this is overrided when the path to the ipynb file is also provided at command-line. Thus, even on servers where a desktop web-browser cannot be run (e.g. cluster login node), the jupyter tries to open the web browser. 

**Minimal example**

Using the --edit-notebook option can reproduce the error, but can also run a similar command outside of snakemake to reproduce:

This command tries to launch a browser (even though --no-browser used):
```
jupyter notebook --no-browser --log-level ERROR --ip HOSTNAME_HERE --port 8888 --NotebookApp.quit_button=True PATH_TO_A_IPYNB
```
But this command respects the `--no-browser` option:
```
jupyter notebook --no-browser --log-level ERROR --ip HOSTNAME_HERE --port 8888 --NotebookApp.quit_button=True 
```

**Potential workaround**

Using the `--NotebookApp.default_url` option instead of passing the name of the notebook seems to avoid this problem:
```
jupyter notebook --no-browser --log-level ERROR --ip HOSTNAME_HERE --port 8888 --NotebookApp.quit_button=True --NotebookApp.default_url='/tree/REL_PATH_TO_IPYNB'
```
This prevents the browser from opening on server start-up, but when the server is accessed, jupyter notebook it loads up the desired ipynb. However, an issue with this workaround, is there is no way to access the Quit button from the notebook. So, the user must CTRL-C from the server side to quit jupyter to save the notebook and continue snakemake.

I've made a draft PR that implements this workaround to allow some discussion: https://github.com/snakemake/snakemake/pull/406 

BTW the new jupyter notebook integration is *super*, really improves the development process. Much appreciated!

**Comment by johanneskoester** [comment]
Thanks for the warm words and your PR. As mentioned in the PR, I have done a slightly different fix now, so that we can close this issue.
