### ISSUE TITLE
about expand function! 

### ISSUE THREAD

**Issue by kevin-furant** [snakemake/snakemake#432]
configfile: "config.yaml"
merge_samples = config['merge']
single_samples = config['single']

rule all:
    input:
        expand("01.BWA/bam/{sample}.bam",sample=['T1','T2']),
        expand("01.BWA/merge_bam/T3/{sample_x}.bam",sample_x=['T3.1','T3.2']),
        expand("01.BWA/merge_bam/{sample}/{sample}.samHead",sample=merge_samples.keys())
rule single_bwa_mem:
    message: "samples not need merge."
    input:
        clean_reads=lambda wildcards: single_samples[wildcards.sample], 
        fa=config['fa']
    output:
        bam="01.BWA/bam/{sample}.bam"
    params:
        bwa=config['bwa'],
        samtools=config['samtools'],
        fai=config['fai']
    log: "log/{sample}.mem.log"
    shell:
        "{params.bwa} mem -t 4 -k 32 -M -R \"@RG\tID:{wildcards.sample}\tLB:{wildcards.sample}\tSM:{wildcards.sample}\" {input.fa} {input.clean_reads} "
        "|{params.samtools} view -bS -t {params.fai} > {output.bam}"
rule merge_bwa_mem:
    message: "samples which need merge."
    input:
        clean_reads=lambda wildcards: merge_samples[wildcards.sample][wildcards.sample_x],
        fa=config['fa']
    output:
        bam="01.BWA/merge_bam/{sample}/{sample_x}.bam"
    log: "log/{sample_x}.mem.log"
    params:
        bwa=config['bwa'],
        samtools=config['samtools'],
        fai=['fai']
    shell:
        "{params.bwa} mem -t 4 -k 32 -M -R \"@RG\tID:{wildcards.sample}\tLB:{wildcards.sample}\tSM:{wildcards.sample}\" {input.fa} {input.clean_reads} "
        "| {params.samtools} view -bS -t {params.fai} > {output.bam}"
rule getSamHead:
    input:
        bams=lambda wildcards: expand("01.BWA/merge_bam/{{sample}}/{sample_x}.bam",sample_x=merge_samples[wildcards.sample].keys())
    output: "01.BWA/merge_bam/{sample}/{sample}.samHead"
    params:
        perl=config['perl'],
        script=config['getSamHead']
    shell:
        "{params.perl} {params.script} {input.bams} > {output}"
in rule getSamHead,expand function's second parameter can not be a functions,it's a list ,so ,how can i do ,let it work?  the config.yaml file is like this :
perl: /PUBLIC/software/public/System/Perl-5.18.2/bin/perl
getSamHead: /PUBLIC/software/RESEQ/modules/current/BWA/bin/getSamHead.pl
bwa: /PUBLIC/software/public/Alignment/bwa/bwa-0.7.8/bwa
samtools: /PUBLIC/software/RESEQ/software/samtools-1.3.1/setup/bin/samtools
fa: /TJPROJ2/Animal/Project/Cooperation/P101SC17061004-02_duck_cxf/01.bwa/duck.fa
fai: /TJPROJ2/Animal/Project/Cooperation/P101SC17061004-02_duck_cxf/01.bwa/duck.fa.fai
single:
  T1:
    - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/single_clean/T1_1_clean.fq.gz
    - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/single_clean/T1_2_clean.fq.gz
  T2:
    - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/single_clean/T2_1_clean.fq.gz
    - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/single_clean/T2_2_clean.fq.gz
merge:
  T3:
    T3.1:
      - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/merge_clean/T3.1_1_clean.fq.gz
      - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/merge_clean/T3.1_2_clean.fq.gz
    T3.2:
      - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/merge_clean/T3.2_1_clean.fq.gz
      - /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/merge_clean/T3.2_2_clean.fq.gz

**Comment by kevin-furant** [comment]
in rule getSamHead,expand function's second parameter can not be a functions,it's a list ,so ,how can i do ,let it work?

**Comment by kevin-furant** [comment]
InputFunctionException in line 27 of /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/bwa.smk:
KeyError: '{sample}'
Wildcards:
sample={sample}
sample_x=T3.1

**Comment by kevinrue** [comment]
Hi @kevin-furant , I'm just another user with a similar issue, but I suggest you use the triple quote ``` to enclose your copy pasted chunks, for readability, e.g. 
```
InputFunctionException in line 27 of /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/bwa.smk:
KeyError: '{sample}'
Wildcards:
sample={sample}
sample_x=T3.1
```

**Comment by kevin-furant** [comment]
Thank you for your advice. I have solved the problem.
```
rule getSamHead:
    input:
        bams=lambda wildcards: expand("01.BWA/merge_bam/{sample}/{sample_x}.bam",zip,sample=[wildcards.sample]*len(merge_samples[wildcards.sample]),sample_x=merge_samples[
wildcards.sample].keys())
    output: "01.BWA/merge_bam/{sample}/{sample}.samHead"
    params:
        perl=config['perl'],
        script=config['getSamHead']
    shell:
        "{params.perl} {params.script} {input.bams} > {output}"
```

**Comment by kevin-furant** [comment]
> 
> 
> Hi @kevin-furant , I'm just another user with a similar issue, but I suggest you use the triple quote ``` to enclose your copy pasted chunks, for readability, e.g.
> 
> ```
> InputFunctionException in line 27 of /TJPROJ2/RESEQ/Project_Crop/Users/fuxiangke/snakemake/bwa/bwa.smk:
> KeyError: '{sample}'
> Wildcards:
> sample={sample}
> sample_x=T3.1
> ```
now  it works well .
my snakemake version is 3.13 
```
configfile: "config.yaml"
merge_samples = config['merge']
single_samples = config['single']
all_samples = list(merge_samples.keys()) + list(single_samples.keys())
rule all:
    input:
        "01.BWA/result/map_cov.release.xls",
        expand("01.BWA/bam/{sample}.rmdup.bam",sample=all_samples),
        expand("01.BWA/bam/{sample}.rmdup.bam.bai",sample=all_samples)
       # expand("01.BWA/bam/{sample}.sort.bam",sample=all_samples),
       # expand("01.BWA/merge_bam/T3/{sample_x}.bam",sample_x=['T3.1','T3.2']),
       # expand("01.BWA/merge_bam/{sample}/{sample}.samHead",sample=merge_samples.keys())
rule single_bwa_mem:
    message: "samples not need merge."
    input:
        clean_reads=lambda wildcards: single_samples[wildcards.sample], 
        fa=config['fa']
    output:
        bam="01.BWA/bam/{sample}.bam"
    params:
        bwa=config['bwa'],
        samtools=config['samtools'],
        fai=config['fai']
    log: "log/{sample}.mem.log"
    shell:
        "{params.bwa} mem -t 4 -k 32 -M -R \"@RG\tID:{wildcards.sample}\tLB:{wildcards.sample}\tSM:{wildcards.sample}\" {input.fa} {input.clean_reads} "
        "|{params.samtools} view -bS -t {params.fai} > {output.bam}"
rule merge_bwa_mem:
    message: "samples which need merge."
    input:
        clean_reads=lambda wildcards: merge_samples[wildcards.sample][wildcards.sample_x],
        fa=config['fa']
    output:
        bam="01.BWA/merge_bam/{sample}/{sample_x}.bam"
    log: "log/{sample_x}.mem.log"
    params:
        bwa=config['bwa'],
        samtools=config['samtools'],
        fai=['fai']
    shell:
        "{params.bwa} mem -t 4 -k 32 -M -R \"@RG\tID:{wildcards.sample}\tLB:{wildcards.sample}\tSM:{wildcards.sample}\" {input.fa} {input.clean_reads} "
        "| {params.samtools} view -bS -t {params.fai} > {output.bam}"
rule getSamHead:
    input:
        bams=lambda wildcards: expand("01.BWA/merge_bam/{sample}/{sample_x}.bam",zip,sample=[wildcards.sample]*len(merge_samples[wildcards.sample]),sample_x=merge_samples[wildcards.sample].keys())
    output: "01.BWA/merge_bam/{sample}/{sample}.samHead"
    params:
        perl=config['perl'],
        script=config['getSamHead']
    shell:
        "{params.perl} {params.script} {input.bams} > {output}"
rule merge_bam:
    input:
        bams=lambda wildcards: expand("01.BWA/merge_bam/{sample}/{sample_x}.bam",zip,sample=[wildcards.sample]*len(merge_samples[wildcards.sample]),sample_x=merge_samples[wildcards.sample].keys()),
        header="01.BWA/merge_bam/{sample}/{sample}.samHead"
    output: "01.BWA/bam/{sample}.bam"
    params:
        samtools=config['samtools']
    shell:
        "{params.samtools} merge -f {output} -h {input.header} {input.bams}"
rule sort_bam:
    input:
        bam="01.BWA/bam/{sample}.bam"
    output:
        bam="01.BWA/bam/{sample}.sort.bam",
        aln="01.BWA/aln/{sample}.alninfo"
    params:
        samtools=config['samtools'],
        perl=config['perl'],
        script=config['stat_bwa_mem_v5'],
        dir="01.BWA/aln/"
    shell:
        "{params.perl} {params.script} -bam {input.bam} -out {params.dir} |{params.samtools} "
        "view -bS - |{params.samtools} sort -m 4000000000 -T {wildcards.sample} -o {output.bam}"
rule rmdup_bam:
    input:
        bam="01.BWA/bam/{sample}.sort.bam"
    output: "01.BWA/bam/{sample}.rmdup.bam"
    params:
        samtools=config['samtools']
    shell:
        "{params.samtools} rmdup {input.bam} {output}"
rule depth_static:
    input:
        bam="01.BWA/bam/{sample}.rmdup.bam"
    output:
        summary="01.BWA/coverage/{sample}/summary.txt",
        cov="01.BWA/coverage/{sample}"
    params:
        perl=config['perl'],
        script=config['depth_v2'],
        length=config['length']
    shell:
        "{params.perl} {params.script} -l {params.length} {input.bam} {output.cov}"
rule build_index:
    input: "01.BWA/bam/{sample}.rmdup.bam"
    output: "01.BWA/bam/{sample}.rmdup.bam.bai"
    params:
        samtools=config['samtools']
    shell:
        "{params.samtools} index {input}"
rule merge_stat:
    input:
        aln=expand("01.BWA/aln/{sample}.alninfo",sample=all_samples),
        summary=expand("01.BWA/coverage/{sample}/summary.txt",sample=all_samples)
    output:
        map_cov="01.BWA/result/map_cov.xls"
    params:
        perl=config['perl'],
        script=config['merge_bwa_stat'],
        aln="01.BWA/aln",
        cov="01.BWA/coverage",
        result_dir="01.BWA/result"
    shell:
        "{params.perl} {params.script} {params.aln} {params.cov} {params.result_dir}"
rule map_cov_release:
    input:
        map_cov="01.BWA/result/map_cov.xls"
    output: "01.BWA/result/map_cov.release.xls"
    shell:
        "cut -f 1,2,4,8,9,10,11 {input.map_cov} > {output}"
```

**Comment by kevinrue** [comment]
Dear @kevin-furant 
If you solved your problem, you should close this issue. I cannot do that. It has to be you or the Snakemake developer.
Best
Kevin
