### ISSUE TITLE
When did deprecation of singularity keyword happen?

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#440]
**Snakemake version**

`5.17.0`

---

When running `snakemake --lint` I get the following warning:

```
    * Deprecated singularity directive used for container definition in line 186.:
      Use the container directive instead (it is agnostic of the underlying container runtime).
      Also see:
      https://snakemake.readthedocs.io/en/latest/snakefiles/deployment.html#running-jobs-in-containers
```

I can't see anywhere in the changelog or version info where `singularity` was deprecated in favour of `container`?

**Comment by johanneskoester** [comment]
Good catch, might be that it was not mentioned in the changelog.

**Comment by johanneskoester** [comment]
Version 5.11

**Comment by johanneskoester** [comment]
I have fixed it in the change log.
