### ISSUE TITLE
Mandatory --cores command line option

### ISSUE THREAD

**Issue by jjarmagost** [snakemake/snakemake#450]
**Snakemake version**
5.19.3

**Describe the bug**
When I run my flow Snakemake immediately stops, saying the --cores command line option is mandatory.

**Logs**
mymachine>snakemake compile_sim_models
Error: you need to specify the maximum number of CPU cores to be used at the same time with --cores.

I sincerely hope this is some kind of accident.  I have been absolutely loving Snakemake for the last year or so.  _Snakemake is by far the nicest flow management tool I've used_.  However, this change just makes absolutely no sense.  

1. It breaks preexisting flows.
2. It chooses the worst of three possible options (all cores, 1 core, no cores).  
3. It deviates from GNU make behavior that Snakemake claims to be inspired by.  (GNU make assumes one core, but at least it assumes something other than 0!)
4. It lowers the user-friendliness of the tool.  Typing "--cores all" every single time I invoke the tool is pure overhead.  

Please rethink this change.  I'm begging you.   :-)

**Comment by SultanOrazbayev** [comment]
Seems like you haven't upgraded for a while, this was introduced in 5.11 (see [link](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id37))

It's unlikely to change, see previous discussions:
https://github.com/snakemake/snakemake/issues/283
https://github.com/snakemake/snakemake/issues/308
https://github.com/snakemake/snakemake/issues/312

As suggested in https://github.com/snakemake/snakemake/issues/312, you might find `profile` helpful...

**Comment by SultanOrazbayev** [comment]
Alternatively, as a hack, you can create an alias in the shell...

**Comment by johanneskoester** [comment]
4. If you want full parallelization, you had to type --cores all (or -j, which is still possible) before as well. We just changed the default of choosing 1 thread, into requiring to explicitly specify them.

**Comment by johanneskoester** [comment]
For further discussion, please join issue #308.

**Comment by jjarmagost** [comment]
Thanks very much for your responses.  I understand your points but for me personally this seems like too severe of a departure from an otherwise exceptionally thought out tool.  I just can't wrap my head around making the tool less user friendly in order to help new users of the tool understand their parallelization options.  That's what a FAQ is for.  

Anyway, I do appreciate the responses.
