### ISSUE TITLE
Rules with outputfiles in subfolders on Windows (possible path separator issue)

### ISSUE THREAD

**Issue by eivindgl** [snakemake/snakemake#46]
**Snakemake version**
5.7.1
**Describe the bug**
Unable to specify output files in subfolders on windows. I have tried both 
This works on linux and WSL.

**Logs**
Powershell
```
PS > snakemake -np tmp/entries.feather
Building DAG of jobs...
MissingRuleException:
No rule to produce tmp\entries.feather (if you use input functions make sure that they don't raise unexpected exceptions).
```

Git-bash (MINGW)
```
$ snakemake -np tmp/entries.feather
Building DAG of jobs...
MissingRuleException:
No rule to produce tmp\entries.feather (if you use input functions make sure that they don't raise unexpected exceptions).
```

**Minimal example**
Snakefile
```
rule convert_xlsx:
    input:
        "input/pi/{filename}.xlsx"
    output:
        "tmp/{filename}.feather"
    shell:
        "echo {input} > {output}"
```

**Additional context**
I believe this is caused by the path separator. Are there any recommended best practices for writing windows and linux compatible workflows?

**Comment by melund** [comment]
@eivindgl Could you check #19. It fixes many different things related to windows. I can't remember if this particular problem is fixed. But if the same example with subfolders are  already present in the test suite then chances are that it may have been fixed. 

The PR also adds a new functionality to use bash as the shell on windows. It makes it much easier to write linux/windows compatible workflows.

**Comment by eivindgl** [comment]
very nice, thank you @melund . I will check this out.

**Comment by fneum** [comment]
Just to add 2 cents: I ran into the same issue and a try with #19 did not solve it (but I won't exclude I haven't done a mistake there). I added `shell.use_bash_on_win()` to the `Snakefile` and have git BASH installed.

**Comment by melund** [comment]
Does it only happen when you specify the file to produce on the command line?

**Comment by fneum** [comment]
Yes, that's correct

**Comment by melund** [comment]
I never used snakemake like that. So it explains it. I think we should just endsure that paths from the command line are also converted to forward slashes. I think that is what snakemake currently does with all paths in the snakefile. Right now the opposite happens. Probably because of argparse...

**Comment by fneum** [comment]
Seems, you are correct. 

```
C:\Users\fneum\snakemake-windows>snakemake tmp/entries.feather
Building DAG of jobs...
MissingRuleException:
No rule to produce tmp\entries.feather (if you use input functions make sure that they don't raise unexpected exceptions).
```

```
C:\Users\fneum\snakemake-windows>snakemake --keep-target-files tmp/entries.feather
Building DAG of jobs...
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       convert_txt
        1

[Thu Nov  7 13:03:14 2019]
rule convert_txt:
    input: input/pi/entries.txt
    output: tmp/entries.feather
    jobid: 0
    wildcards: filename=entries

[Thu Nov  7 13:03:14 2019]
Finished job 0.
1 of 1 steps (100%) done
Complete log: C:\Users\fneum\snakemake-windows\.snakemake\log\2019-11-07T130314.005983.snakemake.log
```

**Comment by nickdelgrosso** [comment]
I've encountered this bug, too, using Snakemake 5.25.0 in Windows 10.  It's a really annoying gotcha and indicates some core problems with how Snakemake parses filepaths (which is kind of key to the whole Snakemake design), but writing this bug report helped me find a workaround until it's fixed: **windows users should use backslashes in the output filename**

Maybe this is documented somewhere, but I never found it.  Below are some test cases that will hopefully help:

## No subdirectory works fine.

Using this rule everything is fine:

```python
rule hist:
    input:
        "data/processed/AL/Onshort-AL-{year}.csv"
    output:
        "h{year}.png"
    run:
```

```
>> snakemake -np h1990.png
rule hist:
    input: data/processed/AL/Onshort-AL-1990.csv
    output: h1990.png
    jobid: 0
    wildcards: year=1990

echo Hello > h1990.png
Job counts:
        count   jobs
        1       hist
        1
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

## Subdirectory with forward-slash output filenames does *not* work.

This doesn't work:

```python
rule hist:
    input:
        "data/processed/AL/Onshort-AL-{year}.csv"
    output:
        "results/h{year}.png"
    shell:
        "echo Hello > {output}"
```

```
>> snakemake -np results/h1990.png
Building DAG of jobs...
MissingRuleException:
No rule to produce results\h1990.png (if you use input functions make sure that they don't raise unexpected exceptions).
```

Using backslashes in the terminal also doesn't help:

```
>> snakemake -np results\h1990.png
Building DAG of jobs...
MissingRuleException:
No rule to produce results\h1990.png (if you use input functions make sure that they don't raise unexpected exceptions).
```

## Backslashes in the Snakemake rule output definition works, though.

```python
rule hist:
    input:
        "data/processed/AL/Onshort-AL-{year}.csv"
    output:
        r"results\h{year}.png"
    shell:
        "echo Hello > {output}"
```

```
>> snakemake -np results\h1990.png
Building DAG of jobs...
Job counts:
        count   jobs
        1       hist
        1

[Wed Oct  7 17:40:19 2020]
rule hist:
    input: data/processed/AL/Onshort-AL-1990.csv
    output: results\h1990.png
    jobid: 0
    wildcards: year=1990

echo Hello > results\h1990.png
Job counts:
        count   jobs
        1       hist
        1
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
```

**Comment by nickdelgrosso** [comment]
This also comes up with the conda option:

```
conda:
    "envs/environment.yml"
```

```>> snakemake -F -j1 --use-conda
WorkflowError:
Conda env file does not exist: C:\Users\Nick\Desktop\GE2\envs/environment.yml
```

**Comment by melund** [comment]
This must be a regression. I have forward slashes for all my output files in my snakefiles. They last ran before summer. Actually, using forward slashes was the only thing working as I recall it.

**Comment by melund** [comment]
Strike that. I see it is about calling snakemake from the command line to produce a certain output file. That is an old bug.

 I suggest we stick with forward slashes in snakemake. I might have time to look at this later this year. But it is not a priority for my workflow. If anyone else can solve this it would be great.
