### ISSUE TITLE
Conda environment setup slow on Mac OS X

### ISSUE THREAD

**Issue by bkohrn** [snakemake/snakemake#463]
I have noticed that Conda environment setup seems to be exceptionally slow on Mac OS X when done through Snakemake.  Is there any particular reason that should be, and is there anything I can do to make setup faster?  My particular pipeline (https://github.com/Kennedy-Lab-UW/Duplex-Seq-Pipeline) has a large, complicated environment, and, on Mac OS X, it feels like it sits there forever on "Downloading Remote Packages" without doing anything.

**Comment by jmeppley** [comment]
I don't know enough about snakemake internals to know for sure, but conda can definitely be slow all on it's own.

Have you tried creating the same environment manually? Is it faster?

Have you read the Anaconda document on [speeding up conda](https://www.anaconda.com/blog/understanding-and-improving-condas-performance)?

The easy trick is to specify versions very precisely. 

You can also look into using a [metachannel](https://medium.com/@marius.v.niekerk/conda-metachannel-f962241c9437) to reduce the solve size.

**Comment by bkohrn** [comment]
If I create an empty environment, and then manually install all the packages, it finishes a lot faster.  My solution for the moment (although it doesn't work long-term) is to let snakemake start creating the environment, then go to where snakemake would have made the environment and put the environment together manually (installing one package at a time), and then create the env_setup_done file; this seems to trick Snakemake into thinking the environment is set up correctly.  The setup happens in a few hours via Snakemake on linux, but can sit for days and not finish through snakemake on mac os.  

I haven't tried all of the speeding up conda stuff; I'll give that a try.

**Comment by jmeppley** [comment]
It's one of the known issues with conda that it's slow to resolve all the dependencies for a bunch of packages at once. I doubt it's practical to get snakemake to do the install one at a time, but maybe snakemake could also accept the path of an existing environment instead of a YAML file. That would give you a good workaround.

**Comment by jmeppley** [comment]
It looks like someone suggested just this in #352.

If that gets implemented, it'd be a good workaround for you and probably the best you'll get. I don't think it's within the scope of snakemake to speed up the conda build.

**Comment by jmeppley** [comment]
Hey @bkohrn,

In the discussion of issue #352, Johannes says that snakemake now supports [Mamba](https://github.com/TheSnakePit/mamba), which (as I just learned) is a drop in replacement for conda that's significantly faster.

It [seems](https://snakemake.readthedocs.io/en/stable/executing/cli.html) you can install mamba in your environment with snakemake, then add the flag `--conda-frontend mamba`.

**Comment by bkohrn** [comment]
The mamba setup seems to work, and I'm also considering moving to using docker containers in the future.  

Thank you for the help.
