### ISSUE TITLE
Support pathlib in expand()

### ISSUE THREAD

**Issue by keller-mark** [snakemake/snakemake#468]
**Is your feature request related to a problem? Please describe.**
Pathlib works most places in snakemake, which is great. However, in calls to expand(), pathlib paths must be converted to `str`, otherwise the following error occurs:

```sh
TypeError in line 29 of /Users/.../Snakefile:
'PosixPath' object is not iterable
  File "/Users/.../Snakefile", line 29, in <module>
```

**Describe the solution you'd like**
Update the `expand()` function to check whether the first argument is a `Path` object, and convert it to a string if so.

**Comment by jmeppley** [comment]
Oh, yes! This would be great.
