### ISSUE TITLE
breaking '--configfile <file>' behaviour change from 5.6

### ISSUE THREAD

**Issue by theJasonFan** [snakemake/snakemake#47]
**Snakemake version**
5.6 / 5.7

**Describe the bug**
`snakemake all --configifile config.yml` and `snakemake --configfile config.yml all` have different behaviors. The latter fails.

e.g.)

**Logs**
![image](https://user-images.githubusercontent.com/9468659/67317103-9cf5a100-f4d7-11e9-8db9-f71a2c83b000.png)

**Comment by johanneskoester** [comment]
Your terminal output suggests that you actually want to pass datasets/ci-config.yml in the first command, right?

Apart from that: the semantic is different here. --configfile accepts multiple files. The python argument parser hence sees all the downstream args (all, verify) as additional config files being passed. You need to either put them before or separated them via `--`. This is standard behavior for command line tools.

**Comment by theJasonFan** [comment]
@johanneskoester Thanks!

I should have looked closer at the change logs.

Love the tool 👍!
