### ISSUE TITLE
Using file:// url for wrappers triggers warning

### ISSUE THREAD

**Issue by holtgrewe** [snakemake/snakemake#48]
**Snakemake version**
5.7.1

**Describe the bug**
I'm using `file://` URLs for paths to wrappers.
This causes warnings.

**Logs**

```
File path file:///fast/basecalls/seqmux/home/digestiflow-demux/digestiflow_demux/wrappers/fastqc/environment.yaml contains double '/'. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
```

**Comment by johanneskoester** [comment]
I think file:// is always absolute. Does it also warn wil `file://fast/basecalls/...`?

**Comment by johanneskoester** [comment]
For relative file URLs, one would use `file:fast/basecalls`. See here: https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#wrappers

**Comment by johanneskoester** [comment]
But I agree that the error message is misleading.

**Comment by johanneskoester** [comment]
I think it was fixed in the latest release though, wasn't it? Closing for now. Please reopen if I am wrong.

**Comment by camillescott** [comment]
This still seems to exist when using absolute wrapper paths in version 5.20.1.
