### ISSUE TITLE
The csv file change to csv.html in report file.

### ISSUE THREAD

**Issue by tiramisutes** [snakemake/snakemake#503]
Dear,
The CSV format output file from rule change to csv.html format when report a workflow using command `snakemake --report report.html`. And can not be download when clicking it.

![image](https://user-images.githubusercontent.com/10768210/87563727-24ccac80-c6f2-11ea-8c8d-2b88b7cd51aa.png)

How to keep in original format? Thanks.

**Comment by mbhall88** [comment]
@johanneskoester  I'm also seeing this. The CSV seems to get turned into some weird HTML-like file. When you open it in a browser it prompts you to download the same file again...

**Comment by cpauvert** [comment]
I have the same issue with v 5.27.4 . Updating to 5.28.0 did not resolve the issue neither (it raises actually #745).
 It seems the HTML file is the rendering of your csv file following the template [`table.html.jinja2`](https://github.com/snakemake/snakemake/blob/22c98891a1d10247c31223895b1a3e36255a2986/snakemake/report/table.html.jinja2). I will try to hunt the responsible line to pinpoint the issue more precisely.
Best,

**Comment by HenningTimm** [comment]
I can confirm this also for TSV files. Pdf, svg, log and txt seem unaffected.

**Comment by cpauvert** [comment]
> I can confirm this also for TSV files. Pdf, svg, log and txt seem unaffected.

Thanks for confirming. The `FileRecord` class change the path for tables files (tsv/csv) after running them through the Jinja2 template at the following [line](https://github.com/snakemake/snakemake/blob/22c98891a1d10247c31223895b1a3e36255a2986/snakemake/report/__init__.py#L445)
```python
self.path = os.path.basename(self.path) + ".html"
```
A path that is printed in the final HTML report under the File column (see [code](https://github.com/snakemake/snakemake/blob/22c98891a1d10247c31223895b1a3e36255a2986/snakemake/report/report.html.jinja2#L588)).

A potential workaround would be, IMHO, to set the path to the original file, not the processed table. But link the processed table as a thumbnail, just like we benefit from picture thumbnail. I can try to PR something.

What do you think?
Best,

**Comment by johanneskoester** [comment]
Thanks a lot for reporting. I have removed the automatic conversion functionality. We will soon have a more scalable and generic solution for the interactive display of tables in reports.

**Comment by cpauvert** [comment]
Ok no problem. Thanks a lot for the continuous improvements!
