### ISSUE TITLE
How to specify the pass of R/Rscript command installed by `--use-conda` option

### ISSUE THREAD

**Issue by kokitsuyuzaki** [snakemake/snakemake#510]
**Is your feature request related to a problem? Please describe.**
I couldn't get the path of R/Rscript command installed by `--use-conda`.
I saved the config file of conda environment in `envs/myenv.yaml`.
However, If I perform R/Rscript inside bash script, other R/Rscript I recently installed is specified.
```
shell:
	"src/myprogram.sh"
```

The reason is that `.bashrc` the pass of R/Rsript is written is read by bash before performing this shell script but even if I use options so as not to use `.bashrc`, snakemake use other R/Rscript installed in the system (e.g. /usr/local/bin/R).
```
shell:
	"bash --norc --noprofile src/myprogram.sh"
```

I also know that after using conda tag and `--use-conda` option,
new conda environment is created as a directory in .snakemake/conda/.
Such environement is named `$hash`, which is a MD5 hash value.
https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management

So I can access the Rscript to specify the directory as ad hoc solution like below.
```
shell: 
	"Rscript=`ls .snakemake/conda/*/bin/Rscript`"
	"$Rscript myRprogram.R"
```

However, if I want to create multiple conda environments, how can I identify which directory is what I want to use?

**Describe the solution you’d like**

If I specify conda tag, I want to use R/Rscript inside shell tag immediately.

Or, I want to use the value of $hash inside of shell tag.
Because, if I can access the value, I can specify the corresponding program like below.

```
shell:
	'.snakemake/conda/$hash/bin/Rscript myRprogram.R'
```

**Comment by aryam7** [comment]
Hi @kokitsuyuzaki,
I was in your shoes once. Perhaps this might work for you?
```
Rscript="$CONDA_PREFIX"/bin/"$(ls "$CONDA_PREFIX"/bin | grep 'Rscript' | head -n1)"
```
See [lines 20-28 for a full, working example](https://github.com/aryam7/varCA/blob/f1d330c6d336480d1053a147129218461304f01f/callers/breakca#L20).

**Comment by kokitsuyuzaki** [comment]
Thanks, @aryam7

That's what I really want to know!

**Comment by kokitsuyuzaki** [comment]
Thanks.
I might have forgotten adding `--use-conda`.
If not specifying `--use-conda`, `$CONDA_PREFIX` seem to be specified as the local conda environment activated in my machine (e.g. `/home/koki/miniconda3/envs/myenv`), not `.snakemake/conda`.
I'll check the details.

**Comment by aryam7** [comment]
yup, that is indeed what should happen

**Comment by kokitsuyuzaki** [comment]
Sorry, I guess this is due to me forgetting to add `--use-conda`.
