### ISSUE TITLE
Snakemake --unlock requires users to set number of cores

### ISSUE THREAD

**Issue by jmeppley** [snakemake/snakemake#530]
**Snakemake version**
Latest from github: 5.14.0+130.g7741731a.dirty
 
**Describe the bug**
Snakemake requires the user specify a number of cores for the simple task of removing lock files. It's not apparent why this is necessary.

**Logs**
If applicable, any terminal output to help explain your problem.

**Minimal example**
```
(/mnt/data0/jmeppley/projects/snakemake/test-env) [jmeppley@tyrosine test_issue471]$ snakemake --unlock
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -jN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -j1.
(/mnt/data0/jmeppley/projects/snakemake/test-env) [jmeppley@tyrosine test_issue471]$ snakemake --unlock -j 1
Unlocking working directory.
```

**Comment by albertas** [comment]
I also think, that the default maximum number of cores should be set by default (e.g. --cores all). I have already raised similar issue before: https://github.com/snakemake/snakemake/issues/312
