### ISSUE TITLE
Checkpoint aggregate returns checkpoint output dir instead of files

### ISSUE THREAD

**Issue by ptrebert** [snakemake/snakemake#55]
Hi,
the following has been observed in 5.7.1 (edit: also in v5.7.4 and v5.6.0)

For jobs waiting for checkpoint output, I get failed jobs with the following irritating output (simplified):

```
rule merge_mono_dinucleotide_fraction:
    input: <TBD>
    output: <OMITTED path to output file>
    log: <OMITTED path to log file>
    jobid: 0
   <OMITTED wildcards, resources etc...>

Error in rule merge_mono_dinucleotide_fraction:
    jobid: 0
    output: <OMITTED>
    log: <OMITTED>
    shell:
        samtools merge -@ 6 -O BAM <OMITTED: correct path to output file> input/fastq/strand-seq/HG00733_PRJEB12849/requests &> <OMITTED: path to log file>
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
The `<TBD>` (to be determined?) probably tells me that Snakemake needs to evaluate the checkpoint in the input function - ok. The checkpoint is long-running (downloading data), and adding a `pdb.set_trace()` inside my input function shows that there is an IncompleteCheckpoint exception raised (as expected, I presume). Now the problematic part: the path `input/fastq/strand-seq/HG00733_PRJEB12849/requests` is the `directory()` output of the checkpoint. Checking the log file of samtools for the above failed job shows the following:
```
[E::hts_hopen] Failed to open file input/fastq/strand-seq/HG00733_PRJEB12849/requests
[E::hts_open_format] Failed to open file input/fastq/strand-seq/HG00733_PRJEB12849/requests
samtools merge: fail to open "input/fastq/strand-seq/HG00733_PRJEB12849/requests": Is a directory
```
Apparently, Snakemake detects the unfinished checkpoint, but returns the `directory()` of the checkpoint as input to the rule (in this case `merge_mono_dinucleotide_fraction`). ~~If I wait for all jobs to fail, and for the checkpoint to finish, and restart the pipeline, the workflow continues as expected (= showing that the aggregate input function works as intended).~~

I have trouble coming up with a minimal reproducible example for this, maybe because it's about timing, or the reason is actually something else - nevertheless, the log output of samtools clearly shows that Snakemake executes the rule with the checkpoint output, instead of the output collected by the aggregate input function.
Thanks for looking into this.

Best,
Peter

Below the code of my aggregate input function - as stated above, this works as intended ~~after waiting for the checkpoint to complete~~ (see my comment below):

```
def collect_merge_files(wildcards):
    """
    """
    individual = wildcards.individual
    bioproject = wildcards.bioproject
    platform = wildcards.platform
    project = wildcards.project
    lib_id = wildcards.lib_id

    requests_dir = checkpoints.create_bioproject_download_requests.get(individual=individual, bioproject=bioproject).output[0]

    search_pattern = '_'.join([individual, project, '{spec}', lib_id, '{run_id}', '1'])

    search_path = os.path.join(requests_dir, search_pattern + '.request')

    checkpoint_wildcards = glob_wildcards(search_path)

    bam_files = expand(
        'output/alignments/strandseq_to_reference/{reference}.{individual}.{bioproject}/{individual}_{project}_{spec}_{lib_id}_{run_id}.filt.sam.bam',
        zip,
        reference=[wildcards.reference, wildcards.reference],
        individual=[individual, individual],
        bioproject=[bioproject, bioproject],
        project=[project, project],
        spec=checkpoint_wildcards.spec,
        lib_id=[lib_id, lib_id],
        run_id=checkpoint_wildcards.run_id)

    assert len(bam_files) == 2, 'Missing merge partner: {}'.format(bam_files)

    return sorted(bam_files)
```

**Comment by ptrebert** [comment]
Just as addendum: the environment is a compute cluster with PBS/TORQUE. Running Snakemake with a single file as build target (that is produced by the above stated merge rule) succeeds w/o any issues.

**Comment by ptrebert** [comment]
Right now, the only way of getting around this seems to be to manually compile a list of expected output files and execute Snakemake with these explicit build targets once; after this has been completed, the rest of the pipeline can be executed in the same way as before...

I am also testing the same pipeline now on a single server to check if this is an environment thing (cluster and/or PBS/TORQUE)

**Comment by ptrebert** [comment]
I had the sudden idea of simply declaring the rule(s) using an checkpoint aggregate input function as "local" (`localrules:`), and it turns out this does the trick. So, to summarize:

- "aggregate"-style input functions fail on a PBS/TORQUE cluster, returning no/nonsensical values as input to the respective rules that are then executed by Snakemake (on a cluster node) and fail
- this can be avoided by explicitly specifying the output file of the rule that uses the "aggregate"-style input function as build target for Snakemake
--- obvious downside: for dozens or hundreds of small merge operations after a checkpoint, this is either quite tedious or requires an external script (as described above)
- another way to avoid this is to specify the affected rules as `localrules`, i.e. execute them on the head/master node
--- this is obviously creating an artificial bottleneck since the head node is usually less potent than the compute nodes
--- in environments where doing computations on the head node is actually forbidden, this may create even more problems

**Comment by johanneskoester** [comment]
I cannot reproduce this here with latest master. Did you use --immediate-submit?
If not, can you provide a minimal example for me to test?

**Comment by ptrebert** [comment]
No, I did not use `--immediate-submit`. You tested this using which type of scheduler? I have access to another cluster running SGE, I can check if it fails also there. For a minimal example, I'll try to come up with something over the weekend.

**Comment by ptrebert** [comment]
I wrote a minimal Snakefile to test this, but unfortunately the cluster I am using has hardware issues at the moment (or, this has been going on for longer, and the error I observed is a weird consequence of that...). On another cluster, my test Snakefile did not reproduce the error, but this cluster also runs a different scheduler...

**Comment by ptrebert** [comment]
I received feedback from the tech support about the potential cause for the compute cluster malfunction; this problem was solved and the cluster is operational again.
Now, I also could not reproduce the error using my minimal Snakefile. Since there were quite a few things going on here, I'll assume that this presumed "bug" was actually a weird side effect resulting from the file system issues on the cluster.
In case anyone ever stumbles across this again:
VM-based cluster running PBS/TORQUE scheduler (1 master, 3 workers); cluster hosts its own BeeOND file system. "Diagnostic" feature: rules calling an aggregate-style input function receive the checkpoint output (i.e., usually a directory) instead of the respective set of files as input (see samtools example above).
Closing this now as not reproducible...

**Comment by ptrebert** [comment]
Re-open...
The issue persists, now I get the same error on a completely different system (single server, no cluster). Apparently, the minimal test Snakefile that I wrote does not capture this issue, and it is obviously also nothing related to the cluster env or the file system; still no clue what is going on. Bottom line: I still get the checkpoint output (= the directory) instead of the collected files as input:
```
Input BAMS: input/fastq/strand-seq/HG00733_PRJEB12849/requests
Type: <class 'str'>
```

**Comment by ptrebert** [comment]
now re-open...

**Comment by johanneskoester** [comment]
Thanks for digging into this @ptrebert. All checkpoint related tests and real world examples are passing on my side. Hence, we can only proceed with an (as minimal as possible) example. Once that is available, I am happy to debug for you.

**Comment by ptrebert** [comment]
I am now quite confused about this: the progress output of Snakemake shows me the correct input files for the rule:
```
localrule write_strandseq_merge_fofn:
    input: output/[...]/aln/HG00732_1kg_il25k-075mo_P0IIL094_ERR1295549.filt.sam.bam, output/[...]/aln/HG00732_1kg_il25k-150di_P0IIL094_ERR1295548.filt.sam.bam
    output: output/[...]/mrg/HG00732_1kg_il25k-npe_P0IIL094.fofn
    jobid: 1284
    wildcards: reference=HG00732_hgsvc_pbsq2-ccs_sqa-wtdbg, bioproject=PRJEB12849, individual=HG00732, project=1kg, platform=il25k, lib_id=P0IIL094
```
Everything about this is correct - however, inside the `run` block, the content of `input.bams` is not a path to a file:

```
rule write_strandseq_merge_fofn:
    input:
        bams = collect_strandseq_merge_files  # note: name change relative to my first comment
    output:
        fofn = 'output/[...]/{reference}/{bioproject}/temp/mrg/{individual}_{project}_{platform}-npe_{lib_id}.fofn'
    log:
        'log/[...]/{reference}/{bioproject}/temp/mrg/{individual}_{project}_{platform}-npe_{lib_id}.fofn.log'
    run:
        with open(output.fofn, 'w') as dump:
            for file_path in input.bams:
                if not os.path.isfile(file_path):
                    with open(log[0], 'w') as error_log:
                        _ = error_log.write('Invalid path to merge BAM file: {}\n'.format(file_path))
                        _ = error_log.write('Input BAMS: {}\n'.format(input.bams))
                        _ = error_log.write('Type: {}\n'.format(type(input.bams)))
                        raise AssertionError('Invalid path to merge BAMs - see log: {}\n'.format(log[0]))

                _ = dump.write(file_path + '\n')
```
The log content tells me that `input.bam` is again the checkpoint output directory:
```
Input BAMS: input/fastq/strand-seq/HG00732_PRJEB12849/requests
```
When I try to debug this using pdb, it looks like the evaluation of the checkpoint/the `input` object is somehow delayed/not triggered correctly. In the series of steps, I see the following:

```
-> _ = error_log.write('Invalid path to merge BAM file: {}\n'.format(file_path))
--Return--
prepare_custom_references.smk(79)collect_strandseq_merge_files()->['output/align....filt.sam.bam', 'output/align....filt.sam.bam']
rules.py(628)apply_input_function()
--Return--
/rules.py(628)apply_input_function()->['output/align....filt.sam.bam', 'output/align....filt.sam.bam']
```
I don't find this highly informative, but if the series of steps is correct, it looks like as if the content of `input` is evaluated again (or for the first time?) only after I already tested it for being a path to a file (which, for the record, is indeed the case, all BAM files do exist on the file system).
Adding to my confusion is the fact that a `pdb` run with a minimal Snakefile to reproduce this behavior does not show any sign of this behavior, in particular the `input` object is just the list of files as expected...

**Comment by ptrebert** [comment]
@johanneskoester 
Sure, if only I could come up with a minimal example for this...

**Comment by ptrebert** [comment]
Since it seems that I cannot recreate this error in a minimal Snakefile, this is at least a workaround (should have though of that earlier...):

Inside the `run` block, just call the aggregate function again...
```
[...]
run:
    bam_files = collect_strandseq_merge_files(wildcards)
    with open(output.fofn, 'w') as dump:
            for file_path in bam_files:
                [...]  # works as expected...
```

**Comment by johanneskoester** [comment]
This is really weird. I don't really understand what is going on there. This almost sounds like some concurrent overwrite is happening (which does not occur when using pdb). But I have no idea where that should come from...

**Comment by ptrebert** [comment]
At least I am not the only one thinking this is weird :-)
For the time being, I have to live with the workaround as mentioned above because the pipeline needs to go in production. If you don't have an epiphany about this, it has to wait until I find the time to make a copy of the pipeline and "reverse-engineer" (= disassemble) it to the minimum necessary for recreating this error...

**Comment by ptrebert** [comment]
beacon: same error still exists in Snakemake v5.10.0

**Comment by johnstonmj** [comment]
Hi @johanneskoester and @ptrebert 

I've stumbled into the same issue and created a minimal reproducible example.
Interestingly, this bug reproduces when submitted to our LSF cluster, but not when run locally.

Setup:
```
# Setup input
# In reality, there are a variable number of runs for each samples
# And the input filenames contain unpredictable hash strings
# Leading to my glob below
mkdir logs
mkdir -p input/sampleA_run{1,2,3}
touch input/sampleA_run1/{apple,banana,cucumber}.txt
touch input/sampleA_run2/{alpha,beta,bubble,balloon}.txt
touch input/sampleA_run3/{blue,baboon}.txt
```


Contents of my 'minimal_example.smk':
```
import glob

rule all:
    input: "output/aggregated/sampleA.txt.link"

# The downstream function desires input of a single folder containing all inputs
# I symlink them all of the input for one sample into one here
# As an aside, if it is better to use glob_wildcards for this job, I would be eager to learn how 
rule collect_input_txt:
    input:
        lambda wildcards: glob.glob("input/{sample}_*/*.txt".format(sample=wildcards.sample))
    output:
        directory("output/all_txt_links/{sample}"),
    params:
        path_corrected = lambda wildcards, input: ["../../../" + txt for txt in input]
    shell:
        """
        # Make output directory
        mkdir -p {output}
        # Fill output directory
        ln -s -t {output} {params.path_corrected}
        """

# In reality, there is not a one-to-one relationship between input and output files for my next step
# Often many inputs are aggregated into fewer outputs, but not predictably named or numbered
# Therefore I use a checkpoint to determine how many output files have been created
# Here, I reduce the files present by keeping only the 6 filenames beginning with 'b'
checkpoint link_processor:
    input:
        "output/all_txt_links/{sample}"
    output:
        directory("output/processed_links/{sample}"),
    shell:
        """
        mkdir {output}

        for some_file in {input}/*
        do
            outfile=$(basename "$some_file")

            if [[ "$outfile" =~ ^b.* ]]
            then
                touch "{output}/$outfile"
            fi
        done
        """

def aggregate_input(wildcards):
    checkpoint_output = checkpoints.link_processor.get(**wildcards).output[0]
    return expand("output/processed_links/{sample}/{i}.txt",
           sample=wildcards.sample,
           i=glob_wildcards(os.path.join(checkpoint_output, "{i}.txt")).i)

rule aggregate:
    input:
        aggregate_input
    output:
        link = "output/aggregated/{sample}.txt.link"
    params:
        real_out = "output/aggregated/{sample}.txt"
    shell:
        """
        echo {input} | tr ' ' $'\n' > {params.real_out}

        numlines=$(wc -l < {params.real_out})
        echo $numlines

        if [ $numlines -ne 6 ]
        then
            exit 1
        fi

        ln -s ./{wildcards.sample}.txt {output.link}
        """
```

This command succeeds
`snakemake --snakefile "minimal_example.smk" all`
Generating `output/aggregated/sampleA.txt` with contents:

> output/processed_links/sampleA/balloon.txt
> output/processed_links/sampleA/blue.txt
> output/processed_links/sampleA/bubble.txt
> output/processed_links/sampleA/banana.txt
> output/processed_links/sampleA/baboon.txt
> output/processed_links/sampleA/beta.txt


This command fails:
`snakemake --snakefile "minimal_example.smk" --jobs 10 --cluster "bsub -o logs/{rule}.%J.out -e logs/{rule}.%J.err < " all`
Generating `output/aggregated/sampleA.txt` with contents:

> output/processed_links/sampleA

Note that this is the directory only, as reported by @ptrebert 

Thanks for any suggestions or bug fixes you may be able to offer!

**Comment by johnstonmj** [comment]
I've made a workaround based on @ptrebert making it work by re-running aggregate within a `run` block above.

The edited below aggregate rule that now succeeds.
aggregate_input function runs again within `params`.
Also fixed escaping of newline characters and added additional comments.
```
rule aggregate:
    input:
        aggregate_input
    output:
        link = "output/aggregated/{sample}.txt.link"
    params:
        real_out = "output/aggregated/{sample}.txt",
        retry_input_function = aggregate_input
    shell:
        """
        # echo {input} | tr ' ' $'\\n' > {params.real_out}
        echo {params.retry_input_function} | tr ' ' $'\\n' > {params.real_out}

        # Count output lines
        numlines=$(wc -l < {params.real_out})

        # If outputlines != 6, then it is wrong and exits before generating desired symlink output
        if [ $numlines -ne 6 ]
        then
            exit 1
        fi

        # Symlink to output. This preserves params.real_out file contents while debugging.
        # As only symlink gets deleted upon failure.      
        ln -s ./{wildcards.sample}.txt {output.link}
        """
```


If I run
```
snakemake -np --snakefile "minimal_example.smk" --jobs 10 --cluster "bsub -o logs/{rule}.%J.out -e logs/{rule}.%J.err < " all
```

I can see both the incorrect substitution from `{input}` and the desired wait-for-checkpoint from `{params}`
```
[Mon Mar 30 16:24:57 2020]
rule aggregate:
    input: <unknown>
    output: output/aggregated/sampleA.txt.link
    jobid: 1
    wildcards: sample=sampleA


        # echo output/processed_links/sampleA | tr ' ' $'\n' > output/aggregated/sampleA.txt
        echo <incomplete checkpoint> | tr ' ' $'\n' > output/aggregated/sampleA.txt

        numlines=$(wc -l < output/aggregated/sampleA.txt)

        if [ $numlines -ne 6 ]
        then
            exit 1
        fi

        ln -s ./sampleA.txt output/aggregated/sampleA.txt.link
```

Hope this helps!

**Comment by votti** [comment]
Thanks so much for the workaround with the `params` - this issue was driving me nuts!
I am doing a big workflow with couple of checkpoints and it was occurring at several points.
Some locations only when running the workflow on a slurm cluster.
An observation was also, that the issue was sometimes  only occurring  when runing a python snippet with `run:` and then absent when using `shell:` or `script:`.

I am very much looking forward to any fix.
Apart from this issue I am really impressed by snakemake!

**Comment by jmeppley** [comment]
I've seen similar behavior a few times when a workflow fails or gets interrupted and has to restart midstream. I've similarly had trouble making a minimal reproducible example.

Most recently on version 5.9.1

The workflow works fine when starting from scratch, but restarts aren't working. I get <TBD> as the reported input and the checkpoints output directory as the actual input:

```
[Thu Jun  4 17:11:57 2020]
localrule combine_outputs:
    input: <TBD>
    output: aloha.genes.emapper.annotations
    jobid: 1

Job counts:
        count   jobs
        1       combine_outputs
        1
input:  aloha.genes.fragments
[Thu Jun  4 17:11:57 2020]
Error in rule combine_outputs:
    jobid: 0
    output: aloha.genes.emapper.annotations

RuleException:
IsADirectoryError in line 60 of /mnt/lts/nfs_fs02/scope/scratch/jme/eggnog/Snakefile:
[Errno 21] Is a directory: 'aloha.genes.fragments'
```

I put a print statement in aggregate input function which never gets reached. 

If I put a second call to the aggregate input function in params, that works as expected, but it doesn't work as a workaround because not all the intermediate steps have been completed.

FWIW, I get the same error whether I try to run locally or with --cluster.

**Comment by jmeppley** [comment]
I can (sort-of) reproduce this with a small makefile running locally. I added "sort of" because it requires a missing input (that would normally be OK) to trigger the behavior.

The Snakefile:
```
"""
Dummy snakefile to reprouce issue #55

 * fragments input test
 * runs grep on each fragment separately
 * combines output

"""

input_file = config['input_file']
grep_pattern = config.get('pattern', 'rule ')
out_prefix = config.get('out_prefix', 'output')
chunk_size = config.get('chunk_size', 10)

wildcard_constraints:
    chunk=r'\w+'

rule all:
    input:
        f"{out_prefix}.matches",

checkpoint fragment_input:
    input: input_file
    output: directory(f'{out_prefix}.fragments')
    shell:
        """
            mkdir -p {output}
            split -l {chunk_size} {input} {output}/fragment.
        """

rule annotate_fragment:
    input: '{out_prefix}.fragments/fragment.{chunk}'
    output: '{out_prefix}.fragments/fragment.{chunk}.matches'
    threads: 2
    shell:
        'grep "{grep_pattern}" {input} > {output} || true'

def get_fragment_outputs(wildcards):
    frag_dir = checkpoints.fragment_input.get().output[0]
    chunks, = glob_wildcards(f'{out_prefix}.fragments/fragment.{{chunk}}')
    # wildcard_costraints not honored, so we do it manually
    chunks = [c for c in chunks if re.match(r'^\w+$', c)]
    return expand('{out_prefix}.fragments/fragment.{chunk}.matches',
                  out_prefix=out_prefix,
                  chunk=chunks)

rule combine_outputs:
    input: get_fragment_outputs
    output:
        f"{out_prefix}.matches",
    shell:
        "cat {input} > {output}"
```

If you run this with:
```
snakemake -p --config input_file=Snakefile
```

...it works fine. If you delete the output file and some of the inputs and re-run with a missing input, you get the error:

```
(/mnt/data0/jmeppley/projects/snakemake/test-env) [jmeppley@tyrosine test-tbd]$ rm output.fragments/fragment.ac.matches output.matches 
(/mnt/data0/jmeppley/projects/snakemake/test-env) [jmeppley@tyrosine test-tbd]$ snakemake -p --config input_file=Snakefil -j 3
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 3
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       combine_outputs
        2

[Thu Jun  4 16:23:25 2020]
rule combine_outputs:
    input: <TBD>
    output: output.matches
    jobid: 1

cat output.fragments > output.matches
cat: output.fragments: Is a directory
[Thu Jun  4 16:23:25 2020]
Error in rule combine_outputs:
    jobid: 1
    output: output.matches
    shell:
        cat output.fragments > output.matches
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job combine_outputs since they might be corrupted:
output.matches
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/data0/jmeppley/projects/snakemake/test-tbd/.snakemake/log/2020-06-04T162325.566085.snakemake.log
```
 If you build a comparable makefile without a checkpoint and re-run it from the same spot with a missing start file, it will recognize that the intermediate files exist and work from them. But with a checkpoint rule, you get this TBD behavior.

**Comment by jmeppley** [comment]
Hmm, on further exploration, this may be a different issue, but with the same symptom.

**Comment by votti** [comment]
Hi,
I just noticed that in the latest Snakemake version (5.30.2) this issue also happens when running workflows locally.
The workaround using `params` still works.

**Comment by brcopeland** [comment]
I believe I have found the source of this issue.  Here is the beginning of my example rule:
```
rule haplotype_caller:
    input:
        bam=get_final_bam,
```
which is the following function:
```
def get_final_bam(wildcards):
    """
    Returns the path to the final BAM for the sample while enforcing that it is
    insufficiently contaminated to continue.
    """
    checkpoints.check_contamination.get(**wildcards)
    return f"../output/bams/{wildcards['sample']}.bam"
```

The checkpoint is used to enforce checking the contamination of my BAM of interest is sufficiently low and creates the file as follows:
```
checkpoint check_contamination:
    input:
        "../output/qc/verifybamid/{sample}.selfSM",
    output:
        touch("../scratch/{sample}/check_contamination.done"),
```
Now if I run this pipeline locally this step (and all the others) work fine.  When I run it on a cluster (TORQUE - but I don't think this is relevant), the `input.bam` gets set to `../scratch/{sample}/check_contamination.done` instead of the proper BAM.  My investigation of the snakemake codebase indicated the problem exists in https://github.com/snakemake/snakemake/blob/87567e25ce7e5424e74e5be8e2ff747e67b0020a/snakemake/dag.py#L1327.  I ran a test rule with pdb both with the exact command snakemake put into a jobscript (which failed) and without all the additional parameters (which worked).  So, when snakemake sets up the jobscript for execution on the cluster, because `--allowed-rules` is set to only the rule of interest, the `jobs = [job for job in self.jobs if not self.needrun(job)]` is empty and therefore there are no updates to the DAG as occurs when we include the relevant checkpoint rule.  When I told snakemake to allow the checkpoint rule it inferred it needed to update downstream dependencies properly and the command is formatted properly.

My failing command was:
```
ipdb -m snakemake ../scratch/7954_Br/gvcfs/7954_Br_1.g.vcf.gz --snakefile ~/changuk/workflow/Snakefile --force --cores 1 --keep-targ
et-files --keep-remote --max-inventory-time 0 --latency-wait 60 --attempt 1 --force-use-threads --scheduler ilp --wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ -p --allowed-rules ha
plotype_caller --verbose --nocolor --notemp --no-hooks --nolock --scheduler-solver-path ~/miniconda3/bin --mode 2 --skip-script-cleanup --shadow-prefix /oasis/tscc/scratch/bcopeland -
-use-conda --conda-prefix /oasis/tscc/scratch/bcopeland/.snakemake --conda-base-path ~/miniconda3 --default-resources "tmpdir=system_tmpdir"
```
while the successful one is:
```
ipdb -m snakemake ../scratch/7954_Br/gvcfs/7954_Br_1.g.vcf.gz --snakefile ~/changuk/workflow/Snakefile --force --cores 1 --keep-targ
et-files --keep-remote --max-inventory-time 0 --latency-wait 60 --attempt 1 --force-use-threads --scheduler ilp --wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ -p --allowed-rules ha
plotype_caller check_contamination --verbose --nocolor --notemp --no-hooks --nolock --scheduler-solver-path ~/miniconda3/bin --mode 2 --skip-script-cleanup --shadow-prefix /oasis/tscc/scratch/bcopeland -
-use-conda --conda-prefix /oasis/tscc/scratch/bcopeland/.snakemake --conda-base-path ~/miniconda3 --default-resources "tmpdir=system_tmpdir"
```
As can be seen the only difference is the addition of the checkpoint rule `check_contamination`.  I don't know how best to address this but hopefully this helps to getting this fixed.

**Comment by brcopeland** [comment]
Here is a minimal example:
```
checkpoint a:
    output: touch("a.txt")

rule b:
    output: touch("b.txt")

def get_input(wildcards):
    checkpoints.a.get()
    return "b.txt"

rule c:
    input: get_input
    shell: "echo {input}"
```
Running `snakemake --cores 1 c` gives `b.txt` while `snakemake --cores 1 c --allowed-rules c` gives `a.txt`.  I think it might suffice in https://github.com/snakemake/snakemake/blob/87567e25ce7e5424e74e5be8e2ff747e67b0020a/snakemake/dag.py#L1332 to simply update `jobs` to include all checkpoints.

**Comment by ptrebert** [comment]
@brcopeland wow, finally someone could track down the potential cause, thanks a lot!
Which version of Snakemake are you using for testing this? I want to run your minimal example on our cluster...

**Comment by brcopeland** [comment]
I came across this issue recently myself so I upgraded to the latest build at the time, which for me was 6.8.1, to see if I was still encountering the problem (which I did).

**Comment by brcopeland** [comment]
This would also explain why your solution of adding the rule using an input function utilizing checkpoints to `localrules:` would work - in that case snakemake would never be attempting to run said rule by itself (i.e. without being restricted to only consider that rule with `--allowed-rules`).

**Comment by ptrebert** [comment]
> Thanks for digging into this @ptrebert. All checkpoint related tests and real world examples are passing on my side. Hence, we can only proceed with an (as minimal as possible) example. Once that is available, I am happy to debug for you.

@johanneskoester Now that @brcopeland could come up with a minimal example, I hope the Snakemake tests can be updated to cover this (besides fixing the bug itself...)

**Comment by johanneskoester** [comment]
Awesome work folks! I'll have a look into fixing this now :-).

**Comment by johanneskoester** [comment]
Mhm, after writing the testcase, I found that the issue is actually already foreseen in the executor code: https://github.com/snakemake/snakemake/blob/main/snakemake/executors/__init__.py#L349

We only use --allowed-rules when a rule has not been updated after a checkpoint has been running. So, I don't know why this would cause an issue in your case actually. Maybe one of you could debug into that code lines, checking why allowed-rules is still used in your case although you are downstream of a checkpoint?

**Comment by johanneskoester** [comment]
I believe this to be fixed, as there was no further comment in this thread. Please reopen if the problem persists.
