### ISSUE TITLE
Canceling jobs through Snakemake profiles?

### ISSUE THREAD

**Issue by holtgrewe** [snakemake/snakemake#570]
**Is your feature request related to a problem? Please describe.**

- When running cluster jobs through DRMAA, they are nicely canceled when Snakemake is stopped with Ctrl-C. This is not the case for the Slurm profile.

**Describe the solution you'd like**

- Similarly to when running DRMAA cluster jobs, I'd like to have child jobs being killed (e.g., via `scancel`).

**Describe alternatives you've considered**

- I don't think there are alternatives. I have not seen any mention of "canceling" in the Slurm or SURF profile.

**Additional context**

- Maybe I'm missing something?

**Comment by percyfal** [comment]
Hi @holtgrewe, I have just been reviewing a related bug report for the slurm profile (referenced above). Much of the solutions you request cannot be implemented in the profile itself, but would require modifications to the job executors, maybe even adding a specific SlurmExecutor; I believe there is an ongoing effort to refactor the executors. `scancelling` jobs should work, but whereas metadata for failed jobs is removed, incomplete files are not; see [Persistence.cleanup](https://github.com/snakemake/snakemake/blob/07f73006dcee1e6ce6c271355fff83705f188de4/snakemake/persistence.py#L201). Adding a `job.cleanup()` statement here seems to fix that particular issue, but there may be a reason for it's absence that I'm unaware of.

**Comment by holtgrewe** [comment]
Hi @percyfal thanks for your reply.

IMO it's borderline cheeky to mark `--cluster`/`--drmaa` support in Snakemake as deprecated without the profiles offering equivalent functionality. Well, the good is the enemy of the better. I'd dearly like to see profile support to reach the same level of features as `--drmaa` as using `--time=7-00` is much nicer than saying `--time=168:00:00`...
