### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'logfile_handler'

### ISSUE THREAD

**Issue by CezCz** [snakemake/snakemake#58]
**Snakemake version**
5.5.1, 5.7.4

**Describe the bug**
Trying to run snakemake with cluster-mode on slurm system. Job fails with exception
AttributeError: 'Logger' object has no attribute 'logfile_handler'

**Logs**
If applicable, any terminal output to help explain your problem.

**Minimal example**

**Snakefile:**
```
experiment_location = config["experiment_location"]
results = config["results"]

input_files, = glob_wildcards(experiment_location + "{IDS}.fastq.gz")

print(experiment_location)
print(results)

rule all:
    input: expand(results+"{IDS}.bam", IDS=input_files)

rule transform:
    input: experiment_location + "{IDS}.fastq.gz"
    output: results + "{IDS}.bam"
    shell: 'echo {input}; echo "test123" > {output}'
```

**Snakemake command:**
```
cluster_base_path=/path/to/dir/

experiment_location=path/to/experiment

results=results/

result_dir=Condition3_N_A_N_A/

snakemake -s ${cluster_base_path}Snakefile --config experiment_location="${cluster_base_path}${experiment_location}" results="${cluster_base_path}${results}${result_dir}" --cluster-config cluster.json --cluster "sbatch -n {cluster.n} -t {cluster.time}" --jobs 1

```

**cluster.json:**
```
{
    "\_\_default\_\_" :
    {
        "account" : "openbisrun",
        "time" : "00:15:00",
        "n" : 1,
        "partition" : "core"
    }
}
```

**Full exception**:

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	transform
	1
Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	transform
Selected jobs (1):
	transform
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Mon Oct 28 10:48:42 2019]
rule transform:
    input: /data5/openbis/data_volume/bbb-hub-data/snakemake_input/YVESN/PROJECT_TEST1/TEST1/test1_14_R2.fastq.gz
    output: /data5/openbis/data_volume/bbb-hub-data/results/Condition3_N_A_N_Atest1_14_R2.bam
    jobid: 0
    wildcards: IDS=test1_14_R2

echo /data5/openbis/data_volume/bbb-hub-data/snakemake_input/YVESN/PROJECT_TEST1/TEST1/test1_14_R2.fastq.gz; echo "test123" > /data5/openbis/data_volume/bbb-hub-data/results/Condition3_N_A_N_Atest1_14_R2.bam
/data5/openbis/data_volume/bbb-hub-data/snakemake_input/YVESN/PROJECT_TEST1/TEST1/test1_14_R2.fastq.gz
[Mon Oct 28 10:48:42 2019]
Finished job 0.
1 of 1 steps (100%) done
Complete log: None
Traceback (most recent call last):
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/site-packages/snakemake/__main__.py", line 4, in <module>
    main()
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/site-packages/snakemake/__init__.py", line 1989, in main
    show_failed_logs=args.show_failed_logs,
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/site-packages/snakemake/__init__.py", line 637, in snakemake
    logger.cleanup()
  File "/home/openbisrun/.conda/envs/sm/lib/python3.7/site-packages/snakemake/logging.py", line 113, in cleanup
    self.logger.removeHandler(self.logfile_handler)
AttributeError: 'Logger' object has no attribute 'logfile_handler'

**Comment by johanneskoester** [comment]
Thanks for reporting. Hopefully fixed with the referenced PR.
