### ISSUE TITLE
Touch with default-remote-prefix fails with missing files

### ISSUE THREAD

**Issue by ilyavs** [snakemake/snakemake#583]
**Snakemake version**
5.20.1
**Describe the bug**
I ran a workflow, then added additional output to some of the rules. I needed to run with --touch because after syncing to S3 something went wrong with the time stamps for parts of the workflow and it wanted to re-execute parts that were already complete. When running with --touch and --default-prefix snakemake complains about missing files. For example, benchmark files that were added to the workflow after it was already run. When running snakemake with --touch but without --default-remote-prefix it just skips the missing files and only touches the existing ones. I would have expected the same behavior with --default-remote-prefix.

**Comment by vsoch** [comment]
@ilyavs is this still an issue for you? We added a fix for missing files and using a remote prefix (issue #576) but I'm not sure if it would be different from using touch.

**Comment by ilyavs** [comment]
@vsoch I currently don't have a workflow to test this on. Feel free to close the issue. I will re-open if I encounter it again.

**Comment by vsoch** [comment]
Great, thanks @ilyavs !
