### ISSUE TITLE
ModuleNotFoundError: No module named 'pulp'

### ISSUE THREAD

**Issue by yangkky** [snakemake/snakemake#584]
**Snakemake version**
5.23.0

**Describe the bug**
After installing according to the [instructions](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html), I make a very simple Snakefile with one rule and try to execute the rule. It immediately fails with the error `ModuleNotFoundError: No module named 'pulp'`. 

**Logs**
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       download_pfam_hmm
        1
Traceback (most recent call last):
  File "/home/kevyan/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/__init__.py", line 709, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/kevyan/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/workflow.py", line 957, in execute
    success = scheduler.schedule()
  File "/home/kevyan/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/scheduler.py", line 402, in schedule
    else self.job_selector_ilp(needrun)
  File "/home/kevyan/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/scheduler.py", line 538, in job_selector_ilp
    import pulp
ModuleNotFoundError: No module named 'pulp'
```
**Minimal example**
This is the Snakefile: 

```
rule download_pfam_hmm:
    output:
        'raw/Pfam-A.hmm'
    shell:
        "wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz -O raw/Pfam-A.hmm.gz"
        "tar raw/Pfam-A.hmm.gz"
```
I run `snakemake -R download_pfam_hmm -j1` to reproduce the output above.

**Comment by FelixMoelder** [comment]
Thanks for reporting.
This is an issue with the new scheduler introduced in version 5.23.0.
I'll update the conda recipe to solve this.

**Comment by FelixMoelder** [comment]
The recipe has been updated and the error should not occure anymore.
To get this working please remove und reinstall your snakemake environment.

**Comment by yangkky** [comment]
That fixes it. Thanks!

**Comment by rababerladuseladim** [comment]
Unfortunately, build 2 is broken again :-(

I have the following versions installed:
  - snakemake=5.23.0=2
  - snakemake-minimal=5.23.0=py_1

Running snakemake crashes with a failed import of pulp :-(

log: 
```
Traceback (most recent call last):
  File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/__init__.py", line 631, in snakemake
    success = workflow.execute(
  File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/workflow.py", line 957, in execute
    success = scheduler.schedule()
  File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/scheduler.py", line 402, in schedule
    else self.job_selector_ilp(needrun)
  File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/scheduler.py", line 538, in job_selector_ilp
    import pulp
ModuleNotFoundError: No module named 'pulp'

```

**Comment by FelixMoelder** [comment]
> Unfortunately, build 2 is broken again :-(
> 
> I have the following versions installed:
> 
> * snakemake=5.23.0=2
> * snakemake-minimal=5.23.0=py_1
> 
> Running snakemake crashes with a failed import of pulp :-(
> 
> log:
> 
> ```
> Traceback (most recent call last):
>   File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/__init__.py", line 631, in snakemake
>     success = workflow.execute(
>   File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/workflow.py", line 957, in execute
>     success = scheduler.schedule()
>   File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/scheduler.py", line 402, in schedule
>     else self.job_selector_ilp(needrun)
>   File "..../miniconda3/envs/prophane-test/lib/python3.8/site-packages/snakemake/scheduler.py", line 538, in job_selector_ilp
>     import pulp
> ModuleNotFoundError: No module named 'pulp'
> ```

Could you try again?
I forgot to add pulp for snakemake-minimal and updated the recipe yesterday. So probably conda did not install the right version of snakemake-minimal which should be `snakemake-minimal=5.23.0=py_2`

**Comment by rababerladuseladim** [comment]
It works again, thanks!
