### ISSUE TITLE
google life sciences executor: log output is always empty

### ISSUE THREAD

**Issue by aryam7** [snakemake/snakemake#589]
**Snakemake version**
5.23.0

**Describe the bug**
When running Snakemake on the Google Life Sciences backend, logs specified via the `log` directive are always empty.

**Steps to reproduce**
Follow the [Google Life Sciences Executor Tutorial](https://snakemake.readthedocs.io/en/stable/executor_tutorial/google_lifesciences.html) but apply the following patch to create (and capture) `stdout` and `stderr` from `plot_quals.py`:
```
diff --git a/Snakefile b/Snakefile
index 68974d1..9cfee52 100644
--- a/Snakefile
+++ b/Snakefile
@@ -58,5 +58,6 @@ rule plot_quals:
         "plots/quals.svg"
     conda:
         "environment.yaml"
+    log: "logs/plot_quals.log"
     script:
         "plot-quals.py"
diff --git a/plot-quals.py b/plot-quals.py
index fe89694..36c2c9a 100755
--- a/plot-quals.py
+++ b/plot-quals.py
@@ -1,3 +1,4 @@
+import sys
 import matplotlib

 matplotlib.use("Agg")
@@ -7,4 +8,7 @@ from pysam import VariantFile
 quals = [record.qual for record in VariantFile(snakemake.input[0])]
 plt.hist(quals)

+print('put me in stderr!', file=sys.stderr)
+print('and put me in stdout!', file=sys.stdout)
+
 plt.savefig(snakemake.output[0])
```
After Snakemake is finished running, check the log output. It appears to be empty for me:
```
gsutil cat gs://snakemake-testing-data/logs/plot_quals.log
```

**Comment by aryam7** [comment]
see https://github.com/snakemake/snakemake/issues/457#issuecomment-681066466 for a potential workaround if you also have this problem

**Comment by johanneskoester** [comment]
Your code does not print the messages to the log file. It just prints to stderr and stdout. Snakemake does not by default write stderr and stdout into the logfile. This has to happen explicitly in the shell command or the script. Also see [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#log-files).

So, in your example, you could do something like
```
sys.stderr = open(snakemake.log[0], "w")
```

or alternatively
```
log = open(snakemake.log[0], "w")

print("my message", file=log)
```

**Comment by aryam7** [comment]
ah ok thanks! sorry about this!
