### ISSUE TITLE
Container behavior

### ISSUE THREAD

**Issue by nhartwic** [snakemake/snakemake#590]
I'm currently attempting to containerize Funannotate for a workflow. I'm getting very inconsistent behavior though, probably just because I don't understand how snakemake uses containers or something. Basically, I have a container at...

shub://nhartwic/salk-containers:fun 

...Container seems to be fine and I can run the following command and get reasonable output...

$ singularity run salk-containers_fun.sif which prefetch
/opt/conda/envs/myenv/bin/prefetch

...However, when I actually try to run the workflow, I get an error...

bash: prefetch: command not found

...Why would I be getting this error and how can I make this container work properly with snakemake?

Some other information, my run script in the container first activates a conda environment "myenv" then executes whatever command the user specifies. Clearly this run script isn't being used by snakemake or is being broken somehow. 

So I guess my real question is how to conveniently use conda to install software inside a singularity container and have that container work with snakemake. Failing that info, an explanation of how snakemake is actually using the containers would be great. Why doesn't the runscript get used?

**Comment by nhartwic** [comment]
For anyone finding this, snakemake seems to use "exec" to run containers. Wrapping a conda env in a singularity container is kind of a pain, but the following recipe works...

```
Bootstrap:docker
From:continuumio/miniconda3

%files
    some.conda.env.yml

%post
    # build our env
    . /opt/conda/etc/profile.d/conda.sh
    conda activate
    conda env create -f some.conda.env.yml -n myenv

    # add some lines to the environment shell script to activate conda
    echo '. /opt/conda/etc/profile.d/conda.sh' >> /.singularity.d/env/91-environment.sh
    echo 'conda activate myenv' >> /.singularity.d/env/91-environment.sh

    # dangerous wizardry below required to change from sh to bash for env sourcing
    rm /bin/sh
    ln -s /bin/bash /bin/sh

%runscript
    exec "$@"

```

Some notes...

1. This uses the standard conda tools for managing the environment so should generalize to any conda env
2. Writing directly to an env script feels dirty and potentionally likely to get depracated, but it works
3. We have to force the container to use bash instead of sh in order for conda to work. My current method feels dangerous, but it works.

For those who want to use dockerhub to host containers, the following template should work for any conda env with snakemake
```
FROM continuumio/miniconda3

# specify  environment yml:
COPY edta.yml environment.yml

# build provided env
RUN conda env create -f environment.yml -n myenv
RUN echo "source activate myenv" > ~/.bashrc

# force bash to be used instead of shell
run rm /bin/sh && ln -s /bin/bash /bin/sh

# build singularity dir structure to hopefully hack singularity functionality when relevant
run mkdir -p /.singularity.d/env
# run echo '#!/bin/bash' >> /.singularity.d/env/91-environment.sh
run echo '. /opt/conda/etc/profile.d/conda.sh' >> /.singularity.d/env/91-environment.sh
run echo 'conda activate myenv' >> /.singularity.d/env/91-environment.sh

# Make RUN commands use the new environment (for docker execution):
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]
```

...Similar notes as with the pure singularity version, only it feels even messier now because most of this recipe doesn't do anything unless singularity is used to wrap the docker container.

**Comment by sapoudel** [comment]
For me the issue would be fixed if we could somehow pass the prepend stuff from singularity to snakemake. For example, my singularity exec command works if I can run it with pretending the path to conda bin + passing a clean env:
`SINGULARITYENV_PREPEND_PATH=/opt/conda/bin singularity exec --cleanenv /home/spo/repos/wastewater-viral-id/.snakemake/singularity/968d29ff8a2795025ecade73014509f0.simg env`

But I can't figure out how to pass the `SINGULARITYENV_PREPEND_PATH` to singularity from snakemake.
