### ISSUE TITLE
GNU Parallel execution backend

### ISSUE THREAD

**Issue by sappjw** [snakemake/snakemake#60]
If a group of machines do not run a proper cluster backend (e.g., Slurm) and users do not have root access, [GNU Parallel](https://www.gnu.org/software/parallel/) is a good option.

It seems like an execution backend could be written to use [GNU Parallel as a batch manager](https://www.gnu.org/software/parallel/man.html#EXAMPLE:-GNU-Parallel-as-queue-system-batch-manager).  It could use a temp file writable only by the user running `snakemake` as a job queue.  

I don't see an alternative, unless there is a batch scheduler that can run as an unprivileged user (I'm not experienced with batch schedulers).

**Comment by johanneskoester** [comment]
Snakemake itself can parallelized local runs. Just run it with `snakemake --cores n` with `n` being the number of cores you want to use.

**Comment by johanneskoester** [comment]
I have changed the master branch to include a warning if --cores is not specified.

**Comment by sappjw** [comment]
Right, but not across multiple machines.  Parallel can distribute the workload to many machines over ssh, something Snakemake does not do.

**Comment by danijoo** [comment]
Is there any news on this. I think it would be very nice to be able to distribute workload across multiple machines that do not have a proper cluster engine. GNU Parallel would be a good option, but I think it could also be done using ssh/scp as toolchain.

**Comment by sappjw** [comment]
Thanks for the encouragement 😃
I've cobbled something together but it isn't good enough to make into a proper PR yet.  Using plain ssh/scp would require much of the functionality Parallel already has built in to be re-invented in Snakemake.

**Comment by danijoo** [comment]
You are absolutely right. It makes no sense to reimplement the wheel.
So If I understand you correctly, you are still working on this? If you want, I can also have a look in what you already have and maybe contribute to it.

**Comment by sappjw** [comment]
I'm still interested, but I haven't had time to make progress.  I would like to post my code so others can build on it.  The basic concept I was using is to use Parallel as a queue, prime with null jobs, then fill in the actual jobs.  There were some assumptions being made in order to keep the `snakemake` workflow transparent (i.e., the same with or without GNU Parallel), so it didn't require multiple steps as you've suggested.

**Comment by alexkeizer** [comment]
I'm curious if any progress has been made on this? I saw that snakemake now has some plugin-based architecture for executors, has anybody tried writing a GNU Parallel plugin for snakemake yet?
