### ISSUE TITLE
Release 5.23 breaks Python 3.5 compatibility 

### ISSUE THREAD

**Issue by davidnewman02** [snakemake/snakemake#600]
Python 3.5 goes officially out of all support as of 2020-09-13, so this may not be an issues that need to be addressed, but I had understood from that it was still intended to be supported at the present time (e.g. Changelog 5.20, explicitly restored support).

**Snakemake version**
5.23.0

**Describe the bug**
Release 5.23.0 includes some f-string syntax which breaks compatibility with python 3.5 for example in the Scheduler: https://github.com/snakemake/snakemake/blob/v5.23.0/snakemake/scheduler.py#L544

```
Traceback (most recent call last):
  File "venv/bin/snakemake", line 5, in <module>
    from snakemake import main
  File "venv/lib/python3.5/site-packages/snakemake/__init__.py", line 21, in <module>
    from snakemake.workflow import Workflow
  File "venv/lib/python3.5/site-packages/snakemake/workflow.py", line 34, in <module>
    from snakemake.scheduler import JobScheduler
  File "venv/lib/python3.5/site-packages/snakemake/scheduler.py", line 544
    f"job_{job}_{idx}", lowBound=0, upBound=1, cat=pulp.LpInteger
                     ^
SyntaxError: invalid syntax
```

**Comment by johanneskoester** [comment]
Good catch, thanks! I have fixed it in the master branch. We'll release a new version ASAP.
