### ISSUE TITLE
Google Cloud Executer does not recognize Snakefile specified by --snakefile properly

### ISSUE THREAD

**Issue by hnawar** [snakemake/snakemake#605]
**Snakemake version**
5.23

**Describe the bug**
When spcifying a snakefile with --snakefile and there is a file called Snakefile in the same folder, the file specified is ignored and the file named Snakefile is copied to the Cloud workers
**Logs**
If applicable, any terminal output to help explain your problem.

**Minimal example**
Add a minimal example for reproducing the bug.

**Additional context**
I had a folder with Snakefile and Snakefile2
I used snakemake --snakefile Snakefile2 but kept getting errors, when inspecting the logs, within the cloud VM Snakefile was being executed instead of the Snakefile2

**Comment by dcroote** [comment]
It looks like the function below may be responsible, but @vsoch will likely have more insight

https://github.com/snakemake/snakemake/blob/2b124753c659a0e8cee765113421f6883e919132/snakemake/executors/google_lifesciences.py#L577-L588

**Comment by vsoch** [comment]
Yep that function is based on the assumption that the snakefile *must* be defined in `SNAKEFILE_CHOICES` - it looks like the snakefile (or a custom one) is provided at self.workflow.snakefile so let's try using that. I'll open a PR shortly.

**Comment by vsoch** [comment]
Thanks for pinging me @dcroote ! I don't get notifications for all snakemake issues, so I didn't know about this. Please ping me right away next time there is any issue with the gls executor! Here is a PR to test for the current issue https://github.com/snakemake/snakemake/pull/618.
