### ISSUE TITLE
Question about snakemake installing requierer conda env

### ISSUE THREAD

**Issue by ALFLAG** [snakemake/snakemake#606]
Hello everyone.

I have a question. Imagine we have the following directory architecture
/home/alflag/dir1/dir1bis/

If I launch snakemake in dir1/, then all tools will be downloaded and installed in a .snakemake/ directory that is placed in dir1/ according to the environment conda files that are specified in the snakefile.

Now, I want to launch the same snakefile, but this time while I'm in dir1bis/ .
If I do that, then snakemake will again download and installed te requiered tools according to the conda environment files.
But if I had executed the same snakefile while being in dir1/ then the snakefile would have been executed without downloading and reinstalling the requiered conda tools, since the .snakemake/ directory was previously generated.

I would like to know if there is any way to tell snakemake where to find the .snakemake/ directory in order to avoid new downloads every time the snakefile is launched in a different directory.

Was I clear enough?

Thank you for your time.
Alex

**Comment by carissableker** [comment]
Caveat: Not a snakemake contributor. 

I think what you need is the `--conda-prefix` commandline argument. According to the [docs](https://snakemake.readthedocs.io/en/stable/executing/cli.html#CONDA): 

<table align="center">
    <tr>
        <td align="center"><code>--conda-prefix</code></td>
        <td align="left">Specify a directory in which the ‘conda’ and ‘conda-archive’ directories are created. These are used to store conda environments and their archives, respectively. If not supplied, the value is set to the ‘.snakemake’ directory relative to the invocation directory. If supplied, the <i>–use-conda </i> flag must also be set. The value may be given as a relative path, which will be extrapolated to the invocation directory, or as an absolute path.</td>
    </tr>
</table>

**Comment by ALFLAG** [comment]
Hi,

I forgot I asked this question...
Yes indeed, the argument you mentionned is the one I was looking for.
Thank you for your reply.

Alexandre
