### ISSUE TITLE
remote prefix for input and output files separately?

### ISSUE THREAD

**Issue by shukwong** [snakemake/snakemake#607]
The google life sciences option is wonderful and very easy to use. However, I don't seem to have figured out a way to specify input and output buckets separately. 

I would like to store the output of the workflow in a different bucket from the input bucket. It seems that --default-remote-prefix needs to be specified (otherwise I get an error) and cannot be an empty string (I tried "" and ''). 

I would like to either have an option to specify an empty string so that I can set the buckets for each input and output in the workflow; or have an option to specify input and output buckets separately, would that be possible?

**Comment by aryarm** [comment]
Hi @shukwong,
My understanding is that the default remote prefix won't be applied to inputs that are marked as remote files via [`GS.remote()`](https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html#google-cloud-storage-gs). I'm not sure if this approach also works for outputs, though.
If you'd like to request a new feature related to the Google Life Sciences backend, you should put it in #457.

**Comment by shukwong** [comment]
Thanks @aryarm! Your suggestion works very well indeed!
