### ISSUE TITLE
Tutorial not useable

### ISSUE THREAD

**Issue by alex4200** [snakemake/snakemake#613]
**Snakemake version**
https://snakemake.readthedocs.io/en/stable/tutorial/setup.html

**Describe the bug**
I have downloaded the miniconda file (50MB) and the tutorial file(7 MB), and when I tried to create the virtualenv it downloaded hundreds of packages _including python3.6_!  I am using already python 3.8! 

**Minimal example**
Follow the instructions on the 'tutorial'.

**Additional context**
I was looking for a small, easy to use tutorial on snakemake, not to download and to install an entire old operating system!

The tutorial seems very unusable to me. It should be fixed.

**Comment by johanneskoester** [comment]
The tutorial currently pins to an old version of Snakemake. This old version still requires Python 3.6, which is downloaded along with the rest of the required software via the conda commands in the tutorial setup. I agree that we should update that to a current release, which will then of course also work in combination with Python 3.8.

The old version does not render the tutorial unusable, but I understand your point. Thanks! I will update it ASAP.

**Comment by alex4200** [comment]
Thanks a lot!

I also did not mean to say the tutorial is completely not usable, I rather wanted to say that the **usability** of the tutorial is sub-efficient.

**Comment by johanneskoester** [comment]
All fine, I understood it like that. The current stable docs should have lifted those version constraints.
