### ISSUE TITLE
Dealing with incomplete output from cluster executors

### ISSUE THREAD

**Issue by percyfal** [snakemake/snakemake#627]
**Snakemake version**
5.24.0  (but I have tried multiple versions >=5)

**Describe the bug**
Failed cluster jobs leave incomplete output files, making snakemake think the job is complete

**Logs**

**Minimal example**
NB: this example needs to be run on a HPC that runs the slurm scheduler. Snakefile:
```
rule long_running_rule:
    output:
        "out.txt",
    shell:
        """
        for i in $(seq 1 300)
        do
            echo $i >> {output}
            sleep 1
        done
        """
```
status.py:
```
#!/usr/bin/env python3
import sys
import shlex
import subprocess as sp

sacct_res = "RUNNING"
status = "running"
jobid = sys.argv[4]

try:
    sacct_res = sp.check_output(shlex.split(f"sacct --format=\"state,jobid\" -P -j {jobid} -n")).split()[0].decode().split("|")[0]
except:
    pass
if sacct_res == "TIMEOUT":
    status = "failed"
print(status)
```
Run command 
```
snakemake out.txt  -j 1 --cluster "sbatch -A account_name -p devel -t 00:01:00 -n 1" --cluster-status ./status.py 
```
will leave an incomplete output file `out.txt` such that rerunning snakemake will result in "Nothing to be done".

**Additional context**

See also https://github.com/Snakemake-Profiles/slurm/issues/49 and https://github.com/snakemake/snakemake/issues/570

**Comment by percyfal** [comment]
Additional comment: I have solved the issue by adding a `job.cleanup()` statement (e.g. to [Job.postprocess](https://github.com/snakemake/snakemake/blob/07f73006dcee1e6ce6c271355fff83705f188de4/snakemake/jobs.py#L997) or [Persintence.cleanup](https://github.com/snakemake/snakemake/blob/07f73006dcee1e6ce6c271355fff83705f188de4/snakemake/persistence.py#L201)), but I'm reluctant to submit a PR as I'm uncertain which, if any, place would be the best to add it, or if some other solution is warranted.

**Comment by SultanOrazbayev** [comment]
A reliable way is to integrate touching an additional 'dummy' file, which is blank file whose only purpose is to signify that the job was completed, either explicitly within the shell/script or using `touch('job_done.txt')` in the rule outputs.

**Comment by sebschmi** [comment]
@SultanOrazbayev Is there a way to automatically add this `touch` directive to all rules, instead of doing it manually?

**Comment by SultanOrazbayev** [comment]
Hmm, I don't know of a way to do it automatically... but I'm not sure if that's needed. So in my workflow when I have cases where I have a risk of incomplete files, I put `open('somefile.txt', 'a').close()` at the end of the script and make sure that the rule contains `somefile.txt` as an expected output.

**Comment by sebschmi** [comment]
Okay thanks. I will do that until this pull request will hopefully get merged.

**Comment by SultanOrazbayev** [comment]
Great, this looks like a useful feature to have!
