### ISSUE TITLE
`--jobs` overrides `threads` set by rules

### ISSUE THREAD

**Issue by Asutu** [snakemake/snakemake#638]
**Snakemake version**
```
$ snakemake -v
5.25.0
```

**Describe the bug**
I have a working computer with 16 cores and usually try to set up rules, for which commands can take a number of processing cpus from some command line argument, to use 4 cores, using something like `threads: 4` in the rule. In these cases, I usually would like snakemake to run three (3) instances of that rule in parallel, thus using 12 cores in total, leaving 4 other available for the snakemake process itself and other stuff I might be doing on the background.

For example, in a rule I have the following, where `config['bwa']['cpu']` is 4:

```
threads:
	config['bwa']['cpu']
shell:
	"""
	bwa mem -t {threads} -R '{params.rg}' {params.other} {params.idx} {input.reads} > {output}
	"""
```

When this snakefile is run with `snakemake -j`, the shell process uses the `threads` as defined by the rule and snakemake prints `threads: 4` to the log (the wildcard in the shell is also exapanded to 4).

However, if I run with `snakemake -j 3`, the snakemake log now reads `threads: 3` for that same rule (and the wildcard in the shell is also exapanded to 3). It seems that by using `--cores [N], --jobs [N], -j [N]` snakemake restricts any `threads` directive in rules to N if `threads` > N. 

Wouldn't it be better to let `--cores [N], --jobs [N], -j [N]` control the _maximum_ number of jobs run in parallel (for example, conditional on the number in `threads` in each rule), instead of munging with the `threads`in rules? And now, I'm also a bit confused... because I don't know how to set my snakemake pipeline to do what I intended in the beginning, i.e. run 3 parallel rules each using 4 cores.

Thanks,
Pedro

**Comment by Maarten-vd-Sande** [comment]
Ideally this question should be asked on stackoverflow.

Take a look at the docs: https://snakemake.readthedocs.io/en/stable/executing/cli.html


> --cores, --jobs, -j
>     Use at most N CPU cores/jobs in parallel. If N is omitted or ‘all’, the limit is set to the number of available CPU cores.

So you should use --cores 16 (or --jobs 16), as they mean the same

**Comment by Asutu** [comment]
Great, in the case described above would be `-j 12`. I think I was confused between the maximum number of cores to use in parallel in a single run and the maximum number of "rules" that can run in parallel.

**Comment by Maarten-vd-Sande** [comment]
I agree that the naming is not that clear
