### ISSUE TITLE
Snakemake >= 5.26.0 launches jobs regardless of specified cores

### ISSUE THREAD

**Issue by alxsimon** [snakemake/snakemake#659]
I was previously on v5.19.2 due to issue #568 

After a few tests I found v5.26.0 and 5.26.1 solved this first one, great!

However I encountered another one. In my setting, snakemake launches all jobs at the same time without any limitation from the number of cores.

For example I have ten jobs running with 8 cores each. If I use `snakemake -j 8`, the scheduler launches all jobs at once and fills up all cores on my computer. Version 5.25.0 is working correctly in this regard and launches only one job at a time.

Running snakemake with `--use-singularity` and `--use-conda`.

**Comment by dcroote** [comment]
@alxsimon - Can you provide a minimal example demonstrating the issue? I was unable to reproduce the error you observed with snakemake v5.26.1, singularity v3.6.4, and the following:

*Snakefile*:
```python
samples = range(8)

rule all:
    input: expand('output-{i}', i=samples)

rule touch_output:
    output: 'output-{i}'
    container:
        'docker://continuumio/miniconda3:4.4.10'
    conda:
        'python.yaml'
    threads: 2
    shell:
        """
        sleep 30
        touch {output}
        """
```

*python.yaml*:
```yaml
dependencies:
  - python=3.8
```

*Command to execute*:
```bash
snakemake --version && snakemake -j 2 -r --verbose --use-conda --use-singularity
```

*Output*:
```
5.26.1
Building DAG of jobs...
Singularity image location: /home/derek/sm-jobs/.snakemake/singularity/a060bec98ea437bf9f05b082d8047ef0.simg
Using shell: /usr/bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        8       touch_output
        9
Resources before job selection: {'_cores': 2, '_nodes': 9223372036854775807}
Ready jobs (8):
        touch_output
        touch_output
        touch_output
        touch_output
        touch_output
        touch_output
        touch_output
        touch_output
Selected jobs (1):
        touch_output
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Thu Oct 22 22:29:11 2020]
rule touch_output:
    output: output-6
    jobid: 7
    reason: Missing output files: output-6
    wildcards: i=6
    threads: 2

<singularity exec commands were here>

Activating singularity image /home/derek/sm-jobs/.snakemake/singularity/a060bec98ea437bf9f05b082d8047ef0.simg
Activating conda environment: /home/derek/sm-jobs/.snakemake/conda/744cb370
[Thu Oct 22 22:29:46 2020]
Finished job 7.
1 of 9 steps (11%) done
```

And the workflow continued with a maximum of 1 job at a time, obeying the `-j 2` command line argument

**Comment by alxsimon** [comment]
Thank you very much for the reproducible example, I did not had time to create one myself.
The example do not cause any problems with versions 5.26.0 and 5.26.1 and I get the same output as you.

I need to try again my original pipeline as the issue must have come from another thing than Snakemake.
