### ISSUE TITLE
Unexpected behaviour for `ancient` flag in intermediate rules

### ISSUE THREAD

**Issue by pibis** [snakemake/snakemake#661]
**Snakemake version**
5.26.1

**Describe the bug**
The `ancient` flag has no effect if the flagged file is modified upstream in the workflow.

**Minimal example**
```
rule third:
    input:
        "b",
        "c"
    output: "d"
    shell: "touch {output}"

rule second:
    input: ancient("b")
    output: "c"
    shell: "touch {output}"

rule first:
    input: "a"
    output: "b"
    shell: "touch {output}"
```

I would have expected that the second rule will only be executed if `c` is missing, as the input is flagged as ancient.
Instead, the second rule will always run if the first rule updates `b`, the input of the second rule.
This seems to be in conflict with the [documentation](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#ignoring-timestamps) for ancient.

**Comment by mhulsman** [comment]
I can confirm this, I've also encountered this issue. I've opened a pull request with a fix.

**Comment by johanneskoester** [comment]
Hi folks, I want to inform you that I have reverted to the previous behavior and instead updated the docs. Not considering modification time of intermediate files was not what ancient was intended for. I have clarified  that in the docs. I think if we want that, we might need a different flag, but I cannot see the use case yet.

**Comment by mhulsman** [comment]
For me the use case is as follows:

I have fastq files on tape, which I retrieve to the staging area with a batch job (doing that file by file would be highly inefficient, as the tape has to be loaded and read again and again for each file).  

On finishing this batch job, i touch an indicator file to notify that the fastq files are present in the staging area (which allows the rest of the pipeline to start, i.e. the copying of each fastq file to online disk and processing them).  

However, after a while files in the staging area are automatically de-staged by the system. Also, in some situations I have to redo a few samples.  In these situations I have to rerun the staging-job (by removing the indicator file).  Unfortunately, snakemake then starts to rerun all dependent samples, which is really not necessary as the fastq files will not have changed content. 

So I mark the indicator file as 'ancient', which solves the problem.  

I dont mind if this is handled by another flag then 'ancient', but to be honest I dont see why this is necessary. Why would someone mark an input file as 'ancient' when it can actually change contents once it is recreated?

**Comment by johanneskoester** [comment]
Ok, understood. This makes somewhat sense. I'll reactivate it :-).

**Comment by johanneskoester** [comment]
Ok, behavior is now as desired here. Sorry for the noise :-).
