### ISSUE TITLE
bug in report for version 5.26.1

### ISSUE THREAD

**Issue by jbloom** [snakemake/snakemake#682]
For version 5.26.1, I get the following error sometimes when trying to build a report:
```
snakemake/report/__init__.py", line 295, in code
    return [
TypeError: 'NoneType' object is not iterable
```

The problem seems to be when the language cannot be identified, which leaves the variable `source` assigned to `None` in `RuleRecord.code`. In the past (version 5.25), this simply lead to a simple return of a string [as here](https://github.com/snakemake/snakemake/blob/v5.25.0/snakemake/report/__init__.py#L282). But now in version 5.26.1, it tries to build a return object by iterating over `source` (see [here](https://github.com/snakemake/snakemake/blob/v5.26.1/snakemake/report/__init__.py#L295-L298)), which causes an error as `source` is `None` and so is not iterable.

**Comment by johanneskoester** [comment]
Should be fixed in current master.

**Comment by johanneskoester** [comment]
A new release will come soon.
