### ISSUE TITLE
Running web request and heavy computing at same time

### ISSUE THREAD

**Issue by iquasere** [snakemake/snakemake#693]
**Is your feature request related to a problem? Please describe.**
I thought snakemake sees the computing necessity of tasks, and if they can be run simultaneously, will attemp to do so, dividing the resources as needed. I have, in my pipeline, two tasks that should be run at same time: a request using [UPIMAPI](https://anaconda.org/bioconda/upimapi) to retrieve information from UniProt - which takes a lot, because must respect the limits of the API, but takes little computation effort, and a functional annotation using [reCOGnizer](https://anaconda.org/bioconda/recognizer) - which is multithreaded, so computationally intensive.

**Describe the solution you'd like**
I would like for there to be a way both tasks can be run simultaneously, so UPIMAPI's requests can take their time while reCOGnizer works hard on those protein sequences.

**Describe alternatives you've considered**
I though snakemake did this by default, considering the cores not being used by UPIMAPI, and allocating them to reCOGnizer.

**Comment by nhartwic** [comment]
Can you show the snakemake spell you are using? And the Snakefile you are using? Snakemake definitely permits parallel execution of rules.

**Comment by iquasere** [comment]
This may have already been solved by setting ```threads``` information, since that is likely what snakemake uses to determine computation usage. Have not tested it yet, however. Now, the [Snakefile](https://github.com/iquasere/MOSCA/blob/master/workflow/Snakefile) already has that information explicit. Where max threads are now 1, there was no information before.

**Comment by nhartwic** [comment]
I can't predict behavior without knowing the actual snakemake command you are running. Seems like your snakefile is fine. If you aren't careful, you will set "-j" to be equal to "config['threads']". If you do, than any time a job uses "config["threads"]" threads, there will be no cores left to run any other job at the same time.

**Comment by iquasere** [comment]
Exactly, that was what I was always doing! xD Will have to test it now, to see if it working as intended

**Comment by iquasere** [comment]
Just remember to come back, tis working fine ^^
