### ISSUE TITLE
Support execution of Jupyter Notebooks using script directive

### ISSUE THREAD

**Issue by kpj** [snakemake/snakemake#70]
When writing pipelines which involve many visualizations and light data processing, I tend to implement the individual steps using Jupyter Notebooks and glue them together using Snakemake.
At the moment, I execute them manually using `nbconvert`. This is inconvenient and makes passing parameters difficult/impossible.

An elegant solution to this situation would be to allow Jupyter notebooks (`*.ipynb`) to be used via the script directive:
```
rule foo:
  input: 'data.csv'
  output: 'figure.pdf'
  script: 'CreateFigure.ipynb'
```

This was already discussed in a now stale [bitbucket issue](https://bitbucket.org/snakemake/snakemake/issues/529/support-running-from-ipython-notebooks), but no solution was proposed.
Other [efforts](https://github.com/nick-youngblut/snakemakeNB) exist, but seem outdated and not well integrated into Snakemake itself.
Taking a quick look at the [current Snakemake source](https://github.com/snakemake/snakemake/blob/cd0be446d310a3a6aa9a65bec563ef53d548d311/snakemake/script.py#L266) suggests that no implementation efforts have been started.

If this is a feature others would be interested in as well, I'd be very happy to contribute a PR.

edit: I started an implementation [here](https://github.com/kpj/snakemake/tree/jupyter_notebook_support).

**Comment by SultanOrazbayev** [comment]
Looks good, but maybe a `notebook` would be better instead of `script`.

**Comment by kpj** [comment]
@SultanOrazbayev: I feel like using `script` would fit the existing functionality better.

**Comment by sappjw** [comment]
I've implemented a wrapper for calling [papermill](https://papermill.readthedocs.io) from Snakemake.  This may be a cleaner way to do it out of the box.

**Comment by kpj** [comment]
@sappjw: Very cool! How do you handle passing parameters (more specifically, the `snakemake` object) to the notebook?

**Comment by sappjw** [comment]
The wrapper handles putting together the shell command, so it would suffer the same limitations as `papermill`.  No objects can get passed ([even using the Python API](https://github.com/jupyter/nbconvert/issues/1070#issuecomment-515798400)), just parameters.  I didn't think about the advantage of integrating notebook-running functionality into Snakemake is that you could pass objects to the notebook.

**Comment by kpj** [comment]
At the moment, passing objects is handled by pickling them (see e.g. [here](https://github.com/snakemake/snakemake/blob/5f57bc23edd41b39c0d3331a0acf9017b1644027/snakemake/script.py#L387)), and the notebook execution is handled [here](https://github.com/snakemake/snakemake/blob/5f57bc23edd41b39c0d3331a0acf9017b1644027/snakemake/notebook.py#L27).

It sounds interesting to see how the wrapper might improve the implementation.
