### ISSUE TITLE
pypi install requires python>=3.7

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#715]
**Snakemake version**
`5.27.*`

**Describe the bug**
Cannot install version 5.27 on `python<3.7`.

**Minimal example**
```
$ python -V
Python 3.5.9
$ pip install 'snakemake==5.27.*'
Collecting snakemake==5.27.*
  Using cached snakemake-5.27.3.tar.gz (246 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/michael/.pyenv/versions/3.5.9/envs/tmp_snakemake/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g840_80j/snakemake/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g840_80j/snakemake/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gn_89tny
         cwd: /tmp/pip-install-g840_80j/snakemake/
    Complete output (2 lines):
    At least Python 3.7 is required.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Add a minimal example for reproducing the bug.

**Additional context**
I can see from https://github.com/snakemake/snakemake/blob/a813ea96fcd546c63654f06ce67e429104e5ca5c/setup.py#L14-L16 that this seems to be deliberate.

That is fine of course, but **I have a very strong feeling that this should have been a major version bump** (sorry, I know I have complained about this in the past also).

Additionally, pypi lists the package as being compatible with Python version 3.5 or above (and so does the front page of the github repo - but this badge is getting that info from pypi).

**Comment by johanneskoester** [comment]
Hi Michael,
this was actually not intentional, it should still be python 3.5. During development, I thought at some point that we need to raise the minimum version to 3.7, but then I found a nice solution to avoid that. However, I forgot to fix the constraints again before releasing. I will release another patch release tomorrow, which will fix the version constraint.
