### ISSUE TITLE
Markdown cells in edited notebook have invalid "outputs"

### ISSUE THREAD

**Issue by justinfinkle** [snakemake/snakemake#718]
**Snakemake version**
`5.26.1`

**Describe the bug**
For notebooks that contain markdown cells, when loading a previously edited notebook `nbformat.validate` raises the error `Notebook JSON is invalid: Additional properties are not allowed ('outputs' was unexpected)`

**Logs**
```
[E 16:26:01.489 NotebookApp] Notebook JSON is invalid: Additional properties are not allowed ('outputs' was unexpected)

    Failed validating 'additionalProperties' in markdown_cell:

    On instance['cells'][5]:
    {'cell_type': 'markdown',
     'metadata': {},
     'outputs': ['...0 outputs...'],
     'source': '# Test markdown\n'
               '\n'}
```

**Minimal example**
Any markdown cell should do

**Additional context**
All cell outputs are set to an empty list when saving an edited notebook, which might be the source of the error:
https://github.com/snakemake/snakemake/blob/a16ed719fbee96f0119c663eaa13a46c24025d03/snakemake/notebook.py#L95

**Comment by Hoeze** [comment]
Same problem here :)
```[NbConvertApp] ERROR | Notebook JSON is invalid: Additional properties are not allowed ('id' was unexpected)

Failed validating 'additionalProperties' in code_cell:

On instance['cells'][0]:
{'cell_type': 'code',
 'execution_count': None,
 'id': 'waiting-sound',
 'metadata': {'tags': ['snakemake-job-properties']},
 'outputs': ['...0 outputs...'],
 'source': '\n'
           '######## snakemake preamble start (automatically inserted, do '
           'n...'}

```

**Comment by mbhall88** [comment]
Yeah, I'm also seeing it with `id` now also. It must be some weird environment mismatch or maybe a bug in the latest nbconvert (6.1.0)?
