### ISSUE TITLE
error during report generation for run rules

### ISSUE THREAD

**Issue by hunter-cameron** [snakemake/snakemake#741]
**Snakemake version**
5.27.4

**Describe the bug**
When trying to generate a report for workflows that have a "run" rule in them, I got a `TypeError: '<' not supported between instances of 'NoneType' and 'int'` error. This occurs because there is no start time recorded for run rules. 

I did some digging and it seems that run rules might be getting scheduled twice which clobbers the file snakemake uses to get the start time for the stats because one run finishes and cleans up the file and then the next run cannot read the start time (but this run writes the metadata). Since it cannot find the file, it becomes None in the metadata which, when compared to an integer, throws the error. I verified the double scheduling wasn't happening with shell directives, only with run.

However, I haven't been able to figure out where to fix this so I can't submit a merge request. 

**Logs**
```
user@:/analysis$ snakemake --cores 1 -pr --report test.html all
Building DAG of jobs...
Creating report...
Adding shell_rule.txt (0 MB).
Adding run_rule.txt (0 MB).
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 668, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.8/dist-packages/snakemake/workflow.py", line 816, in execute
    auto_report(dag, report, stylesheet=report_stylesheet)
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/__init__.py", line 758, in auto_report
    rec.starttime = min(rec.starttime, meta["starttime"])
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
**Minimal example**

Snakefile used:
```
rule shell_rule:
    """ A rule that runs a shell command """
    output: report("shell_rule.txt")
    shell:
        "touch {output}"

rule run_rule:
    """ A rule that runs a 'run' command """
    output: report("run_rule.txt")
    run:
        with open(output[0], 'w'):
            pass


rule all:
    input:
        rules.shell_rule.output,
        rules.run_rule.output
```

**Additional context**

**Comment by lparsons** [comment]
I'm running into the same issue with `5.27.4`

**Comment by lparsons** [comment]
Did not experience the error with `5.26.1`

**Comment by lparsons** [comment]
I believe the problem here is this change:
https://github.com/snakemake/snakemake/pull/663/files#diff-ea35c3ed2e47884b4280b7d8d7be5bcf8672ddf661fcbe0b1e2268f17de1e239L178-R225

@mhulsman Would you mind taking a look at this? If I change it back to use `_metadata_path` instead of `_incomplete_path`, then shell rules break in the report, but the run rules seem to work.

**Comment by lparsons** [comment]
Also, just a note, but it might be nice to create a test for this sort of thing. From what I can tell, the current test architecture does not seem to easily support running snakemake and then subsequently running it again to generate the report using the generated metadata from the previous run. I'd be happy to take a stab at it, but any suggestions on how best to approach this would be welcome.

**Comment by mbhall88** [comment]
I am also seeing this on v5.30.1. I have no `run` directives though, so I think it is a more general issue.
