### ISSUE TITLE
Broken link to source code in documentation

### ISSUE THREAD

**Issue by sappjw** [snakemake/snakemake#75]
There's at least one broken link (to source code) in the documentation: https://snakemake.readthedocs.io/en/stable/project_info/contributing.html#contributing-a-new-cluster-or-cloud-execution-backend.

Instead of https://github.com/snakemake/snakemake/src/master/snakemake/executors.py it looks like the target should be https://github.com/snakemake/snakemake/tree/master/snakemake/executors.py.

**Comment by johanneskoester** [comment]
Thank you! Fixed in the master branch.
