### ISSUE TITLE
Set rule name via variable

### ISSUE THREAD

**Issue by Hoeze** [snakemake/snakemake#754]
Hi, is there a way to specify rule names via some variable?

An example where this would be useful:
```python
(cfg_files, ) = glob_wildcards(SNAKEMAKE_DIR + "/config/{file}")
for file in cfg_files:
    rule:
      input: f"{SNAKEMAKE_DIR}/config/{file}"
      output: f"{OUTPUT_DIR}/{file}"
      priority: 50
      shell:
          "cp {input} {output}"
```
Here, the rules' names are just ascending numbers.

**Comment by nhartwic** [comment]
I Seems like that situation could be handled with wildcards pretty easily...

```
import os

rule do_all:
    input:
        [f"{OUTPUT_DIR}/{f}" for f in os.listdir(f"{SNAKEMAKE_DIR}/config/")]  

rule:
    input: f"{SNAKEMAKE_DIR}/config/{{file}}"
    output: f"{OUTPUT_DIR}/{{file}}"
    shell: "cp {input} {output}"
```

**Comment by Hoeze** [comment]
@nhartwic I specifically needed one rule per file here, because I had multiple rules generating possibly the same wildcards.
The alternative would have been here to setup `wildcard_constraints` like `file="|".join(cfg_files)` but this looked to me like an ugly hack.

This is also only an example. I often see the case where I'd like to set rule names, e.g. when defining them inside for loops.
In those cases, it is not possible to define for example rule orders, since the rule names are not known beforehand.

**Comment by nhartwic** [comment]
Can you elaborate on such an example? As is the example provided can be implemented using wildcards very easily

**Comment by Hoeze** [comment]
@nhartwic It's mainly a code generation issue.

I do have scripts that can take different input files, e.g. like different sets of input features when training a model.
Further, I want to be able to change certain parameters for the rules like cutoffs for filters.

Instead of copy-pasting the snakemake rule `<Nr. of configurations>` times, I wanted to store the configurations inside `.yaml` files.
Also, some of the configurations should be generated automatically, because I do not want to copy the config files 100x for slightly different cutoff values.

So in theory, I create an input function that reads the yaml files and adjusts the rule's input accordingly.
In practice, this fails as soon as there is no corresponding yaml file, even if it could be generated by a different rule beforehand.

My solution for now was a hacky way with `checkpoint` rules, but this requires to always run `snakemake` multiple times until all configuration files are correctly generated.
A much better solution would be to **generate a set of (very similarly named) rules** that very specifically define what files they can generate with which input.

This works when I do not give rule names manually, since snakemake then just numerates them.
However, there is no way to get some rule handle to say `use rule 1 that provides hand-coded configuration preferred over rule 2 that automatically generates it`.

**Comment by nhartwic** [comment]
I still don't think I understand the issue, but I'll take your word for it that its a problem. Here is some magic for you in any case. You can programmatically set rule names inside a for loop...

```
rule all:
    input:
        [f"something.{i}.txt" for i in range(10)]


for i in range(10):
    rule:
        output:
            [f"something.{i}.txt"]
        shell:
            "touch {output}"

    list(workflow.rules)[-1].name = f"rule_{i}"

```

This works. I find it hideous. It is undocumented behavior so could in principle break at some point but I doubt it ever does.

Mostly, I'm still skeptical that programmatically generating rules is ever a good design choice.

**Comment by Hoeze** [comment]
@nhartwic I accidentally stumbled over such a use case:
https://stackoverflow.com/questions/48993241/varying-known-number-of-outputs-in-snakemake

Here, @johanneskoester actually recommended using `rule:` in a for loop.
However, as soon as you have a for loop it's not possible to use rule names any more.
The only solution to name the rules properly is your `fix_name` method then.

**Comment by pvandyken** [comment]
Closing as this issue is stale and the requested feature has reasonable work-arounds. Please continue the discussion if anything remains unresolved.
