### ISSUE TITLE
Temp() and possible Pipe() not working on Google Cloud

### ISSUE THREAD

**Issue by cademirch** [snakemake/snakemake#755]
**Snakemake version**
5.25.0

**Describe the bug**
Output files flagged with temp() or pipe() are uploaded to remote bucket.

**Logs**
N/a

**Minimal example**
I have an alignment rule which produces a BAM file which I mark with pipe(). The piped BAM is input for a SAMtools rule that filters it and outputs a final filtered BAM. Both the filtered and original BAM are uploaded to my bucket. Even making the original BAM a temp() file results in it being uploaded to the remote bucket.

**Comment by ricardovialle** [comment]
Hi, I'm having the same issue.  
Was this fixed somehow?

**Comment by cademirch** [comment]
> Hi, I'm having the same issue.  
> 
> Was this fixed somehow? 

I don't think so. I think using the group directive when defining a rule is probably the right way to  achieve what pipe does. This will put all of a groups jobs in one instance. 

Temp() is actually mutually exclusive with remote() files. A solution I and others have used is a cleanup script that runs at the end of our workflow to delete intermediate files in our bucket to avoid unnecessary costs.
