### ISSUE TITLE
self.workflow.default_remote_provider reference not relevant for single workflow

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#76]
Hey @johanneskoester this is a question for you since the git blame references you for doing this change yesterday! In this section:

https://github.com/snakemake/snakemake/blob/0d3da7235d0e23401a4d7a60089d0a228558258a/snakemake/workflow.py#L319-L328

the check for the remote provider checks `self.workflow.default_remote_provider.remote(path)` and this doesn't make sense given that the default_remote_provider parameter is a part of the workflow instance (e.g., it should be `self.default_remote_provider.remote(path)`. I think this might work, however, if there is a subworkflow that holds a workflow. I'm testing now for the addition I'm working on, and it seems to work correctly given the case of no subworkflow, so I'm wondering if this should:

  1. use self.default_remote_provider globally,
  2. check for the workflow attribute (a subworkflow) and if it exists, use it instead
  3. Some other logic?

is there any case of doing some sort of further nesting (e.g., can subworkflows have subworkflows?) For now I'll change it to be  1. until further discussion.

**Comment by vsoch** [comment]
Also I found a fantastic way to develop and test! You can do:

```python
import code
code.interact(local=locals())
```
and then jump right into an interactive terminal! After I make a tweak and want to test again it gets me back very quickly to where I want to be!

**Comment by johanneskoester** [comment]
Thanks, this was a copy-paste error from some refactoring. I am indeed suprised that it did not lead to a failing test case for default_remote_provider.
