### ISSUE TITLE
Systemwide availability of workflow

### ISSUE THREAD

**Issue by gonzalobenegas** [snakemake/snakemake#761]
As per the "Distribution and Reproducibility" section of the docs, deployment to a new system requires git cloning a repo.
This can be awkward, especially if the user wants to run the workflow in multiple directories in a system (possibly in a programmatic manner).
An alternative I envision could look like something like this, where the workflow is available systemwide (like a regular software package):
```
$ pip install my_workflow
$ cd any/path
$ snakemake -s pip:my_workflow
```
Would it make sense?

**Comment by nhartwic** [comment]
Couldn't this be easily done by adding a bash or python script to your repo that automates setting "--snakefile" and "--directory"?

**Comment by gonzalobenegas** [comment]
Thank you, I manage to get it to work using your approach!

**Comment by nhartwic** [comment]
Maybe consider making your repo public and doing a post on stackoverflow tagging snakemake to make it easier for people to find your solution in the future? No pressure of course.
