### ISSUE TITLE
Python3.5 support broken

### ISSUE THREAD

**Issue by giesselmann** [snakemake/snakemake#77]
**Snakemake version**
Version 5.7.4

**Describe the bug**
Current versions of snakemake are no longer python 3.5 compatible due to the f'' formatting of strings (PEP 498)

**Logs**
SyntaxError: invalid syntax
(snakemake_35) user@server:temp> snakemake --version
...
from snakemake.dag import DAG
File "~/virtual/snakemake_35/lib/python3.5/site-packages/snakemake/dag.py", line 1665
f'<td align="left"><font face="monospace">{in_file}</font></td>'

**Minimal example**
Add a minimal example for reproducing the bug.
snakemake --version

**Additional context**
none

**Comment by johanneskoester** [comment]
Thanks for reporting! Should be fixed in master.
