### ISSUE TITLE
Snakemake version 5.7.0 throws error for symbolic links

### ISSUE THREAD

**Issue by alping** [snakemake/snakemake#8]
**Snakemake version**
5.7.0

**Describe the bug**
When I updated to the latest Snakemake version (5.7.0) and ran snakemake with my workflow rules I got an error referring to symlinks not being available on my platform (which is Windows). My data folder (which is used for both input and output in my rules) is symlinked to a remote drive, which I guess trips up this version of Snakemake.

Previous versions of Snakemake still work, so I downgraded to 5.6.0 for now.

I couldn't find this documented anywhere.

**Logs**
```
NotImplementedError: access: follow_symlinks unavailable on this platform
```

**Additional context**
Snakemake installed via pip within an Anaconda environment on Windows.

**Comment by johanneskoester** [comment]
Fixed in the master branch. Thanks!

**Comment by alping** [comment]
Amazingly fast, thanks!
And thank you for your work on Snakemake; it has become an indispensable tool for my work.
