### ISSUE TITLE
checkpoint: cleanup-metadata does not work

### ISSUE THREAD

**Issue by nick-youngblut** [snakemake/snakemake#828]
I'm running snakemake v5.31.1 on Ubuntu 18.04.5, and I'm using 1 checkpoint in my pipeline. I don't know if the checkpoint is causing the issue, but I haven't run into this problem with pipelines that don't use a checkpoint. 

The pipeline completed, except for the last file-aggregation step. When I tried to re-run the pipeline to complete the aggregation, I got the error:

```
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/42/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/44/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/46/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/63/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/64/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/71/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/97/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/106/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/112/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/125/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/131/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/155/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/156/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/34/2/blastn.txt
```

According to the snakemake log, the jobs that generated these files completed successfully, and the downstream jobs that use these files also completed successfully. These files are marked via `temp()`, but I used `--notemp`, which is why they persisted. 

Running `snakemake -j 1  --cleanup-metadata /ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/42/blastn.txt` completes successfully, but does not get rid of the error shown above. The same goes if I run it on the other problematic files individually or altogether. 

It appears I now have to re-run a good chunk of the pipeline via `--rerun-incomplete`, which will require a lot of computation and is completely unnecessary, given the downstream files are available. 

I haven't been able to produce a small reproducible example, but this would be pretty hard to reproduce, given that it requires jobs to fail, and snakemake to think that some of the intermediate files are incomplete. 

More generally: I'm finding the use of `checkpoint` to make snakemake pipelines highly unreliable. I've run into a number of semi-reproducible issues, and based on other issues posted, it seems that many other users are as well.

**Comment by nick-youngblut** [comment]
If I use the `--rerun-incomplete` param, the pipeline shows the 2 aggregation jobs:

```
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	clusters_concat_info
	1	primers_concat_info
```

...and starts executing both jobs, but then both jobs die, each with the same `IncompleteFilesException:` error:

```
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/42/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/44/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/46/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/63/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/64/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/71/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/97/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/106/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/112/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/125/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/131/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/155/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/28/156/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/34/2/blastn.txt
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with
```

After deleting these problematic files, I re-ran snakemake with `--rerun-incomplete`, and the pipeline finally completed successfully.

**Comment by nick-youngblut** [comment]
I have 2 checkpoint rules that run locally at the end of the pipeline:

```
localrule primers_concat_info:
localrule clusters_concat_info:
```

Both generate errors such as the following when they run:

```
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/9/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/42/blastn.txt
/ebio/abt3_scratch/nyoungblut/LLPRIMER_101310211274/primers_nontarget_blastn/56/blastn.txt
[...]
```

...which are not even the input files used for these final two rules in the pipeline. Even when using `--rerun-incomplete`, the pipeline will not finish. I keep getting the same `To re-generate the files rerun` errors. 

Therefore `--rerun-incomplete` is not working as it should be. Also, `snakemake --cleanup-metadata <filenames>` does not work in situation.

snakemake 5.31.1; Ubuntu 18.04.5

**Comment by nick-youngblut** [comment]
This seems to be fixed with v5.32.0. Thanks!

**Comment by dluecking** [comment]
Hi everyone,

I'm running into a similar problem: I provided some input files instead of letting the pipeline compute them (there are cases where this is better) and snakemake throws the incomompleteFilesException:
```
(sm) [15:46:32] ~/projects/mvome_pipeline/mv_signals $ snakemake -npr -j 24 --use-conda --conda-frontend mamba 
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
results/TARA_111_5/contigs/virome.contigs.fasta
```
If I run `snakemake -j 1 --cleanup-metadata results/TARA_111_5/contigs/virome.contigs.fasta` the error is persists. Running `touch -a  results/TARA_111_5/contigs/virome.contigs.fasta` as suggested in [this google group](https://groups.google.com/g/snakemake/c/m0xYrdHGw2M) does not help. 
I've also tried adding an "ancient(<file>)" for that specific file, still the same error.

Snakemake version: 6.15.3

Anything that I'm missing or is this just the same bug again?

**Comment by VGalata** [comment]
I have the same problem with the `snakemake` version `6.15.1`.

I had to run the workflow on another server (because of some file system issues on the initial server) and `rsync`ed new files back. But, `snakemake` wants to re-create these files and using `--cleanup-metadata` does not solve the issue.

**Comment by ning-y** [comment]
It seems this GitHub issue will remain closed. I have created a new one at #1497, since the problem appears to persist for others, in newer versions of Snakemake.

An appropriate solution for some might be to manually delete the `.snakemake/incomplete` directory.
