### ISSUE TITLE
Is it possible to use Docker instead of singularity 

### ISSUE THREAD

**Issue by dongzhang0725** [snakemake/snakemake#846]
**Is your feature request related to a problem? Please describe.**
I like to use Docker, but can't use it in snakemake, when I use --use-singularity, I get: "The singularity command has to be available in order to use singularity integration." I have tried to use docker with "-d" parameter using shell command, however I got  the following error:
```
Job Missing files after 5 seconds:
BUSCO/NextDenovo/short_summary_busco3.txt 
...........
Job id: 6 completed successfully, but some output files are missing. 6
```
I checked the tasks' status using `docker ps`, the BUSCO analysis was still running, but snakemake thought it was finished without output files.

**Describe the solution you'd like**
Support `docker` in snakemake like `singularity`.

**Comment by epruesse** [comment]
I would not recommend doing this. Using Docker in this context has only disadvantages, some quite severe:

 -  Docker must be installed with administrator privileges and every user allowed to launch containers effectively has administrator privileges as well. Installing Singularity is trivial and even possible as unprivileged user.
 
 - Docker requires you to "map" the folders inside and outside the container by hand (all those `-v` statements you see usually), while Singularity will (by default) always map your entire home directory and a few other things, so it looks like its the same file system.
 
 - Docker will, by default, run things as root (it's up to the container to drop those privileges). So output files created will typically be owned by root, which is inconvenient, and everything you map into the container can be edited by it (deleted by accident, etc). Singularity will run things inside the container with your user ID, so with your privileges. 

This isn't by accident. Singularity was created explicitly to address the problems with Docker when all we want is a 100% self-contained software image, not a whole "micro server".

**Comment by dongzhang0725** [comment]
Dear @epruesse ,

Thank you for your answer, now I understand the limitations of docker. I will learn Singularity then, hope it is not different much from Docker.

Sincerely,

Dong

**Comment by epruesse** [comment]
Almost same command line. Tries to be drop in replacement. Just need to use "docker://" as prefix for containers from docker hub.

**Comment by dongzhang0725** [comment]
Thank you, I get it, can't wait to give it a try.

**Comment by dongzhang0725** [comment]
Dear@epruesse , 

I tried singularity today, however, I get a permission error, below is the procedure that I use singularity:

First, I build the image from docker hub:
```singularity build busco3.1.simg docker://comics/busco:3.0.2```

Then I add singularity to the rule:
```
rule BUSCO_simg:
    input:
        contig = "cintigs.fasta",
        busco_db = config["busco_db"]
    output:
        "run_{output_name}/short_summary_{output_name}.txt"
    params:
        mode = "geno",  # genome, proteins, transcriptome
    log:
        "run_{output_name}/{output_name}_busco_log.txt"
    container:
        "busco3.simg"
    shell:
        "run_BUSCO.py -i {input.contig} -o {wildcards.output_name} -m {params.mode} -l {input.busco_db} -c 1 -f &> {log}"
```
I use `snakemake -s Snakefile.rule -p --use-singularity` to run snakemake, but get the following error:
```
INFO	****************** Start a BUSCO 3.0.2 analysis, current time: 01/21/2021 17:34:19 ******************
INFO	Configuration loaded from /software/applications/busco/3.0.2/scripts/../config/config.ini
INFO	Init tools...
INFO	Check dependencies...
ERROR	Cannot write to Augustus config path, please make sure you have write permissions to /software/applications/augustus/3.2.2/config/
ERROR	BUSCO analysis failed !
ERROR	Check the logs, read the user guide, if you still need technical support, then please contact mailto:support@orthodb.org
```

The same parameters can run normally using docker . The difference is that docker run the image as root, whereas singularity run it as non-root, so it causes permission error. Do you have any suggestions for such error?

Thank you for your kindly help,

Sincerely,

Dong

**Comment by epruesse** [comment]
This is beyond snakemake now, I think. Try to run the command line manually, without snakemake. You will likely see the same error. That means it's a problem either in busco itself or, more likely, the docker image `comics/busco` you are using. Try using the official image instead, or just install the thing via bioconda.

**Comment by dongzhang0725** [comment]
Dear @epruesse ,

I tried to run `busco` without snakemake using singularity, it indeed get the same error. But it can be run with docker normally, which is run as root user. I am not sure if there is a similar way to run singularity container with root, I searched, but didn't find yet. I will try to install `busco` using conda or source code.

Thank you for your reply!

Dong
