### ISSUE TITLE
Use params and/or job properties in touch command

### ISSUE THREAD

**Issue by powelleric** [snakemake/snakemake#87]
It would be great if I could do:

```
rule myrule
    params:
        a="hello"
    output:
        touch("{params.a}.done")

Or even better:
```
    output:
        touch("{jobproperties.rulename}.done")
```

**Comment by SultanOrazbayev** [comment]
Hmm, could you give some further guidance? The fact that output depends on the same-rule parameter makes it odd (params appear to be fixed?).

Would splitting it into two rules work?:
```
rule myrule:
   output: touch('{key}.done'}

rule loop_params:
   input: expand('{key}.done', key=param_list)
```

**Comment by powelleric** [comment]
Thank you for your help on this.  I am honestly not sure what I was even attempting.  Probably I was just misunderstanding snakemake existing functionality.
