### ISSUE TITLE
Pass --cluster-status by environment

### ISSUE THREAD

**Issue by Phhere** [snakemake/snakemake#891]
**Is your feature request related to a problem? Please describe.**
Especially new users to not know that --cluster-status may be required on an hpc system to correctly track job states. It would be nice t have an option to set this as site administrator.

**Describe the solution you'd like**
Maybe it would be possible to pass SNAKEMAKE_CLUSTER_STATUS as environment to set this parameter

**Describe alternatives you've considered**
Any other solution to set the parameter as site administator is good.

**Additional context**
Most Schedulers need a --cluster-status script to correctly handle jobs states and it would be nice to have a system option to pass this script.

**Comment by phspo** [comment]
would be a very helpful feature, i often have issues tracking timeouts on HPC systems with snakemake

**Comment by LukeLR** [comment]
Should be fixed by #893.
