### ISSUE TITLE
Python 3.5 compatibility - Paths

### ISSUE THREAD

**Issue by mbhall88** [snakemake/snakemake#910]
**Snakemake version**
6.0.5

**Describe the bug**

Snakemake isn't currently compatible with python version 3.5. Whilst I had thought #898 had solved this problem, it turns out there is more to it. [`open()`](https://docs.python.org/3/library/functions.html#open) only added support for `os.PathLike` objects in python 3.6. So all uses of `pathlib.Path` objects in `open()` calls are causing the version incompatibility. I list a couple of examples, but these aren't all of the cases.

https://github.com/snakemake/snakemake/blob/f55801bfabfb916f77fa4ec8f9eb0667e5c8a92e/snakemake/persistence.py#L113

https://github.com/snakemake/snakemake/blob/f55801bfabfb916f77fa4ec8f9eb0667e5c8a92e/snakemake/unit_tests/__init__.py#L50

Would you like me to try and fix all of these and add python 3.5 to the CI - or do you want to remove python 3.5 support?

**Comment by johanneskoester** [comment]
Closing as suggested by @jdblischak since Snakemake requires Python 3.7 now.
