### ISSUE TITLE
[help] merging all inputs into one output 

### ISSUE THREAD

**Issue by mewu3** [snakemake/snakemake#917]
Dear all, 
I am aware that this question has been asked by others, yet I need to pose it once more because I have a different situation. 
Here you could find all the written scripts: https://github.com/mewu3/stage_m2/tree/dev, this is a working project for primer design. The basic idea is to split an MSA file into overlapping segments where kmer are counted, after calculate some basic primer parameters. I need to aggregate multiples files into one single output.  
Things went well till I tried to merge files: 
```
rule reverse_add_LC:
    input:
        datadir + "/{sample}/filtering/reverse{seg}.nessieOut",
        datadir + "/{sample}/filtering/reverse{seg}.fa"
    output:
        datadir + "/{sample}/filtering/reverse{seg}.calculated2"
    run:
        input2 = open(input[1], "r")
        outputFile = open(output[0], "w")

        dict_id_lc = {}

        with open(input[0], "r") as input1 :
            next(input1)
            for li1 in input1:
                li1 = li1.rstrip("\n")
                if li1.startswith(">"):
                    id = li1.split("|")[0].lstrip(">")
                    dict_id_lc[id] = 0
                else:
                    LC = float(li1.split(":")[1])
                    dict_id_lc[id] = LC

        ### write to fasta format
        # for li2 in input2:
        #     li2 = li2.rstrip("\n")
        #     seq = ""
        #     newHeader = ""
        #     if li2.startswith(">"):
        #         header2 = li2
        #         id_ = li2.split("|")[0].lstrip(">")
        #         for id in dict_id_lc:
        #             if id_ == id :
        #                 newHeader = "{} |LC {:.3f}".format(header2, dict_id_lc[id])
        #                 outputFile.write(newHeader+"\n")
        #     else:
        #         seq = li2
        #         outputFile.write(seq + "\n")

        ### write to tsv format
        outputFile.write("position\tkmerCount\tCG%\tTm\thomodimer-dG\thairpin-dG\tLC\toligo\n")
        for li2 in input2:
            li2 = li2.rstrip("\n")
            if li2.startswith(">"):
                ls = li2.split("|")
                id_ = ls[0].lstrip(">")
                position = ls[1].split()[1]
                count = ls[2].split()[1]
                cg = ls[3].split()[1]
                tm = ls[4].split()[1]
                homodimer_dG = ls[5].split()[1]
                hairpin_dG = ls[6].split()[1]
                outputFile.write("{}\t{}\t{}\t{}\t{}\t{}\t".format(position, count, cg, tm, homodimer_dG, hairpin_dG))
                for id in dict_id_lc:
                    if id_ == id :
                        lc = float(dict_id_lc[id_])
                        outputFile.write("{:.3f}\t".format(lc))
            else:
                seq = li2
                outputFile.write("{}\n".format(seq))

def aggregate_reverseInput(wildcards):
    checkpoint_output = datadir + "/{sample}/filtering/"
    return expand(datadir + "/{sample}/filtering/reverse{seg}.calculated2",
                  sample = wildcards.sample,
                  seg = glob_wildcards(os.path.join(checkpoint_output, "reverse{seg}.calculated2")).seg)

rule aggregate_allReverseOligo:
    input:
        aggregate_reverseInput
    output:
        datadir + "/{sample}/filtering/allOligos_reverse.calculated2"
    shell:
        """
        echo -e "position\tkmerCount\tCG%\tTm\thomodimer-dG\thairpin-dG\tLC\tkmer" > {output}
        """
        """
        sed -s 1d {input} >> {output}
        """
```
```        
        dynamic(
            expand(
                datadir + "/{sample}/filtering/reverse{seg}.calculated2",
                sample = samples,
                seg="{seg}"
            )
        ),
        # expand(
        #     datadir + "/{sample}/filtering/allOligos_reverse.calculated2",
        #     sample = samples,
        # ),
```

error message: 
```
Job Missing files after 5 seconds:
/datater/wu/data/{sample}/splitFiles/forward{seg}.fasta
/datater/wu/data/{sample}/splitFiles/reverse{seg}.fasta
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 0 completed successfully, but some output files are missing. 0
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 583, in handle_job_success
  File "/datater/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 252, in handle_job_success
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
```

I have no idea how to get this over, please do offer some help kindly. 

Best regards, 
mewu3

**Comment by SichongP** [comment]
It doesn't seem that your output file is closed. Depending on implementation, changes to files may take a long time to reach target files, or may not happen at all, without explicitly closing file handle. Can you try adding `outputFile.close()` to the end?

**Comment by mewu3** [comment]
> It doesn't seem that your output file is closed. Depending on implementation, changes to files may take a long time to reach target files, or may not happen at all, without explicitly closing file handle. Can you try adding `outputFile.close()` to the end?

Thank you for your comment :D 
That is actually a very good point, yet the problem persists after fixing that. I still get the same error message.

**Comment by SichongP** [comment]
Can you find the output file? If so, have you tried increase `latency-wait` to 60 or 120?

**Comment by mewu3** [comment]
without command the following lines, nothing could be found except the split fasta files. 
```
        expand(
            datadir + "/{sample}/filtering/allOligos_reverse.calculated2",
            sample = samples,
        ),
```
`latency-wait` option upto 120 does not solve the problem either

**Comment by SichongP** [comment]
Ok sorry I just noticed the missing file names in your error message. Those ({sample}/splitFiles/*) don't seem to match input in any rules you put here ({sample}/fltering/*)? Can you post the rules with this input?

What's also odd is the wildcards are not expanded in the error message, which suggests a wildcard issue to me.

**Comment by mewu3** [comment]
> Ok sorry I just noticed the missing file names in your error message. Those ({sample}/splitFiles/*) don't seem to match input in any rules you put here ({sample}/fltering/*)? Can you post the rules with this input/output?
> 
> What's also odd is the wildcards are not expanded in the error message, which suggests a wildcard issue to me.

the wildcards come from here the rule splitFiles. 

```
rule splitFiles: # split MSA fasta file into seperates files #########
    input:
        datadir + "/msa/{sample}.msa"
    output:
        dynamic(datadir + "/{sample}/splitFiles/forward{seg}.fasta"),
        dynamic(datadir + "/{sample}/splitFiles/reverse{seg}.fasta")
    params:
        step = config["step"],
        overlap = config["overlap"]
    run:
        #!/usr/bin/env python3.8
        from pyfaidx import Fasta

        inputFile = input[0]
        step = params.step
        overlap = params.overlap

        fasta = Fasta(inputFile)
        seqLength = len(fasta[0])

        remainder = seqLength % (step-overlap)
        chunkNumber = int(seqLength / (step-overlap))
        print("The sequences are splitted into "+str(chunkNumber)+" chunks, and there are "+str(remainder)+" bp left.")

        if remainder <= step/2: # primux fasta_tile_overlap.pl
            newStep = int(remainder/chunkNumber) + 1 + step
            print("Changing step size from {} to {} so there will be no remainder.".format(step, newStep))

        chunks = [[i,i+newStep] for i in range(0, seqLength, newStep-overlap)]
        chunks[-1][1] = len(fasta[0])

        for chunk in chunks:

            seg = str(chunk[0])+"-"+str(chunk[1])

            f1 = open(datadir + "/" + wildcards.sample + "/splitFiles/forward{}.fasta".format(seg), "w")
            f2 = open(datadir + "/" + wildcards.sample + "/splitFiles/reverse{}.fasta".format(seg), "w")

            for id in fasta.keys() :
                segment = fasta[id][chunk[0]:chunk[1]]
                forward = str(segment[:50])
                reverse = str(segment[-50:])
                f1.write("> {} |{}-{} \n {} \n".format(fasta[id].long_name, str(chunk[0]), str(chunk[1]), forward))
                f2.write("> {} |{}-{} \n {} \n".format(fasta[id].long_name, str(chunk[0]), str(chunk[1]), reverse))

            f1.close()
            f2.close()
```
![image](https://user-images.githubusercontent.com/60400481/111179760-aa1f9e00-85ac-11eb-8c67-f35a8f616d12.png)

the wildcards work fine before merging thought ... all files are processed parallelly till the merging step. 
since the merging step will not need two wildcards I discard it from the output, that's why i wrote the def function to get the wildcards.

**Comment by SichongP** [comment]
> wildcards come from here the rule split

Sorry I'm a little confused... So which rule requests these output files? The `aggregate_reverseInput` function you posted doesn't use input from `splitFiles/` directory?

**Comment by mewu3** [comment]
> > wildcards come from here the rule split
> 
> Sorry I'm a little confused... So which rule requests these output files? The `aggregate_reverseInput` function you posted doesn't use input from `splitFiles/` directory?

Sorry that I was not clear enough, between rule splitFiles and rule Merge, there are several rules who take these two wildcards without causing any problems (that's what I called the parallel processes).

**Comment by SichongP** [comment]
Your error messaage:

> Job Missing files after 5 seconds:
> /datater/wu/data/**{sample}/splitFiles**/forward{seg}.fasta
> /datater/wu/data/**{sample}/splitFiles**/reverse{seg}.fasta

Indicates a problem with one of the rules that requests `/datater/wu/data/{sample}**/splitFiles/**forward{seg}.fasta` as input. All the rules you posted here are requesting files from `/filtering/`. They are not what caused the error.

The wildcards here are not expanded, suggesting some errors in that rule. So you need to paste your rule here for us to see if there is anything wrong. I tried looking in your repo but I couldn't find such a rule.

**Comment by mewu3** [comment]
> Your error messaage:
> 
> > Job Missing files after 5 seconds:
> > /datater/wu/data/**{sample}/splitFiles**/forward{seg}.fasta
> > /datater/wu/data/**{sample}/splitFiles**/reverse{seg}.fasta
> 
> Indicates a problem with one of the rules that requests `/datater/wu/data/{sample}**/splitFiles/**forward{seg}.fasta` as input. All the rules you posted here are requesting files from `/filtering/`. They are not what caused the error.
> 
> The wildcards here are not expanded, suggesting some errors in that rule. So you need to paste your rule here for us to see if there is anything wrong. I tried looking in your repo but I couldn't find such a rule.

Dear Sir, 
The problem has been solved by using checkpoint instead of dynamic(), if you are interested in the codes, please look up at my repository https://github.com/mewu3/stage_m2/tree/merge. 
I thank you for your follow-up and your time, I wish you a good day :D
