### ISSUE TITLE
Using input lambda in param can cause FileNotFoundError in dry-run

### ISSUE THREAD

**Issue by ASLeonard** [snakemake/snakemake#927]
Couldn't see anything like this in previous issues, but encountered this in at least versions 5.32 and 6.0.5.

Dry-runs break when a rule uses the a lambda expression with an input file, **IF** that files does not currently exist. The file is generated before this rule should execute (it is in its input), but obviously the dry-run mechanism bypasses the actual generation. As such, a `FileNotFoundError` is raised. 

Without the dry-run flag, this works correctly as expected, as that rule (and so params) is presumably not evaluated until its input is available.

A simplified version is 

```python
rule all:
    input:
        'final.txt'

rule generate_value:
    output:
        'model.txt'
    shell:
        'echo 1 > {output}'

rule text:
    input:
	    model = 'model.txt'
    output:
        'final.txt'
    params:
	    lambda wildcards, input: [int(i) for i in open(input.model)]
    shell:
	    'echo {params} > {output}'
```

Running with `snakemake -n` breaks with FileNotFoundError

Running with `snakemake -j 1` works correctly.

**Comment by epruesse** [comment]
It's been like this for a while. Even theoretically, `snakemake -j1 -n -p` cannot work with a params function like above. It would be helpful to have a `dryrun` value that can be requested for function parameters, so that they can respond properly, "faking" something plausible when running in dryrun mode. I.e.

```
rule:
   params:
      lambda wildcards, input, dryrun: "<MODEL_PARAMETERS>" if dryrun else [int(i) for i in open(input.model)]
```

I've just been assuming dry-run mode whenever the files are missing. Not exactly defensive coding, but usually if the file isn't there it means that you are running in dry-run mode (or something went really wrong). 

```
lambda wildcard, input: [int(i) for i in open(input.model)] if os.path.exists(input.model) else "MODEL_PARAMETERS" 
```
```

**Comment by ASLeonard** [comment]
I agree that is a relatively easy work around, and after unsuccessfully searching for where the param lambda is in source, I can't comment much beyond this.

However, it seems like there must be a better solution. Something like setting memory resources through `lambda wildcards, input: input.size` is explicitly set as `resources: mem_mb=<TBD>` in the dryrun. It feels like this should be the case for **any** lambda expression which depends explicitly on an input item, as it either exists at time of evaluation (and can take the value) or needs to be generated first (and so TBD).

**Comment by epruesse** [comment]
>I agree that is a relatively easy work around, and after unsuccessfully searching for where the param lambda is in source, I can't comment much beyond this.

The code is here:
https://github.com/snakemake/snakemake/blob/9b358024d8e289edc105db779757829ad823ca6d/snakemake/rules.py#L664

It's the same code that runs the functions for any of the rule sections. The function I linked is the thing that determines which parameters need to be passed to the function given it's synopsis (i.e. which variables you requested). The same file should have the code that expands functions for all of the sections individually.

**Comment by epruesse** [comment]
I guess there could be code in Snakemake that emits `<TBD>` instead of calling the function when in dry-run mode and the file isn't there yet.

**Comment by SichongP** [comment]
You should use [checkpoint](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#data-dependent-conditional-execution):

```
rule all:
    input:
        'final.txt'

checkpoint generate_value:
    output:
        'model.txt'
    shell:
        'echo 1 > {output}'

rule text:
    input:
            model = 'model.txt'
    output:
        'final.txt'
    params:
            lambda wildcards, input: [int(i) for i in open(checkpoints.generate_value.get().output[0])]
    shell:
            'echo {params} > {output}'
```

**Comment by ASLeonard** [comment]
@SichongP checkpoints have been buggy in the past (many issues reported and only some fixed), and is overkill in this situation, so I'd rather avoid that as much as I can.

@epruesse, in the `expand_resources` method [here](https://github.com/snakemake/snakemake/blob/9b358024d8e289edc105db779757829ad823ca6d/snakemake/rules.py#L940), there is an explicit try/except wrap over the `apply_input_function`, which directly causes the <TBD> if the file is an input.
```
except FileNotFoundError as e:
                        # Resources can depend on input files. Since expansion can happen during dryrun,
                        # where input files are not yet present, we need to skip such resources and
                        # mark them as [TBD].
                        if e.filename in input:
                            # use zero for resource if it cannot yet be determined
                            res = TBDInt(0)
```
a similar wrap could be placed on L717 of that file, but that may have other unintended effects as the `_apply_wildcards` may have more general uses. I can make a PR and see if it would integrate smoothly, but this would become a higher-level decision in my opinion.

**Comment by ASLeonard** [comment]
This looks like a bit of a rabbit hole.

The `apply_input_function` used by `expand_params` does not get passed `input` directly, but through an aux_params dictionary `"input": input._plainstrings(),`. While that may take some more work to get it right, it would be possible to put the `except FileNotFoundError as e:` check directly part of the existing try statement on [L679](https://github.com/snakemake/snakemake/blob/9b358024d8e289edc105db779757829ad823ca6d/snakemake/rules.py#L679).

This would allow handling param and resource expansion in the same way and avoid violating DRY.

**Comment by epruesse** [comment]
> You should use [checkpoint](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#data-dependent-conditional-execution):

> @SichongP checkpoints have been buggy in the past (many issues reported and only some fixed), and is overkill in this situation, so I'd rather avoid that as much as I can.

My feeling too. Using `checkpoint` as suggested would fix the error and in a sense is the correct approach here. However, printing the shell command or the DAG won't work at all when using that feature (at this time).

**Comment by epruesse** [comment]
> This looks like a bit of a rabbit hole.

It may well be. There is a lot of interaction inside Snakemake getting all the features to work right. Depends on how much time you can invest to get it right.

**Comment by ASLeonard** [comment]
PR #932 resolves this test case, and doesn't seem to cause any existing tests to fail. It was actually relatively simple to fix, as the content in resource and param expansion was similar, just very differently named/stored.

I'll leave this open for now in case there are different use cases or discussions.
