### ISSUE TITLE
Inheritance cannot be used multiple times safely

### ISSUE THREAD

**Issue by epruesse** [snakemake/snakemake#929]
**Snakemake version**

6.0.5

**Describe the bug**

The new inheritance system modifies the `RuleInfo` of the parent rule when creating the derived rule. It should first create a copy of the original `RuleInfo` and modify this, so that subsequent uses of the parent `RuleInfo` are not altered.

**Minimal example**

```
rule baserule:
  params:
    mymessage = "I am the base rule",
  shell: "echo {params.mymessage}"

use rule baserule as childrule_1 with:
  params:
    mymessage = "I am childrule_1",

use rule baserule as childrule_2 with:
  output: touch("test.file")
```

```
snakemake -qfj1 childrule_2
[...]
I am childrule_1
```

Fix would involve making the RuleInfo object copyable. It used to be, but it now contains an environment reference which cannot be `deepcopy`'ed.

**Comment by epruesse** [comment]
It's the `path_modifier` that has a reference to `workflow` to get to `default_remote_provider`, etc. The `workflow` has a `vanilla_globals`, which can't be copied. Is Snakemake now using multiple instances of the `workflow`? Or could `workflow.rule()` just pass `self` down to where the path_modifier needs workflow attributes?

**Comment by jaicher** [comment]
This is still an issue, unfortunately. It has the same behavior with resource specifications. This is particularly painful if you use a resources or params function that is dependent on wildcards that do not exist in all of the child rules.

This issue directly conflicts with the documentation saying that:

> Analogously to the use rule from external modules, any properties of the rule (input, output, log, params, benchmark, threads, resources, etc.) can be modified, except the actual execution step (shell, notebook, script, cwl, or run). **All unmodified properties are inherited from the parent rule**.

**Comment by johanneskoester** [comment]
Thanks a lot for reporting and the detective work! Should be closed by above PR.
