### ISSUE TITLE
Localrules not compatible with new module mechanism

### ISSUE THREAD

**Issue by timtroendle** [snakemake/snakemake#945]
**Snakemake version**
6.1.1

**Describe the bug**
Rules defined as ``localrules`` aren't localrules anymore when imported from a module. 

**Logs**
```bash
localrules directive specifies rules that are not present in the Snakefile:
	a
```

**Minimal example**
```Python
# module.smk

localrules: a

rule a:
    output: "something.txt"
    shell: "touch {output}"

rule b:
    input: rules.a.output
    output: "another.txt"
    shell: "touch {output}"

# Snakefile

module other_workflow:
    snakefile: "module.smk"

use rule * from other_workflow as other_*
```

**Comment by ImNotaGit** [comment]
I am using Snakemake v6.5.1. Although there was the message "localrules directive specifies rules that are not present in the Snakefile", the pipeline was still able to run and complete successfully. As a workaround to re-declare the local rule in the imported module, you may add `localrules: other_a` after the line `use rule * from other_workflow as other_*` in the above example.
