### ISSUE TITLE
Broken link in documentation (reports)

### ISSUE THREAD

**Issue by Gutorm** [snakemake/snakemake#95]
**Snakemake version**
Current documentation:
https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html
**Describe the bug**
Documentation links to a code example https://github.com/snakemake/snakemake/src/master/tests/test_report/ - but that document yields a 404 error.
Correct link seems to be https://github.com/snakemake/snakemake/tree/master/tests/test_report 
**Logs**
NA
**Minimal example**
click https://github.com/snakemake/snakemake/src/master/tests/test_report/
**Additional context**
I would love the FAQ  ( https://snakemake.readthedocs.io/en/stable/project_info/faq.html ) to have a section on where to report bugs (and what to do before you do so ...) as well as how to report broken links or other errors in the docs - Is what I am doing the 'right' way?
Also thanks for Snakemake and being part of that community!

**Comment by dcroote** [comment]
Fixed by #505
