### ISSUE TITLE
Command being run in cluster is different from the one printed

### ISSUE THREAD

**Issue by fgvieira** [snakemake/snakemake#954]
**Snakemake version**
v6.1.1

**Describe the bug**
I am trying to make a function that return the path to `tmp_dir`, depending if the rule is being run locally or sent to a cluster.

So far, I have:
```
def get_tmp(
    name: str = None,
    local: bool = True
) -> str:
    """
    Returns path to temporary folder

    :param name: name of folder (randomly generated if not provided)
    :param local: should the temp folder be local (/tmp/) or not?
    :return path: a string with path to temp folder
    """

    if '__default__' in cluster_config:
        path = Path(cluster_config["__default__"]["tmp_dir"])
    else:
        if local:
            path = Path("/tmp")
        else:
            path = Path("temp/large_files")

    if name:
        path = path / "{0}{1:06d}".format(name, random.randrange(1e6))
        path.mkdir(parents=True, exist_ok=True)

    return(str(path))
```

with a `cluster.yaml` file:
```
__default__:
  output: /dev/null
  error:  logs/cluster/
  tmp_dir: /scratch/$PBS_JOBID
```

**Logs**
When I run the pipeline with `-p`, `snakemake` prints:
```
[...] | bcftools sort --max-mem 2048M --output-file z --temp-dir /scratch/$PBS_JOBID > output.bcf
```
but, if I check the job actually being run, it shows:
```
bcftools sort --max-mem 2048M --output-file z --temp-dir /tmp > output.bcf
```
and when it eventually fails, it shows:
```
[...] | bcftools sort --max-mem 2048M --output-file z --temp-dir /scratch/$PBS_JOBID > output.bcf
```

It seems that when the function is called for `-p` or when it fails, `cluster_config` is defined. But, when the job is actually launched, `cluster_config` is not set.
Is there a better way to check if a job is being run locally or sent to a cluster?
Is there a better way to define `tmp_dir` accordingly?

thanks,

**Comment by SichongP** [comment]
I think cluster configuration has been deprecated in favor of [profiles](https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles). Can you try if that solves your problem?

Alternatively, can you check if $PBS_JOBID is set with something like `[ ! -n ${{PBS_JOBID-}} ]`? If a job is run locally, $PBS_JOBID should be empty.

**Comment by fgvieira** [comment]
Testing for `$PBS_JOBID` actually works but it does feel a bit hacky, since `--printshellcmds` shows:
```
[...] | bcftools sort --max-mem 2048M --output-file z --temp-dir /tmp 
```
but what is actually being run is:
```
[...] | bcftools sort --max-mem 2048M --output-file z --temp-dir /scratch/3223876
```

I guess the issue is that `--printshellcmds` calls `get_tmp()` locally (and gets `/tmp`), while the actual job calls the function in the cluster (and gets `/scratch/3223876`). Is there a way to make things more consistent?

**Comment by boulund** [comment]
I have encountered this issue recently as well. I have a rule with a threads definition that sets the number of threads based on what's in the cluster profile. It checks if the rule has has a number of cores defined in the cluster_config (read from the `--profile`).

Here is an example: 
https://github.com/ctmrbio/stag-mwc/blob/master/rules/taxonomic_profiling/kraken2.smk#L88

```
rule kraken2:
    ... (removed for brevity) ...
    threads:
        cluster_config["kraken2"]["n"] if "kraken2" in cluster_config else 4
    ... (removed for brevity) ...
    shell:
        """
        kraken2 \
            --db {params.db} \
            --confidence {params.confidence} \
            --threads {threads} \
            --output {output.kraken} \
            --report {output.kreport} \
            --use-names \
            --paired \
            {input.read1} {input.read2} \
            {params.extra} \
            2> {log}
        """
```

Here are the relevant lines from the cluster config:
```
kraken2:
    n: 10
    time: "02:00:00"
```

I get the impression that when Snakemake generates the jobscript that is actually running Snakemake in the cluster job it does not include `--profile` so the `cluster_profile` dictionary is not populated with any values, leading the above definition to evaluate to `4` instead of whatever is defined in the profile (`10` in my example above).
