### ISSUE TITLE
Specifying user project for google storage requests

### ISSUE THREAD

**Issue by jaicher** [snakemake/snakemake#96]
Some google storage buckets are only accessible on a ["requester pays"](https://cloud.google.com/storage/docs/requester-pays) basis. The current implementation of `snakemake.remote.GS` does not support downloading these files.

I have implemented a possible solution to this in pull request #79 which extends the `GS.remote(url)` syntax to include a named argument `GS.remote(url, user_project={...})`. Specifying the billed user project can be done in the Snakemake configuration.

Other possibilities for handling this are discussed in the comments of pull request #79. This approach is probably a stopgap solution before a more elegant solution for how to handle google storage, projects, and pipelines in a more general way.

The creation of this issue is primarily to address naming of tests (so we do not have to start a new convention for tests with respect to a pull request instead of an issue) as brought up by @vsoch.

**Comment by vsoch** [comment]
I think this was fixed with https://github.com/snakemake/snakemake/pull/79. Thanks again @jaicher !
