### ISSUE TITLE
Batch flag counting input lines, not the number of input files based on expanding wildcards

### ISSUE THREAD

**Issue by jcmcnch** [snakemake/snakemake#98]
**Snakemake version**
5.7.4

**Describe the bug**
When running batch flag, snakemake appears to count the number of input lines, not the number of input files as determined by expanding wildcards. As a result, the run fails with this error unless the number of batches is <= to the number of input lines:

```
WorkflowError:
Batching rule samtools_sort has less input files than batches. Please choose a smaller number of batches.
```

In other words, even if you have thousands of input files as determined by wildcard expansion, the workflow cannot be divided into less than the number of input lines. I posted about this on stackoverflow already with a real-world example:

[https://stackoverflow.com/questions/58739674/how-to-properly-use-batch-flag-in-snakemake-to-subset-dag](url)

**Logs**

N/A, workflow will not execute.

**Minimal example**
Behaviour not specific to my data. See attached MWE (below) based on snakemake tutorial. There are three samples "A", "B", and "C" (I changed the snakefile to make sure all three are used). But if you try to run:

```
snakemake --batch samtools_sort=1/3
```

It fails with the same error. From my understanding of how the batch should work, I thought it should be possible to divide the workflow into three batches given that there are three samples. Please accept my apologies if I've made a fundamental misconception here! 

Thanks for your help,
Jesse

[smk-batch-MWE.zip](https://github.com/snakemake/snakemake/files/3825801/smk-batch-MWE.zip)

**Comment by johanneskoester** [comment]
--batch is meant for large aggregating rules (with many input files already in the rule). The reason is that only there, it is possible to omit large parts of the dag. For your case, it would not work because snakemake would still have to evaluate the DAG to all those thousands of samtools jobs. Hence, no speed improvement at all. You have a choose some kind of aggregating  rule (this can also be the target rule if there is no aggregation in between).

**Comment by jcmcnch** [comment]
OK thank you Johannes for clarifying my misunderstanding. For my workflow then I will have to just continue doing what I've done previously and subset my config files to run parts of my workflow that allow reasonable runtimes for calculating the DAG. Best, Jesse
