### ISSUE TITLE
module 'snakemake.checkpoints' has no attribute 'register'

### ISSUE THREAD

**Issue by mazzalab** [snakemake/snakemake#986]
Hi,
maybe I have made any mistake, but this code:

```
checkpoint split_fastq:
    input:
        "data/{sample}_fixed.fastq"
    output:
        directory("data/{sample}_fixed.fastq.chunks")
    log:
        "logs/split_fastq/split_fastq_chunks.{sample}.log"
    shell:
        "split -l 4 --numeric-suffixes {input} {output}/{input}."
```

causes the error in object at line "split -l 4 --numeric-suffixes {input} {output}/{input}."

snakemake --version
6.3.0

python --version
3.9.4

I am not able to understand where the error is. Can you help?

**Comment by mazzalab** [comment]
I get the same error with the latest 6.4 version. Any feedback?

**Comment by sstadick** [comment]
I had the same error and was importing `from snakemake import chekcpoints`. When I removed the import the error was fixed.
